terraforming-mars/terraforming-mars

- src/Game.ts
when reaching 0 degrees and oceans are already maxed
> Fix bug with bonus ocean

- src/cards/Moss.ts
- tests/cards/Moss.spec.ts
Cards descriptions can be checked here : https://ssimeonoff.github.io/cards-list
> Fix Moss bug

- src/Game.ts
- src/Player.ts
- src/cards/Tardigrades.ts
- src/cards/WaterSplittingPlant.ts
- Add TR to final score
- Fix final greenery bug
- Fix WaterSplittingPlant missing canAct
- Fix Tardigrades missing canAct
> Bug fixes and add TR to final score

- server.ts
- src/ClaimedMilestone.ts
- src/Game.ts
- src/Milestone.ts
- src/Player.ts
- src/components/ClaimedMilestone.ts
- src/components/FundedAward.ts
- src/milestones/Builder.ts
- src/milestones/Gardener.ts
- src/milestones/IMilestone.ts
- src/milestones/Mayor.ts
- src/milestones/Milestones.ts
- src/milestones/Planner.ts
- src/milestones/Terraformer.ts
- src/models/ClaimedMilestoneModel.ts
Milestones rework (same as awards, to prepare hellas & elysium)
> Milestones rework

- src/Dealer.ts
- src/Game.ts
- src/Player.ts
- src/cards/corporation/Inventrix.ts
- src/cards/prelude/AquiferTurbines.ts
- src/cards/prelude/BusinessEmpire.ts
- src/cards/prelude/EcologyExperts.ts
- src/cards/prelude/GalileanMining.ts
- src/cards/prelude/HugeAsteroid.ts
- src/cards/prelude/ValleyTrust.ts
- src/inputs/SelectCard.ts
- tests/cards/corporation/Inventrix.spec.ts
Fix requirements bugs
Add mechanism for "shoot again" cards
Modify solo with prelude
> Prelude implementation part 1

- src/Dealer.ts
- src/Player.ts
- src/cards/IProjectCard.ts
- src/cards/prelude/EccentricSponsor.ts
- src/cards/prelude/EcologyExperts.ts
Another attempt to implement those "play another card" cards.
Right now postAction only triggers a playProjectCard but could be modified in the future if needed.
> Prelude play another card cards

- styles.css
> Fix expansion icons

- src/cards/ImportedNitrogen.ts
- tests/cards/ImportedNitrogen.spec.ts
Implemented the canPlay method from being a tautology to checking if there are cards which can have the resources needed added to them.
> Better ImportedNitrogen #49

- server.ts
- src/components/SelectHowToPayForCard.ts
- src/models/PlayerModel.ts
Addition of client side validation for `SelectHowToPayForCard`. Will add similar validation for `SelectCard` next.
> Client side validation for SelectHowToPayForCard

- server.ts
- src/Game.ts
- src/components/GameEnd.ts
- src/models/PlayerModel.ts
Correct count oceans and generation conditions for victory
> Fix solo win conditions; refs #67

- package.json
- src/Player.ts
- src/cards/AerobrakedAmmoniaAsteroid.ts
- src/cards/Ants.ts
- src/cards/AquiferPumping.ts
- src/cards/ArtificialLake.ts
- src/cards/Asteroid.ts
- src/cards/BigAsteroid.ts
- src/cards/BiomassCombustors.ts
- src/cards/GiantIceAsteroid.ts
- tests/cards/AerobrakedAmmoniaAsteroid.spec.ts
- tests/cards/Ants.spec.ts
- tests/cards/AquiferPumping.spec.ts
- tests/cards/ArtificialLake.spec.ts
- tests/cards/Asteroid.spec.ts
- tests/cards/GiantIceAsteroid.spec.ts
Please review and merge it, but do not remove the branch - we will continue to work on it
> Rework some cards requirements check code; Add new tests; #81

- src/cards/BusinessNetwork.ts
- tests/cards/BusinessNetwork.spec.ts
This puts in a simple solution for Business Network which will display the full card drawn to the user. Will put in this solution for Inventors' Guild when approved in a separate pull request.
> Better Business Network implementation #95

- src/Player.ts
This stacks the requirement bonus in the case that a player has multiple cards which apply a +2 / -2 requirements bonus.
> Stack requirements bonus #106

- src/HTML_data.ts
- src/Player.ts
- src/components/Card.ts
- src/components/OtherPlayer.ts
- src/components/PlayerHome.ts
Add resource marker for Ecological Zone
Remove hideCost property for cards
Remove Board header on home page
Add research phase card bought to log
> Missing resource

- package-lock.json
- server.ts
- src/Player.ts
- src/cards/AquiferPumping.ts
- src/cards/BusinessNetwork.ts
- src/cards/IndustrialCenter.ts
- src/cards/InventorsGuild.ts
- src/cards/RestrictedArea.ts
- src/cards/SearchForLife.ts
- src/cards/SpaceMirrors.ts
- src/cards/UndergroundDetonations.ts
- src/cards/WaterImportFromEuropa.ts
- src/cards/prelude/Psychrophiles.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForCard.ts
- src/inputs/SelectHowToPay.ts
- src/inputs/SelectHowToPayForCard.ts
- src/models/PlayerInputModel.ts
The client side validation being used in `SelectHowToPay` wasn't working with `Psychrophiles` where a user can pay with microbes for plant cards. This fixes the client side validation.
> Fix for Psychrophiles

- server.ts
- src/Game.ts
- src/Player.ts
- src/components/CreateGameForm.ts
> Draft variant - Issue #18

- src/components/Board.ts
- src/components/SelectSpace.ts
- src/styles/board.less
After pressing the "Select space" button all available spaces should be hilit with little blinking animation
> Hilight available spaces for the tile placement on the board; #133

- src/Player.ts
- src/cards/Asteroid.ts
- src/cards/BigAsteroid.ts
- src/cards/Comet.ts
- src/cards/DeimosDown.ts
- src/cards/GiantIceAsteroid.ts
- src/cards/MiningExpedition.ts
- src/cards/Predators.ts
- src/cards/Virus.ts
- tests/cards/Comet.spec.ts
- tests/cards/GiantIceAsteroid.spec.ts
- tests/cards/Predators.spec.ts
We found some bugs with ProtectedHabitas and Pets
Fixes and additional test are in this PR
> Fix ProtectedHabitas and Pets behavior on some cards

- src/Player.ts
- src/cards/Asteroid.ts
- src/cards/BigAsteroid.ts
- src/cards/Comet.ts
- src/cards/DeimosDown.ts
- src/cards/GiantIceAsteroid.ts
- src/cards/MiningExpedition.ts
- src/cards/Virus.ts
I had a comment on the last @alrusdi pull request for a more consolidated check for other players with plants. This small refactor is included here in this pull request.
> Small refactor for other players with plants

- src/Player.ts
- src/components/PaymentWidgetMixin.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForCard.ts
- src/styles/common.less
- src/styles/payments.less
- src/styles/resources.less
Next step will be general payment widget
> New 'Pay for card widget'; #145

- src/Game.ts
- src/Player.ts
- src/cards/corporation/CorporationCard.ts
- src/cards/corporation/CrediCor.ts
- src/cards/corporation/InterplanetaryCinematics.ts
- src/cards/corporation/SaturnSystems.ts
- src/cards/prelude/PointLuna.ts
- tests/Game.spec.ts
- tests/Player.spec.ts
- tests/cards/corporation/CrediCor.spec.ts
- tests/cards/corporation/InterplanetaryCinematics.spec.ts
- tests/cards/corporation/SaturnSystems.spec.ts
This should fix issue #168 . When _any_ player now plays a card the Saturn Systems discount will be applied.
> Apply Saturn Systems discount when any player plays a card

- src/cards/prelude/PolarIndustries.ts
- src/cards/prelude/PowerGeneration.ts
- src/cards/prelude/PreludeCard.ts
- src/cards/prelude/Psychrophiles.ts
- src/cards/prelude/ResearchCoordination.ts
- tests/cards/prelude/PointLuna.spec.ts
- tests/cards/prelude/PolarIndustries.spec.ts
- tests/cards/prelude/PowerGeneration.spec.ts
- tests/cards/prelude/Psychrophiles.spec.ts
- tests/cards/prelude/ResearchCoordination.spec.ts
- tsconfig-test.json
More unit tests and small fixes for prelude cards.
> More prelude unit tests

- src/cards/ViralEnhancers.ts
Viral Enhancers was offering to put resource on cards that cannot hold them
> Viral Enhancer resource check

- src/Game.ts
- src/Player.ts
- src/cards/BusinessNetwork.ts
- src/cards/InventorsGuild.ts
Small change to allow buying card cost to be modified for a given player.
This will be usefull for 2 corporations.
> Card Cost Rework

- server.ts
- src/CardName.ts
- src/Game.ts
- src/Player.ts
- src/cards/CaretakerContract.ts
- src/cards/LocalHeatTrapping.ts
- src/cards/TowingAComet.ts
- src/cards/colonies/Arklight.ts
- src/cards/colonies/StormCraftIncorporated.ts
- src/components/OtherPlayer.ts
- src/components/PlayerHome.ts
- src/models/PlayerModel.ts
Display resource counter for corporations (still needs some work as it overlaps with corporation title)
Display resource counters for other players played cards
Cleanup in corporations with resources (remove dummy parameters)
Remove corporations from cardName enum
Cleanup in OtherPlayer.ts
> Select card rework

- src/Player.ts
- src/components/AndOptions.ts
- src/components/Board.ts
- src/components/OrOptions.ts
- src/components/PlayerInputFactory.ts
- src/components/SelectAmount.ts
- src/components/SelectCard.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForCard.ts
- src/components/SelectOption.ts
- src/components/SelectPlayer.ts
- src/components/SelectSpace.ts
- src/components/WaitingFor.ts
- src/styles/board.less
* First semi working version
* Mostly working solution
* Hilight selected board space; #200
* Auto-save select space while selecting space for a parent AndOptions
Co-authored-by: alrusdi <alrusdi@gmail.com>
> Better AndOptions with only one save button! (#220)

- src/Board.ts
- src/OriginalBoard.ts
- src/Player.ts
- src/cards/venusNext/VenusWaystation.ts
- src/cards/venusNext/Viron.ts
Also a bug with Viron and 2 small other fixes
> Fix Noctis on other boards

- src/Game.ts
- src/Player.ts
- src/cards/GiantIceAsteroid.ts
- src/cards/RoboticWorkforce.ts
- src/cards/promo/Philares.ts
- src/interrupts/PlayerInterrupt.ts
- src/interrupts/SelectOcean.ts
- tests/cards/GiantIceAsteroid.spec.ts
- tests/cards/RoboticWorkforce.spec.ts
- tsconfig.json
Please do not merge.
This is a POC for interrupt rework. Please review and let me know if the implementation seems correct.
For testing purpose, GiantIceAsteroid is always available from card selection.
This needs to be tested in a multiplayer game.
> Change GiantIceAsteroid

- src/Player.ts
- src/cards/colonies/Poseidon.ts
- src/cards/colonies/TitanFloatingLaunchPad.ts
- src/components/Card.ts
- src/components/Colony.ts
Vistor rework was wrong and missing reference for ALL_COLONIES_PROJECTS_CARDS in `card `class
> Issues 294 and 293

- src/Game.ts
- src/Player.ts
- src/cards/Hackers.ts
- src/cards/colonies/Aridor.ts
- src/cards/colonies/MarketManipulation.ts
- src/cards/venusNext/Gyropolis.ts
- src/milestones/Ecologist.ts
- tests/Game.spec.ts
- tests/cards/Hackers.spec.ts
- tests/cards/colonies/Aridor.spec.ts
- tests/cards/venusNext/Gyropolis.spec.ts
- Fix multiple tags card bug (Ecologist milestone bug)
- Fix Aridor bug
- Fix a test in hackers card
- Fix Market Manipulation cost
- Add not active colony filter to market manipulation card
- Fix Venus bonus steps bug with +3 Venus increment
> issue-306 and various bugs

- src/Player.ts
After playing the 2nd prelude card play will now progress to the next player. This should allow players to play their prelude cards before their initial actions.
> After playing 2nd prelude card progress to next player

- src/Game.ts
- src/Player.ts
- src/cards/RoboticWorkforce.ts
- src/components/SelectHowToPay.ts
- src/interrupts/SelectCity.ts
- src/interrupts/SelectGreenery.ts
- src/interrupts/SelectHowToPayInterrupt.ts
Use interrupts to pay for standards projects. This removes a lot of lines in player class.
Add a log message for robotic workforce to indicate which card is copied
> Standard projects htp rework

- src/Game.ts
This was giving steel production for Mining Guild owner even when other players were placing tiles
> Fix tilePlaced player bug

- package-lock.json
- src/components/CreateGameForm.ts
The players array uses 0 based indices. When calling slice we only need to pass `playersCount` as the second argument
> Use 0 based array index

- server.ts
- src/Dealer.ts
- src/Game.ts
- src/Player.ts
- src/cards/colonies/Aridor.ts
- src/colonies/ColonyDealer.ts
- src/components/CreateGameForm.ts
- src/interrupts/SelectRemoveColony.ts
This will allow to set the random seed to reproduce a game.
Could be used for duplicate tournaments.
Drafted cards will remain the same too, as well as first player
> Seeded games

- src/Game.ts
- src/Player.ts
- src/cards/Ants.ts
- src/cards/CloudSeeding.ts
- src/cards/Predators.ts
- src/colonies/ColonyDealer.ts
- src/components/LogPanel.ts
- src/components/PlayerHome.ts
- src/styles/player_home.less
- tests/cards/Ants.spec.ts
Fix Solo game broken if you win before last turn with Venus Next #355
Fix Cannot use Celestic action on first turn #351
Fix Only four colonies in a two player game #349
Suggestion: Expandable logging #288, thanks @alrusdi for this one
Enable Ants and Predators for solo game play
> Misc changes

- src/Dealer.ts
- src/Game.ts
- src/colonies/ColonyDealer.ts
Seeded games are merely shuffling cards . I need to find a way to make it predictable and add a lot more shuffling. Let's disable this for now.
> Disable seeded games

- server.ts
- src/ITagCount.ts
- src/Player.ts
- src/cards/Tags.ts
- src/components/OtherPlayer.ts
- src/components/PlayerHome.ts
- src/components/PlayerMixin.ts
- src/components/Tag.ts
- src/components/TagCount.ts
- src/models/PlayerModel.ts
- src/styles/player_home.less
- src/styles/resources.less
Will display also number of events played
> Add tags count

- src/HTML_data.ts
- src/styles/cards.less
- src/styles/common.less
- src/styles/create_game_form.less
- src/styles/player_home.less
These are tweaks that give a darker background, improve card selection highlights, and set color styles for card and other text that had not been set. 
issue: https://github.com/bafolts/terraforming-mars/issues/397
> ui color tweaks

- src/components/GameEnd.ts
- src/styles/common.less
- src/styles/game_end.less
- src/styles/log.less
- src/styles/player_home.less
Added the game log to the end game screen as requested in issue #255.
> Added game log to end game screen

- src/HTML_data.ts
- src/Player.ts
- src/components/OtherPlayer.ts
- src/components/PlayerHome.ts
- src/styles/cards.less
- src/styles/other_player.less
- src/styles/preferences.less
Fixes after visual schema change
> Issue 397 bugfixes

- README.md
- index.html
- script.ts
- server.ts
- src/components/GamesOverview.ts
Tried myself on a page displaying all games available on the server as requested in #284.
> Added page with overview of all games on the server (Issue 284)

- src/CardName.ts
- src/HTML_data.ts
- src/Player.ts
- src/cards/CarbonateProcessing.ts
- src/cards/RoboticWorkforce.ts
Wildcards tag was counting for every tag.
Fix typo on Carbonate Processing card
> Fix tag count

- src/HTML_data.ts
- src/styles/cards.less
fixed the coords of points for Arklight, Pristar and Celestic
> fix corporation points coords

- src/styles/cards.less
Moved the card resource counter down as to not interfere with card content.
> Fix card resource counter

- src/styles/cards.less
Removed inherited filters from the card contents so text would remain readable when selected.
> removed filters from card content

- src/cards/venusNext/AirScrappingExpedition.ts
- tests/cards/venusNext/AirScrappingExpedition.spec.ts
Playing the game does not raise Venus (but it adds floaters).
The most important line of code is missing.
> Air scrapping expedition bug

- src/cards/prelude/SupplyDrop.ts
Removed energy tag from Supply Drop as the card does not have this tag.
> Removed energy tag from Supply Drop

- src/cards/VestaShipyard.ts
- tests/cards/VestaShipyard.spec.ts
We were not including the victory point for vesta shipyard which led to other issues where we check for cards with victory points.
> Give victory point for vesta shipyard for #452

- package.json
- src/components/PlayerHome.ts
- src/components/WaitingFor.ts
My changes for i18n introduced some bugs. Here some fixes...
> Bug fixes after i18n merge

- Dockerfile
translation.json was not having the right permissions
> Fix dockerfile permissions

- src/components/CreateGameForm.ts
This adds the option to play on a random board (from the three available) when creating a game. For times when you just can't decide...
> Allow to choose board randomly when creating a game

- src/components/LogPanel.ts
- src/components/PlayerHome.ts
- src/styles/log.less
- src/styles/player_home.less
> Player name style 2

- server.ts
- src/Game.ts
- src/Player.ts
- src/components/PlayerHome.ts
- src/components/PlayerMixin.ts
- src/styles/player_home.less
Cards in hands are ordered by drawing order not type. 
The latest active card played is on the left. 
The latest automated card played is on top of the stack pile
> Issue #487, Issue #486 and saves corrections.

- src/components/LogPanel.ts
Log Cards: prevents from showing empty cards. Prevents from showing two time the same card
> Log Cards #428

- src/components/Award.ts
- src/components/Milestone.ts
- src/components/OtherPlayer.ts
- src/components/PlayerHome.ts
- src/locales/ru/ui.json
- src/styles/player_home.less
Correct show of VP in OtherPlayer component
Fix Awards and Milestones glitch on game setup page
Remove unnecessary large player name from the top of PlayerHome page
Fix start page when translated into russian
> Visual fixes

- src/components/GameHome.ts
- src/components/GamesOverview.ts
- src/styles/common.less
- src/styles/player_home.less
Added names and colors to overview and game home:
> added names and colors to overview and game home

- src/cards/AsteroidMiningConsortium.ts
- tests/cards/AsteroidMiningConsortium.spec.ts
Wasn't considering player's titanium production
> Fix not considering player's titanium production

- src/components/GameEnd.ts
- src/styles/common.less
- src/styles/player_home.less
Added slight margin to see full VP table
Restored global parameters show near the board
> End game visuals fix

- src/styles/player_home.less
> Player order design cleanup

- src/Game.ts
- src/Player.ts
- src/cards/Ants.ts
- src/cards/AsteroidMiningConsortium.ts
- src/cards/BiomassCombustors.ts
- src/cards/Birds.ts
- src/cards/CloudSeeding.ts
- src/cards/EnergyTapping.ts
- src/cards/Fish.ts
- src/cards/Flooding.ts
- src/cards/GreatEscarpmentConsortium.ts
- src/cards/Hackers.ts
- src/cards/HeatTrappers.ts
- src/cards/Herbivores.ts
- src/cards/HiredRaiders.ts
- src/cards/PowerSupplyConsortium.ts
- src/cards/Predators.ts
- src/cards/RoboticWorkforce.ts
- src/cards/SmallAnimals.ts
- src/cards/colonies/AirRaid.ts
- src/cards/colonies/SubZeroSaltFish.ts
- src/cards/prelude/Vitor.ts
- src/cards/venusNext/CometForVenus.ts
- src/interrupts/SelectResourceProductionDecrease.ts
- tests/cards/AsteroidMiningConsortium.spec.ts
- tests/cards/CloudSeeding.spec.ts
- tests/cards/EnergyTapping.spec.ts
- tests/cards/GreatEscarpmentConsortium.spec.ts
- tests/cards/Hackers.spec.ts
- tests/cards/PowerSupplyConsortium.spec.ts
same as Titanium Consortium for other consortiums
> Fix consortiums

- src/cards/prelude/LavaTubeSettlement.ts
Bug fix.
Jacob says: you can place this city anywhere, but must follow standard city restrictions, i.e. no city adjacency.
https://boardgamegeek.com/thread/1953628/article/29627211#29627211
> Fix Lava Tube Settlement placement on Hellas board

- src/cards/GanymedeColony.ts
- src/cards/IoMiningIndustries.ts
- src/cards/WaterImportFromEuropa.ts
- tests/cards/AdvancedEcosystems.spec.ts
Doesn't include wild tags when counting victory points for jovian based cards.
> Don't count wild tags as jovian for victory points

- src/cards/InventorsGuild.ts
- src/components/Preferences.ts
- src/components/PreferencesManger.ts
- src/styles/cards.less
- src/styles/preferences.less
> Magnify card and / or descriptions with preferences

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/promo/DuskLaserMining.ts
- src/cards/promo/InterplanetaryTrade.ts
- src/cards/promo/MercurianAlloys.ts
- src/cards/promo/RegoPlastics.ts
- src/cards/promo/SmallAsteroid.ts
- src/cards/promo/SnowAlgae.ts
- tests/cards/promo/DuskLaserMining.spec.ts
- tests/cards/promo/InterplanetaryTrade.spec.ts
- tests/cards/promo/MercurianAlloys.spec.ts
- tests/cards/promo/RegoPlastics.spec.ts
- tests/cards/promo/SmallAsteroid.spec.ts
- tests/cards/promo/SnowAlgae.spec.ts
- tsconfig-test.json
Includes pull requests #569, #570, #571, #572 and #573, please merge those first.
> Added promo card Interplanetary Trade (#539)

- src/styles/cards.less
fixed card stacking hover when not magnified. issue# https://github.com/bafolts/terraforming-mars/issues/583
> fix card stack hover issue 583

- src/styles/cards.less
fixes issue 
Fixes #591
was:
now fixed:
> card stacking margin adjustment

- src/HTML_data.ts
Interplanetary Trade and Rego Plastics incorrect html
> Fix some promo cards markup

- src/Dealer.ts
I've tested this card and it seems to be ok.
> Make Atmoscoop card available in game; #575

- src/styles/board.less
Fixed red line on card bonus. Noticeable in Firefox browser
> Fix card bonus css

- src/cards/MarsUniversity.ts
- tests/cards/MarsUniversity.spec.ts
This finishes the other science related card for #453. If a card is played like `Research` with multiple science tags each science tag gets the corresponding action.
> Run MarsUniversitry logic for multiple science tags

- src/components/OtherPlayer.ts
- src/components/PlayerHome.ts
I've did something wrong and Improved player layout #472 didn't come through
> Layout improvement

- src/turmoil/Turmoil.ts
- src/turmoil/parties/Greens.ts
- src/turmoil/parties/IParty.ts
- src/turmoil/parties/Kelvinists.ts
- src/turmoil/parties/MarsFirst.ts
- src/turmoil/parties/Party.ts
- src/turmoil/parties/PartyName.ts
- src/turmoil/parties/Reds.ts
- src/turmoil/parties/Scientists.ts
- src/turmoil/parties/Unity.ts
- First implementation of parties
- Work on end of generation part
> Turmoil: begin of turmoil implementation #577

- src/components/OtherPlayer.ts
- src/styles/other_player.less
Clicking anywhere in other player window will close it.
> Other player details cleanup

- src/locales/de/cards.json
First batch of German translations for cards. This covers cards 001 to 050.
> German translations for cards (001 to 050)

- src/Game.ts
- src/Player.ts
- src/cards/promo/LawSuit.ts
Storing players ids instead of player objects so no need to modify restore function.
> revert to array of ids

- src/Player.ts
- tests/cards/venusNext/Manutech.spec.ts
It didn't add energy resources when Energy production was increased by Power Plant std project
> Fix Manutech for Power Plant std project

- src/cards/venusNext/HydrogenToVenus.ts
- tests/cards/venusNext/HydrogenToVenus.spec.ts
Adds filtering to the Hydrogen To Venus card to only allow selection of venus cards.
> Only allow selection of venus cards for HydrogenToVenus

- src/HTML_data.ts
- src/cards/ViralEnhancers.ts
- tests/cards/ViralEnhancers.spec.ts
This change applies any bonus for viral enhancers separately.
> Apply each tag bonus separately for ViralEnhancers

- src/components/Card.ts
- src/directives/i18n.ts
- src/styles/cards.less
There are more players showing up who speak better languages than english. I noticed we don't translate the cards. I have put in this first change to translate direct matching parts of the card. I will put in another check next to efficiently find strings that are close and replace the translations we have for those so that we do not need a direct match.
> Translate more parts of the card

- src/components/Card.ts
- src/components/Preferences.ts
- src/directives/i18n.ts
- src/locales/ru/cards.json
- src/locales/ru/ui.json
- src/styles/cards.less
- src/styles/common.less
- src/styles/language_hacks.less
Some additions to make cards localization easier
> Cards localization

- server.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/Player.ts
- src/ResourceType.ts
- src/awards/Excentric.ts
- src/cards/promo/SelfReplicatingRobots.ts
- src/components/SelectHowToPayForCard.ts
- src/models/PlayerModel.ts
- tests/cards/promo/SelfReplicatingRobots.spec.ts
- tsconfig-test.json
> Add self replicating Robots

- server.ts
- src/Dealer.ts
- src/Game.ts
- src/cards/RoboticWorkforce.ts
- src/components/Card.ts
- src/components/CreateGameForm.ts
- src/interrupts/SelectResourceProductionDecrease.ts
- tests/cards/venusNext/DawnCity.spec.ts
- tests/cards/venusNext/LunaMetropolis.spec.ts
- tests/cards/venusNext/MaxwellBase.spec.ts
- tests/cards/venusNext/Stratopolis.spec.ts
- Add promo cards as an option
- Allow to select between 1 and 6 corporation for starting game, 2 is the default
- Fix bug with Hackers (see issue #648)
- Fix Robotic Workforce works incorrectly with Preludes
> Add options

- src/Player.ts
- src/cards/colonies/Aridor.ts
Issue #648 part 1
And also fix for issue #655
> Fix Aridor colony activation bug

- src/Game.ts
- src/Player.ts
Flushes any pending interrupts which may have happened during a world government phase prior to finishing the world government phase.
> During world government phase take any interrupts prior to next phase

- src/interrupts/SelectParty.ts
This should fix the delegate bug that give 5 M€ instead of removing it.
> Fix delegate

- src/interrupts/SelectParty.ts
Parties list to remove delegate from was always empty
> Fix Reqruitment card party selection

- src/Game.ts
- src/cards/promo/SelfReplicatingRobots.ts
- tests/cards/promo/SelfReplicatingRobots.spec.ts
- tests/globalEvents/MudSlides.spec.ts
- Throw an error if M€ goes negative after card selection
- Fix Mudslides flaky test
- Add log message for Self Replicating Robots
> Negative mc

- src/Player.ts
Add corporation card to result if relevant
> Fix getCardsWithResources

- src/cards/Asteroid.ts
- src/cards/BigAsteroid.ts
- src/cards/Comet.ts
- src/cards/DeimosDown.ts
- src/cards/GiantIceAsteroid.ts
- src/cards/promo/HiTechLab.ts
- src/cards/promo/SmallAsteroid.ts
- Set minimum amount to 1 for Hi Tech Lab
- Reorder of the interrupts for the following cards so remove plant action will always be resolved after Arctic Algae.
ASTEROID
COMET
BIG ASTEROID
DEIMOS DOWN
GIANT ICE ASTEROID
SMALL ASTEROID
> Fix HiTechLab and reorder interrupts

- src/constants.ts
- src/styles/language_switcher.less
> fix flag button

- src/components/CreateGameForm.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/721
> Automatically set player name if not entered

- server.ts
- src/Game.ts
- src/Player.ts
- src/SerializedPlayer.ts
- src/components/CreateGameForm.ts
- src/database/IDatabase.ts
- src/database/SQLite.ts
- tests/Turmoil.spec.ts
- tests/cards/turmoil/AerialLenses.spec.ts
- tests/cards/turmoil/BannedDelegate.spec.ts
- tests/cards/turmoil/CulturalMetropolis.spec.ts
- tests/cards/turmoil/DiasporaMovement.spec.ts
- tests/cards/turmoil/EventAnalysts.spec.ts
- tests/cards/turmoil/GMOContract.spec.ts
- tests/cards/turmoil/MartianMediaCenter.spec.ts
- tests/cards/turmoil/PROffice.spec.ts
- tests/cards/turmoil/ParliamentHall.spec.ts
- tests/cards/turmoil/PublicCelebrations.spec.ts
- tests/cards/turmoil/Recruitment.spec.ts
- tests/cards/turmoil/RedTourismWave.spec.ts
- tests/cards/turmoil/SponsoredMohole.spec.ts
- tests/cards/turmoil/SupportedResearch.spec.ts
- tests/cards/turmoil/VoteOfNoConfidence.spec.ts
- tests/cards/turmoil/WildlifeDome.spec.ts
- tests/cards/venusNext/DawnCity.spec.ts
- tests/cards/venusNext/LunaMetropolis.spec.ts
- tests/cards/venusNext/MaxwellBase.spec.ts
- tests/cards/venusNext/Stratopolis.spec.ts
Add a new feature to allow to replay an existing game.
The number of players in the create game form must match the number of players for the cloned game.
> Replay games

- server.ts
- src/Game.ts
- src/Player.ts
- src/components/CreateGameForm.ts
- tests/Turmoil.spec.ts
- tests/cards/turmoil/AerialLenses.spec.ts
- tests/cards/turmoil/BannedDelegate.spec.ts
- tests/cards/turmoil/CulturalMetropolis.spec.ts
- tests/cards/turmoil/DiasporaMovement.spec.ts
- tests/cards/turmoil/EventAnalysts.spec.ts
- tests/cards/turmoil/GMOContract.spec.ts
- tests/cards/turmoil/MartianMediaCenter.spec.ts
- tests/cards/turmoil/PROffice.spec.ts
- tests/cards/turmoil/ParliamentHall.spec.ts
- tests/cards/turmoil/PublicCelebrations.spec.ts
- tests/cards/turmoil/Recruitment.spec.ts
- tests/cards/turmoil/RedTourismWave.spec.ts
- tests/cards/turmoil/SponsoredMohole.spec.ts
- tests/cards/turmoil/SupportedResearch.spec.ts
- tests/cards/turmoil/VoteOfNoConfidence.spec.ts
- tests/cards/turmoil/WildlifeDome.spec.ts
- tests/cards/venusNext/DawnCity.spec.ts
- tests/cards/venusNext/LunaMetropolis.spec.ts
- tests/cards/venusNext/MaxwellBase.spec.ts
- tests/cards/venusNext/Stratopolis.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/728
> Fix: Make allowing Undo optional

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/turmoil/SeptumTribus.ts
- src/cards/turmoil/TurmoilCorporation.ts
- tests/cards/turmoil/SeptumTribus.spec.ts
**Scope:** Add Septum Tribus (Turmoil corporation)
> Add Septum Tribus corporation

- tests/cards/turmoil/SeptumTribus.spec.ts
> Update test for Septum Tribus

- src/Game.ts
- src/colonies/ColonyDealer.ts
Fixes some bugs linked with replay feature.
> Replay feature bug fixes and cleanup

- src/Player.ts
**Scope:**
- Fix milestones' positions in player actions list and ensure consistent title
- Fix terminal sequence of "End Turn", "Pass" and "Undo Turn" in player actions list
**Ref:** https://github.com/bafolts/terraforming-mars/issues/726
> Sort actions

- src/cards/colonies/MarketManipulation.ts
- tests/cards/colonies/MarketManipulation.spec.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/423
This fix involves minimal code change, so we don't have to rewrite and pass additional arguments around
> Suggestion: Fix minor issue for Market Manipulation

- src/Player.ts
**Context:** Show info about number of cards sold in the log
> Improve sell patents description

- src/cards/colonies/Arklight.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/760
> Fix: Arklight should not gain resources when other players play cards

- src/components/CreateGameForm.ts
**Context:** Initial draft is set to true by default, and it gives a strange experience in solo mode
**Suggested fix:** Switch this variant off by default
> Set initial draft to off by default

- src/Player.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/749#issue-627949117
**Suggested order:** (for all possible actions across all expansions)
1. Claim a milestone
2. Convert 8 heat to temperature
3. Convert n plants to greenery
4. Perform an action from a played card
5. Play project card
6. Send a delegate (from lobby/reserve)
7. Trade with a colony
8. Fund an award
9. Pay for a Standard Project
10. End turn
11. Pass
12. Sell patents
13. Undo turn
> Update actions list order

- package-lock.json
- package.json
- src/database/Database.ts
- src/database/PostgreSQL.ts
Heroku supports a free postgres database that can be upgraded if need be. This change adds the addition of a postgres IDatabase implementation.
> Add postgres database for heroku

- src/locales/ru/ui.json
- src/milestones/Milestones.ts
- src/milestones/Tactician.ts
- src/styles/player_home.less
**Scope:** Fix typo and rename file
> Fix typo for Tactician

- src/Player.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForCard.ts
Ref:
https://github.com/bafolts/terraforming-mars/issues/359
https://github.com/bafolts/terraforming-mars/issues/749
> Improve payment validation: Add warning confirmation if player is overpaying

- src/cards/venusNext/Celestic.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/792
> Fix: Celestic should be able to draw any card with floater icon(s)

- src/Game.ts
@vincentneko I updated to randomize Venus milestone and award as well, if the option is selected
> Also randomize Venus milestone and award if option selected

- src/cards/Ants.ts
- tests/cards/Ants.spec.ts
Similar implementation to Predators if there is only 1 valid target - should not need to click
> Auto select target for Ants if there is only 1 choice

- src/cards/colonies/AirRaid.ts
- tests/cards/colonies/AirRaid.spec.ts
**Scope:**
- Automatically remove floater if there is only one possible valid target
- Automatically remove MC if there is only one other opponent player
> Improvement for Air Raid

- src/cards/AerobrakedAmmoniaAsteroid.ts
- tests/cards/AerobrakedAmmoniaAsteroid.spec.ts
Add microbes automatically if only one target
> Improve Aerobraked Ammonia Asteroid

- src/cards/EOSChasmaNationalPark.ts
- src/cards/LargeConvoy.ts
- src/cards/venusNext/VenusianPlants.ts
- tests/cards/EOSChasmaNationalPark.spec.ts
- tests/cards/LargeConvoy.spec.ts
- tests/cards/venusNext/VenusianPlants.spec.ts
**Scope:** Improve EOS Chasma National Park, Venusian Plants and Large Convoy to add resource immediately when there is only one valid target
> Improve add animal cards

- src/cards/venusNext/CorroderSuits.ts
- src/cards/venusNext/FloatingHabs.ts
- src/cards/venusNext/MaxwellBase.ts
- src/cards/venusNext/VenusSoils.ts
- tests/cards/venusNext/CorroderSuits.spec.ts
- tests/cards/venusNext/FloatingHabs.spec.ts
- tests/cards/venusNext/MaxwellBase.spec.ts
- tests/cards/venusNext/VenusSoils.spec.ts
**Scope:** Corroder Suits, Floating Habs, Maxwell Base, Venus Soils
Will address **Thermophiles** separately after https://github.com/bafolts/terraforming-mars/pull/802 is merged
> Improve Venus cards: Skip selection if only one possible target

- src/Player.ts
- src/cards/Ants.ts
- src/cards/Predators.ts
- src/components/CreateGameForm.ts
> Improvement: Better logs for Ants and Predators

- src/Game.ts
- src/cards/turmoil/Pristar.ts
- src/components/PlayerHome.ts
Resolve Turmoil interrupts before research phase
Display Turmoil board on select card screen
> Fix Turmoil interrupts

- src/cards/venusNext/StratosphericBirds.ts
- tests/cards/venusNext/StratosphericBirds.spec.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/818
> Patch: Handle edge case for Stratospheric Birds

- src/cards/colonies/TitanAirScrapping.ts
- src/cards/venusNext/ForcedPrecipitation.ts
- src/cards/venusNext/JetStreamMicroscrappers.ts
- src/cards/venusNext/LocalShading.ts
- src/cards/venusNext/RotatorImpacts.ts
- src/cards/venusNext/SulphurEatingBacteria.ts
- tests/cards/colonies/TitanAirScrapping.spec.ts
- tests/cards/venusNext/ForcedPrecipitation.spec.ts
- tests/cards/venusNext/JetStreamMicroscrappers.spec.ts
- tests/cards/venusNext/RotatorImpacts.spec.ts
- tests/cards/venusNext/SulphurEatingBacteria.spec.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/822
**Scope:**
- Add missing return statements
- Add unit tests
- Clean up `RotatorImpacts`
> Fix bug on some cards caused by missing return statements

- src/cards/ExtremeColdFungus.ts
- src/cards/colonies/EcologyResearch.ts
- src/cards/colonies/UrbanDecomposers.ts
- tests/cards/ExtremeColdFungus.spec.ts
- tests/cards/colonies/EcologyResearch.spec.ts
- tests/cards/colonies/UrbanDecomposers.spec.ts
**Scope:**
- Improve Ecology Research and Urban Decomposers
- Improve unit tests
- Swap action order for Extreme Cold Fungus
> Improve colonies cards

- src/locales/de/cards.json
This is the last bunch of cards from the base game. 🎉
> Added German translation for cards 201 to 208

- src/HTML_data.ts
- src/styles/cards.less
> Improve Mons Insurance display

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/promo/Advertising.ts
- tests/cards/promo/Advertising.spec.ts
> Add Advertising promo card

- src/HTML_data.ts
- src/styles/cards.less
> Minor CSS edit for Arcadian Communities and Factorum

- src/cards/RoboticWorkforce.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/843
> Fix: Robotic Workforce should be able to copy Spinoff Department

- src/HTML_data.ts
- src/styles/cards.less
> Minor CSS edits for remaining corps

- src/cards/LocalHeatTrapping.ts
- tests/cards/LocalHeatTrapping.spec.ts
**Scenario:** Helion player has 5 heat, pays 1 to play card. Now there is not enough heat left to spend 5 for the card's effect
> Fix edge case for Local Heat Trapping

- server.ts
- src/Dealer.ts
- src/components/PlayerHome.ts
- src/components/Preferences.ts
- src/models/PlayerModel.ts
- src/styles/player_home.less
Counter shows how many cards remaining in the deck
> Counter for cards remaining in deck

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/promo/CometAiming.ts
- src/styles/cards.less
- tests/cards/promo/CometAiming.spec.ts
> Add Comet Aiming promo card

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/promo/CuttingEdgeTechnology.ts
- src/styles/cards.less
- tests/cards/promo/CuttingEdgeTechnology.spec.ts
> Add Cutting Edge Technology promo card

- src/CardName.ts
- src/HTML_data.ts
- src/cards/turmoil/TurmoilCorporation.ts
**Scope:** Fix a typo in the displayed name
> Minor: Update display name for Septem Tribus

- src/Player.ts
- src/cards/ImmigrantCity.ts
- src/cards/corporation/TharsisRepublic.ts
- tests/cards/ImmigrantCity.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/849
> Fix edge cases for Immigrant City

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/promo/FieldCappedCity.ts
- src/styles/cards.less
- tests/cards/promo/FieldCappedCity.spec.ts
> Add Field-Capped City promo card

- src/Game.ts
- src/Player.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/865
> Fix: Philares should receive bonus for final greenery placements

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/promo/MagneticShield.ts
- tests/cards/promo/MagneticShield.spec.ts
> Add Magnetic Shield promo card

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/promo/Meltworks.ts
- tests/cards/promo/Meltworks.spec.ts
> Add Meltworks promo card

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/promo/MoholeLake.ts
- tests/cards/promo/MoholeLake.spec.ts
> Add Mohole Lake promo card (?)

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/promo/DiversitySupport.ts
- src/cards/promo/JovianEmbassy.ts
- src/cards/promo/MoholeLake.ts
- src/styles/cards.less
- tests/cards/promo/DiversitySupport.spec.ts
- tests/cards/promo/JovianEmbassy.spec.ts
- tests/cards/promo/MoholeLake.spec.ts
> Add Jovian Embassy promo card; update Mohole Lake and Diversity Support

- src/HTML_data.ts
- src/locales/ru/colonies_cards.json
- src/locales/ru/colonies_corporations.json
Colonies cards translated into Russian
> Colonies cards i18n

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/Player.ts
- src/cards/Ants.ts
- src/cards/GHGProducingBacteria.ts
- src/cards/NitriteReducingBacteria.ts
- src/cards/RegolithEaters.ts
- src/cards/Tardigrades.ts
- src/cards/prelude/Psychrophiles.ts
- src/cards/promo/ImportedNutrients.ts
- src/cards/promo/Recyclon.ts
- src/cards/promo/TopsoilContract.ts
- src/cards/venusNext/Extremophiles.ts
- src/cards/venusNext/SulphurEatingBacteria.ts
- src/cards/venusNext/Thermophiles.ts
- src/cards/venusNext/VenusianInsects.ts
- src/styles/cards.less
- tests/cards/Tardigrades.spec.ts
- tests/cards/prelude/Psychrophiles.spec.ts
- tests/cards/promo/ImportedNutrients.spec.ts
- tests/cards/promo/TopsoilContract.spec.ts
- tests/cards/venusNext/VenusianInsects.spec.ts
Also updated all "add microbe" effects to use `player.addResourceTo`
> Add Topsoil Contract and Imported Nutrients promo cards

- src/CardName.ts
- src/Dealer.ts
- src/Game.ts
- src/HTML_data.ts
- src/Player.ts
- src/cards/Virus.ts
- src/cards/promo/AsteroidDeflectionSystem.ts
- src/cards/promo/SubCrustMeasurements.ts
- src/styles/cards.less
- tests/cards/promo/AsteroidDeflectionSystem.spec.ts
- tests/cards/promo/SubCrustMeasurements.spec.ts
- Extend logic: Plants can now be protected by two different cards
> Add Asteroid Deflection System and Sub-Crust Measurements

- server.ts
- src/Game.ts
- src/components/CreateGameForm.ts
- src/locales/ru/ui.json
> An option to set number of rounds of initial draft

- src/components/CreateGameForm.ts
**Scope:** Clear a TODO item to check and auto assign colors in case of duplicates
> Auto assign an available color if players picked duplicate colors

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/promo/Potatoes.ts
- tests/cards/promo/Potatoes.spec.ts
> Add Potatoes promo card

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/Player.ts
- src/cards/Birds.ts
- src/cards/Fish.ts
- src/cards/Herbivores.ts
- src/cards/Livestock.ts
- src/cards/Pets.ts
- src/cards/Predators.ts
- src/cards/SmallAnimals.ts
- src/cards/colonies/Arklight.ts
- src/cards/colonies/SubZeroSaltFish.ts
- src/cards/promo/MeatIndustry.ts
- src/cards/promo/Penguins.ts
- src/cards/venusNext/StratosphericBirds.ts
- tests/cards/Birds.spec.ts
- tests/cards/Fish.spec.ts
- tests/cards/Livestock.spec.ts
- tests/cards/Pets.spec.ts
- tests/cards/SmallAnimals.spec.ts
- tests/cards/colonies/SubZeroSaltFish.spec.ts
- tests/cards/promo/MeatIndustry.spec.ts
- tests/cards/promo/Penguins.spec.ts
- tests/cards/venusNext/StratosphericBirds.spec.ts
> Add Meat Industry promo card

- src/Game.ts
- tests/Turmoil.spec.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/915
World Government terraforming should not give steel placement bonus from Mars First ruling policy.
> Fix: Mars First ruling policy shouldn't trigger on worldGov terraforming

- src/Game.ts
- src/Player.ts
- src/cards/corporation/UnitedNationsMarsInitiative.ts
- src/cards/turmoil/CulturalMetropolis.ts
- src/cards/turmoil/MartianMediaCenter.ts
- src/cards/turmoil/Pristar.ts
- src/cards/turmoil/Recruitment.ts
- src/cards/turmoil/VoteOfNoConfidence.ts
- src/turmoil/globalEvents/HomeworldSupport.ts
- src/turmoil/parties/Greens.ts
- src/turmoil/parties/MarsFirst.ts
- src/turmoil/parties/Scientists.ts
- src/turmoil/parties/Unity.ts
- tests/cards/turmoil/Pristar.spec.ts
I did something wrong in last pull request so I close that one and create this new one. Sorry for the inconvenience (and forgive me, the poor GitHub beginner)!
> Delegates and wildtag bug fixed

- src/cards/colonies/MarketManipulation.ts
- tests/cards/colonies/MarketManipulation.spec.ts
> fixbugs #939

- src/Player.ts
- src/cards/corporation/Inventrix.ts
- src/colonies/Callisto.ts
- src/colonies/Ceres.ts
- src/colonies/Europa.ts
- src/colonies/Ganymede.ts
- src/colonies/Io.ts
- src/colonies/Luna.ts
- src/colonies/Pluto.ts
- src/colonies/Triton.ts
- src/components/LogHelper.ts
> Add logs to indicate quantity of resources gained from Colony trades

- src/cards/Moss.ts
- src/cards/NitrophilicMoss.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/931
Partial fix (point 1 only)
> Fix edge case: Manutech can play Moss cards with 1 less plant required

- src/cards/promo/AsteroidHollowing.ts
- src/cards/promo/Astrodrill.ts
- src/cards/promo/CometAiming.ts
- src/cards/promo/CrashSiteCleanup.ts
- src/cards/promo/DirectedImpactors.ts
- src/cards/promo/MoholeLake.ts
- src/cards/promo/PharmacyUnion.ts
- tests/cards/promo/AsteroidDeflectionSystem.spec.ts
- tests/cards/promo/AsteroidHollowing.spec.ts
- tests/cards/promo/Astrodrill.spec.ts
- tests/cards/promo/CometAiming.spec.ts
- tests/cards/promo/CrashSiteCleanup.spec.ts
- tests/cards/promo/DeimosDownPromo.spec.ts
- tests/cards/promo/DirectedImpactors.spec.ts
- tests/cards/promo/DiversitySupport.spec.ts
- tests/cards/promo/GreatDamPromo.spec.ts
- tests/cards/promo/ImportedNutrients.spec.ts
- tests/cards/promo/MagneticFieldGeneratorsPromo.spec.ts
- tests/cards/promo/MagneticShield.spec.ts
- tests/cards/promo/Meltworks.spec.ts
- tests/cards/promo/MoholeLake.spec.ts
- tests/cards/promo/PharmacyUnion.spec.ts
- tests/cards/promo/Potatoes.spec.ts
- tests/cards/promo/SubCrustMeasurements.spec.ts
- tests/cards/promo/TopsoilContract.spec.ts
**Scope:**
- Add logs for Big Box promo cards
- Cleanup and improve tests
> Add bigbox promo logs

- src/HTML_data.ts
- src/styles/cards.less
**Ref:** https://github.com/bafolts/terraforming-mars/issues/955
> Fix CSS class for Pharmacy Union

- src/components/GameEnd.ts
> Fix endgame corporation display

- src/HTML_data.ts
- src/styles/cards.less
> Fix PharmacyUnion expansion icon and RedSpotObservatory CSS

- src/cards/promo/Astrodrill.ts
- tests/cards/promo/Astrodrill.spec.ts
If there is only one option available, it does not need to be a click.
> Improve Astrodrill: Remove unnecessary click

- src/cards/RoboticWorkforce.ts
There might be more cards need be added into,I have no time to check it all
> add  promo cards into RoboticWorkforce 's copy list

- src/cards/EcologicalZone.ts
- src/cards/NuclearZone.ts
- src/cards/promo/DeimosDownPromo.ts
- src/cards/promo/GreatDamPromo.ts
- src/cards/promo/MagneticFieldGeneratorsPromo.ts
- src/cards/turmoil/WildlifeDome.ts
- tests/cards/promo/MagneticFieldGeneratorsPromo.spec.ts
This commit fixes edge case bugs for some cards that require placing a tile. We should check that there is an available space to place the tile on.
> Fix canPlay for some tile placement cards

- src/components/CreateGameForm.ts
- src/components/GameEnd.ts
- src/locales/de/game_end.json
- src/locales/de/ui.json
- src/locales/ru/game_end.json
- src/locales/ru/ui.json
- src/styles/create_game_form.less
Ref: https://github.com/bafolts/terraforming-mars/issues/873
> Add tooltips for game options

- src/HTML_data.ts
- src/locales/ru/promo.json
> Improve wording for Diversity Support requirement

- src/milestones/Tactician.ts
- tests/milestones/Tactician.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/995
> Fix: Tactician should not count Event cards

- server.ts
- src/Player.ts
- src/components/PaymentWidgetMixin.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForCard.ts
- src/inputs/HowToPay.ts
- src/models/PlayerModel.ts
- tests/cards/BusinessNetwork.spec.ts
- tests/cards/venusNext/RotatorImpacts.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1000
(Checking by title to avoid introducing too many changes)
> Fix: Allow Helion to adjust MC amount when buying cards during Research

- src/Game.ts
- src/Player.ts
- src/colonies/Pluto.ts
- src/interrupts/PlayerInterrupt.ts
- src/interrupts/SelectDiscard.ts
This will fix issue #949 and will add some logic to run some code at interrupt resolution (like draw a card for Pluto colony bonus)
> Add interrupt beforeAction logic

- src/cards/BusinessNetwork.ts
- src/cards/InventorsGuild.ts
- src/cards/corporation/Inventrix.ts
- src/colonies/Pluto.ts
- src/components/LogHelper.ts
Add a log to show whether the player drew or discarded the card when using Business Networks and Inventor's Guild.
> Log action for Business Network and Inventor's Guild

- server.ts
- src/Player.ts
- src/ResourceType.ts
- src/awards/Excentric.ts
- src/cards/promo/SelfReplicatingRobots.ts
- src/components/LogPanel.ts
- src/components/OtherPlayer.ts
- src/components/PlayerHome.ts
- src/components/SelectHowToPayForCard.ts
- src/models/PlayerModel.ts
- tests/cards/promo/SelfReplicatingRobots.spec.ts
This one is long overdue !
Self Replicating Robots can now store multiple cards.
Stored cards under SRR are displayed in a separate section, with counters.
> Robots strike back

- src/cards/promo/CometAiming.ts
- tests/cards/promo/CometAiming.spec.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/1019
> Fix bugs for Comet Aiming

- src/Dealer.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1028
> Fix: Saturn Surfing appears in wrong deck

- src/HTML_data.ts
- src/cards/venusNext/VenusSoils.ts
- src/locales/ru/venus_next_cards.json
Ref: https://github.com/bafolts/terraforming-mars/issues/1023
> Fix prompt for Venus Soils

- src/CorporationName.ts
- src/components/CorporationsFilter.ts
- src/components/CreateGameForm.ts
Custom corporation list is no longer all selected by default.
> Populate custom corporation list based on selected expansions.

- src/turmoil/globalEvents/DryDeserts.ts
- src/turmoil/globalEvents/SnowCover.ts
- tests/globalEvents/SnowCover.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1033
> Fix: Global Events should not reduce maxed global parameters

- src/cards/promo/MagneticFieldGeneratorsPromo.ts
- tests/Turmoil.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1037
> Fix playability of MagneticFieldGenerators when Reds are ruling

- server.ts
- src/components/Award.ts
- src/components/Milestone.ts
- src/components/Preferences.ts
- src/components/PreferencesManager.ts
- src/milestones/Builder.ts
- src/milestones/Diversifier.ts
- src/milestones/Ecologist.ts
- src/milestones/Energizer.ts
- src/milestones/Gardener.ts
- src/milestones/Generalist.ts
- src/milestones/Hoverlord.ts
- src/milestones/IMilestone.ts
- src/milestones/Legend.ts
- src/milestones/Mayor.ts
- src/milestones/Planner.ts
- src/milestones/PolarExplorer.ts
- src/milestones/RimSettler.ts
- src/milestones/Specialist.ts
- src/milestones/Tactician.ts
- src/milestones/Terraformer.ts
- src/milestones/Tycoon.ts
- src/models/ClaimedMilestoneModel.ts
- src/models/FundedAwardModel.ts
- src/styles/player_home.less
- src/styles/preferences.less
This will display current score for each player for milestones and awards.
The layout is far from perfect...
This will help a lot for some milestones / awards (looking at you Tycoon, Celebrity and Excentric)
It can be deactivated through game preferences.
Thanks @pierrehilbert for the sort !
> Improve ms awards

- src/Player.ts
- src/locales/de/ui.json
- src/locales/ru/ui.json
- src/milestones/Builder.ts
- src/milestones/Ecologist.ts
- src/milestones/Energizer.ts
- src/milestones/Generalist.ts
- src/milestones/Hoverlord.ts
- src/milestones/Legend.ts
- src/milestones/Planner.ts
- src/milestones/RimSettler.ts
- src/milestones/Specialist.ts
- src/milestones/Tactician.ts
- src/milestones/Terraformer.ts
- src/milestones/Tycoon.ts
- tests/Game.spec.ts
- tests/milestones/Tactician.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/903#issuecomment-662669763
- Clearer wording for Pass option
- Clean up some milestones and awards code
> Minor improvements

- server.ts
- src/components/Award.ts
- src/components/Milestone.ts
- src/models/ClaimedMilestoneModel.ts
- src/models/FundedAwardModel.ts
- src/styles/player_home.less
I implemented @ssimeonoff suggestion.
> Improve rending for ms awards ranking

- src/components/LogPanel.ts
- src/components/OtherPlayer.ts
- src/components/PlayerHome.ts
- src/components/Preferences.ts
- src/components/PreferencesManager.ts
- src/styles/preferences.less
And also remove RES:0 for all log cards
> Add option hide non-blue cards

- src/components/Award.ts
- src/components/Milestone.ts
Remove whitespace from Award id and onclick in template. This is to fix #1072 
Assuming this works, I will modify Milestone.ts similarly.
> Fix for #1072 Award Info does not display

- src/Player.ts
- src/components/PaymentWidgetMixin.ts
- src/components/SelectHowToPay.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/1075
> Fix: Allow Helion to spend heat during Research phase

- src/ElysiumBoard.ts
- src/OriginalBoard.ts
> fix #1076 infinity loop

- src/styles/cards.less
> Fix title display for Technology Demonstration

- tests/Game.spec.ts
- tests/TestingUtils.ts
- tests/Turmoil.spec.ts
- tests/cards/turmoil/AerialLenses.spec.ts
- tests/cards/turmoil/BannedDelegate.spec.ts
- tests/cards/turmoil/CulturalMetropolis.spec.ts
- tests/cards/turmoil/DiasporaMovement.spec.ts
- tests/cards/turmoil/EventAnalysts.spec.ts
- tests/cards/turmoil/GMOContract.spec.ts
- tests/cards/turmoil/MartianMediaCenter.spec.ts
- tests/cards/turmoil/PROffice.spec.ts
- tests/cards/turmoil/ParliamentHall.spec.ts
- tests/cards/turmoil/PoliticalAlliance.spec.ts
- tests/cards/turmoil/PublicCelebrations.spec.ts
- tests/cards/turmoil/Recruitment.spec.ts
- tests/cards/turmoil/RedTourismWave.spec.ts
- tests/cards/turmoil/SeptumTribus.spec.ts
- tests/cards/turmoil/SponsoredMohole.spec.ts
- tests/cards/turmoil/SupportedResearch.spec.ts
- tests/cards/turmoil/VoteOfNoConfidence.spec.ts
- tests/cards/turmoil/WildlifeDome.spec.ts
- tests/cards/venusNext/DawnCity.spec.ts
- tests/cards/venusNext/LunaMetropolis.spec.ts
- tests/cards/venusNext/MaxwellBase.spec.ts
- tests/cards/venusNext/Stratopolis.spec.ts
This will make it easier to update existing/introduce new game options, as we won't have to modify gameOptions-related code in 20+ test files.
> Refactor to TestingUtils.setCustomGameOptions()

- src/components/CreateGameForm.ts
- src/locales/de/ui.json
- src/locales/ru/ui.json
Missing the updated Russian translation
> Clearer name for TR solo mode option

- README.md
- src/Board.ts
And also add a link to the discord on the README
> Fix issue #1080

- src/HTML_data.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/1088
> Update Astrodrill description

- src/cards/ImportedNitrogen.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/1085
Microbes / animals should only be added once.
> Fix microbes exploit for Imported Nitrogen

- src/components/GameEnd.ts
- src/locales/ru/colonies_cards.json
- src/locales/ru/promo.json
- src/locales/ru/ui.json
- src/styles/game_end.less
> Go home btn

- src/database/PostgreSQL.ts
- src/database/SQLite.ts
- Finished games will now appear in the clonable game list
- Auto pruning of unfinished games. When a game is finished, a query will be launched to purge other unfinished games that are older than 10 days.
@bafolts this should reduce the memory footprint and maybe avoid to manually purge the table. 10 days is maybe too high, we can change this if needed.
> Enable clone finished game and auto prune

- src/components/CreateGameForm.ts
Concerning #1058
/new-game
+ toggle beginner corp switch interface on toggling "initial draft"
+ toggle beginner corp switch interface on toggling any corporation
> Beginner corp ui improvements

- src/Game.ts
- src/components/LogHelper.ts
> Add simple log showing tile placement's coordinates

- src/Game.ts
- src/database/IDatabase.ts
- src/database/PostgreSQL.ts
- src/database/SQLite.ts
Create game_results table in postgreSQL database only.
A row will be inserted for each finished game.
Tested locally on my laptop with a local postgreSQL database with a solo game.
> Add game results

- src/components/PaymentWidgetMixin.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForCard.ts
I believe this fixes issue #969 by ignoring attempts to use more resources once MC need is 0.
> Fix overpayment of resources

- src/components/Board.ts
- src/styles/preferences.less
#1130
+Fixed oceans NaN in initial phase
+Smaller cards scale properly on selection now
> Minor fixes after ui update

- src/Player.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/1144
The option to spend 8 heat to raise temperature or X plants to place greenery should not be available if it raises TR while Reds are ruling and player cannot afford to pay the 3 MC cost.
> Fix: Should not be able to spend 8 heat/plants to raise TR if can't afford Reds

- src/Player.ts
- tests/cards/promo/MonsInsurance.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1150
> Fix: MonsInsurance shouldn't payout when player removes own resources

- src/components/CreateGameForm.ts
- src/locales/cn/ui.json
- src/locales/de/ui.json
- src/locales/ru/ui.json
#1141
Changed the label to WGT as discussed in discord.
We need someone to update the wiki too. I'll add the proper link to the (i) button once this is done.
Edit. We can leave the wiki as it is. Merge whenever
> Changed label

- src/cards/colonies/TitanShuttles.ts
- tests/cards/colonies/TitanShuttles.spec.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/1143
> Improve TitanShuttles: Skip selection steps if only 1 choice

- src/Player.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1163
> Fix button label when there is only one SP option

- src/cards/turmoil/UtopiaInvest.ts
- src/components/StartScreen.ts
- src/locales/ru/start_screen.json
+ by popular demand in discord - changing the "Chat with us" to "Join us on Discord"
@alrusdi need some help with the ru translation for "Join us on Discord"
> +Changed home page chat with us +changed button label of UtopiaInvest

- src/cards/promo/Splice.ts
- tests/cards/promo/Splice.spec.ts
> Fixed splice to add +2 for each microbe played

- src/cards/venusNext/Atmoscoop.ts
Not sure if it will change anything but it makes more sense to return undefined.
> Tentative fix for 1172

- src/cards/Tags.ts
- src/components/PlayerHome.ts
- src/components/TagOverview.ts
- src/styles/common.less
- src/styles/player_home.less
- stars background (as the homepage)
- tags sorted by priority/frequency
- minor css
> tags overview ui

- src/cards/venusNext/Atmoscoop.ts
This one should fix it. (issue #1172)
> Fix options[0]

- server.ts
- src/Game.ts
- src/Player.ts
- src/components/CreateGameForm.ts
- Rework initial draft, following Kyshantry guidelines (see below)
- Remove Initial Draft rounds option and parameter.
start with a hand of 5, pick one, pass the remainder left
you receive 4, pick one, pass the remainder left
lather rinse and repeat
til that pack is gone
then start with another hand of 5, pick one, pass right
lather rinse repeat
> Initial draft v2

- server.ts
- src/Game.ts
- src/components/PlayerHome.ts
- src/models/PlayerModel.ts
Enable draft of prelude cards if initial draft and prelude option are activated.
Preludes will be drafted after the 2 rounds of 5 project cards draft.
> Prelude drafting

- server.ts
- src/BoardName.ts
- src/Game.ts
- src/Player.ts
- src/components/CreateGameForm.ts
Also rename original board to Tharsis as suggested by @ssimeonoff
> Fast mode option

- src/components/Board.ts
- src/locales/cn/ui.json
- src/locales/de/ui.json
- src/locales/ru/ui.json
Ref: https://github.com/bafolts/terraforming-mars/issues/1228
> Update map name references from original to tharsis

- server.ts
- src/Game.ts
- src/Player.ts
- src/cards/LavaFlows.ts
- src/cards/NoctisCity.ts
- src/cards/colonies/Aridor.ts
- src/cards/colonies/Poseidon.ts
- src/cards/prelude/LavaTubeSettlement.ts
- src/cards/prelude/ValleyTrust.ts
- src/cards/turmoil/SeptumTribus.ts
- src/milestones/Terraformer.ts
- src/turmoil/globalEvents/GlobalEventDealer.ts
- src/turmoil/parties/PartyHooks.ts
- tests/Game.spec.ts
- tests/cards/colonies/MarketManipulation.spec.ts
Remove individual options variables in game to rely only on gameOptions
> Rework game options

- src/cards/colonies/AirRaid.ts
- src/inputs/AndOptions.ts
- tests/cards/colonies/AirRaid.spec.ts
> Improve Air Raid to show MC amount stolen

- src/database/SQLite.ts
date('now', '-10 day') is a date and created_time is a timestamp
> Fix sqlite prune

- src/cards/prelude/Vitor.ts
> Add missing label for Vitor initial action

- src/Player.ts
- src/components/OrOptions.ts
- src/locales/ru/colonies.json
Select how to pay and colony in a single step
@bafolts thanks for fixing the OrOptions issue !
> Colony trade rework

- server.ts
- src/Game.ts
- src/Player.ts
- src/cards/LavaFlows.ts
- src/cards/NoctisCity.ts
- src/cards/colonies/Aridor.ts
- src/cards/colonies/Poseidon.ts
- src/cards/prelude/LavaTubeSettlement.ts
- src/cards/prelude/ValleyTrust.ts
- src/cards/turmoil/SeptumTribus.ts
- src/milestones/Terraformer.ts
- src/turmoil/globalEvents/GlobalEventDealer.ts
- src/turmoil/parties/PartyHooks.ts
- tests/Game.spec.ts
- tests/cards/colonies/MarketManipulation.spec.ts
Reverts bafolts/terraforming-mars#1223
I don't think this change is serializing the game properly. Upon restoring games from database or an undo action I assume all game options are being lost.
> Revert "Rework game options"

- src/HTML_data.ts
- src/styles/cards.less
+ fix for some cards that could not have their description read because of res box
> Hover show description over res box

- server.ts
- src/Dealer.ts
- src/Game.ts
- src/components/CardsFilter.ts
- src/components/CreateGameForm.ts
- src/styles/cards_filter.less
- src/styles/common.less
- tests/TestingUtils.ts
Ability to exclude some cards from the game
Please check my english too
> Cards black list on game creation form

- server.ts
- src/Game.ts
- src/components/CreateGameForm.ts
- src/turmoil/globalEvents/GlobalEventDealer.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1208
> Add game option to remove negative Global Events

- server.ts
- src/Dealer.ts
- src/Game.ts
- src/Player.ts
- src/SerializedGame.ts
- src/cards/LavaFlows.ts
- src/cards/NoctisCity.ts
- src/cards/colonies/Aridor.ts
- src/cards/colonies/Poseidon.ts
- src/cards/prelude/LavaTubeSettlement.ts
- src/cards/prelude/ValleyTrust.ts
- src/cards/turmoil/SeptumTribus.ts
- src/milestones/Terraformer.ts
- src/turmoil/globalEvents/GlobalEventDealer.ts
- src/turmoil/parties/PartyHooks.ts
- tests/Game.spec.ts
- tests/cards/colonies/MarketManipulation.spec.ts
Previous commit was rollbacked because of a bug. This bug has been fixed.
> Rework game options, take 2

- src/turmoil/globalEvents/GlobalEventDealer.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1267
> Update negative global events

- src/Game.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1272
> Fix: Solo mode breaks if tile placed on Hellas South pole during setup

- tests/cards/Herbivores.spec.ts
Related to issue https://github.com/bafolts/terraforming-mars/issues/1271 from Discord. Can't seem to reproduce the issue in solo mode though
> Minor test update for Herbivores

- README.md
- src/database/PostgreSQL.ts
Cleanup finished games from games table
Cleanup solo games after one day instead of 10 days
> Update retention policy

- src/Game.ts
- src/components/LogHelper.ts
- src/components/PlayerHome.ts
- src/components/Preferences.ts
- src/components/PreferencesManager.ts
- src/styles/preferences.less
Game log is displayed for solo games
Game log can be hidden with a new preference switch
Game id is diplayed in the log for solo games
> Solo improvements

- package-lock.json
- package.json
- script.ts
- src/directives/i18n.ts
- tsconfig.json
Added translations.json to common bundle. Initial loading should be faster now
> Fast i18n loading

- .gitignore
- README.md
- package-lock.json
- package.json
- server.ts
Add the ability to use HTTPS cert.pem/key.pem by setting their paths
in the `.env` file. Updated the README to reflect this.
> Fixes #1291

- src/turmoil/Turmoil.ts
- tests/Turmoil.spec.ts
- tests/globalEvents/AquiferReleasedByPublicCouncil.spec.ts
- tests/globalEvents/AsteroidMining.spec.ts
- tests/globalEvents/CelebrityLeaders.spec.ts
- tests/globalEvents/CorrosiveRain.spec.ts
- tests/globalEvents/GenerousFunding.spec.ts
- tests/globalEvents/HomeworldSupport.spec.ts
- tests/globalEvents/InterplanetaryTrade.spec.ts
- tests/globalEvents/JovianTaxRights.spec.ts
- tests/globalEvents/ParadigmBreakdown.spec.ts
- tests/globalEvents/Productivity.spec.ts
- tests/globalEvents/RedInfluence.spec.ts
- tests/globalEvents/Sabotage.spec.ts
- tests/globalEvents/ScientificCommunity.spec.ts
- tests/globalEvents/SnowCover.spec.ts
- tests/globalEvents/SolarFlare.spec.ts
- tests/globalEvents/SolarnetShutdown.spec.ts
- tests/globalEvents/SpinoffProducts.spec.ts
- tests/globalEvents/SponsoredProjects.spec.ts
- tests/globalEvents/StrongSociety.spec.ts
- tests/globalEvents/SuccessfulOrganisms.spec.ts
- tests/globalEvents/VenusInfrastructure.spec.ts
- tests/globalEvents/VolcanicEruptions.spec.ts
- tests/globalEvents/WarOnEarth.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1295
> Fix influence count

- README.md
- src/Game.ts
- src/Player.ts
- src/cards/Ants.ts
- src/cards/Flooding.ts
- src/cards/HiredRaiders.ts
- src/cards/PowerSupplyConsortium.ts
- src/cards/Predators.ts
- src/cards/Sabotage.ts
- src/cards/colonies/AirRaid.ts
- src/cards/prelude/Vitor.ts
- src/cards/venusNext/CometForVenus.ts
- src/turmoil/globalEvents/Election.ts
- src/turmoil/globalEvents/Revolution.ts
Remove unnecessary variable
Fix Contributors
> Solo seed bug

- src/components/PlayerHome.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1290
> Add cards in hand number

- src/components/SelectAmount.ts
**Ref:** https://github.com/bafolts/terraforming-mars/issues/1147
When clicked, it will set the input to the max possible value for that action.
> Add MAX button for SelectAmount

- src/Game.ts
The removed code was adding duplicates in spaces and raising a "Error with getting space"
> Fix venus next tiles for seeded games

- tests/Game.spec.ts
Fixes #1329 
The first 132 of 1000 tests have passed, and my arrogant confidence says send this out now - the remining 870 tests will finish in another hour.
> Fix flaky Game tests related to the Hellas ocean tile.

- src/cards/promo/PharmacyUnion.ts
- tests/cards/promo/PharmacyUnion.spec.ts
- tests/cards/promo/Splice.spec.ts
Ref: https://boardgamegeek.com/thread/2470876/article/35415932#35415932
> Fix: PharmacyUnion science card draw timing

- src/components/App.ts
- src/components/Award.ts
- src/components/Milestone.ts
- src/components/PlayerHome.ts
- src/styles/player_home.less
+ reveal milestones, awards and board by default 
The `Award.ts` and `Milestone.ts` just got two comments removed and some formatting.
> Reveal milestones, awards and board by default

- src/components/AndOptions.ts
- src/components/OrOptions.ts
- src/components/PlayerHome.ts
- src/components/SelectCard.ts
- src/styles/cards.less
- src/styles/colonies.less
- src/styles/player_home.less
Few minor UI changes:
- Submit button is bigger and with margin below it (main reason is to make it clickable on mobile -currently you can barely hit it without misclicking the below option)
- Colonies tile are slightly smaller and with adjusted margins 
- Cards titles font is Ubuntu now (it was Arial) 
- Backlog is now above the Actions menu (FYI @chosta - couldn't resist that easy fix) (main reason is to keep is fixed in the same position - currently it jumps up and down based on if it is your turn and what action is selected - annoying)
> Mobile improvments

- src/milestones/Generalist.ts
- tests/milestones/Generalist.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1349
> Fix: Generalist should require +2 production without corporate era

- index.html
- src/styles/player_home.less
Just making the mobile width to be enough to fit 4 cards.
A good side-effect fix is that 6th milestone/award will also be on the same row.
Another is that 2 colonies fits now on the same row (it was one....no comment)
> mobile width

- src/cards/Ants.ts
I just need to either write a test or manually test it.
> [WIP] When playing Ants, log the name of the player whose card was taken.

- src/cards/Ants.ts
I've incorrectly merged a not-ready-for-prod branch. Here is the fix
> Revert incorrect Ants WIP merge

- src/cards/SearchForLife.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1408
> Add log when SearchForLife action is successful

- src/components/LogPanel.ts
TESTED=all manual
Fixes #1398.
I created a bad entry like so
game.log(
LogMessageType.DEFAULT,
"${0} played ${1} ${2}",
new LogMessageData(LogMessageDataType.PLAYER, this.id),
new LogMessageData(LogMessageDataType.CARD, card.name));
Some of the testing had to be done by changing data live in the
browser's debugger to verify extreme cases will preserve the log.
For example
"[{"type":1,"value":"adfe8b3a97d8"},{"type":2,"value":"Rover Construction"},null,{}]"
renders as
"BUG: Unparseable message: ${0} played ${1} ${2}, (1) adfe8b3a97d8, (2) Rover Construction, undefined, (undefined) undefined"
Which is ugly, but better than a broken log. Also, if the log entry is
that broken, you have bigger problems. But now it's fairly resilient.
> Safely parse bad log messages so as to not destroy the log.

- src/components/overview/PlayerStatus.ts
Fixes #1397
TESTED=manually tested
> Hovering over corporation name pops up full title name.

- src/cards/Ants.ts
- tests/cards/Ants.spec.ts
OK, this I tested, :D. Manually, but it's right.
> Further Ants repair, and minor test change.

- src/HTML_data.ts
- src/locales/cn/bigboxpromo.json
- src/locales/ru/promo.json
- src/styles/cards.less
Ref: https://github.com/bafolts/terraforming-mars/issues/1357
> Update Pharmacy Union start text

- src/components/LogPanel.ts
TESTED=manually tested.
Fixes #1399
> Clicking on a card a second time removes it from the card display panel.

- src/Game.ts
This will make it simpler to implement Ecological Survey and Geological Survey cards from Ares and as a side benefit increases comprehension.
I'd like to put in the main branch first as I'd like to keep that order if possible.
TESTED=all tests still pass.
> Restructure Game.addTile to be executed in more logical steps.

- src/turmoil/globalEvents/GlobalEventDealer.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1338
> Fix: Remove VenusInfra global event if Venus expansion not selected

- src/components/Colony.ts
- src/styles/colonies.less
@alrusdi 
I will work on colonies vusual fixes for the new icons and let you know when ready
[do not merge]
> Colonies fixes

- src/components/PaymentWidgetMixin.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForCard.ts
- src/styles/payments.less
Ref: https://github.com/bafolts/terraforming-mars/issues/1367
> Add MAX buttons for payment resource selection

- src/Game.ts
- src/Player.ts
- src/cards/Ants.ts
- src/cards/ElectroCatapult.ts
- src/cards/Predators.ts
- src/cards/RoboticWorkforce.ts
- src/cards/SearchForLife.ts
- src/cards/colonies/Aridor.ts
- src/cards/community/ProjectWorkshop.ts
- src/cards/corporation/TharsisRepublic.ts
- src/cards/prelude/AcquiredSpaceAgency.ts
- src/cards/prelude/ExperimentalForest.ts
- src/cards/promo/ArcadianCommunities.ts
- src/cards/promo/AsteroidDeflectionSystem.ts
- src/cards/promo/Factorum.ts
- src/cards/promo/PharmacyUnion.ts
- src/cards/promo/Philares.ts
- src/cards/promo/ProjectInspection.ts
- src/cards/promo/SelfReplicatingRobots.ts
- src/cards/promo/Splice.ts
- src/cards/turmoil/BannedDelegate.ts
- src/cards/venusNext/Celestic.ts
- src/cards/venusNext/MorningStarInc.ts
- src/cards/venusNext/Viron.ts
- src/colonies/Colony.ts
- src/components/LogHelper.ts
- src/interrupts/SelectParty.ts
- src/interrupts/SelectTradeColony.ts
- src/turmoil/Turmoil.ts
Fixing each card was going to be a bit of a hassle, so I did them separately. Also the subsequent changelist removes the "newLog" method name so everything looks normal again. **I recommend reading each commit separately.**
> Complete the transition to the new log API.

- src/Game.ts
- src/Player.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1435
> Include Turmoil VP when game is in final generation

- server.ts
- src/Player.ts
- src/components/PlayerMixin.ts
- src/models/CardModel.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1437
> Gray out PharmacyUnion if it has been flipped

- src/styles/turmoil.less
> Fix reference to delegate.png image

- src/styles/cards.less
Update is on the left. original is on the right.
> Add right margin to global parameters box.

- src/cards/community/Hygiea.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1475
> Fix: Filter out protected players for Hygiea plant removal

- src/components/Preferences.ts
- src/styles/player_home.less
- src/styles/preferences.less
- Remove the old css in playerhome.less that I made. Not needed anymore.
- Move Venus to the bottom, adjust it aspect ratio and bottom-margin.
> Remove unused class and readjust Venus

- src/components/CreateGameForm.ts
- src/styles/create_game_form.less
Separating official expansions from fan-made content.
I would also like to add a button for turning all official expansions at once, but I am not sure yet how to do.
> Separating fan-made content

- src/cards/colonies/Aridor.ts
**Scenario:** Play with a custom colonies list. If too few colonies were selected, game is stuck as Aridor cannot select any colony tile to add
> Fix bug where game gets stuck if Aridor has no colonies to select

- src/HTML_data.ts
- src/components/DebugUI.ts
- src/styles/cards.less
Show all preludes and corps too
> Add more cards to debug page

- src/components/ColoniesFilter.ts
- src/components/CreateGameForm.ts
> Extend ColoniesFilter to toggle community colonies

- package.json
> Remove wildcards from package.json that necessitate directory maintenance.

- src/HTML_data.ts
- src/styles/cards.less
- Update the corporations with new graphics.
Some examples:
Old
Updated
> Fix new graphics on corporations

- src/CardName.ts
- src/Dealer.ts
- src/HTML_data.ts
- src/cards/community/CommunityCorporation.ts
- src/cards/community/Midas.ts
- src/styles/cards.less
- tests/cards/community/Midas.spec.ts
> Add Midas corporation

- src/components/CreateGameForm.ts
- src/styles/create_game_form.less
A few images will probably be the best to show what it does. The changes are also much clearer in French because sentences are longer but I wouldn't want to hurt your eyes with it everywhere :)
Please test it and let me know if I missed something, like the reason those widths were set.
-----
> Modifies the create game form styles

- src/components/CreateGameForm.ts
+ just one misalignment fix but it hurt my eyes :)
> Player label and color misalignment fix

- server.ts
- src/Game.ts
- src/Player.ts
- src/SerializedGame.ts
- src/SerializedPlayer.ts
No functional change at all, purely so it's clear what's in Game and Player and why.
> Reorder fields in Game and Player into logical clusters

- src/cards/community/AerospaceMission.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1557
> Fix incomprehensible option text on Aerospace Mission

- server.ts
- src/components/CreateGameForm.ts
While calculating the random board within the vue component we are updating data which could then modify the vue state. This moves the random calculation to the server. This _could_ help resolve #1539 . The client side solution updating data could be timing related or vue.js related in some way.
> move random board to server from vue component

- src/cards/LandClaim.ts
- src/components/LogHelper.ts
> Log where a land claim is made.

- src/cards/WaterImportFromEuropa.ts
- tests/cards/AquiferPumping.spec.ts
- tests/cards/WaterImportFromEuropa.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1474
> Fix: WaterImportFromEuropa can act even if oceans are maxed

- src/components/CreateGameForm.ts
- src/styles/create_game_form.less
- Fix negative global event button
- Left align create game button
> fixing negative global event button, left align create game button

- src/Game.ts
- src/cards/corporation/CorporationCard.ts
- src/cards/corporation/SaturnSystems.ts
- src/cards/promo/PharmacyUnion.ts
- src/cards/promo/Splice.ts
- tests/cards/promo/Splice.spec.ts
Also added a test to check that Splice -> Recyclon works.
This fixes #1577.
I made a test game with all 4 impacted corps, the results were as expected **\***.
**\*** Noone bought any card. **SS** got +1 MC Production. **PU** got -16 MC and 4 diseases. **Splice** got +6 MC. **Recyclon** chose to receive 1 microbe.
> Fix onCorpCardPlayed not adding interrupts.

- src/styles/create_game_form.less
> Restore color of anchor tags in create form when parent  checkbox is selected

- src/HTML_data.ts
- src/styles/cards.less
- src/styles/player_home.less
- src/styles/players_overview.less
- Replace min_big.png or minimum requirement box with linear-gradient.
- Fix card icon path in the tags overview box.
> Minor ui fix

- src/HTML_data.ts
- src/locales/cn/cards.json
- src/locales/de/cards.json
- src/locales/fr/base_cards.json
- src/locales/ru/cards.json
- src/styles/cards.less
- src/styles/language_hacks.less
> Css for OpenCity, MonsInsurance, MolecularPrinting, NuclearZone, Midas

- src/components/CreateGameForm.ts
- src/styles/create_game_form.less
- Minor UI adjustment on the create game page to satisfy Simon's OCD :P
- More padding when Beginner Option is turned on.
> making all buttons the same height

- src/Board.ts
- tests/Board.spec.ts
> Fix large cards being drawn placing random elements on the board.

- server.ts
- src/Player.ts
- src/cards/venusNext/StratosphericBirds.ts
- src/components/PaymentWidgetMixin.ts
- src/models/CardModel.ts
- tests/cards/venusNext/StratosphericBirds.spec.ts
It doesn't really change the core of what's happening since it was working properly.
But this way it lets you spend only the correct amount of floaters instead of letting you spend all of them and fixing it by paying an additional 3M€.
It adds a bit of code here and there (couldn't think of a less intrusive way of doing it) so it might not be that good. Let me know.
> Fix Stratospheric Birds + Dirigibles edge case interaction

- src/components/GameEnd.ts
- Change the player username class to be the same as in log.
New: ![image](https://user-images.githubusercontent.com/14239220/96005754-c3a89800-0e0a-11eb-8e0e-e662ded97040.png)
Previous:
> change class of end game player name

- src/HTML_data.ts
- src/locales/cn/cards.json
- src/locales/de/cards.json
- src/locales/fr/base_cards.json
- src/locales/ru/cards.json
fix 'space tag you **__r__** have' to 'space tag you have'.
> fixing typo on Satellites

- src/components/overview/PlayerInfo.ts
- src/components/overview/PlayerStatus.ts
- src/components/overview/PlayersOverview.ts
- src/utils/utils.ts
from #1625
The recent change of player.id to player.color caused 2 bugs that this PR fixes:
+ not showing live VP for not selected live option
+ not scrolling to player hand once 'show' on active player is clicked
> Fix issues with activePlayer.color causing trouble

- src/styles/cards.less
Seems like one of the recent merges did some damage on the cards res box.
> Resource box on cards fixed after merge issue

- src/Game.ts
- tests/Game.spec.ts
Same as #1622 but with test from @kberg. I screwed up Git again somehow so I am opening another PR for clean commits.
> only draw from custom corp list if enough corp selected.

- src/HTML_data.ts
- src/styles/cards.less
This PR can close #1626 .
Tagging @nwai90 .
> fix quantum comm ui

- src/turmoil/Turmoil.ts
- tests/cards/community/Incite.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1650
> Fix: turmoil.addInfluence should set new influence value

- src/Game.ts
- src/cards/community/Venus.ts
- src/cards/venusNext/CorroderSuits.ts
Scope:
- Celestic corporation should activate Venus colony
- Game should not get stuck if player who is trading has no cards that collect Venus resources
> Fix Venus colony activation and trade

- src/HTML_data.ts
- src/styles/cards.less
> fixing utopia ui, moving in-line styles to css classes

- src/components/CreateGameForm.ts
Ability to upload and download (no server side involved) game settings on game creation form
> Settings upload download prototype

- src/styles/cards.less
Make the box large enough to fit the plant.
> fix crash site cleanup requirement box

- src/components/PlayerHome.ts
> add space between gen and number

- src/cards/prelude/ExperimentalForest.ts
Now it draws two plant tag cards first.
I am not sure how to reverse the log order.
> experimental forest: draw first

- server.ts
- src/components/GameEnd.ts
Exposes player id at end of game
> expose player id at end of game

- src/CardName.ts
- src/HTML_data.ts
- src/cards/promo/AsteroidRights.ts
- src/cards/promo/PromoCardManifest.ts
- src/locales/ru/promo.json
- src/styles/cards.less
- src/styles/language_hacks.less
- tests/cards/promo/AsteroidRights.spec.ts
Ref: https://github.com/bafolts/terraforming-mars/issues/1678
> Add Asteroid Rights promo card

- src/CardName.ts
- src/Player.ts
- src/cards/CardType.ts
- src/cards/community/Leavitt.ts
- src/cards/community/ScienceTagCard.ts
- src/cards/promo/PharmacyUnion.ts
- tests/cards/promo/PharmacyUnion.spec.ts
The Science tag gained needs to trigger effects on all relevant cards in play. Easiest way is probably to add a "dummy" card for it that has nothing but a science tag, with a different `CardType` so that it does not count for Tycoon/Magnate, show up in the game log, etc.
> Fix: Leavitt should trigger Aridor's effect

- src/Game.ts
- src/cards/OlympusConference.ts
- tests/cards/OlympusConference.spec.ts
> Add defer() argument to unshift deferred actions

- src/cards/promo/PharmacyUnion.ts
- tests/cards/promo/PharmacyUnion.spec.ts
Fixes #1286
Added tests for it as well.
> Let player choose for Pharmacy Union edge case

- src/deferredActions/DecreaseAnyProduction.ts
For 3 consortium cards, player's own production got decreased in solo mode
> Fix: Don't decrease own production in solo mode

- tests/cards/GreatEscarpmentConsortium.spec.ts
@alrusdi That was a fast merge! This is the unit test :D
> Add unit test for GreatEscarpmentConsortium in solo mode

- src/components/GameEnd.ts
- Don't display winner message if solo game was lost
- Updated text copy
> Update win message and hide it if solo loss

- src/components/PreferencesManager.ts
This was actually broken since july.
Fixes #1736
> Fix in-game alerts not showing

- compile-vue-templates.js
- src/components/Award.ts
- src/components/Milestone.ts
- src/styles/player_home.less
- tests/components/Award.spec.ts
- tests/components/Milestone.spec.ts
- tests/utils/Vue.ts
This moves the Award component into the vue type checking system. Also added unit tests to test the `methods` and `data` of the component.
> Vue type checking and unit tests for Award component.

- src/components/card/Card.ts
- src/styles/cards.less
> Fix: Expansion icons appear twice on corporation cards

- compile-vue-templates.js
- src/components/OtherPlayer.ts
- src/components/PlayerMixin.ts
- src/components/Tag.ts
- src/components/TagCount.ts
- src/components/overview/PlayerStatus.ts
- tests/components/OtherPlayer.spec.ts
- tests/components/Tag.spec.ts
- tests/components/TagCount.spec.ts
- tsconfig-test.json
- tsconfig-vue.json
Add type checking and unit tests for more components.
> Add OtherPlayer, Tag, and TagCount component tests and type checking

- src/components/CorporationsFilter.ts
This PR will close https://github.com/bafolts/terraforming-mars/issues/1743
> Fix: Select base corps by default in custom corps list

- src/Game.ts
Closes https://github.com/bafolts/terraforming-mars/issues/1663
> Add initial log for playing corporation card

- src/HTML_data.ts
- src/styles/cards.less
> fix herbivore and rotator impact

- src/components/card/CardExpansion.ts
- src/styles/cards.less
This PR closes #1757 .
Tagging @kberg for review.
> add ares icon to project cards

- compile-vue-templates.js
- src/components/AndOptions.ts
- src/components/OrOptions.ts
- src/components/SelectAmount.ts
- src/components/SelectOption.ts
Type checking for more vue components.
> Vue type checking for more components

- src/deferredActions/DiscardCards.ts
- tests/globalEvents/ParadigmBreakdown.spec.ts
Also adds tests for the behavior.
> Fix DiscardCards if need to discard more than 1 card

- compile-vue-templates.js
- src/components/SelectAmount.ts
- src/components/SelectHowToPayForCard.ts
- src/models/PlayerInputModel.ts
More type safety on vue components. Adds `SelectAmount` and `SelectHowToPayForCard`.
> More type checking on vue components

- src/components/SelectHowToPayForCard.ts
Model properties don't seem to be running through type checker. I changed the `card` property to be a `string` and not the entire card.
> fix for card model vue property

- tests/colonies/Callisto.spec.ts
- tests/colonies/Ceres.spec.ts
- tests/colonies/Enceladus.spec.ts
- tests/colonies/Europa.spec.ts
- tests/colonies/Ganymede.spec.ts
- tests/colonies/Io.spec.ts
- tests/colonies/Luna.spec.ts
- tests/colonies/Miranda.spec.ts
- tests/colonies/Pluto.spec.ts
- tests/colonies/Titan.spec.ts
- tests/colonies/Triton.spec.ts
Will add more generic tests in a futur PR.
> Add tests for official colonies

- compile-vue-templates.js
- index.html
- package-lock.json
- package.json
- server.ts
- src/components/App.ts
- src/components/GameHome.ts
- src/components/LoadGameForm.ts
- src/components/StackedCards.ts
- src/components/StartScreen.ts
- src/components/overview/PlayerTags.ts
- src/models/GameHomeModel.ts
- src/models/GameModel.ts
More work adding type safety to the vue components. Trying to do this piece mail to ease reviewing and since most of this I am testing manually as the change goes out. I added beautify to the compiled vue template to ease with debugging any type errors that may arise. We didn't get any model for `getGame` and were returning serialized `Player` to the client. We will only pass back the data we need from the server now as well as the included type safety.
> Type safety vue game model

- src/Game.ts
- src/components/ShiftAresGlobalParameters.ts
- tests/components/ShiftAresGlobalParameters.spec.ts
Includes a sanity test, but honestly it doesn't do anything of value.  Well, it's a starting point.
> Restore missing variable ADJUSTMENT_TESTS.

- compile-vue-templates.js
- src/components/LogPanel.ts
- src/components/PlayerHome.ts
- src/components/Preferences.ts
- src/components/overview/PlayerResource.ts
- src/components/overview/PlayerResources.ts
- src/components/overview/PlayerTags.ts
- src/components/overview/PlayersOverview.ts
Another round of changes mostly changing `props` from `[]` to the typed object.
> More vue components updated with type checking

- src/Game.ts
- src/ares/AresHandler.ts
- tests/ares/AresHandler.spec.ts
> Ocean placement is not subject to adjacency production costs.

- src/Player.ts
> Fix: Aridor cannot take initial action

- src/HTML_data.ts
- src/styles/cards.less
Add red border to Venus icon.
Move style to css.
> update aphrodite ui

- src/cards/venusNext/Atmoscoop.ts
- tests/cards/venusNext/Atmoscoop.spec.ts
Also rewrote the code to make it much less bulky.
Fixes #1835
> Fix Atmoscoop if no actions are available

- src/Player.ts
Closes https://github.com/bafolts/terraforming-mars/issues/1807
> Show TitanFloatingLaunchPad in trade payment options

- compile-vue-templates.js
- server.ts
- src/components/SelectProductionToLose.ts
- src/components/ShiftAresGlobalParameters.ts
- src/components/Turmoil.ts
- src/components/WaitingFor.ts
- src/components/overview/PlayerInfo.ts
- src/components/overview/PlayerStatus.ts
- src/models/PlayerInputModel.ts
- src/models/TurmoilModel.ts
This adds type checking to the remaining vue components! Between this and the unit tests in place for vue components now in great shape.
> remaining vue components typed

- src/cards/turmoil/UtopiaInvest.ts
- tests/cards/turmoil/UtopiaInvest.spec.ts
TESTED by using interactive debugger to break at the end of its test and inspect `game.gameLog`
Fixes #1855
> Add log when Utopia Invest is acted upon.

- src/HTML_data.ts
- src/cards/CardRequirement.ts
- src/cards/CardRequirements.ts
- src/cards/ares/MetallicAsteroid.ts
- src/components/card/CardRequirementsComponent.ts
+ fix for aerial lenses requirements
+ fix metallic asteroid double event
+ fix geological survey max
> Party ruling requirements label

- compile-vue-templates.js
- src/components/AndOptions.ts
- src/components/Board.ts
- src/components/Bonus.ts
- src/components/CorporationsFilter.ts
- src/components/GameEnd.ts
- src/components/LogPanel.ts
- src/components/OrOptions.ts
- src/components/Preferences.ts
- src/components/SelectAmount.ts
- src/components/SelectCard.ts
- src/components/SelectColony.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForCard.ts
- src/components/SelectOption.ts
- src/components/SelectPartyPlayer.ts
- src/components/SelectPlayer.ts
- src/components/SelectProductionToLose.ts
- src/components/SelectSpace.ts
- src/components/ShiftAresGlobalParameters.ts
- src/components/StackedCards.ts
- src/components/StartScreen.ts
- src/components/card/CardCost.ts
- src/components/card/CardProductionBoxComponent.ts
- src/components/card/CardRowComponent.ts
- src/components/overview/PlayerResource.ts
- src/styles/log.less
With the `development` flag set on webpack warnings are logged to the console during runtime for vue typing errors. Fixes included here.
> vue runtime warning fixes

- src/Game.ts
Removes function not used and commented out.
> remove commented out function

- package.json
- src/Board.ts
- src/cards/LandClaim.ts
- tests/cards/LandClaim.spec.ts
- tests/utils/Vue.ts
This allows `LandClaim` to reserve the south pole at all times.
> allow land claim to place on south pole

- .dockerignore
- DOCKER.md
- Dockerfile
- README.md
- docker-compose.yml
Fixes https://github.com/bafolts/terraforming-mars/issues/1899
> Fixes Issue #1899

- src/cards/colonies/MarketManipulation.ts
> Add log for Market Manipulation

- server.ts
- src/database/GameLoader.ts
Change order of messages appearing when server starts.
First show all the lines like "load game ..."
and then "Starting server on port..." to make game overview links more available to copy
> Delay messages about server start

- tsconfig.json
It improves compilation time for consequential builds. I believe it can speed up "cover" step on CI too
> Compiller flag to enable incremental builds

- src/cards/Algae.ts
- src/cards/BigAsteroid.ts
I should be careful with this :/
> fix algae and big asteroid

- src/cards/community/Mercury.ts
- src/colonies/Colony.ts
Closes https://github.com/bafolts/terraforming-mars/issues/1915
@Lynesth
> Fix colony bugs for Mercury and Titania

- src/HTML_data.ts
- src/cards/AICentral.ts
- src/cards/AdvancedAlloys.ts
- src/cards/AerobrakedAmmoniaAsteroid.ts
- src/cards/AntiGravityTechnology.ts
- src/cards/AquiferPumping.ts
- src/cards/ArcticAlgae.ts
- src/cards/Asteroid.ts
- src/cards/AsteroidMiningConsortium.ts
- src/cards/BigAsteroid.ts
- src/cards/BiomassCombustors.ts
- src/cards/GiantIceAsteroid.ts
- src/cards/OptimalAerobraking.ts
- src/cards/ares/BioengineeringEnclosure.ts
- src/cards/colonies/AtmoCollectors.ts
- src/cards/colonies/CryoSleep.ts
- src/cards/promo/Advertising.ts
- src/cards/promo/EnergyMarket.ts
- src/cards/render/CardRenderItemType.ts
- src/cards/render/CardRenderSymbol.ts
- src/cards/render/CardRenderSymbolType.ts
- src/cards/render/CardRenderer.ts
- src/cards/turmoil/EventAnalysts.ts
- src/cards/turmoil/GMOContract.ts
- src/cards/venusNext/AerialMappers.ts
- src/cards/venusNext/DeuteriumExport.ts
- src/cards/venusNext/ExtractorBalloons.ts
- src/components/card/CardRenderItemComponent.ts
- src/components/card/CardRowComponent.ts
- src/styles/cards_v2.less
* Some action cards
* More symbols and items on cards
Note: Instead of dealing with painful abstractions by creating CardAction classes, I decided to just modify the `description()` function to accept the full text `Action:...` or `Effect...`
> Cards vue actions

- server.ts
The https://terraforming-mars.herokuapp.com site seems to be getting more traffic. As we don't cache any resources we get continual requests for file reads. If enough of these come in I believe they are slowing down requests for some users. With this change in production the reads for `fs.readFile` are cached. Also added compression to `styles.css` which takes it down to 40kb from 242kb.
> in production cache file reads

- src/HTML_data.ts
- src/cards/ares/BiofertilizerFacility.ts
- src/cards/render/CardRenderer.ts
- src/components/card/CardRenderTileComponent.ts
- src/components/card/CardRowComponent.ts
No question this isn't lining up right, yet. I'm sure the use of the special-tile background isn't going to work, and the sizing is also off. Of course at some point these tiles deserve a refresh.
> Move BiofertilizerFacility to CardRender. Create CardRenderTileComponent, which I'm sure isn't right yet.

- src/cards/promo/Factorum.ts
- src/turmoil/globalEvents/Election.ts
Requests from Discord
https://discord.com/channels/737945098695999559/742721510376210583/780628354188574740
https://discord.com/channels/737945098695999559/738006783955697704/780607551024136222
> Add log for Factorum and Election global event

- src/cards/AICentral.ts
> quickfix - AI Central

- src/cards/ares/BiofertilizerFacility.ts
- src/cards/ares/ButterflyEffect.ts
- src/cards/ares/DesperateMeasures.ts
- src/cards/render/CardRenderer.ts
- src/components/card/CardRenderTileComponent.ts
> Fix Ares tile automatic rendering

- src/HTML_data.ts
- src/cards/AICentral.ts
- src/cards/BeamFromAThoriumAsteroid.ts
- src/cards/Birds.ts
- src/cards/BlackPolarDust.ts
- src/cards/BribedCommittee.ts
- src/cards/BuildingIndustries.ts
- src/cards/Bushes.ts
- src/cards/BusinessContacts.ts
- src/cards/BusinessNetwork.ts
- src/cards/CardMetadata.ts
- src/cards/ares/BiofertilizerFacility.ts
- src/cards/ares/ButterflyEffect.ts
- src/cards/render/CardRenderDynamicVictoryPoints.ts
- src/cards/render/CardRenderItemType.ts
- src/cards/render/CardRenderer.ts
- src/cards/render/ICardRenderDescription.ts
- src/cards/turmoil/BannedDelegate.ts
- src/components/DebugUI.ts
- src/components/card/CardContent.ts
- src/components/card/CardDescription.ts
- src/components/card/CardRenderEffectBoxComponent.ts
- src/components/card/CardRenderItemComponent.ts
- src/components/card/CardRenderTileComponent.ts
- src/components/card/CardRowComponent.ts
- src/styles/cards_v2.less
All cards starting with the letter B
* Added animals to VP class
* Added .tr()
* Improved effect description to accept undefined
* [WIP] Improved the CardRenderTile to use the TileType enum and started separating logic and abstacting css classes (should be done for all tiles in the next PR)
> Cards vue b

- src/HTML_data.ts
- src/cards/CEOsFavoriteProject.ts
- src/cards/CallistoPenalMines.ts
- src/cards/CarbonateProcessing.ts
- src/cards/CloudSeeding.ts
- src/cards/Comet.ts
- src/cards/ConvoyFromEuropa.ts
- src/cards/Decomposers.ts
- src/cards/DeepWellHeating.ts
- src/cards/DeimosDown.ts
- src/cards/DesignedMicroOrganisms.ts
- src/cards/DevelopmentCenter.ts
- src/cards/EarthCatapult.ts
- src/cards/ares/DesperateMeasures.ts
- src/cards/colonies/Conscription.ts
- src/cards/colonies/CoronaExtractor.ts
- src/cards/colonies/EarthElevator.ts
- src/cards/promo/CometAiming.ts
- src/cards/promo/DirectedImpactors.ts
- src/cards/promo/DuskLaserMining.ts
- src/cards/render/CardRenderItemType.ts
- src/cards/render/CardRenderSymbol.ts
- src/cards/render/CardRenderSymbolType.ts
- src/cards/render/CardRenderer.ts
- src/cards/turmoil/DiasporaMovement.ts
- src/cards/venusNext/Dirigibles.ts
- src/components/card/CardRenderItemComponent.ts
Just to keep the momentum going
* Added 20 more cards (skipping some as they need some additional logic)
* Added jovian, venus tags and = sign
> Cards vue C-E

- src/cards/base/RoboticWorkforce.ts
- tests/cards/base/RoboticWorkforce.spec.ts
Please check the PR commit by commit.
The first one contains the actual changes.
The second one is simply formatting and reordering things around.
Tests inspired by @Starcalc.
> Fix Robotic Workforce to work with Ares cards

- src/Player.ts
- src/cards/colonies/TitanFloatingLaunchPad.ts
- src/deferredActions/RemoveColonyFromGame.ts
- src/locales/cn/ui.json
- src/locales/de/ui.json
- src/locales/fr/ui.json
- src/locales/ru/colonies.json
- src/locales/ru/ui.json
Fixes  #1870, but also for other places where it was called. Fixed for the translations so that the translations still work. (Did not change the translations itself, except for german).
> changed 'colony' to 'colony tile', where appropriate

- src/cards/base/Asteroid.ts
> Fix temperatureMaxed check in Asteroid

- src/cards/promo/EnergyMarket.ts
- src/cards/venusNext/SulphurEatingBacteria.ts
- tests/cards/venusNext/SulphurEatingBacteria.spec.ts
> Add logs for SulphurEatingBacteria and EnergyMarket

- src/HTML_data.ts
- src/cards/base/MagneticFieldDome.ts
- src/cards/base/MagneticFieldGenerators.ts
- src/cards/base/Mangrove.ts
- src/cards/base/MarsUniversity.ts
- src/cards/base/MartianRails.ts
- src/cards/base/MethaneFromTitan.ts
- src/cards/base/Mine.ts
- src/cards/base/MineralDeposit.ts
- src/cards/base/MiningExpedition.ts
- src/cards/base/MirandaResort.ts
- src/cards/render/CardRenderItemType.ts
- src/cards/render/CardRenderer.ts
- src/components/card/CardRenderItemComponent.ts
- src/styles/cards_v2.less
My first commit here. I'll be grateful If you could tell me if I'm doing the right thing. Thanks!
> Cards Vue M

- src/cards/base/MagneticFieldDome.ts
- src/cards/base/MagneticFieldGenerators.ts
- src/cards/base/MethaneFromTitan.ts
- src/cards/base/MirandaResort.ts
Some cards were a bit off. Need this approved and merged before updating the heroku instance.
> Quickfixes

- src/locales/cn/start_screen.json
add   "join us on discard" and "create game"(this create game chinese translation just work here) Chinese translation
> Chinese translation for Main menu.

- src/locales/cn/ui.json
add more Chinese translation for ui.json
> Chinese translation for ui.json

- src/cards/prelude/GalileanMining.ts
Note to self: also check preludes before merge.
> Quickfix for g mining

- src/locales/cn/preferences.json
Chinese translation for preferences
> Create preferences.json (chinese ver)

- src/cards/promo/SelfReplicatingRobots.ts
Shows option to duplicate cards first. Changed some `.filter.length > 0` to leverage `.some` while in file. Closes #1965
> show card duplication option first

- src/HTML_data.ts
- src/locales/cn/cards.json
- src/locales/de/cards.json
- src/locales/fr/base_cards.json
- src/locales/ru/cards.json
Is there any plan to change the translation system? This is not really optimal.
> protected valley word fix

- src/locales/cn/ui.json
> Update ui.json Chinese translation.

- src/cards/community/Playwrights.ts
- tests/cards/community/Playwrights.spec.ts
Closes https://github.com/bafolts/terraforming-mars/issues/2022. In the case of Law Suit the card goes into another player's discard pile
> Fix Law Suit edge case for Playwrights action

- Dockerfile
Add Label for publish on docker hub
eg:
https://hub.docker.com/search?q=terraforming-mars&type=image
> update dockfile for publish on docker hub

- src/cards/venusNext/RotatorImpacts.ts
- tests/cards/venusNext/RotatorImpacts.spec.ts
Closes https://github.com/bafolts/terraforming-mars/issues/2040
> Fix bug and add log for Rotator Impacts

- src/Game.ts
- src/Player.ts
There is a lot of code that is not that good looking even when u just scroll through it.
Does it make sense to improve those little things?
> Simplified some code

- src/Dealer.ts
- src/Game.ts
- src/SerializedDealer.ts
- tests/Dealer.spec.ts
- tests/Game.spec.ts
Two additional changes:
1. Removed a few really unnecsesary fields in the serialization protocol. So funny.
2. Moved a couple of Dealer-only tests from `Game.spec.ts` to `Dealer.spec.tMoved a couple of Dealer-only tests from `Game.spec.ts` to `Dealer.spec.ts`.
> Adjust Dealer serialization using the same approach used for Turmoil.

- src/HTML_data.ts
- src/cards/base/UndergroundCity.ts
- src/cards/base/UndergroundDetonations.ts
- src/cards/base/UrbanizedArea.ts
- src/cards/base/VestaShipyard.ts
- src/cards/base/ViralEnhancers.ts
- src/cards/base/Virus.ts
- src/cards/base/WaterImportFromEuropa.ts
- src/cards/base/WaterSplittingPlant.ts
- src/cards/base/WavePower.ts
- src/cards/base/Windmills.ts
- src/cards/base/Worms.ts
- src/cards/base/Zeppelins.ts
- src/cards/colonies/UrbanDecomposers.ts
- src/cards/colonies/WarpDrive.ts
- src/cards/render/CardRenderItem.ts
- src/cards/render/CardRenderer.ts
- src/cards/turmoil/VoteOfNoConfidence.ts
- src/cards/turmoil/WildlifeDome.ts
- src/cards/venusNext/VenusGovernor.ts
- src/cards/venusNext/VenusMagnetizer.ts
- src/cards/venusNext/VenusSoils.ts
- src/cards/venusNext/VenusWaystation.ts
- src/cards/venusNext/VenusianAnimals.ts
- src/cards/venusNext/VenusianInsects.ts
- src/cards/venusNext/VenusianPlants.ts
- src/cards/venusNext/WaterToVenus.ts
- src/components/card/CardRenderItemComponent.ts
- src/styles/cards_v2.less
Mixing it a bit by starting from the end. Not much in terms of new functionality so feel free to check it if you are tagged as @kberg and @nwai90 have been doing the heavy lifting recently :)
@bafolts, @alrusdi, @Lynesth
> Cards vue U-Z

- src/components/Preferences.ts
This can perhaps close #2024 .
> open help page in a new tab

- server.ts
- src/Game.ts
- src/SerializedGame.ts
- src/components/CreateGameForm.ts
- src/database/GameLoader.ts
- src/database/IDatabase.ts
- src/database/PostgreSQL.ts
- src/database/SQLite.ts
- src/models/GameHomeModel.ts
There's a PlayerId assignment in there, too.
> Add GameId type, apply it everywhere it seemed to make sense.

- src/ares/AresHandler.ts
- tests/cards/ares/EcologicalSurvey.spec.ts
> Ecological Survey does not grant bonuses during WGT.

- src/Game.ts
- tests/Game.spec.ts
Do not review until after reviewing #2099
> Games can't have the same color apply to two different players.

- src/Player.ts
- src/SerializedPlayer.ts
- tests/Player.spec.ts
(ignore what the commit description says.)
> Remove uses of string in Player, update serialization to match.

- src/Player.ts
> Process missing fields when deserializing player

- src/components/overview/PlayerStatus.ts
- tests/components/overview/PlayerStatus.spec.ts
This includes the corporation card with the played card count. In most other places we consider the corporation card as well as the played cards. This does the same here.
> include corporation card with played card count

- src/cards/community/CommunityCardManifest.ts
Closes https://github.com/bafolts/terraforming-mars/issues/2128
> Fix: Incite should not appear by default without Turmoil expansion

- src/components/card/CardRenderTileComponent.ts
> Restore Natural Preserve card iconography.

- src/cards/ares/SolarFarm.ts
Option 2. from https://github.com/bafolts/terraforming-mars/issues/2134
> Updated SolarFarm.ts

- src/cards/ares/MoholeAreaAres.ts
- src/cards/ares/RestrictedAreaAres.ts
- src/cards/base/Fish.ts
- src/cards/base/ImportedHydrogen.ts
- src/cards/base/ImportedNitrogen.ts
- src/cards/base/MineralDeposit.ts
- src/cards/base/MoholeArea.ts
- src/cards/base/QuantumExtractor.ts
- src/cards/colonies/CoronaExtractor.ts
- src/cards/colonies/SolarReflectors.ts
- src/cards/promo/AsteroidDeflectionSystem.ts
- src/cards/promo/ImportedNutrients.ts
- src/cards/venusNext/FloatingHabs.ts
- src/styles/cards_v2.less
* Reverting some experiments on vusial representation for items with 4+ cubes.
* Minor fixes
@vsrisuknimit
> Reworked some cards

- src/turmoil/globalEvents/GlobalEventDealer.ts
- tests/GlobalEventsDealer.spec.ts
Also adds a test to prevent similar issues.
Fixes #2152
> Add Leadership Summit to GlobalEventDealer's ALL_EVENTS

- src/cards/corporation/PhoboLog.ts
> Fixed PhoboLog

- src/cards/turmoil/BannedDelegate.ts
- src/deferredActions/SendDelegateToArea.ts
- src/inputs/SelectDelegate.ts
- src/turmoil/SerializedTurmoil.ts
- src/turmoil/Turmoil.ts
- src/turmoil/parties/IParty.ts
- src/turmoil/parties/Party.ts
I'm not sure this is worthwhile, someone else tell me if I'm wrong -- but the overzealous use of the literal `'NEUTRAL'` seems a bit of an invitation for typos.
I tried making a `const NEUTRAL = 'NEUTRAL'` but that causes all other types of problems. This may be the best we can do, in which case perhaps it's not even worthwhile. Let me know.
> Add custom type NeutralPlayer

- src/cards/colonies/LunarExports.ts
- src/cards/turmoil/BannedDelegate.ts
- tests/cards/colonies/LunarExports.spec.ts
> Clearer BannedDelegate and LunarExports logs + swap option order

- src/Game.ts
- src/Player.ts
- src/boards/Board.ts
Sometimes minor refactors cause the compiler to dislike the 4-character
indent for the first indentation.
> Reduce spacing in Game, Player and Board.

- package.json
- server.ts
Will look like this:
It can also add colors and whatnot but all I really cared about were timestamps. Someone else can make it pretty if they want afterwards :)
> Add timestamps to server logs

- package-lock.json
- src/components/DebugUI.ts
I know the button is boxy. Since this is a debug-only UI, this is probably good enough.
> Added "Toggle all" button to debug-ui making it easier to focus on one expansion.

- src/Dealer.ts
Official rules:
"The deck is reshuffled from the discard pile if it becomes empty."
_Edit: didn't mean to create a branch on this repo haha, but that's what you get at 1:17 am on the 25th of dec_
> Reshuffle deck as soon as it's empty

- src/Player.ts
- src/components/overview/PlayerTags.ts
If you aren't playing with the venus extension you most likely don't need to see the venus tag count.
> only show venus tags when on venus

- server.ts
- src/Player.ts
- tests/globalEvents/LeadershipSummit.spec.ts
Once this is done, I think cloning will be easier.
> Move player ID generation outside of the Player constructor.

- src/boards/BoardRandomizer.ts
Some suggestions I had during code review of #2089 were lost in translation or in the mix of the larger pull request as a lot was changing. This is first pass of changes I would like to make before merging to `main`. I see a few more things that may need to be updated prior to merging.
As an upcoming change, I am not sure what order https://github.com/bafolts/terraforming-mars/blob/main/src/boards/BoardBuilder.ts#L75 is trying to sort. If it is supposed to be ascending or descending order I am not sure it is achieving that.
> move adjacent map away from property and remove undefined return values

- src/components/Board.ts
> Add explicit lines to the Tharsis map for volcano spaces.

- src/Player.ts
- src/cards/standardProjects/SellPatents.ts
- src/cards/standardProjects/StandardProjectCard.ts
This moves the sell patents option back to a separate option.
> use a separate option for sell patents

- src/database/Database.ts
- src/database/LocalFilesystem.ts
Need to restore to an old version? Copy the history entry!
Need to know what happened in between saves? Run `diff`!
Want to query details about a savepoint? Use `jq`!
> Add a local filesystem for storing game results. Meant as a new development option.

- src/Game.ts
- src/GameSetup.ts
- src/ares/AresHandler.ts
- src/ares/AresHazards.ts
- src/ares/AresSetup.ts
- src/ares/_StringGen.ts
- tests/ares/AresHandler.spec.ts
This makes The Moon run again by breaking up the a dependency chain, roughly from Board to Ares to Milestones to Moon to MoonBoard to Board.
> Split Ares into smaller pieces, which breaks up the dependencies.

- src/cards/ares/RestrictedAreaAres.ts
- src/cards/base/QuantumExtractor.ts
- src/cards/base/RadChemFactory.ts
- src/cards/base/RadSuits.ts
- src/cards/base/RegolithEaters.ts
- src/cards/base/ReleaseOfInertGases.ts
- src/cards/base/Research.ts
- src/cards/base/ResearchOutpost.ts
- src/cards/base/RestrictedArea.ts
- src/cards/base/RoboticWorkforce.ts
- src/cards/base/RoverConstruction.ts
- src/cards/base/Sabotage.ts
- src/cards/base/Satellites.ts
- src/cards/base/SearchForLife.ts
- src/cards/base/SecurityFleet.ts
- src/cards/base/Shuttles.ts
- src/cards/base/SmallAnimals.ts
- src/cards/base/SoilFactory.ts
- src/cards/base/SolarPower.ts
- src/cards/base/SolarWindPower.ts
- src/cards/base/Soletta.ts
- src/cards/base/SpaceElevator.ts
- src/cards/base/SpaceMirrors.ts
- src/cards/base/SpaceStation.ts
- src/cards/base/SpecialDesign.ts
- src/cards/base/Sponsors.ts
- tests/cards/base/RoboticWorkforce.spec.ts
Doing these in small batches for ease of reviewing. This is another 25 cards updated to pass static values through constructor.
> Another batch of cards updated for less memory.

- src/styles/cards_v2.less
With repeat on by default. 
Without repeat.
> remove background repeat on tile

- src/cards/base/StandardTechnology.ts
- src/cards/base/Steelworks.ts
- src/cards/base/StripMine.ts
- src/cards/base/SubterraneanReservoir.ts
- src/cards/base/SymbioticFungus.ts
- src/cards/base/Tardigrades.ts
- src/cards/base/TechnologyDemonstration.ts
- src/cards/base/TectonicStressPower.ts
- src/cards/base/TerraformingGanymede.ts
- src/cards/base/TitaniumMine.ts
- src/cards/base/TollStation.ts
- src/cards/base/TowingAComet.ts
- src/cards/base/TransNeptuneProbe.ts
- src/cards/base/Trees.ts
- src/cards/base/TropicalResort.ts
- src/cards/base/TundraFarming.ts
Few more cards converted to the less memory pattern.
> another batch of cards for less memory

- server.ts
- src/Player.ts
- src/components/CreateGameForm.ts
- src/database/Cloner.ts
…ient as a string.
Related to #2299
> Fix hanidicap field, which was a string for quite some time.

- src/cards/ares/BioengineeringEnclosure.ts
- src/cards/ares/BiofertilizerFacility.ts
- src/cards/ares/ButterflyEffect.ts
- src/cards/ares/DesperateMeasures.ts
- src/cards/ares/EcologicalSurvey.ts
- src/cards/base/UndergroundCity.ts
- src/cards/base/UndergroundDetonations.ts
- src/cards/base/UrbanizedArea.ts
- src/cards/base/VestaShipyard.ts
- src/cards/base/ViralEnhancers.ts
- src/cards/base/Virus.ts
- src/cards/base/WaterImportFromEuropa.ts
- src/cards/base/WaterSplittingPlant.ts
- src/cards/base/WavePower.ts
- src/cards/base/Windmills.ts
- src/cards/base/Worms.ts
- src/cards/base/Zeppelins.ts
This adds the rest of the base cards and starts to add the ares cards to the pattern to re-use static properties in memory.
> Static memory card properties: rest of base cards, start of ares cards.

- src/cards/base/LavaFlows.ts
- src/cards/base/NuclearZone.ts
> rearrange order for temp/tile placement

- src/cards/ares/GeologicalSurvey.ts
- src/cards/ares/MarketingExperts.ts
- src/cards/ares/MetallicAsteroid.ts
- src/cards/ares/OceanCity.ts
- src/cards/ares/OceanFarm.ts
- src/cards/ares/OceanSanctuary.ts
- src/cards/ares/SolarFarm.ts
Remaining ares cards. The prelude cards will need to come in one batch with how they extend `PreludeCard`. Getting these out of the way.
> remaining ares cards for static memory

- src/Player.ts
- src/cards/base/MediaArchives.ts
- src/milestones/Legend.ts
- tests/cards/promo/PharmacyUnion.spec.ts
Closes https://github.com/bafolts/terraforming-mars/issues/2235
> Fix: Flipped PharmacyUnion should count as a played event

- tests/cards/CardMetadata.spec.ts
That sets up forests and cities that would be considered worth victory points according to some cards,
and makes these tests less brittle.
> Change CardMetadata test to not play solo mode.

- src/Game.ts
- src/boards/Board.ts
- src/cards/base/NoctisCity.ts
- tests/Game.spec.ts
- tests/awards/EstateDealer.spec.ts
- tests/boards/Board.spec.ts
- tests/cards/base/LavaFlows.spec.ts
- tests/cards/base/NoctisCity.spec.ts
- tests/cards/base/UrbanizedArea.spec.ts
- tests/cards/prelude/LavaTubeSettlement.spec.ts
- tests/cards/turmoil/RedTourismWave.spec.ts
Testing whether the build will accept this.
> Move Game.getSpace to Board.

- src/Player.ts
> Fix SRR (de)serializing

- src/cards/community/ByElection.ts
- src/turmoil/Turmoil.ts
- tests/cards/community/ByElection.spec.ts
Issue reported by @sienmich . New Agenda was not being set when ruling party was changed
> Fix: Set new ruling party bonus and policy for ByElection

- src/cards/base/Flooding.ts
- tests/cards/base/Flooding.spec.ts
Bug report from Discord: https://discord.com/channels/737945098695999559/742721510376210583/798565553681596436
> Fix: Flooding shouldn't suggest to remove MC if oceans are maxed

- src/cards/base/LightningHarvest.ts
- src/cards/base/Livestock.ts
- src/cards/base/LocalHeatTrapping.ts
- src/cards/base/LunarBeam.ts
Somehow missed based cards while converting to static memory pattern.
> add missed base cards for static memory pattern

- src/Player.ts
- src/deferredActions/DrawCards.ts
Fixes bug from discord, `ASA does not say what it drew`: https://discord.com/channels/737945098695999559/742721510376210583/798579400919875645
> Fixed logging cards that were drawn

- src/cards/base/Virus.ts
- tests/cards/base/Virus.spec.ts
Closes https://github.com/bafolts/terraforming-mars/issues
> Fix: Virus should enable playing CrashSiteCleanup in solo

- src/components/GameHome.ts
> add https if not localhost

- src/cards/ares/CapitalAres.ts
- src/cards/ares/CommercialDistrictAres.ts
- src/cards/base/Capital.ts
- src/cards/base/CommercialDistrict.ts
- src/cards/base/Decomposers.ts
- src/cards/base/Herbivores.ts
- src/cards/base/ImmigrationShuttles.ts
- src/cards/colonies/JovianLanterns.ts
- src/cards/promo/AsteroidHollowing.ts
- src/cards/venusNext/Extremophiles.ts
- src/cards/venusNext/FloatingHabs.ts
This closes #2325
Managed to resolve all but two of the cards mentioned. `Birds` and `Asteroid deflection system` don't have enough space to work with. I'll leave them for a future iteration.
> Vp text consistency

- src/locales/cn/turmoil.json
update new Chinese translation
> update new Chinese translation 15th JAN

- .env.sample
- README.md
> Sample dot env

- src/cards/promo/AsteroidRights.ts
- src/cards/venusNext/ExtractorBalloons.ts
> Fixed extractor baloons + asteroid rights

- src/locales/cn/preferences.json
> hotkey funtion cn translation

- src/locales/cn/moon.json
> create moon CN translation

- tests/TestingUtils.ts
Timer off for test as requested by @kberg .
> timer off for test

- README.md
smallest change for reference to default branch name on repo
> change default branch name reference

- src/Player.ts
https://github.com/bafolts/terraforming-mars/commit/0cdd287cf584dc21cf0cae0d2355ccf44651c082#r46035374
Edit: Could need some tests that player inputs are doing what they say they do, not just testing the underlying methods. Not gonna write them though :D
> Fix not being able to pass anymore

- src/turmoil/Turmoil.ts
- tests/Turmoil.spec.ts
Closes https://github.com/bafolts/terraforming-mars/issues/2449
> Turmoil resolution fix

- src/Player.ts
- src/cards/community/Playwrights.ts
- src/cards/promo/LawSuit.ts
- src/cards/promo/ProjectInspection.ts
- src/colonies/Colony.ts
- tests/cards/promo/ProjectInspection.spec.ts
Should be good to fix https://github.com/bafolts/terraforming-mars/pull/2441
Wrote a verbose test to make sure things won't be broken again later.
> Fix Playwrights / Project Inspection interaction

- src/cards/base/SpaceElevator.ts
I'll follow up with a test in a moment. This should get the active game going.
> Add productionDelta for Space Elevator when using Robotic Workforce.

- src/cards/colonies/AtmoCollectors.ts
> fix atmo collect button text

- src/cards/base/BiomassCombustors.ts
- src/cards/base/HeatTrappers.ts
- src/cards/base/RoboticWorkforce.ts
- src/cards/base/SpaceElevator.ts
- src/cards/moon/MareNubiumMine.ts
- tests/cards/base/RoboticWorkforce.spec.ts
> Restore RoboticWorkforce registration for four cards, and add a future-proofing test.

- src/cards/promo/Advertising.ts
- src/cards/promo/ArcadianCommunities.ts
- src/cards/promo/AsteroidDeflectionSystem.ts
- src/cards/promo/AsteroidHollowing.ts
- src/cards/promo/AsteroidRights.ts
- src/cards/promo/Astrodrill.ts
- src/cards/promo/CometAiming.ts
- src/cards/promo/CrashSiteCleanup.ts
- src/cards/promo/CuttingEdgeTechnology.ts
- src/cards/promo/DeimosDownPromo.ts
- src/cards/promo/DirectedImpactors.ts
- src/cards/promo/EnergyMarket.ts
- src/cards/promo/Factorum.ts
- src/cards/promo/FieldCappedCity.ts
- src/cards/promo/HiTechLab.ts
- src/cards/promo/ImportedNutrients.ts
- src/cards/promo/InterplanetaryTrade.ts
- src/cards/promo/JovianEmbassy.ts
- src/cards/promo/LawSuit.ts
- src/cards/promo/MagneticFieldGeneratorsPromo.ts
- src/cards/promo/MagneticShield.ts
- src/cards/promo/MeatIndustry.ts
- src/cards/promo/Meltworks.ts
- src/cards/promo/MercurianAlloys.ts
- src/cards/promo/MoholeLake.ts
Introduces the static card memory property initialization for 25 promo cards.
> static card memory for 25 promo cards

- src/components/CardsFilter.ts
- src/components/Preferences.ts
- src/components/SelectAmount.ts
- src/components/SelectCard.ts
- src/components/SelectColony.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForProjectCard.ts
- src/components/SelectOption.ts
- src/components/SelectPartyPlayer.ts
- src/components/SelectPlayer.ts
- src/components/SelectProductionToLose.ts
- src/components/TranslateMixin.ts
- src/components/moon/MoonBoard.ts
Introduce mixin for template translations.
Reduce translation function imports and use TranslateMixin
> Translate mixin

- src/cards/base/SpaceElevator.ts
- tests/MilestoneAwardSelector.spec.ts
This was more interesting a while ago, but the synergy list is on the verge of update with milestones and awards not related. The code that did this can be recovered and used if someone wants to provide a big update.
> Remove the array validation tests for the milestone award selector.

- src/cards/StandardProjectCard.ts
- src/cards/base/standardProjects/AquiferStandardProject.ts
- src/cards/base/standardProjects/AsteroidStandardProject.ts
- src/cards/base/standardProjects/CityStandardProject.ts
- src/cards/base/standardProjects/GreeneryStandardProject.ts
- src/cards/base/standardProjects/PowerPlantStandardProject.ts
- src/cards/base/standardProjects/SellPatentsStandardProject.ts
- src/cards/colonies/BuildColonyStandardProject.ts
- src/cards/moon/MoonColonyStandardProject.ts
- src/cards/moon/MoonMineStandardProject.ts
- src/cards/moon/MoonRoadStandardProject.ts
- src/cards/prelude/BufferGasStandardProject.ts
- src/cards/venusNext/AirScrappingStandardProject.ts
Now the Standard Projects are static, like the rest of cards.
> Made StandardProjectCard extends Card

- src/colonies/Colony.ts
Discord bug report: https://discord.com/channels/737945098695999559/742721510376210583/800214708606205972
> Fix: Don't award colony bonuses when Mercury copies trade

- src/components/overview/ActionLabel.ts
- src/components/overview/PlayerInfo.ts
- src/components/overview/PlayerStatus.ts
- src/components/overview/PlayerTimer.ts
- src/styles/common.less
- src/styles/player_home.less
- src/styles/players_overview.less
Part 1 of #2150. Another PR will handle the tag discounts.
Took some liberties and changed some of the original design:
* No sharp edges
* Player names in white instead of black
> Player boards rework

- src/cards/colonies/MinorityRefuge.ts
- src/cards/colonies/PioneerSettlement.ts
- src/deferredActions/BuildColony.ts
Fixes #2460 
Could use some tests but I've been lazy this time.
Also, Pioneer Settlement somehow never checked that you had enough MC prod to play it. =/
> Fix Minority Refuge & Pioneer Settlement

- src/Player.ts
- src/cards/promo/MonsInsurance.ts
- src/cards/promo/OrbitalCleanup.ts
- src/cards/promo/Penguins.ts
- src/cards/promo/PharmacyUnion.ts
- src/cards/promo/Philares.ts
- src/cards/promo/Potatoes.ts
- src/cards/promo/ProjectInspection.ts
More promo cards modified to use static memory pattern for properties.
> static card memory pattern for more promo cards

- src/cards/promo/Recyclon.ts
- src/cards/promo/RegoPlastics.ts
- src/cards/promo/SaturnSurfing.ts
- src/cards/promo/SelfReplicatingRobots.ts
- src/cards/promo/SmallAsteroid.ts
- src/cards/promo/Splice.ts
- src/cards/promo/StanfordTorus.ts
- src/cards/promo/SubCrustMeasurements.ts
- src/cards/promo/TopsoilContract.ts
Uses the static card property pattern for the remaining promo cards.
> static card property pattern for remaining promo cards

- src/Game.ts
- src/Player.ts
- src/turmoil/TurmoilHandler.ts
- src/turmoil/parties/PartyHooks.ts
- tests/Turmoil.spec.ts
- tests/cards/base/StripMine.spec.ts
- tests/cards/base/standardActions/ConvertHeat.spec.ts
- tests/cards/base/standardActions/ConvertPlants.spec.ts
- tests/cards/turmoil/WildlifeDome.spec.ts
- tests/cards/venusNext/GiantSolarShade.spec.ts
> Fix policy phase

- src/Game.ts
> Fix undoing the first action going back to research

- src/cards/base/Ants.ts
- src/cards/base/Predators.ts
- src/cards/colonies/AirRaid.ts
- src/cards/venusNext/SponsoredAcademies.ts
- src/colonies/Colony.ts
- src/deferredActions/AddResourcesToCard.ts
- src/deferredActions/DecreaseAnyProduction.ts
- src/deferredActions/DeferredAction.ts
- src/deferredActions/PlaceCityTile.ts
- src/deferredActions/PlaceGreeneryTile.ts
- src/deferredActions/PlayProjectCard.ts
- src/deferredActions/RemoveAnyPlants.ts
- src/deferredActions/RemoveResourcesFromCard.ts
- src/deferredActions/SelectHowToPayDeferred.ts
- src/deferredActions/SelectProductionToLoseDeferred.ts
- src/deferredActions/SendDelegateToArea.ts
- src/deferredActions/StealResources.ts
- src/moon/PlaceMoonColonyTile.ts
- src/moon/PlaceMoonMineTile.ts
- src/moon/PlaceMoonRoadTile.ts
- tests/cards/colonies/AirRaid.spec.ts
- tests/colonies/Enceladus.spec.ts
- tests/colonies/Miranda.spec.ts
- tests/colonies/Titan.spec.ts
First PR of a few that will then add priorities everywhere needed to finally try to get effects order as good as we can.
> Make a proper Priority list for deferred actions

- src/components/overview/PlayerTags.ts
> Display Unity P4 and Iapetus discount

- src/Game.ts
- src/Phase.ts
- src/components/GameSetupDetail.ts
- src/components/PlayerHome.ts
- src/models/PlayerModel.ts
- src/server/ServerModel.ts
I hope for this PR to close #2542 .
But so far I only removed initialDraft from playerModel since we already have initialdraftvariant in gameoptionsmodel.
I am still not sure what is causing the problem.
> Remove initial draft from playermodel, fix initial draft label

- src/cards/turmoil/AerialLenses.ts
- src/cards/turmoil/BannedDelegate.ts
- src/cards/turmoil/CulturalMetropolis.ts
- src/cards/turmoil/DiasporaMovement.ts
- src/cards/turmoil/EventAnalysts.ts
- src/cards/turmoil/GMOContract.ts
- src/cards/turmoil/LakefrontResorts.ts
- src/cards/turmoil/MartianMediaCenter.ts
- src/cards/turmoil/PROffice.ts
- src/cards/turmoil/ParliamentHall.ts
- src/cards/turmoil/PoliticalAlliance.ts
First half of turmoil cards converted to pattern to use static card properties.
> static card properties for first turmoil cards

- src/components/DebugUI.ts
- src/components/card/CardCorporationLogo.ts
- src/locales/pl/base_corporations.json
- src/styles/cards_v2.less
- src/styles/language_hacks.less
Simplified Tharsis Republic markup
Add language css class to the debug-ui page
Demo: https://tm.alrusdi.ru/debug-ui
@Lynesth can you please fix translation and L&F of this card for French language? Feel free to push additional commits right into this branch (tharsis-republic-renovation)
> Tharsis republic renovation

- src/LogBuilder.ts
> Fix LogBuilder.tileType

- src/LogBuilder.ts
Reverts bafolts/terraforming-mars#2601
> Revert "Fix LogBuilder.tileType"

- src/database/IDatabase.ts
- src/database/LocalFilesystem.ts
- src/database/PostgreSQL.ts
- src/database/SQLite.ts
- src/tools/README.md
- src/tools/export_game.ts
- tests/utils/Vue.ts
It does have some sort of bug in that it doesn't exit. I guess it needs something that disconnects from the database or something.
> Add command-line tool that extracts a game from a production or SQLite database and stores it locally.

- src/styles/turmoil.less
> fix trailing delegate below red and yellow

- src/components/GameSetupDetail.ts
- src/models/GameOptionsModel.ts
- src/server/ServerModel.ts
> add no negative turmoil event to setup details

- src/components/LogPanel.ts
Fixes #2591, this time client-side
> Fix TileType logs

- src/cards/colonies/MarketManipulation.ts
- src/cards/colonies/MartianZoo.ts
- src/cards/colonies/MiningColony.ts
- src/cards/colonies/MinorityRefuge.ts
- src/cards/colonies/MolecularPrinting.ts
- src/cards/colonies/NitrogenFromTitan.ts
- src/cards/colonies/PioneerSettlement.ts
- src/cards/colonies/ProductiveOutpost.ts
- src/cards/colonies/QuantumCommunications.ts
- src/cards/colonies/RedSpotObservatory.ts
- src/cards/colonies/RefugeeCamps.ts
- src/cards/colonies/ResearchColony.ts
- src/cards/colonies/RimFreighters.ts
- src/cards/colonies/SkyDocks.ts
- src/cards/colonies/SolarProbe.ts
- src/cards/colonies/SolarReflectors.ts
- src/cards/colonies/SpacePort.ts
- src/cards/colonies/SpacePortColony.ts
- src/cards/colonies/SpinoffDepartment.ts
- src/cards/colonies/SubZeroSaltFish.ts
- src/cards/colonies/TitanAirScrapping.ts
- src/cards/colonies/TitanFloatingLaunchPad.ts
- src/cards/colonies/TitanShuttles.ts
- src/cards/colonies/TradeEnvoys.ts
- src/cards/colonies/TradingColony.ts
- src/cards/colonies/UrbanDecomposers.ts
- src/cards/colonies/WarpDrive.ts
Second part of colonies static cards - https://github.com/bafolts/terraforming-mars/pull/2595
> Static cards colonies M-Z

- src/Timer.ts
- src/components/overview/PlayerTimer.ts
- src/styles/players_overview.less
- tests/Timer.spec.ts
This update changes the timer behavior so it does not wrap after 24 hours. Instead, additional digits will be shown. Additionally, hours will not be shown until at least one hour has elapsed.
> Timer expand

- src/components/CreateGameForm.ts
I could also do
Or something even more obvious.
> Enable The Moon, mark it as alpha.

- src/components/DebugUI.ts
1) Delay page refresh when user is typing in search box
2) Ability to pass search string parameter via url like this: `/debug-ui?search=ai central`
> Debug UI tweaks

- tests/TestingUtils.ts
- tests/Turmoil.spec.ts
- tests/cards/ares/LavaFlowsAres.spec.ts
- tests/cards/base/LavaFlows.spec.ts
- tests/cards/base/RoboticWorkforce.spec.ts
- tests/cards/prelude/LavaTubeSettlement.spec.ts
- tests/politicalAgendas/Greens.spec.ts
- tests/politicalAgendas/Kelvinists.spec.ts
- tests/politicalAgendas/MarsFirst.spec.ts
- tests/politicalAgendas/Reds.spec.ts
- tests/politicalAgendas/Scientists.spec.ts
- tests/politicalAgendas/Unity.spec.ts
> Remove global function resetBoard in favor of TestingUtils.

- src/cards/moon/CosmicRadiation.ts
- src/cards/moon/HE3ProductionQuotas.ts
- src/cards/moon/LunaConference.ts
- src/cards/moon/LunarMineUrbanization.ts
- src/cards/moon/RevoltingColonists.ts
- src/cards/moon/WeGrowAsOne.ts
> Fixes requirements

- src/Game.ts
- src/cards/ICard.ts
- src/cards/ares/EcologicalSurvey.ts
- src/cards/ares/GeologicalSurvey.ts
- src/cards/base/ArcticAlgae.ts
- src/cards/base/Herbivores.ts
- src/cards/base/ImmigrantCity.ts
- src/cards/base/Pets.ts
- src/cards/base/RoverConstruction.ts
- src/cards/corporation/MiningGuild.ts
- src/cards/corporation/TharsisRepublic.ts
- src/cards/promo/Philares.ts
- src/cards/turmoil/LakefrontResorts.ts
- tests/cards/corporation/MiningGuild.spec.ts
- tests/cards/promo/ArcadianCommunities.spec.ts
After a comment by @kberg I thought it would be a good idea to streamline onTilePlaced a bit more.
To do that, I added a 3rd argument to the method and I tried to improve the logic here and there as well.
I also took care of converting Mining Guild to the new priority system, which I missed in the previous PR.
> Improve and "harmonize" onTilePlaced logic

- src/components/DebugUI.ts
@kevinb9n found a race condition in my implementation of throtling so i removed that functionality.
> Removed throtling when user types in search box

- src/components/CreateGameForm.ts
- src/styles/create_game_form.less
Add a discord invite that only shows up when Solo is selected.
> Discord link create game page

- README.md
Not sure what @chosta and @Lynesth want under their names. I feel like they should be added up there.
> Update readme contributors

- src/styles/resources.less
> show energy to heat conversion in box background

- src/CardLoader.ts
- src/cards/prelude/BufferGasStandardProject.ts
> Buffer Gas only in SoloTR mode

- src/Player.ts
2/2 of #2691
I think just putting the SPs option after the Pass button is the best solution here.
> StandardProjects option after Pass option

- src/locales/cn/cards.json
- src/locales/cn/colonies.json
- src/locales/de/cards.json
- src/locales/fr/base_cards.json
- src/locales/pl/cards.json
- src/locales/pl/colonies_cards.json
- src/locales/ru/cards.json
So, the https://github.com/bafolts/terraforming-mars/pull/2627 broke the translations, this fixes it.
Please update all the text when changing some text variables (Find and replace).
> Fixed translations

- assets/index.html
- src/components/App.ts
- src/components/CreateGameForm.ts
- src/components/GameEnd.ts
- src/components/GamesOverview.ts
- src/components/LoadGameForm.ts
- src/components/WaitingFor.ts
- src/constants.ts
This will close #430 . During multiplayer games animates the document title when user input is required. Most likely better animations. I selected `<^>v`. Suggestions welcome for better character sequences for the animation.
> animate title when waiting for input

- tests/cards/community/AerospaceMission.spec.ts
Closes https://github.com/bafolts/terraforming-mars/issues/2689
> Fix flaky test for AerospaceMission

- src/Game.ts
> Move mentioning the game end ID until after final greenery placement.

- src/Player.ts
- src/cards/community/Incite.ts
- src/cards/community/PoliticalUprising.ts
- src/cards/moon/LunaPoliticalInstitute.ts
- src/cards/turmoil/CulturalMetropolis.ts
- src/cards/turmoil/MartianMediaCenter.ts
- src/cards/turmoil/Recruitment.ts
- src/colonies/Colony.ts
- src/deferredActions/SendDelegateToArea.ts
- src/locales/pl/turmoil_cards.json
- src/turmoil/Turmoil.ts
This is composed of two commits. Reading each separately will probably make it easier to understand.
> Rework the send delegate to area action using an options dictionary.

- src/server.ts
Move the massive if bracket into URL path processing.
This improves readability and comprehension, but more important it wil set up for the oauth API, where  more arbitrary query parameters might be attached to URLs. (Specifically, the root path, but why not get some clean code out of it.)
> Update server URL handling

- src/cards/promo/MoholeLake.ts
- src/deferredActions/AddResourcesToCard.ts
> Minor field rename and text simplification.

- src/cards/moon/MoonCardManifest.ts
- src/cards/moon/TheGrandLunaCapitalGroup.ts
- src/moon/MoonExpansion.ts
- tests/cards/moon/TheGrandLunaCapitalGroup.spec.ts
> Add The Grand Luna Capital Group.

- src/Game.ts
- src/cards/moon/NanotechIndustries.ts
- src/cards/moon/ProcessorFactory.ts
- src/components/GameSetupDetail.ts
- src/components/PlayerHome.ts
- src/turmoil/parties/Reds.ts
Moon solo extends the game by 2 generations
Plus a wording fix - no translations found.
Fix the generation count on the main page when using The Moon.
Fix text on Nanotech Industries and Processor Factory
Show The Moon expansion icon in the Game Setup page.
> Moon solo extends the game by 2 generations

- src/components/CorporationsFilter.ts
- src/components/CreateGameForm.ts
> Add The Moon to the corporation filter.

- src/cards/Card.ts
- src/cards/CardMetadata.ts
- src/cards/ICard.ts
- src/cards/base/AntiGravityTechnology.ts
- src/cards/base/EarthCatapult.ts
- src/cards/base/EarthOffice.ts
- src/cards/base/MassConverter.ts
- src/cards/base/QuantumExtractor.ts
- src/cards/base/ResearchOutpost.ts
- src/cards/base/Shuttles.ts
- src/cards/base/SpaceStation.ts
- src/cards/colonies/SkyDocks.ts
- src/cards/colonies/WarpDrive.ts
- src/cards/corporation/Teractor.ts
- src/cards/corporation/Thorgate.ts
- src/cards/moon/MoonTether.ts
- src/cards/prelude/CheungShingMARS.ts
- src/cards/prelude/ValleyTrust.ts
- src/cards/venusNext/VenusWaystation.ts
- src/components/overview/PlayerTags.ts
- src/models/CardModel.ts
- src/server/ServerModel.ts
> Replace localized card discount reporting, moving it to the card. Add Moon Tether.

- src/routes/GameLogs.ts
There is missing return statement
> Fix error handling when logs loading is failed

- src/styles/cards.less
Continuation of https://github.com/bafolts/terraforming-mars/pull/2702
After some games, I think the darker cards are too dark. This PR gives them some new light.
> Brighter dark cards

- src/components/CreateGameForm.ts
> check custom corp count

- src/routes/Route.ts
- tests/routes/ApiGames.spec.ts
- tests/routes/HttpMocks.ts
Obviously, this is also a PR for the general structure. I'm still not sold on it. More sophisitcated tests will need to read the content itself and convert it from JSON, for instance. But for the moment this does the job.
> Add test for ApiGames.

- src/server/ServerModel.ts
> fix discount from corporation not showing

- src/components/GameSetupDetail.ts
> fix venus next milestone info

- src/cards/base/MarsUniversity.ts
Otherwise this is what you get, two card drawn in a row, it looks like a bug.
> Log that the Mars University Effect is being used.

- compile-vue-templates.js
- src/components/LogPanel.ts
- src/routes/GameLogs.ts
- tests/routes/ApiGameLogs.spec.ts
- tests/routes/FakeGameLoader.ts
This adds back in the ability to see all logs. On the first generation the logs before the first generation are shown. On the final generation the last 50 are shown. Also added tests! Had to expand the api test handler to support loading by player id.
> pull logs one generation at a time

- src/cards/Card.ts
- src/cards/colonies/Aridor.ts
- src/cards/colonies/Arklight.ts
- src/cards/colonies/Polyphemos.ts
- src/cards/colonies/Poseidon.ts
- src/cards/colonies/StormCraftIncorporated.ts
Changes the last few colony cards to use the static property pattern.
> static property card pattern for remaining colony cards

- src/cards/turmoil/Pristar.ts
- src/cards/turmoil/Recruitment.ts
- src/cards/turmoil/SeptumTribus.ts
- src/cards/turmoil/TerralabsResearch.ts
- src/cards/turmoil/UtopiaInvest.ts
- src/cards/turmoil/VoteOfNoConfidence.ts
- src/cards/turmoil/WildlifeDome.ts
Uses static properties for cards for remaining turmoil cards.
> static card property for turmoil cards

- src/MilestoneAwardSelector.ts
Fix for `Unexpected server response: internal server error /game Milestone Networker not found.`
> Fix: Multiplayer games cannot be started

- src/MilestoneAwardSelector.ts
selection by using a controlled list which omits Ares.
> Reduce the number of milestones and awards that are eligible for random

- src/components/WaitingFor.ts
- src/styles/player_home.less
2 of the harvey balls are badly displayed on mac os.
Making the animation using only the supported 4.
The animation now is rotating black semi-circle.
> "waiting for" animation fix

- src/styles/moon.less
> Reduce moon size by ~40%

- .github/stale.yml
This introduces `stale` to close out issues and pull requests which have gone stale.
https://probot.github.io/apps/stale/
I have started it with the default settings.
> use stale bot

- src/tools/README.md
- src/tools/analyze_ma.html
- src/tools/analyze_ma.ts
> Add Analyze MA tool.

- src/components/GameEnd.ts
- src/styles/game_end.less
> Change game-end viz to make points stand out, and reduce less important data.

- src/cards/community/AgricolaInc.ts
- src/cards/community/Incite.ts
- src/cards/community/Midas.ts
- src/cards/community/Playwrights.ts
- src/cards/community/ProjectWorkshop.ts
- src/cards/venusNext/Aphrodite.ts
- src/cards/venusNext/Celestic.ts
- src/cards/venusNext/Manutech.ts
- src/cards/venusNext/MorningStarInc.ts
- src/cards/venusNext/Viron.ts
This should be the last batch of cards before the moon cards.
> more cards to static card properties

- src/cards/moon/TempestConsultancy.ts
> Fix Tempest Consultancy rendering.

- src/components/CardsFilter.ts
Adds support for a CSV string to be pasted into the excluded card list. Will close #1440
> allow for CSV string in excluded card list

- src/Game.ts
- src/cards/base/DesignedMicroOrganisms.ts
- src/cards/base/ElectroCatapult.ts
- src/cards/base/ExtremeColdFungus.ts
- src/cards/base/NaturalPreserve.ts
- src/cards/prelude/MartianSurvey.ts
- src/cards/prelude/Psychrophiles.ts
- src/cards/venusNext/RotatorImpacts.ts
- tests/cards/base/DesignedMicroOrganisms.spec.ts
- tests/cards/base/ElectroCatapult.spec.ts
- tests/cards/base/ExtremeColdFungus.spec.ts
- tests/cards/base/NaturalPreserve.spec.ts
- tests/cards/prelude/MartianSurvey.spec.ts
- tests/cards/prelude/Psychrophiles.spec.ts
- tests/cards/venusNext/RotatorImpacts.spec.ts
Also iuncludes some test cleanup.
> Remove Game.checkMinRequirements, which is no longer necessary.

- src/cards/moon/EarthEmbassy.ts
> Fixing earth embassy - visual issue

- src/cards/base/NitriteReducingBacteria.ts
- src/cards/base/OlympusConference.ts
- src/cards/base/PhysicsComplex.ts
- src/cards/base/SearchForLife.ts
- src/cards/base/SecurityFleet.ts
- src/cards/colonies/AtmoCollectors.ts
- src/cards/colonies/JovianLanterns.ts
- src/cards/colonies/RedSpotObservatory.ts
- src/cards/colonies/RefugeeCamps.ts
- src/cards/colonies/StormCraftIncorporated.ts
- src/cards/colonies/TitanAirScrapping.ts
- src/cards/turmoil/Pristar.ts
- src/cards/venusNext/AerialMappers.ts
- src/cards/venusNext/Celestic.ts
- src/cards/venusNext/DeuteriumExport.ts
- src/cards/venusNext/Dirigibles.ts
- src/cards/venusNext/ExtractorBalloons.ts
- src/cards/venusNext/JetStreamMicroscrappers.ts
- src/cards/venusNext/LocalShading.ts
- tests/cards/venusNext/ExtractorBalloons.spec.ts
This makes the cards compatible with some of the promo cards.
> Use addResourceTo and removeResourceFrom.

- src/cards/ares/OceanSanctuary.ts
- src/cards/moon/AncientShipyards.ts
- src/cards/moon/DarksideIncubationPlant.ts
- src/cards/moon/IntragenSanctuaryHeadquarters.ts
- src/cards/moon/RustEatingBacteria.ts
- src/cards/moon/TheDarksideofTheMoonSyndicate.ts
This makes the cards compatible with some of the promo cards.
> Use addResource and removeResource methods.

- src/locales/cn/cards.json
> Update CN cards.json 

- assets/index.html
Adds a description tags. This might get used by google to provide better result in search results. This can close #3029
> add meta description tag

- src/colonies/Colony.ts
Mixed up the colony bonus and trade bonus previously
> Fix Leavitt colony bug

- src/locales/cn/base_corporations.json
remove colonies company to colonies.json
> Update  base_corporations.json

- src/routes/ApiWaitingFor.ts
- tests/routes/ApiWaitingFor.spec.ts
With the ETag I added to get waiting for route I completely broke when it is time to go sending "GO". This sends the "GO" when it is time to go. I added a regression test for this situation.
> send model when time to go

- src/locales/cn/moon_cards.json
move company to new file. add more moon card translation
> Update CN moon_cards.json

- src/components/Colony.ts
- src/styles/board.less
This PR improves colony cube UI. The cube on the colonies are too small and sometimes hard to see that there is any cube there on some colonies. This UI improvement is inspired by the community server change, although the code is rewritten a bit.
> improve colony cube ui

- src/components/SelectCard.ts
- src/deferredActions/DrawCards.ts
Shows how many cards are being bought or selected. This is particular useful for Business Network:
> Fix typo & show how many cards being bought.

- src/Game.ts
- tests/Game.spec.ts
> Space bonuses are granted en masse.

- src/cards/moon/IntragenSanctuaryHeadquarters.ts
- tests/cards/moon/IntragenSanctuaryHeadquarters.spec.ts
Changes inital action behavior.
> Fix Intragen Sanctuary.

- src/cards/CardRequirement.ts
- src/cards/moon/ColonistShuttles.ts
- src/cards/moon/CosmicRadiation.ts
- src/cards/moon/HE3FusionPlant.ts
- src/cards/moon/HE3ProductionQuotas.ts
- src/cards/moon/HeavyDutyRovers.ts
- src/cards/moon/LunaConference.ts
- src/cards/moon/LunaHyperloopCorporation.ts
- src/cards/moon/LunaMiningHub.ts
- src/cards/moon/LunaTradeStation.ts
- src/cards/moon/LunaTrainStation.ts
- src/cards/moon/LunarMineUrbanization.ts
- src/cards/moon/RevoltingColonists.ts
- src/cards/moon/TheDarksideofTheMoonSyndicate.ts
- src/cards/moon/TheGrandLunaCapitalGroup.ts
- src/moon/MoonBoard.ts
- src/moon/MoonExpansion.ts
- tests/cards/moon/TheGrandLunaCapitalGroup.spec.ts
There's a couple of rewrites that make moon tile testing better in general, including dealing with bug #3088, but it fixes #3086
> Moon tile testing rewrite & Fix Grand Luna Capital Group.

- src/Game.ts
- src/awards/Industrialist.ts
- src/awards/Miner.ts
- src/awards/Thermalist.ts
- src/components/Award.ts
This PR can close #3100.
The awards that count resources should getScore that accounts for the final production as if the game is to end now.
See Thermalist is 7 for Red Player instead of 3.
> calculate award properly

- src/locales/fr/base_cards.json
- src/locales/fr/base_corporations.json
I basically used english keyword input from chinese file as reference for translation. 
I let the traduction unchanged, i changed only the keys.
But I noticed some mistake, so some differences could appear.
> fix french translation for base cards and base corporation

- src/cards/base/PhobosSpaceHaven.ts
> Fix phobos Space Heaven Card city asterix

- src/components/CreateGameForm.ts
Sets the player objects by index while uploading JSON for a game. This will close #3061
> set players by index

- src/cards/base/InvestmentLoan.ts
> fix investment loan card number

- src/moon/MoonExpansion.ts
- tests/cards/moon/LunarMineUrbanization.spec.ts
A stark reminder that special tiles need special care.
> More Lunar Mine Urbanization.

- src/components/GamesOverview.ts
Changing the GameLoader function broke getting a list of games. This fixes it.
> Fix game overview page

- src/cards/moon/TheDarksideofTheMoonSyndicate.ts
It ain't much, but it's better.
> Minor render for Darkside Of The Moon Syndicate.

- src/Game.ts
- src/LogBuilder.ts
- src/LogMessage.ts
- src/components/LogPanel.ts
- src/routes/GameLogs.ts
- tests/routes/ApiGameLogs.spec.ts
This is only going to be used for helping players see what cards they were dealt, but as a demo, it's giving an introductory "good luck" message.
This seems to work between server restarts.
Don't use this feature for cards yet, let's make sure these messages can't accidentally leak into other browsers. I'm fairly certain they can't but anything can happen. Like bad deserialization. (I manually tested deserialization btw)
> Introduce the notion of a private message to a player.

- src/cards/base/SearchForLife.ts
I admit I didn't test this one manually.
> Display what card is drawn before showing that life is found.

- src/cards/promo/Astrodrill.ts
- src/cards/promo/MagneticShield.ts
- tests/cards/promo/MagneticShield.spec.ts
First two points of https://github.com/bafolts/terraforming-mars/issues/3182
> Bigbox edits

- src/turmoil/globalEvents/GlobalEventDealer.ts
- src/turmoil/globalEvents/GlobalEventName.ts
- tests/turmoil/globalEvents/GlobalEventDealer.spec.ts
The miners of strike should be miners on strike. Fixes #3201
> rename for Miners On Strike

- src/cards/promo/Advertising.ts
- src/cards/promo/AsteroidDeflectionSystem.ts
- src/cards/promo/AsteroidHollowing.ts
- src/cards/promo/CometAiming.ts
- src/cards/promo/CrashSiteCleanup.ts
- src/cards/promo/CuttingEdgeTechnology.ts
- src/cards/promo/DeimosDownPromo.ts
- src/cards/promo/DirectedImpactors.ts
- src/cards/promo/DiversitySupport.ts
- src/cards/promo/FieldCappedCity.ts
- src/cards/promo/GreatDamPromo.ts
- src/cards/promo/ImportedNutrients.ts
- src/cards/promo/JovianEmbassy.ts
- src/cards/promo/MagneticFieldGeneratorsPromo.ts
- src/cards/promo/MagneticShield.ts
- src/cards/promo/MeatIndustry.ts
- src/cards/promo/Meltworks.ts
- src/cards/promo/MoholeLake.ts
- src/cards/promo/Potatoes.ts
- src/cards/promo/SubCrustMeasurements.ts
- src/cards/promo/TopsoilContract.ts
As per Kevin's new data on the big box.
https://docs.google.com/spreadsheets/d/1LtewYJWBMFx6OCNgffu6jHQ3L4qsRD4e-cCUw3WAjfw/edit
> update cutting edge cost

- src/cards/moon/OffWorldCityLiving.ts
> Fix Off World City Living formatting.

- compile-vue-templates.js
- src/components/PlayerHome.ts
- src/components/Sidebar.ts
This is the first of a few changes that simplify Preferences a bit, separate components, clean up CSS and also make room for The Moon global parameters on the sidebar.
> Rename Preferences to Sidebar.

- src/components/Award.ts
- src/components/Milestone.ts
- src/components/PlayerHome.ts
Hides the scores for the awards and milestones during initial card selection. Closes #2090
> hide scores for awards and milestones

- src/cards/moon/DarksideIncubationPlant.ts
- src/cards/moon/DarksideMiningSyndicate.ts
- src/cards/moon/TheDarksideofTheMoonSyndicate.ts
> Minor tweaks for moon cards.

- src/components/DebugUI.ts
- src/components/Sidebar.ts
- src/styles/preferences.less
- src/tools/analyze_ma.html
This is the second step in reworking the sidebar a bit.
> Move global parameters to a dedicated sidebar css class.

- src/components/GameEnd.ts
> Add a visual break at game end before showing the milestones.

- src/locales/br/UI.json
- src/locales/br/base_cards.json
- src/locales/br/base_corporations.json
- src/locales/br/colonies_cards.json
- src/locales/br/colonies_corp.json
- src/locales/br/log_messages.json
- src/locales/br/prelude.json
- src/locales/br/prelude_corporations.json
- src/locales/br/promo.json
- src/locales/br/rebalanced.json
- src/locales/br/standard_projects.json
- src/locales/br/turmoil.json
- src/locales/br/turmoil_cards.json
- src/locales/br/turmoil_corporations.json
- src/locales/br/venusnext.json
> Brazilian portuguese translations

- compile-vue-templates.js
- src/LogBuilder.ts
- src/LogMessageDataType.ts
- src/LogMessageType.ts
- src/components/GlobalEvent.ts
- src/components/LogPanel.ts
- src/components/Turmoil.ts
- src/locales/br/log_messages.json
- src/locales/cn/log_messages.json
- src/models/TurmoilModel.ts
- src/styles/cards.less
- src/styles/turmoil.less
- src/turmoil/Turmoil.ts
- src/turmoil/globalEvents/GlobalEventDealer.ts
> Show Global Events when clicking on them in the log.

- src/cards/corporation/TharsisRepublic.ts
- src/components/Board.ts
- src/components/Sidebar.ts
- src/components/card/CardDescription.ts
- src/components/card/CardRenderSymbolComponent.ts
- src/components/overview/PlayerResource.ts
- src/locales/br/base_corporations.json
- src/locales/cn/base_corporations.json
- src/locales/de/cards.json
- src/locales/es/base_corporations.json
- src/locales/fr/base_corporations.json
- src/locales/pl/base_corporations.json
- src/locales/ru/corporations.json
Manually verified all of these with a couple of solo games.
> Remove uses of v-html.

- src/cards/base/NoctisCity.ts
> Fix Noctis City card city asterix

- src/components/Board.ts
- src/tools/README.md
This was due to a bad merge at 1fb5ab1aa2bf8508b086df9d5d6c0692687fb1ba
> Use the translation mixin instead of directives.

- src/CardName.ts
- src/cards/promo/BactoviralResearch.ts
- src/cards/promo/PromoCardManifest.ts
- tests/cards/promo/BactoviralResearch.spec.ts
> Add new promo card Bactoviral Research

- src/cards/base/ArcticAlgae.ts
> arctic algae log

- tests/cards/community/AerospaceMission.spec.ts
This PR fix #3165 .
It ensures the colonies in the list can be build on. (Not Miranda, Titan, and Enceladus)
> fix aerospace mission flaky tests

- src/cards/ares/EcologicalSurvey.ts
- src/cards/ares/GeologicalSurvey.ts
- src/cards/base/ArcticAlgae.ts
- src/deferredActions/GainResources.ts
> Move from logging to a callback.

- src/components/PreferencesDialog.ts
- src/components/Sidebar.ts
- src/components/overview/PlayerInfo.ts
- src/styles/preferences.less
There's only two commits, but you can read each one inidivdually.
I wish there was a way to make this review easier.
> Move preferences to its own component.

- src/database/GameLoader.ts
- src/database/IGameLoader.ts
- src/server.ts
- tests/database/GameLoader.spec.ts
- tests/routes/FakeGameLoader.ts
Reverts bafolts/terraforming-mars#3301
This seems to be blocking the JS thread while it is running. Huge memory spikes and timeouts while this runs.
> Revert "clear ended games on the hour"

- src/Player.ts
> fix steel value in canAfford

- src/cards/base/MarsUniversity.ts
- src/locales/br/log_messages.json
- src/locales/cn/log_messages.json
- src/locales/it/log_messages.json
Also clarify to everyone that you discarded a card.
> Fix Mars University logging, show what card you discarded.

- src/TileType.ts
- src/ares/AresHandler.ts
- src/awards/DesertSettler.ts
- src/awards/EstateDealer.ts
- src/awards/Landlord.ts
- src/milestones/PolarExplorer.ts
- tests/awards/Landlord.spec.ts
Exclude Landclaimed Ares tiles from land-based awards and milestones.
This PR closes #3337 .
> Exclude landclaimed Ares tiles

- tests/components/FakeLocalStorage.ts
- tests/components/SelectHowToPayForProjectCard.spec.ts
- tests/components/SortableCards.spec.ts
Also, `() =>`  is preferred as it provides more powerful reference to `this`
> Clarify testing against localstorage with a Fake.

- src/cards/promo/BactoviralResearch.ts
- src/locales/br/promo.json
https://www.facebook.com/groups/476648132730637/permalink/1293016461093796/
> fix bactoviral number and card description

- src/components/PaymentWidgetMixin.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForProjectCard.ts
- src/components/SelectProductionToLose.ts
`is-disabled` and `is-primary` aren't even in the .less files.
> Remove unused getCssClassFor, and use () => so `this` is the prefered `this`.

- src/cards/venusNext/StratosphericBirds.ts
- tests/cards/venusNext/StratosphericBirds.spec.ts
Fix from Jeep, closes https://github.com/bafolts/terraforming-mars/issues/3346
> Fix bug with Stratospheric Birds and single Dirigibles floater

- src/components/help/HelpPhases.ts
> Typo in Solar Phase -> Turmoil

- .github/workflows/main.yml
- package.json
1. Split server testing to test:server.
2. Run tests without having to delete any part of them.
> package.json test feature enhancements

- src/components/Tag.vue
- src/components/TagCount.vue
- src/components/overview/PlayerTags.ts
- tests/components/Tag.spec.ts
- tests/components/TagCount.spec.ts
Moves two more components to single file components.
> single file component: move Tag.ts to Tag.vue, move TagCount.ts to TagCount.vue

- src/database/LocalFilesystem.ts
Now that game ids start with `g` this is better.
> Remove `game` prefix from the local filesystem db

- src/components/moon/MoonSpace.ts
> Add Bonus.vue to the Moon. Somehow this wasn't part of The Moon. Huh.

- src/deferredActions/ChoosePoliticalAgenda.ts
- src/turmoil/Bonus.ts
- src/turmoil/parties/Greens.ts
- src/turmoil/parties/Kelvinists.ts
- src/turmoil/parties/MarsFirst.ts
- src/turmoil/parties/Reds.ts
- src/turmoil/parties/Scientists.ts
- src/turmoil/parties/Unity.ts
- tests/turmoil/parties/Reds.spec.ts
Closes https://github.com/bafolts/terraforming-mars/issues/2403
> Display ruling bonus scores for new Chairman

- src/Player.ts
- src/cards/moon/LunaArchives.ts
- src/cards/moon/MoonCardManifest.ts
- src/components/PaymentWidgetMixin.ts
- src/components/SelectHowToPay.ts
- src/components/SelectHowToPayForProjectCard.ts
- src/inputs/HowToPay.ts
- src/inputs/SelectHowToPayForProjectCard.ts
- src/models/PlayerInputModel.ts
- src/models/ServerModel.ts
- src/styles/resources.less
- tests/cards/moon/LunaArchives.spec.ts
- tests/cards/venusNext/StratosphericBirds.spec.ts
- tests/components/SelectHowToPayForProjectCard.spec.ts
- tests/components/ShiftAresGlobalParameters.spec.ts
> Add Moon card Luna Archives

- src/turmoil/Turmoil.ts
> Fix duplicate function Turmoil.ifTurmoil

- src/components/PaymentWidgetMixin.ts
> SelectHowToPay doesn't have a science component.

- src/components/PaymentWidgetMixin.ts
- src/components/SelectHowToPay.ts
- src/components/common/Button.vue
- tests/components/SelectHowToPay.spec.ts
Made it more sophsiticated so it's easier to read and more clicks can be verified.
> Add test for SelectHowToPay.

- src/components/card/CardTitle.vue
- src/styles/language_hacks.less
Calculate card title size from translated text instead on English only.
> Better fit of card titles in Russian and Spanish languages

- src/cards/base/RoboticWorkforce.ts
- tests/cards/base/RoboticWorkforce.spec.ts
Check that the player has enough energy to duplicate with Robotic Workforce.
> Robotic Workforce Gyropolis energy check

- src/components/LogPanel.vue
- src/directives/i18n.ts
- tests/TestingUtils.ts
Closes https://github.com/bafolts/terraforming-mars/issues/3373
> Fix for logPanel regex only going up to 9

- src/Player.ts
- src/moon/MoonExpansion.ts
- tests/Player.spec.ts
- tests/moon/MoonExpansion.spec.ts
I will follow up with a couple more tests, as I noticed that the actual WGT operations aren't tested.
Fixes #3448
> Don't place Moon tiles during WGT, just raise the rates.

- src/models/PlayerModel.ts
Manual test and automated tests pass.
> Remove PlayerModel fields  in PublicPlayerModel.

- src/components/overview/PlayerInfo.ts
- src/components/overview/PlayerStatus.ts
- tests/components/overview/PlayerStatus.spec.ts
> Remove unused activePlayer from PlayerStatus.

- .gitignore
- package-lock.json
- package.json
- webpack.config.js
Since switching to single file components the build time has increased. This should improve the situation.
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin
Found this on the world wide web while looking for solutions to speed up build.
> speed up the build for webpack

- src/cards/promo/AsteroidRights.ts
- tests/cards/promo/AsteroidRights.spec.ts
Closes https://github.com/bafolts/terraforming-mars/issues/2930
> Improve options for Asteroid Rights

- tests/database/GameLoader.spec.ts
During my last [PR](https://github.com/bafolts/terraforming-mars/pull/3475) I have borked a few of GameLoader tests, which was not caught during the review, because they were passing...
This PR is fixing this situation. Problems being fixed:
- Most of the test need to become async, because the API became truly async, it used to be a sync with callback before, and the tests relied on it
- In the PR I did a very poor job addressing the above, so many tests became impossible to fail they would come up green no matter what
- Those tests that _would_ fail would give a generic timeout error instead of the real failure reason
- While PR did an attempt to fix problems with async substitution/restoration of the mock database interface functions, it did not do it correctly in all cases
Only the …
> improved GameLoader tests

- src/components/PaymentWidgetMixin.ts
- src/components/PlayerInputFactory.vue
- src/components/SelectHowToPayForProjectCard.vue
- tests/components/SelectHowToPayForProjectCard.spec.ts
Don't approve this. I want to break it into smaller pieces -- one that rewrites the testing, and also have this follow behind SelectHowToPay. But at least now this is here.
> SelectHowToPayForProjectCard as SFC.

- src/components/create/CreateGameForm.vue
Update link from https://github.com/bafolts/terraforming-mars/wiki/Variants#political-agendas to https://www.notion.so/Political-Agendas-8c6b0b018a884692be29b3ef44b340a9
> Update PoliticalAgendas documentation link

- src/Game.ts
- src/cards/base/ArtificialPhotosynthesis.ts
- src/cards/base/Insulation.ts
- src/cards/base/MedicalLab.ts
- src/cards/base/NitrogenRichAsteroid.ts
- src/cards/colonies/Aridor.ts
- src/cards/colonies/CommunityServices.ts
- src/cards/colonies/FloaterLeasing.ts
- src/cards/colonies/GalileanWaystation.ts
- src/cards/colonies/LunarMining.ts
- src/cards/corporation/SaturnSystems.ts
- src/cards/moon/DarksideMiningSyndicate.ts
- src/cards/moon/HE3Lobbyists.ts
- src/cards/moon/RoverDriversUnion.ts
- src/cards/moon/UndermoonDrugLordsNetwork.ts
- src/cards/promo/MonsInsurance.ts
- src/cards/turmoil/ParliamentHall.ts
- src/turmoil/TurmoilHandler.ts
- tests/cards/base/ArtificialPhotosynthesis.spec.ts
- tests/cards/base/MedicalLab.spec.ts
- tests/cards/colonies/CommunityServices.spec.ts
- tests/cards/colonies/LunarMining.spec.ts
(and also Mons Insurance, so players know they lost 2MC production)
> Add logging for variable resources

- src/components/SelectProductionToLose.vue
> Remove the player propery from SelectProductionToLose; it isn't used.

- src/components/AndOptions.vue
- src/components/LogPanel.vue
- src/components/OrOptions.vue
- src/components/PlayerInputFactory.vue
- src/components/SelectPartyPlayer.vue
- src/components/SelectPlayer.vue
- src/components/SelectPlayerRow.vue
- src/components/WaitingFor.vue
- src/models/ServerModel.ts
Also do the same in ServerModel. How is the compiler accepting these in the first place? Well part of it is that AndOptions, OrOptions and PlayerInputFactory abstract this a way a bit. A PlayerInputFactory test would not be an awful idea.
> When components accept 'players' note that players is of type PublicPlayerModel.

- src/components/AndOptions.vue
- src/components/LogPanel.vue
- src/components/OrOptions.vue
- src/components/PlayerInputFactory.vue
- src/components/SelectPartyPlayer.vue
- src/components/SelectPlayer.vue
- src/components/SelectPlayerRow.vue
- src/components/TopBar.vue
- src/components/WaitingFor.vue
- src/components/overview/PlayerInfo.vue
- src/components/overview/PlayerTags.vue
- src/components/overview/PlayersOverview.vue
- src/models/ServerModel.ts
Depends on  #3522
First: activePlayer is not a great term: the active player is the one taking the current action, but here it means "me, the player with the brower."
Second: Anyone who is NOT "me, the active player" is of type PublicPlayer, not PlayerView, so using the right types will clear things up.
There's a minor change for a component key to line it up with the others, too.
> Clarify PlayerTags & PlayerInfo.

- src/database/GameLoader.ts
- src/database/IDatabase.ts
- src/database/LocalFilesystem.ts
- src/database/PostgreSQL.ts
- src/database/SQLite.ts
- src/server.ts
- tests/utils/setup.ts
Allows database to initialize. I started with implementation for SQLite. Can do the others in separate commits.
> add initialize to IDatabase

- src/components/OtherPlayer.vue
- src/components/PlayerHome.vue
- src/components/PlayerMixin.ts
The commits can be broken up as #585919b, which uses PublicPlayerModel, #fb5545f, which also uses PublicPlayerModel, and #3ce7128, which is the change to PlayerHome. It introduces two computed properties, but only uses one of them; that one is easier for you, the reviewer, to consume and understand. The next one will use `thisPlayer`.
> Three minor model changes

- src/turmoil/Policy.ts
- src/turmoil/parties/Kelvinists.ts
- tests/turmoil/parties/Kelvinists.spec.ts
Closes https://github.com/bafolts/terraforming-mars/issues/3530
> Fix: Kelvinists P3 should be reusable with Stormcraft

- src/components/GameEnd.vue
- src/components/PlayerHome.vue
- src/components/overview/PlayerInfo.vue
- src/components/overview/PlayerStatus.vue
- src/components/overview/PlayerTags.vue
- src/components/overview/PlayersOverview.vue
Payment is a big change, and the next ones after are also pretty big. I'm excited!
> Last minor thisPlayer changes before payment

- src/Player.ts
- src/components/AndOptions.vue
- src/components/PlayerInputFactory.vue
- src/components/SelectColony.vue
Not sure this is necessary as much as it's probably just worth fixing selectColony. /shrug
> An attempt at a canSave UI.

- src/components/overview/PlayerInfo.vue
- src/components/overview/PlayerStatus.vue
- src/components/overview/PlayerTimer.vue
- src/models/PlayerModel.ts
- src/models/TimerModel.ts
This should fix #3547 .
I simplified the player status component a lot and only passed in what was needed. Test this with a quick multi player and single player game where I saw the timer tick. Also tested with show timers off and did not see the timer.
> fix player timer

- .gitignore
- make_static_json.js
- src/directives/i18n.ts
- src/main.ts
- src/routes/ServeAsset.ts
Reduce bundle size by 45% (from 387KB to 213KB)
> Async translations loading

- src/components/AndOptions.vue
- src/components/GameHome.vue
- src/components/LoadGameForm.vue
- src/components/LogPanel.vue
- src/components/OrOptions.vue
- src/components/OtherPlayer.vue
- src/components/SelectAmount.vue
- src/components/SelectCard.vue
- src/components/SelectColony.vue
- src/components/SelectHowToPay.vue
- src/components/SelectHowToPayForProjectCard.vue
- src/components/SelectInitialCards.vue
- src/components/SelectOption.vue
- src/components/SelectPartyPlayer.vue
- src/components/SelectPartyToSendDelegate.vue
- src/components/SelectPlayer.vue
- src/components/common/Button.vue
- src/components/create/CardsFilter.vue
- src/components/create/CreateGameForm.vue
- src/components/overview/PlayerInfo.vue
- tests/components/common/Button.spec.ts
I don't know why $root mock doesn't work in tests (tbh I have never seen $root in real vue before)
Btw guys: RTFM - [Accessing the Root Instance](https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-the-Root-Instance)
> This can be convenient for demos or very small apps with a handful of components. However, the pattern does not scale well to medium or large-scale applications, so we strongly recommend using Vuex to manage state in most cases.
I will fix these tests later - with `app.ts` refactor
> Refactor button component

- src/CardName.ts
- src/cards/promo/Harvest.ts
- src/cards/promo/PromoCardManifest.ts
- tests/cards/promo/Harvest.spec.ts
> Add Harvest promo card

- src/components/SelectHowToPayForProjectCard.vue
> Fix button listener

- .prettierrc.yaml
Current config fires formatting in IDE with prettier extensions.
> Remove prettier config

- src/components/SelectCard.vue
- src/components/SelectHowToPay.vue
- src/components/SelectHowToPayForProjectCard.vue
- src/components/SelectInitialCards.vue
Those were supposed to simplify the prior PR. My, they didn't add much.
> Remove the computed fields for player.

- src/Game.ts
- src/cards/venusNext/GiantSolarShade.ts
Since it doesn't actually return SelectSpace, make it return nothing.
> Remove return value from game.increaseVenusScaleLevel

- src/components/LogPanel.vue
Display resource count for cards clicked from LogPanel, if any
> Show resource count when clicking on cards in LogPanel

- src/components/DebugUI.vue
Turned out to be pretty easy after all.
> Remember which modules are selected in the card ui URL.

- assets/index.html
- src/components/App.ts
playerkey was not documented, and I wondered what purpose it served.
Now I know!
> Make Spectator Mode refresh.

- src/CardName.ts
- src/Game.ts
- src/cards/moon/MoonCardManifest.ts
- src/cards/moon/MoonColonyStandardProject.ts
- src/cards/moon/MoonMineStandardProject.ts
- src/cards/moon/MoonRoadStandardProject.ts
- src/cards/moon/MoonStandardProjectVariants.ts
- src/components/create/CreateGameForm.vue
- src/routes/Game.ts
- src/tools/analyze_ma.ts
- tests/TestingUtils.ts
- tests/cards/moon/MoonColonyStandardProject.spec.ts
- tests/cards/moon/MoonMineStandardProject.spec.ts
- tests/cards/moon/MoonRoadStandardProject.spec.ts
- tests/cards/moon/MoonStandardProjectVariants.spec.ts
> Add the Moon standard project variant.

- src/cards/moon/MoonColonyStandardProject.ts
- src/cards/moon/MoonMineStandardProject.ts
- src/cards/moon/MoonRoadStandardProject.ts
> Oh, man, moving the properties to the constructor was embarrassingly simple.
