package.json
=> Run the tests directly in the tests/ directory.

src/components/common/Button.vue, src/styles/common.less
=> Rounded corners for custom buttons.

src/cards/venusNext/FloatingHabs.ts
=> Remove duplicated text from Floating Habs.

src/client/components/GameHome.vue
=> Remove preview mode text for spectator.

src/Game.ts, tests/Game.spec.ts
Added new test for Air Scrapping regardless.
=> Provide default altVenusBoard option for legacy games.

src/database/LocalFilesystem.ts, src/database/SQLite.ts
=> Use process.cwd for declare where databases belong.

src/Game.ts, src/Player.ts
This uses the `some` and `every` functions in a few popular functions. These should be slightly more efficient as they exit earlier and avoid having to compare results. These old Array functions don't get enough respect!
=> perf: use some and every a few places

src/client/components/create/CreateGameForm.vue
Default file selection to json files. Closes #3638
=> limit to json files for create game upload

src/Game.ts, src/SerializedGame.ts, src/pathfinders/IPathfindersData.ts, src/pathfinders/PathfindersExpansion.ts, src/pathfinders/PlanetaryTrack.ts, src/pathfinders/PlanetaryTracks.ts, src/pathfinders/Reward.ts, src/pathfinders/SerializedPathfindersData.ts, tests/Game.spec.ts, tests/cards/moon/MartianEmbassy.spec.ts
This isn't going to have tests; that'll come in PF8, which will raise the tracks, and will verify that the tracks work.
BASED ON PF6.
=> PF7: Add the data structure for the planetary tracks.

src/cards/pathfinders/MartianMonuments.ts, src/cards/pathfinders/MuseumofEarlyColonisation.ts, src/cards/pathfinders/PathfindersCardManifest.ts, src/cards/pathfinders/TerraformingControlStation.ts, src/cards/render/CardRenderItemType.ts, src/cards/render/CardRenderer.ts, src/client/components/card/CardRenderItemComponent.vue, tests/TestPlayer.ts, tests/TestingUtils.ts, tests/cards/pathfinders/MartianMonuments.spec.ts, tests/cards/pathfinders/MuseumofEarlyColonisationspec.ts, tests/cards/pathfinders/NewVenice.spec.ts, tests/cards/pathfinders/TerraformingControlStation.spec.ts
And a minor change to New Venice.
=> PF9: Three more Pathfinders cards

src/routes/Game.ts
A bit of a hack for the time being, I admit to accommodate #3662
=> Remove Arabia Terra from the set of randomly-selected boards.

src/boards/BoardName.ts, src/client/components/create/CreateGameForm.vue, src/routes/Game.ts, tests/routes/Game.spec.ts
=> Separate fan-made Arabia Terra board visually, and reintroduce full random board selection.

src/Player.ts, src/cards/base/IndenturedWorkers.ts, src/cards/base/SpecialDesign.ts, src/cards/colonies/Conscription.ts, src/cards/pathfinders/LastResortIngenuity.ts, src/cards/pathfinders/PathfindersCardManifest.ts, src/cards/prelude/EccentricSponsor.ts, src/cards/prelude/EcologyExperts.ts, src/client/components/SelectHowToPayForProjectCard.vue, src/models/PlayerModel.ts, src/models/ServerModel.ts, tests/cards/pathfinders/LastResortIngenuity.spec.ts, tests/cards/prelude/EccentricSponsor.spec.ts, tests/cards/prelude/EcologyExperts.spec.ts, tests/components/SelectHowToPayForProjectCard.spec.ts, tests/moon/MoonExpansion.spec.ts
=> PF: Implement Last Resort Ingenuity

tests/TestGame.ts, tests/cards/ares/BioengineeringEnclosure.spec.ts, tests/cards/ares/BiofertilizerFacility.spec.ts, tests/cards/ares/ButterflyEffect.spec.ts
I'm writing a couple hundred more tests right now, and all the work for setting up a test is really gnawing at me. This reduces the amount of boilerplate to create a new game to use in a test. What do you think? It no longer keeps track of the number of colors in a game, for instance.
=> More simply express games for tests.

src/cards/pathfinders/Cyanobacteria.ts, src/deferredActions/AddResourcesToCards.ts, tests/deferredActions/AddResourcesToCards.spec.ts
There's a Pathfinders global event that does the same thing. So might as well make it a DeferredAction.
=> Move the Cyanobacteria code to AddResourcesToCards.

src/Player.ts, src/cards/base/AquiferPumping.ts, src/cards/base/CaretakerContract.ts, tests/cards/base/AquiferPumping.spec.ts, tests/cards/base/CaretakerContract.spec.ts
=> Two {tr} cases for actions

src/Player.ts, src/cards/moon/TempestConsultancy.ts, src/turmoil/Turmoil.ts, tests/cards/moon/TempestConsultancy.spec.ts, tests/turmoil/Turmoil.spec.ts
Also, beef up Turmoil tests a little.
=> Use turmoil.hasAvailableDelegates, clean up canPlay, fix TempestConsultancy.

src/Game.ts, src/turmoil/globalEvents/SnowCover.ts
Everything works already, this just prioritizes the check inside increaseTemperature.
=> Don't decrease temperature when it is maxed.

src/client/components/LogPanel.vue, src/client/components/PlayerHome.vue, src/models/GameModel.ts, src/models/ServerModel.ts, src/styles/log.less
This will be useful for debugging, particularly once we preserve full games.
=> Show the current saveid in the log.

package-lock.json, package.json, src/client/components/App.ts, src/client/components/HTMLDialogElementCompatibility.ts, src/client/components/LogPanel.vue, src/client/components/common/ConfirmDialog.vue, src/database/Cloner.ts, src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts, src/routes/PlayerInput.ts, tests/ares/AresHandler.spec.ts
There are two breaking changes:
1. catch blocks have moved from defaulting from type any to unknown. The database and PlayerInput changes reflect that.
2. Some DOM methods do not exist in the interface, and somehow were compiling, and now are not. I moved them to a single location, and tested manually using a Firefox browser.
=> Upgrade to Typescript 4.4.4

src/cards/render/CardRenderDynamicVictoryPoints.ts
I throw enough shade at every usage of `any`. This removes one usage of `any`.
=> remove a usage of any

src/client/components/PreferencesDialog.vue, src/client/directives/TrimWhitespace.ts
Removes more usages of `any` from the code.
=> remove more usages of any

src/database/IDatabase.ts, src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts, tests/database/SQLite.spec.ts, tests/utils/setup.ts
=> Add sanity test for Sqlite and add purge table.

src/cards/pathfinders/ICloneTagCard.ts, src/client/components/LoadGameForm.vue, src/models/LoadGameFormModel.ts, src/routes/LoadGame.ts
Removes another usage of `any` and adds a model for the load game form.
=> remove another any and add LoadGameFormModel

src/cards/pathfinders/EconomicHelp.ts, src/cards/pathfinders/ExperiencedMartians.ts, src/cards/pathfinders/PathfindersCardManifest.ts, src/cards/pathfinders/Steelaris.ts, src/cards/pathfinders/StrategicBasePlanning.ts, tests/cards/pathfinders/EconomicHelp.spec.ts, tests/cards/pathfinders/ExperiencedMartians.spec.ts, tests/cards/pathfinders/Steelaris.spec.ts, tests/cards/pathfinders/StrategicBasePlanning.spec.ts
One project card, one corp and two preludes.
=> PF37: Four pathfinders cards.

src/cards/turmoil/CulturalMetropolis.ts, tests/cards/turmoil/CulturalMetropolis.spec.ts
Card was not playable with 2 delegates in reserve.
Updated tests accordingly.
=> Fix cultural metropolis bug

src/client/components/PlayerHome.vue
=> Move the Pathfinders track back to the bottom.

src/Player.ts, src/cards/base/AsteroidMiningConsortium.ts, src/cards/base/BiomassCombustors.ts, src/cards/base/Birds.ts, src/cards/base/CloudSeeding.ts, src/cards/base/EnergyTapping.ts, src/cards/base/Fish.ts, src/cards/base/GreatEscarpmentConsortium.ts, src/cards/base/Hackers.ts, src/cards/base/HeatTrappers.ts, src/cards/base/Herbivores.ts, src/cards/base/HiredRaiders.ts, src/cards/base/PowerSupplyConsortium.ts, src/cards/base/SmallAnimals.ts, src/cards/colonies/SubZeroSaltFish.ts, src/cards/promo/LawSuit.ts, src/deferredActions/DecreaseAnyProduction.ts, src/deferredActions/StealResources.ts
Issue: https://github.com/terraforming-mars/terraforming-mars/issues/3175
=> Add proper logging for stealing-type cards

src/client/components/card/CardRequirementsComponent.vue
=> Whoops! Fix the visualization issue

src/cards/moon/LunaEcumenopolis.ts, tests/cards/moon/LunaEcumenopolis.spec.ts
=> Fix Luna Ecum. which should use Lunar Mine Urb.

src/client/components/card/CardResourceCounter.vue, src/styles/cards_v2.less
=> Restore resource counter icons.

src/client/components/card/CardRenderItemComponent.vue, src/client/components/card/CardRequirementComponent.vue, src/styles/cards_v2.less, src/styles/pathfinders.less
=> More requirements icon resizing. Global parameters, tags, Mars, floaters.

src/cards/render/CardRenderItem.ts, src/client/components/card/CardParty.vue, src/client/components/card/CardRenderItemComponent.vue, src/client/components/card/CardRequirementComponent.vue, src/styles/cards.less, src/styles/cards_v2.less, src/turmoil/globalEvents/BalancedDevelopment.ts, src/turmoil/globalEvents/ConstantStruggle.ts, src/turmoil/globalEvents/TiredEarth.ts
1. Fix card party requriement viz.
2. Reorder where the mars tag lives.
=> More reqs viz.

src/client/components/card/CardRenderItemComponent.vue, src/client/components/card/CardRequirementComponent.vue, src/styles/cards_v2.less, src/styles/moon.less
=> Card requirements updates: TR and all the moon rates.

src/turmoil/globalEvents/CommunicationBoom.ts, src/turmoil/globalEvents/ConstantStruggle.ts, src/turmoil/globalEvents/RedInfluence.ts
=> Fix global event renderings.

src/cards/pathfinders/PathfindersCardManifest.ts, src/cards/pathfinders/VitalColony.ts, src/colonies/Colony.ts, src/deferredActions/BuildColony.ts, tests/cards/pathfinders/VitalColony.spec.ts
I don't love the way this is going. Any advice?
(Specifically the way to grant the placement bonus twice.)
=> Add Pathfinders card Vital Colony

src/cards/community/TradeAdvance.ts, src/colonies/Colony.ts
Facilitates some new Pathfinders cards.
=> Use an options object to define how trading works.

src/locales/de/cards.json
=> Fix German mis-translation reported by user borbarad

src/client/components/Board.vue
=> Whoops! Added missing board spaces for pathfinders

src/Game.ts, src/Player.ts, src/cards/colonies/Aridor.ts, src/cards/colonies/TitanFloatingLaunchPad.ts, src/colonies/Colony.ts, src/deferredActions/BuildColony.ts, src/deferredActions/RemoveColonyFromGame.ts, src/inputs/SelectColony.ts, src/models/ColonyModel.ts, src/models/ServerModel.ts, tests/cards/colonies/TitanFloatingLaunchPad.spec.ts, tests/cards/colonies/TradingColony.spec.ts, tests/cards/community/AerospaceMission.spec.ts, tests/cards/pathfinders/StrategicBasePlanning.spec.ts, tests/cards/pathfinders/VitalColony.spec.ts
Review this by ignoring whitespace.
=> Simplify SelectColony API

src/cards/pathfinders/RobinHaulings.ts, tests/cards/pathfinders/RobinHaulings.spec.ts
Corp cards have different onCardPlayed semantics.
=> Fix Robin Haulings.

src/Player.ts, src/cards/colonies/Aridor.ts, src/colonies/ColoniesHandler.ts, src/colonies/ColonyDealer.ts, tests/cards/colonies/Aridor.spec.ts
Because the issue was in handling player input, the test uses player input.
Fixes #3882
=> Restore ability to add new colonies to the game.

src/cards/venusNext/Celestic.ts, tests/cards/venusNext/Celestic.spec.ts
This includes a nice test that will ensure future cards can be included.
=> Update known Celestic-compatible cards.

src/cards/pathfinders/HighTempSuperconductors.ts, src/turmoil/parties/Kelvinists.ts, tests/cards/pathfinders/HighTempSuperconductors.spec.ts
The intention was to support the Kelvinists Ruling Policy Action, not card actions.
=> Change High Temp Superconductors behavior.

tests/cards/colonies/TitanFloatingLaunchPad.spec.ts
This tests the path through the standard Trade action.
=> Titan floating launch pad test

src/client/components/SelectHowToPay.vue, src/client/components/SelectHowToPayForProjectCard.vue, src/client/mixins/PaymentWidgetMixin.ts, tests/components/PaymentTester.ts, tests/components/SelectHowToPay.spec.ts
This will be necessary to simplify the upcoming Soylent _something something_ project card.
The SHTP algorithm for computing initial values is now much less complicated, and does the same thing. All the tests pass against both the old version and this newer one. I left the code in for now, though, with a TODO to get rid of in in a couple of months.
=> Simplify PaymentWidgetMixin and SelectHowToPay

src/colonies/ColoniesHandler.ts, tests/cards/pathfinders/CollegiumCopernicus.spec.ts
Also removing repeated code while I'm in there.
=> Remove test flakiness.

src/Player.ts
=> Deserialize hasTurmoilScienceTagBonus.

src/cards/pathfinders/HuygensObservatory.ts
=> Update Huygens Observatory iconography

src/cards/CardRequirement.ts, src/cards/pathfinders/CoordinatedRaid.ts, src/cards/turmoil/VoteOfNoConfidence.ts, src/client/components/card/CardRequirementComponent.vue, src/styles/cards_v2.less
Had to add more --req classes, and do some weird magic with produciton.
Production still isn't perfect, but it's much better. This is basically good enough to almost turn on by default!
You can see it at http://terraforming-mars-kberg.herokuapp.com/cards
=> Nearly complete card requirement rendering.

src/client/components/DebugUI.vue
=> Make debug ui sort order case sensitive.

src/Game.ts, src/Player.ts, src/boards/Board.ts, src/cards/base/Flooding.ts, src/cards/base/standardProjects/AquiferStandardProject.ts, src/cards/pathfinders/Cyanobacteria.ts, src/cards/pathfinders/HydrogenProcessingPlant.ts, src/cards/pathfinders/SmallComet.ts, src/cards/promo/CometAiming.ts, src/deferredActions/PlaceOceanTile.ts, src/turmoil/globalEvents/DryDeserts.ts, src/turmoil/parties/Reds.ts
It's a small optimization, but it will make introducing the Wetlands tile much easier.
=> Bring ocean counting to one place.

src/client/components/SelectHowToPayForProjectCard.vue, src/styles/resources.less
Use this as an opportuninty to reduce duplication in less.
=> Make Seeds visible in project cards.

package-lock.json, package.json
8.4.0 fixes an issue that's been bothering me for a long time: https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#bug-fixes-7
I tried upgrading to a more current release (v9) but could not because
of mochapack. Sent out a request for details about that: https://github.com/sysgears/mochapack/discussions/120
=> Upgrade mocha to 8.4.0.

.github/workflows/main.yml
This adds a job to run docker build to the ci validation
=> Add docker build to ci

src/cards/render/CardRenderItem.ts, src/client/components/GlobalEvent.vue, src/styles/cards_v2.less, src/styles/turmoil.less, src/turmoil/globalEvents/AquiferReleasedByPublicCouncil.ts, src/turmoil/globalEvents/BalancedDevelopment.ts, src/turmoil/globalEvents/CloudSocieties.ts, src/turmoil/globalEvents/CommunicationBoom.ts, src/turmoil/globalEvents/Diversity.ts, src/turmoil/globalEvents/Election.ts, src/turmoil/globalEvents/JovianTaxRights.ts, src/turmoil/globalEvents/ParadigmBreakdown.ts, src/turmoil/globalEvents/RedInfluence.ts, src/turmoil/globalEvents/Revolution.ts, src/turmoil/globalEvents/SnowCover.ts, src/turmoil/globalEvents/SpaceRaceToMars.ts, src/turmoil/globalEvents/SponsoredProjects.ts, src/turmoil/globalEvents/SuccessfulOrganisms.ts, tests/metadata/CardRenderer.spec.ts
Add title, also, compress large titles.
Remove unised 'large' for digit.
Widen the entire global event.
Realign several global events for clarity.
MC -> M€
=> Many fixes for rendering global events.

src/cards/pathfinders/LuxuryEstate.ts
=> Fix Luxury Estate

src/boards/Board.ts, src/boards/BoardBuilder.ts, tests/boards/Board.spec.ts
See https://github.com/terraforming-mars/terraforming-mars/issues/4056
=> Patch for broken boards with no space type on Noctis City.

src/cards/ares/EcologicalZoneAres.ts, src/cards/base/EcologicalZone.ts, src/locales/br/base_cards.json, src/locales/cn/ares_cards.json, src/locales/es/ares_cards.json, src/locales/es/base_cards.json, src/locales/it/ares_cards.json, src/locales/pl/ares_cards.json, src/locales/ru/cards.json
If we had an easy way to do markdown or something, perhaps, but that's not happening.
=> Replace / with capitalization.

src/client/mixins/PaymentWidgetMixin.ts, tests/components/SelectHowToPayForProjectCard.spec.ts
=> Allow other floaters to be the reserve for Stratospheric Birds

src/client/components/App.ts, src/client/components/GameHome.vue, src/client/components/GameSetupDetail.vue, src/client/components/LoadGameForm.vue, src/client/components/Sidebar.vue, src/client/components/create/CreateGameForm.vue, src/client/components/pathfinders/PlanetaryTrack.vue, src/client/components/pathfinders/PlanetaryTrackReward.vue, src/client/components/pathfinders/PlanetaryTrackRewards.vue, src/client/components/pathfinders/PlanetaryTracks.vue, src/common/game/IGameData.ts, src/common/models/GameOptionsModel.ts, src/common/models/SimpleGameModel.ts, src/database/IDatabase.ts, src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts, src/models/GameModel.ts, src/models/ServerModel.ts, src/models/SimpleGameModel.ts
This is great. The amount of things underneath getting simple game models to common/. There's still a lot to go. Quite a lot of hard parts, actually. But still this is good.
=> Move SimpleGameModel to common

src/cards/colonies/MarketManipulation.ts, src/cards/community/Hygiea.ts, src/cards/community/Iapetus.ts, src/cards/community/Leavitt.ts, src/cards/community/Mercury.ts, src/cards/community/Pallas.ts, src/cards/community/Titania.ts, src/cards/community/Venus.ts, src/client/components/create/ColoniesFilter.vue, src/colonies/Callisto.ts, src/colonies/Ceres.ts, src/colonies/Colony.ts, src/colonies/Enceladus.ts, src/colonies/Europa.ts, src/colonies/Ganymede.ts, src/colonies/Io.ts, src/colonies/Luna.ts, src/colonies/Miranda.ts, src/colonies/Pluto.ts, src/colonies/Titan.ts, src/colonies/Triton.ts, src/common/colonies/ColonyDescription.ts, src/common/colonies/ColonyName.ts
This should remove colonies from the client.
I'm taking a different approach for project cards, but this is more than good enough for colonies.
=> Move colony descriptions to common/

src/client/components/create/ColoniesFilter.vue
Also, whoops, Callisto is listed twice.
A test will come later. I'd like to patch.
=> Recent Colonies change broke ColoniesFilter when selecting distinct colonies.

src/cards/promo/NewPartner.ts, src/cards/promo/PromoCardManifest.ts, src/common/cards/CardName.ts, tests/cards/promo/NewPartner.spec.ts
Comes from https://github.com/nwai90/terraforming-mars/commit/95b8557d3c227e38b17deba2bdfae5c2e55a7f28
=> Add promo card New Partner.

src/client/components/DebugUI.vue, src/client/components/create/ColoniesFilter.vue, src/colonies/ColonyDealer.ts, src/common/colonies/AllColonies.ts
=> Add Colonies to the debug view

src/client/components/Colony.vue, src/client/components/DebugUI.vue, src/client/components/create/ColoniesFilter.vue, src/colonies/ColonyDealer.ts, src/common/colonies/AllColonies.ts
This depends on #4166 not just because it further changes the code, but it also is how I can spot-check all the colonies to verify they haven't changed.
=> Modernize colony vue

src/deferredActions/StealResources.ts, tests/cards/pathfinders/BotanicalExperience.spec.ts
=> Botanical Experience is only valid for plants.

src/client/components/LogPanel.vue
=> Show resource count of corporation cards in the log panel.

src/client/components/SelectHowToPay.vue
=> Show seed icon when using standard project.

src/client/components/GlobalParameterValue.vue, src/client/components/MoonGlobalParameterValue.vue
=> Add hover title for Moon global parameters.

src/Game.ts, src/Random.ts, src/SerializedGame.ts, tests/Game.spec.ts, tests/Random.spec.ts, tests/database/Cloner.spec.ts
=> Preserve random numbers order when deserializing.

src/client/components/Bonus.vue
=> Show bonus temperature

src/Game.ts, src/Random.ts, src/colonies/ColonyDealer.ts, tests/colonies/ColonyDealer.spec.ts
=> Use RNG for ColonyDealer to make it testable.

src/colonies/ColonyDealer.ts, src/colonies/ColonyManifest.ts
This'll be useful when resolving ColonyDealer serialization.
=> Move the colonies files to their own class.

src/locales/pl/promo.json
Old translation stated, that asteroid resource will be placed on this card. I also translated card name itself as it is in paper version.
=> Fixed polish translation for Directed Impactors

src/cards/pathfinders/ValuableGases.ts, tests/cards/pathfinders/ValuableGases.spec.ts
=> Make Valuable Gases (PF) omit only global parameters, and set additional floaters correctly.

src/models/ServerModel.ts
Since this is dynamic, it's not as easy as creating an attribute on ICard, though i could extend cardDiscount to also have type that accepts a player.
=> Show discount for Crescent Research Association.

src/deferredActions/ChoosePoliticalAgenda.ts, src/turmoil/Policy.ts, src/turmoil/Turmoil.ts, src/turmoil/TurmoilHandler.ts, src/turmoil/parties/Kelvinists.ts, tests/cards/pathfinders/HighTempSuperconductors.spec.ts
=> When High Temp Superconductors is active, show correct costs in action

src/Player.ts, src/cards/base/ArtificialPhotosynthesis.ts, src/cards/base/MarsUniversity.ts, src/deferredActions/DeferredAction.ts, tests/cards/base/ArtificialPhotosynthesis.spec.ts
Fixes #4239. Also introducing shorthand code for deferring actions.
=> Improve Mars U and Artificial Photosynthesis priorities.

src/client/components/Colony.vue, src/client/components/colonies/BuildBenefit.vue, src/client/components/colonies/ColonyRow.vue, src/client/components/colonies/ColonyTradeRow.vue
Colonies are all hard-coded. This will help.
=> Use IColonyMetadata to render colonies.

src/client/components/card/CardCorporationLogo.vue
I could remove even more, but I think this is a good compromise.
=> Remove redundancy in rendering a corp logo.

src/Player.ts, src/cards/pathfinders/Odyssey.ts, src/cards/pathfinders/PathfindersCardManifest.ts, tests/cards/pathfinders/Odyssey.spec.ts
Boy things worked out well making this card simple.
=> Add Pathfinders corporation card Odyssey

src/client/components/colonies/ColonyTradeRow.vue
=> Fix Europa rendering.

src/client/components/DebugUI.vue
Remove that timer. It makes debugging impossible. Also replace "as" with
a type definition.
=> Clean up DebugUI.

webpack.config.js
Also add some comments for clarity.
=> Add progress output to webpack.

src/cards/ares/SurveyCard.ts, src/deferredActions/AddResourcesToCard.ts, tests/cards/ares/EcologicalSurvey.spec.ts
=> Ensure Survey cards' special logging logs correctly.

src/MilestoneAwardSelector.ts, src/client/components/GameSetupDetail.vue, src/locales/br/game_setting.json, src/locales/cn/gamesetting.json, src/locales/es/game_setting.json, src/locales/it/gamesetting.json
(Also some minor viz while I'm in there.)
=> Be less friendly to invalid MA game setting configurations.

src/cards/StandardProjectCard.ts
=> Only allow data when Aurorai is the player's corporation.

src/client/components/DebugUI.vue, src/client/components/PreferencesIcon.vue, src/client/components/Sidebar.vue, src/client/components/StartScreen.vue, src/client/components/create/CreateGameForm.vue, src/styles/preferences.less
=> Add preferences icon on several other pages

src/client/components/DebugUI.vue
=> Use player_home_colony_cont so colonies lay out horizontally.

package-lock.json, package.json, src/Game.ts, src/Player.ts, src/SerializedPlayer.ts, src/client/components/GameEnd.vue, src/client/components/gameend/VictoryPointChart.vue, src/common/models/PlayerModel.ts, src/locales/pl/cards.json, src/models/ServerModel.ts, src/styles/game_end.less, tests/Player.spec.ts
=> Add end-game VP graph.

package-lock.json, package.json, src/client/components/gameend/VictoryPointChart.vue
Update to most recent version of chart.js.
Add minor graph lines at the 5-point mark
Use standard font
=> Update VP chart:

src/client/cards/ClientCardManifest.ts, src/client/components/HTMLDialogElementCompatibility.ts, src/client/components/SelectInitialCards.vue, src/client/components/common/ConfirmDialog.vue, tests/client/components/SelectInitialCards.spec.ts
Testing got tricky because it was not easy to find whether ConfirmDialog was visible, and, the underlying element did not have a showDialog method. This works nicely.
=> SelectInitialCards dialog wasn't showing with Prelude.

src/routes/PlayerInput.ts, tests/routes/ApiCloneableGame.spec.ts, tests/routes/ApiGame.spec.ts, tests/routes/ApiGameLogs.spec.ts, tests/routes/ApiGames.spec.ts, tests/routes/ApiPlayers.spec.ts, tests/routes/ApiWaitingFor.spec.ts, tests/routes/PlayerInput.spec.ts, tests/routes/Route.spec.ts, tests/routes/RouteTestScaffolding.ts, tests/routes/ServeAsset.spec.ts
This can be applied to other route tests, just these first.
=> Centralize common route testing code.

src/client/colonies/ClientColonyManifest.ts, src/client/components/colonies/Colony.vue, src/common/models/ColonyModel.ts, src/tools/export_card_rendering.ts
This should be the last one of these. Now we just let them bake and look for errors.
=> Provide json option for rendering colonies.

src/client/cards/ClientCardManifest.ts, src/client/components/DebugUI.vue, src/client/components/LogPanel.vue, src/client/components/SelectHowToPayForProjectCard.vue, src/client/components/SelectInitialCards.vue, src/client/components/card/Card.vue, src/client/components/create/CardsFilter.vue, src/client/components/create/CorporationsFilter.vue, src/client/components/overview/PlayerTags.vue, src/common/cards/IClientCard.ts
Now that  ICard is separate from IClientCard, CardAndModule is no longer
necessary.
=> Remove CardAndModule.

tests/cards/base/OlympusConference.spec.ts
I thought it might be broken. Good test.
=> Add Olympus Conference test to verify it gets a resource when played.

src/client/components/help/HelpIconology.vue, src/styles/cards.less
This only addresses part of #3840 as I am bumping up against the CSS issues that came about once cards.less and cards_v2.less clashed.
=> Add some fan content to /help, fix .disease icon

src/cards/pathfinders/SpecializedSettlement.ts, tests/cards/pathfinders/SpecializedSettlement.spec.ts
=> Dont give Specialized Settlement bonus when overplacing.

src/turmoil/Turmoil.ts
=> Log where neutral delegates are placed.

src/cards/ares/CommercialDistrictAres.ts
=> Make Commercial District Ares match visually with non-ares

src/Game.ts
=> Log when player gains energy production by placing tile.

src/Game.ts, src/Player.ts
=> Save every time a player takes action. And don't save when deserializing.

src/Player.ts, src/PlayerInput.ts, src/inputs/SelectAmount.ts, src/inputs/SelectHowToPay.ts, src/inputs/SelectPlayer.ts, src/inputs/SelectSpace.ts
I wanted to do this about a year ago, but this kind of change didn't
work because for some reason it created a dependency cycle that went
from server to client, back to server. Huh?
Now that client and server are mostly separate, this is safe to start
doing. \o/
Getting the processing out of a single method means making more room for
robust validation, and it takes some of the work out of `Player.ts`
=> Start moving input processing to the PlayerInputs.

src/client/components/overview/PlayerInfo.vue, src/styles/players_overview.less
=> When clicking on player name or corp name, show player cards.

src/Player.ts, src/turmoil/globalEvents/SpinoffProducts.ts, src/turmoil/parties/Scientists.ts, tests/globalEvents/SpinoffProducts.spec.ts, tests/turmoil/parties/Scientists.spec.ts
=> Habitat Marte applies to conditions outside of card play.

src/Game.ts, src/Player.ts
This player had two trade fleets.
=> Don't return trade fleets at game end.

tests/cards/colonies/FloaterLeasing.spec.ts
=> Add test for Floater Leasing.

src/locales/de/cards.json, src/locales/fr/base_cards.json, src/locales/fr/ui.json
One German translation which was miscapitalized.
=> Fix and add some translations. Mostly French

src/cards/community/ProjectWorkshop.ts, tests/cards/community/ProjectWorkshop.spec.ts
The cards will work correctly, but this both adds a test, and also fixes
the logging, so it logs the TR loss.
Fixes #3752
=> Project Workshop / Ancient Shipyards compatibility

src/Player.ts
=> Restore prior saving behavior.

src/cards/pathfinders/SolarStorm.ts, tests/cards/pathfinders/SolarStorm.spec.ts
And add those tests that I, with hubris, that were not necessary.
=> Fix Solar Storm, which is not mandatory.

src/client/components/BugReportDialog.vue, src/client/components/PreferencesDialog.vue, src/styles/preferences.less
Surprising amount of rewrite. The <form> tag went away, the timeout went away. Needed some CSS. Also fixed a mis-typed i18-n tag.
=> Add "copy to clipboard" action in bug dialog.

src/client/components/overview/PlayerTags.vue, tests/client/components/overview/PlayerTags.spec.ts
=> Reverse order of how player tags are shown.

src/cards/base/standardProjects/AsteroidStandardProject.ts
=> Make Asteroid Standard Project compatible with Aurorai

src/client/components/App.ts, src/client/components/BugReportDialog.vue
This keeps me from having to wire up game state through the preferences.
Unfortunately it means exposing the interface in App.ts. I really tried
other things. Someone more adept at Typescript is welcome to show me a
thing or two.
=> Properly report a game's state through the spectator ID.

src/Player.ts, src/cards/pathfinders/Chimera.ts, src/milestones/Ecologist.ts, tests/cards/pathfinders/Chimera.spec.ts
=> Make Chimera compatible with Ecologist.

src/cards/pathfinders/AdhaiHighOrbitConstructions.ts, src/cards/pathfinders/EconomicHelp.ts, src/cards/pathfinders/LobbyHalls.ts, src/client/components/pathfinders/PlanetaryTrackRewards.vue, src/common/pathfinders/PlanetaryTrack.ts, src/common/pathfinders/PlanetaryTracks.ts, src/pathfinders/DeclareCloneTag.ts, src/pathfinders/PathfindersExpansion.ts, tests/cards/pathfinders/EconomicHelp.spec.ts
Also created a first-class type for track tags, and made TRACKS fully
readonly. Less code. Simpler code.
Fixes #4323
=> Economic Help now ignores any completed tracks.

src/client/components/TopBar.vue, src/client/components/overview/PlayerInfo.vue, src/client/components/overview/PlayerTags.vue
=> Make tooltips appear on the bottom when shown on the topbar.

src/Player.ts, src/cards/promo/InterplanetaryTrade.ts, src/milestones/Diversifier.ts, src/turmoil/globalEvents/Diversity.ts, tests/cards/pathfinders/Chimera.spec.ts
=> Another Chimera compatibility issue! Fixes Diviersifier.

src/client/colonies/ClientColonyManifest.ts, src/client/turmoil/ClientGlobalEventManifest.ts
Before:
```
asset main.js 2.9 MiB [emitted] [minimized] [big] (name: main) 4 related assets
orphan modules 363 KiB [orphan] 295 modules
runtime modules 1.13 KiB 5 modules
modules by path ./src/ 4.14 MiB 1187 modules
modules by path ./node_modules/ 1.01 MiB
modules by path ./node_modules/mnemonist/*.js 244 KiB 39 modules
modules by path ./node_modules/mnemonist/utils/*.js 25.9 KiB 7 modules
modules by path ./node_modules/css-loader/dist/runtime/*.js 3.79 KiB
./node_modules/css-loader/dist/runtime/cssWithMappingToString.js 2.22 KiB [built] [code generated]
./node_modules/css-loader/dist/runtime/api.js 1.57 KiB [built] [code generated]
modules by path ./node_modules/obliterator/*.js 5.18 KiB
./node_modules/obliterator/foreach.js 3.45 KiB [built] [code generated] …
```
=> Remove server-side colonies and events. webpack-ed code down 50%

src/Game.ts, src/venusNext/GrantVenusAltTrackBonusDeferred.ts, tests/venusNext/GrantVenusAltTrackBonusDeferred.spec.ts
=> The Alt Venus 30% wild bonus is too easy to ignore.

src/client/colonies/ClientColonyManifest.ts, src/client/components/create/CorporationsFilter.vue, src/client/turmoil/ClientGlobalEventManifest.ts, src/common/cards/GameModule.ts
It's used in one place, and reduces the (uncompressed) binary another 100K
=> Remove the mnemonist module from the client

src/boards/Board.ts, tests/boards/Board.spec.ts
Removing temporary patch fixing #4056
=> Remove Noctis City patch.

src/client/components/card/CardRequirementComponent.vue
=> Some cards require 2 production.

src/Player.ts, src/cards/base/standardProjects/SellPatentsStandardProject.ts, src/cards/prelude/ValleyTrust.ts, src/cards/promo/NewPartner.ts, src/cards/promo/SelfReplicatingRobots.ts, src/client/components/SelectCard.vue, src/client/components/card/Card.vue, src/deferredActions/DiscardCards.ts, src/deferredActions/DrawCards.ts, src/deferredActions/RemoveResourcesFromCard.ts, src/inputs/SelectCard.ts, src/inputs/SelectInitialCards.ts, src/models/ServerModel.ts, tests/cards/base/BusinessNetwork.spec.ts, tests/cards/base/InventorsGuild.spec.ts, tests/cards/moon/LunaProjectOffice.spec.ts, tests/colonies/Colony.spec.ts, tests/deferredActions/DrawCards.spec.ts, tests/inputs/SelectCards.spec.ts, tests/turmoil/Turmoil.spec.ts
=> Show adjusted cost and resource count for SRR cards.

src/ares/AresHandler.ts, src/cards/ares/SolarFarm.ts, src/cards/pathfinders/GeologicalExpedition.ts, src/common/boards/SpaceBonus.ts, tests/ares/AresTestHelper.ts, tests/cards/ares/EcologicalSurvey.spec.ts, tests/cards/ares/GeologicalSurvey.spec.ts, tests/cards/ares/SolarFarm.spec.ts, tests/cards/pathfinders/SpecializedSettlement.spec.ts
This makes sense. The bonus is units of energy.
=> Rename SpaceBonus.POWER to SpaceBonus.ENERGY

src/client/directives/i18n.ts
=> Reduce the number of false translation error reports.

src/cards/base/standardProjects/SellPatentsStandardProject.ts
=> Show card discount when selling patents.

src/deferredActions/CorrosiveRainDeferredAction.ts, tests/globalEvents/CorrosiveRain.spec.ts
=> Ensure Corrosive Rain card only applies to cards with 2 resources.

src/boards/Board.ts, tests/boards/Board.spec.ts
In general, if we changed to using maps for a bunch of calculations,
the optimizations will slowly add up.
Also cleaning up the tests a little.
=> Use a map for faster lookups on the board.

src/Game.ts, src/GameSetup.ts, src/ares/AresHazards.ts, src/ares/AresSetup.ts, tests/ares/AresHandler.spec.ts
=> 2,3, and 5-player Ares games have one hazard placed by summing two cards.

src/client/components/create/CreateGameForm.vue
=> Issue a warning when playing solo without the corp era.

src/cards/pathfinders/GeologicalExpedition.ts, src/client/components/DebugUI.vue, src/colonies/ColonyManifest.ts, src/common/colonies/IColonyMetadata.ts, src/common/turmoil/IClientGlobalEvent.ts, src/tools/export_card_rendering.ts, src/turmoil/globalEvents/GlobalEventDealer.ts
Invert for all 3 types.
Remove watch and active URL filtering. UI is much faster.
Tags buttons now only have icons.
Filtering by module applies to colonies and global events.
=> Overhaul debug ui

src/Game.ts
=> Log the number of cards bought during initial draft.

src/CardLoader.ts, src/cards/prelude/ValleyTrust.ts, tests/cards/prelude/ValleyTrust.spec.ts
=> Make Valley Trust corp work without the Prelude ruleset.

src/Game.ts, src/Player.ts, src/cards/base/AsteroidMiningConsortium.ts, src/cards/base/BiomassCombustors.ts, src/cards/base/Birds.ts, src/cards/base/CloudSeeding.ts, src/cards/base/EnergyTapping.ts, src/cards/base/Fish.ts, src/cards/base/GreatEscarpmentConsortium.ts, src/cards/base/Hackers.ts, src/cards/base/HeatTrappers.ts, src/cards/base/Herbivores.ts, src/cards/base/PowerSupplyConsortium.ts, src/cards/base/RoboticWorkforce.ts, src/cards/base/SmallAnimals.ts, src/cards/colonies/SubZeroSaltFish.ts, src/deferredActions/DecreaseAnyProduction.ts, tests/cards/base/AsteroidMiningConsortium.spec.ts, tests/cards/base/BiomassCombustors.spec.ts, tests/cards/base/EnergyTapping.spec.ts, tests/cards/base/GreatEscarpmentConsortium.spec.ts, tests/cards/base/PowerSupplyConsortium.spec.ts, tests/cards/pathfinders/PrivateSecurity.spec.ts
=> When only player that can lose production is self, do proper SelectPlayer anyway.

src/cards/pathfinders/DysonScreens.ts, tests/cards/pathfinders/DysonScreens.spec.ts
The card looks awful, though. :sob:
=> Can't believe I excluded Dyson Screen's production bonuses.

src/locales/de/game_end.json, src/locales/de/preferences.json
Fixed German typos in preferences and game_end and added translation for  "Report a bug".
=> Fixed German typos

src/locales/cn/base_corporations.json, src/locales/cn/colonies.json, src/locales/cn/log_messages.json, src/locales/cn/preludes.json, src/locales/cn/promo.json, src/locales/cn/ui.json, src/locales/cn/venus_next.json
add some Chinese translation for corportation
here's the change between before and after
=> add some CN translation

src/common/models/CardModel.ts, src/models/ServerModel.ts
Show discount for Mars Direct.
Fixes #4456
=> Card model

src/cards/pathfinders/DesignedOrganisms.ts, tests/globalEvents/SpinoffProducts.spec.ts, tests/turmoil/parties/Scientists.spec.ts
=> Replace wrong tags for Designed Organisms

src/cards/pathfinders/PublicSponsoredGrant.ts, tests/cards/pathfinders/PublicSponsoredGrant.spec.ts
=> Make Public Sponsored Grant compatible with Mons Insurance

src/Game.ts, src/cards/community/ProjectWorkshop.ts, tests/cards/community/ProjectWorkshop.spec.ts
=> Make Project Workshop compatible with Reds taxes.

tests/CardLoader.spec.ts, tests/Dealer.spec.ts, tests/EscapeVelocity.spec.ts, tests/Game.spec.ts, tests/MilestoneAwardSelector.spec.ts, tests/Player.spec.ts, tests/TestGame.ts, tests/TestingUtils.ts, tests/ares/AresHandler.spec.ts, tests/ares/AresTestHelper.ts, tests/ares/OtherAresTests.spec.ts, tests/awards/Landlord.spec.ts, tests/boards/ArabiaTerraBoard.spec.ts, tests/boards/VastitasBorealisBoard.spec.ts, tests/cards/CardMetadata.spec.ts, tests/cards/CardRequirements.spec.ts, tests/cards/CardSerialization.spec.ts, tests/cards/ares/ButterflyEffect.spec.ts, tests/cards/ares/DesperateMeasures.spec.ts, tests/cards/ares/EcologicalSurvey.spec.ts, tests/cards/ares/GeologicalSurvey.spec.ts, tests/cards/ares/LavaFlowsAres.spec.ts, tests/cards/ares/MiningAreaAres.spec.ts, tests/cards/ares/MiningRightsAres.spec.ts, tests/cards/ares/OceanCity.spec.ts, tests/cards/ares/OceanFarm.spec.ts, tests/cards/ares/OceanSanctuary.spec.ts
I was wrong about it being a static class, meh.
=> Step 1 moving TestingUtils from class to functions

src/client/components/create/CorporationsFilter.vue
How come this isn't coming up in compilation?
=> Fix broken tag.

src/database/IDatabase.ts, src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts, src/server.ts, tests/database/SQLite.spec.ts, tests/integration/PostgreSQL.spec.ts, tests/utils/setup.ts
Ideally this should work with an admin web page, but one thing at a time.
Example output:
```
Connecting to Postgres database.
node_modules/console-stamp/index.js:38
{
"type": "POSTGRESQL",
"pool-total-count": 1,
"pool-idle-count": 1,
"pool-waiting-count": 3,
"size-bytes-games": "32 kB",
"size-bytes-game-results": "16 kB",
"size-bytes-database": "8065 kB"
}
node_modules/console-stamp/index.js:38
Starting ea600e87f, built at Wed, 25 May 2022 23:43:37 -0400
node_modules/console-stamp/index.js:38
Starting server on port 8080
```
=> Add stats() method to IDatabase. Show at startup.

src/database/GameLoader.ts, src/database/IGameLoader.ts, src/routes/ApiPlayer.ts, src/routes/ApiSpectator.ts, src/routes/ApiWaitingFor.ts, src/routes/GameLogs.ts, src/routes/PlayerInput.ts, tests/database/GameLoader.spec.ts, tests/routes/FakeGameLoader.ts
There's no reason for two methods.
=> Consolidate GameLoader.getByParticipantId

src/client/components/DebugUI.vue, tests/utils/setup.ts
=> Debug UI fixes

src/Game.ts, src/colonies/ColonyDealer.ts, tests/Game.spec.ts
=> Fix how discarded colonies are restored from the database.

src/cards/moon/LunarObservationPost.ts
=> Fix Lunar Observation Post iconography.

src/database/LocalFilesystem.ts, src/routes/ApiGameHistory.ts, src/server.ts
Example output demonstrating a broken undo:
```
["00000","00001","00002","00003","00004","00005","00006","00007","00008","00009","00010","00011","00013",
"00014","00016","00017","00019","00020","00022","00023","00025","00026","00028","00029","00031","00032",
"00034","00035","00037","00039","00040","00041","00043","00044","00045","00047","00048","00050","00051",
"00053","00054","00056","00057","00059","00060","00062","00064","00066","00067","00069","00070","00071",
"00073","00074","00076","00077","00079","00080","00082","00083","00085","00087","00088","00090","00091",
"00093","00094","00096","00098","00100","00102","00103","00104","00106","00107","00109","00110","00112",
"00113","00115","00116","00118","00119","00121","00122","00124","00125","00127","00129","00130","00132", …
```
=> Add API endpoint for game history.

package-lock.json, package.json, src/database/Cloner.ts, src/database/IDatabase.ts, src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts, src/routes/Game.ts, tests/database/Cloner.spec.ts, tests/database/SQLite.spec.ts, tests/integration/PostgreSQL.spec.ts
Added `chai-as-promised` which introduces assertions for promises, yay.
=> Make loadClonableGames async

src/database/PostgreSQL.ts
I can't quite figure out why undo is broken so I'm adding logging for
now.
=> Additional logging for the postgres undo cases.

src/database/PostgreSQL.ts, tests/integration/PostgreSQL.spec.ts
This includes measuring when an insert results in an udpate (using xmax = 0)
and if or when it occurs during an undo operation.
All of this is to measure whether both upserts _actually occur_ and also
whether it's exclusively the purvue of undo operations.
=> Measure PostgreSQL save operations.

src/LogHelper.ts, src/cards/colonies/MarketManipulation.ts, src/locales/de/log_messages.json, src/locales/ko/log_messages.json
Use existing log messages which should simplify translation a little
=> Fix logging for Market Manipulation 

src/database/IDatabase.ts, src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts, src/tools/export_game.ts
This doesn't have a test, yet. I'm going to centralize the tests. Plus, this only impacts exportGame.
=> Make getGameId async

src/database/GameLoader.ts, src/database/IDatabase.ts, src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts
=> Don't deserialize in IDatabase.

src/client/components/App.ts, src/client/components/StartScreen.vue, src/client/components/create/CreateGameForm.vue, src/locales/br/start_screen.json, src/locales/cn/start_screen.json, src/locales/de/start_screen.json, src/locales/es/start_screen.json, src/locales/fr/start_screen.json, src/locales/it/start_screen.json, src/locales/ko/start_screen.json, src/locales/pl/Main Menu.json, src/locales/ru/start_screen.json, src/server.ts, src/styles/start_screen.less
=> Drop dedicated solo page, replace with "How to play" link.

src/Game.ts, src/database/GameLoader.ts, src/database/IDatabase.ts, src/database/IGameLoader.ts, src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts, src/routes/ApiGameLogs.ts, src/routes/ApiPlayer.ts, src/routes/ApiSpectator.ts, src/routes/ApiWaitingFor.ts, src/routes/GameLogs.ts, src/routes/PlayerInput.ts, tests/database/GameLoader.spec.ts, tests/database/SQLite.spec.ts, tests/integration/PostgreSQL.spec.ts, tests/routes/ApiGameLogs.spec.ts, tests/routes/ApiPlayer.spec.ts, tests/routes/ApiSpectator.spec.ts, tests/routes/ApiWaitingFor.spec.ts, tests/routes/FakeGameLoader.ts, tests/routes/RouteTestScaffolding.ts, tests/utils/setup.ts
Remove the sync GameLoader.getByParticipantId.
=> Remove the sync GameLoader.getByParticipantId.

src/Game.ts, src/GameSetup.ts, src/SpaceName.ts, src/awards/Awards.ts, src/boards/AmazonisBoard.ts, src/boards/Board.ts, src/boards/TerraCimmeriaBoard.ts, src/cards/community/CuriosityII.ts, src/client/components/BoardSpace.vue, src/client/components/Bonus.vue, src/client/components/GameSetupDetail.vue, src/client/components/create/CreateGameForm.vue, src/common/boards/BoardName.ts, src/common/boards/SpaceBonus.ts, src/milestones/Milestones.ts, src/routes/Game.ts, src/styles/board.less, src/styles/create_game_form.less, src/styles/variables.less, tests/cards/pathfinders/SpecializedSettlement.spec.ts, tests/client/components/BoardSpace.spec.ts, tests/routes/Game.spec.ts
Milestones and awards not included.
=> Add two fan boards from Community server.

src/colonies/Colony.ts, src/database/LocalFilesystem.ts, src/deferredActions/AddResourcesToCard.ts, src/deferredActions/DeferredAction.ts, src/deferredActions/DeferredActionsQueue.ts, src/tools/export_game.ts, src/turmoil/Turmoil.ts
Only a few more to go after this PR and then I will enable the linting rule for `/src/` directory.
=> a few more removals of non-null assertion

src/client/components/PlayerHome.vue
Moving the Pathfinders map to be at the top.
=> pathfinders map location

src/Game.ts, src/database/GameLoader.ts, src/database/IDatabase.ts, src/database/IGameLoader.ts, src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts, src/routes/ApiGame.ts, src/routes/ApiGameLogs.ts, src/routes/ApiPlayer.ts, src/routes/ApiSpectator.ts, src/routes/ApiWaitingFor.ts, src/routes/GameLogs.ts, src/routes/LoadGame.ts, src/routes/PlayerInput.ts, tests/database/GameLoader.spec.ts, tests/database/SQLite.spec.ts, tests/integration/PostgreSQL.spec.ts, tests/routes/ApiGame.spec.ts, tests/routes/ApiGameLogs.spec.ts, tests/routes/ApiPlayer.spec.ts, tests/routes/ApiSpectator.spec.ts, tests/routes/ApiWaitingFor.spec.ts, tests/routes/FakeGameLoader.ts, tests/routes/RouteTestScaffolding.ts, tests/utils/setup.ts
=> Make GameLoader.getByGameId async.

.eslintrc.js, src/Game.ts, src/Player.ts, src/awards/amazonisPlanitia/Zoologist.ts, src/cards/CardSerialization.ts, src/cards/ICard.ts, src/cards/ares/DesperateMeasures.ts, src/cards/community/ExecutiveOrder.ts, src/cards/promo/PharmacyUnion.ts, src/cards/promo/ProjectInspection.ts, src/cards/turmoil/BannedDelegate.ts, src/cards/venusNext/Viron.ts, src/client/components/create/CorporationsFilter.vue, tests/.eslintrc.js
Enables the @typescript-eslint/no-non-null-assertion rule.
=> enable @typescript-eslint/no-non-null-assertion

src/database/GameLoader.ts, src/routes/ApiStats.ts, src/routes/Route.ts, src/server.ts, src/server/metrics.ts, src/server/requestProcessor.ts
Split out some of the startup processing to make startup easier to read.
=> Add more runtime metrics.

src/database/GameLoader.ts, src/database/IGameLoader.ts, src/routes/ApiGames.ts, src/routes/Handler.ts, tests/database/GameLoader.spec.ts, tests/routes/FakeGameLoader.ts
Each refactor is its own commit, which will help to show that these changes are safe.
=> A series of small refactorings for GameLoader that reduce complexity and clarify behavior

src/database/GameLoader.ts, src/database/IGameLoader.ts, src/routes/ApiGame.ts, tests/database/GameLoader.spec.ts, tests/routes/FakeGameLoader.ts
99.999% of calls this parameter will be with false.
=> Make bypassCache an optional gameLoader parameter.

src/database/PostgreSQL.ts, src/database/SQLite.ts
Not sure it's OK to do the same with SQLite, but add comments to
resolve any conflicts.
=> Reduce loadClonableGame to getGameVersion for Postgres.

src/database/GameLoader.ts, src/database/IGameLoader.ts, src/routes/ApiGame.ts, src/routes/ApiPlayer.ts, src/routes/ApiSpectator.ts, src/routes/ApiWaitingFor.ts, src/routes/GameLogs.ts, src/routes/LoadGame.ts, src/routes/PlayerInput.ts, tests/database/GameLoader.spec.ts, tests/routes/ApiGame.spec.ts, tests/routes/FakeGameLoader.ts
Reduces complexity and makes things a little simpler to grok.
=> Consoldate both calls that get games into one.

tests/TestGame.ts, tests/TestPlayer.ts, tests/TestPlayers.ts
Will help when dealing with GameLoader and GameIds.
=> Add the ability to tag Test player ids and game ids with a suffix.

src/database/PostgreSQL.ts, src/tools/create_game_ids_table.ts
1. Add the table size to stats.
2. Don't report the double-write errors.
=> Features for participants:

tests/database/GameLoader.spec.ts, tests/testing/InMemoryDatabase.ts
No plans for reuse at this time, but it lets GameLoader.spec.ts focus on itself.
=> Move InMemoryDatabase to its own file.

tests/integration/PostgreSQL.spec.ts
Unit test showing undo works in solo mode.
=> Undo tests.

src/Game.ts, src/Player.ts, src/cards/StandardProjectCard.ts, src/cards/corporation/CrediCor.ts, src/cards/corporation/InterplanetaryCinematics.ts, src/cards/pathfinders/MartianInsuranceGroup.ts, src/cards/pathfinders/Ringcom.ts, src/cards/pathfinders/SurveyMission.ts, src/cards/promo/ProjectInspection.ts, src/turmoil/Turmoil.ts
Especially while moving to a Merger-compatible environment.
=> Turns out using isCorporation is going to help out.

src/Game.ts, src/SerializedGame.ts
@pierrehilbert this seems like a good change for readability.
=> Clarify corporationDraftPlayerToNext

.eslintrc.js, src/.eslintrc.js, src/ares/AresHandler.ts, src/cards/venusNext/Atmoscoop.ts, src/client/components/SelectInitialCards.vue, src/client/components/WaitingFor.vue, src/database/PostgreSQL.ts, src/deferredActions/RemoveResourcesFromCard.ts, src/utils/durations.ts, tests/.eslintrc.js, tests/TestingUtils.ts
Enabled `eslint:recommended` and then fixed or disabled certain
lint errors.
=> Updated linting.

src/Player.ts, src/cards/ICard.ts, src/cards/community/Playwrights.ts, src/cards/pathfinders/Odyssey.ts, src/colonies/Colony.ts, src/common/inputs/HowToPay.ts, src/deferredActions/PlayProjectCard.ts, src/locales/de/pathfinder_cards.json, src/locales/de/pathfinder_corporations.json, src/locales/de/pathfinder_preludes.json, tests/cards/pathfinders/Odyssey.spec.ts, tests/cards/pathfinders/ValuableGases.spec.ts, tests/cards/venusNext/StratosphericBirds.spec.ts
This required touching quite a lot of the code for the
select-a-card-to-play,pay-for-it,play-it action sequence.
Also this looks nicer:
=> Rewrite Odyssey to be include paying for the card.

src/Game.ts, src/SerializedGame.ts, src/cards/promo/MonsInsurance.ts, tests/Game.spec.ts
It's purely computable at load time.
=> Mons Insurance doesn't need to be serialized.

src/client/components/LogPanel.vue
=> Centralize card rendering in the log.

src/awards/SpaceBaron.ts
=> Simplify Space Baron description.

src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts, tests/database/databaseSuite.ts
This only impacts `export_game` so I just found this. More tests!
=> Fix getGameId and write tests.

src/client/components/GameSetupDetail.vue
=> Add "Corporation" as a draft option for the game setup details page.

src/Player.ts, src/common/inputs/HowToPay.ts, src/deferredActions/SelectHowToPayDeferred.ts, src/inputs/SelectHowToPay.ts, src/inputs/SelectHowToPayForProjectCard.ts, tests/cards/pathfinders/Odyssey.spec.ts, tests/cards/promo/DirectedImpactors.spec.ts, tests/cards/venusNext/StratosphericBirds.spec.ts
@Strikeskids gets full credit for #4340 . This just became a pain to merge after all the changes.
=> Fix HowToPay bugs in processInput

src/cards/pathfinders/MarsDirect.ts, src/locales/de/pathfinder_corporations.json, tests/cards/pathfinders/MarsDirect.spec.ts
The difference is not that meaningful, and this is more than close
enough.
=> Removing the Mars Direct buff.

src/database/IDatabase.ts, src/database/LocalFilesystem.ts, src/database/PostgreSQL.ts, src/database/SQLite.ts, tests/database/databaseSuite.ts, tests/testing/InMemoryDatabase.ts, tests/utils/setup.ts
Add tests. Add Localfileysstem implementation
=> Make deleteGameNbrSaves a promise.

src/database/SQLite.ts
=> Simplify sqlite code, now that it has tests.

src/client/components/BoardSpace.vue, src/client/components/board/BoardSpaceTile.vue, src/common/boards/SpaceType.ts
I'll use this for Crashlanding.
Verified this manually.
=> Split out the tile component from board space.

src/client/components/SortableCards.vue, src/styles/cards.less, src/styles/preferences.less, tests/client/components/SortableCards.spec.ts
Updates the card sorting to _insert_ the card versus swapping the position. Also updated the card magnification to avoid magnifying cards while dragging and dropping.
This closes #4731
=> insert cards while sorting versus swapping

src/client/components/Board.vue, src/client/components/BoardSpace.vue, src/client/components/PlayerHome.vue, src/client/components/PreferencesDialog.vue, src/client/components/SelectInitialCards.vue, src/client/components/SpectatorHome.vue, src/client/components/board/BoardSpaceTile.vue, src/client/components/board/TileView.ts, src/client/components/moon/MoonBoard.vue, src/client/components/moon/MoonSpace.vue, src/client/utils/PreferencesManager.ts, src/styles/board.css, src/styles/board.less, tests/client/components/Board.spec.ts, tests/client/components/BoardSpace.spec.ts, tests/client/components/SelectInitialCards.spec.ts, tests/client/components/moon/MoonBoard.spec.ts, tests/client/components/moon/MoonSpace.spec.ts
This mode is hidden behind a 'debug ui' preference.
=> Add a new debug view mode for showing and hiding tiles

src/Player.ts, src/cards/prelude/RobinsonIndustries.ts, tests/cards/prelude/RobinsonIndustries.spec.ts
SelectHowToPayDeferred can be much simpler to use. So introducing that.
=> Merger Compatibility: Helion + Robinson Industries.

src/client/components/BugReportDialog.vue, src/client/components/PreferencesDialog.vue
1. Get close button to work
2. Get "redact" checkbox so users can remove their hostnames, though I
don't know why that would actually help. Huh.
Fixes #4770
=> Bug Report Dialog fixes

src/Player.ts, src/deferredActions/SelectHowToPayDeferred.ts, tests/cards/pathfinders/Aurorai.spec.ts
=> Aurorai payment was pretty broken.

src/cards/pathfinders/Ringcom.ts, tests/cards/pathfinders/Ringcom.spec.ts
=> Give player titanium bonus as Ringcom is played.

src/Player.ts, src/deferredActions/SelectHowToPayDeferred.ts, tests/cards/pathfinders/Aurorai.spec.ts
=> Cannot underpay standard projects

src/client/components/SelectHowToPay.vue, src/client/components/SelectHowToPayForProjectCard.vue, src/client/components/SelectProductionToLose.vue, src/common/inputs/Payment.ts, src/server/Player.ts, src/server/cards/community/ValuableGases.ts, src/server/cards/moon/MarketCard.ts, src/server/cards/pathfinders/ValuableGases.ts, src/server/deferredActions/SelectHowToPayDeferred.ts, src/server/inputs/SelectHowToPay.ts, src/server/inputs/SelectHowToPayForProjectCard.ts, tests/cards/base/WaterImportFromEuropa.spec.ts, tests/cards/community/ProjectWorkshop.spec.ts, tests/cards/corporation/UnitedNationsMarsInitiative.spec.ts, tests/cards/pathfinders/Aurorai.spec.ts, tests/cards/pathfinders/Odyssey.spec.ts, tests/cards/prelude/RobinsonIndustries.spec.ts, tests/cards/promo/DirectedImpactors.spec.ts, tests/cards/promo/Factorum.spec.ts, tests/cards/venusNext/StratosphericBirds.spec.ts, tests/client/components/SelectHowToPayForProjectCard.spec.ts
Things read better.
SelectHowToPay will become SelectPayment and
SelectHowToPayForProjectCard will be something similar.
=> Start renaming HowToPay to Payment.

src/server/Player.ts, src/server/cards/community/ValuableGases.ts, src/server/cards/pathfinders/Odyssey.ts, src/server/cards/pathfinders/ValuableGases.ts, src/server/deferredActions/PlayProjectCard.ts, src/server/inputs/SelectProjectCardToPlay.ts, tests/cards/prelude/EccentricSponsor.spec.ts, tests/cards/prelude/EcologyExperts.spec.ts, tests/cards/venusNext/StratosphericBirds.spec.ts
Also make SelectProjectCardToPlay more friendly.
=> Remove getPlayProjectCardInput.

src/server/database/Cache.ts
=> Fix typo: evited -> evicted

src/server/cards/colonies/MinorityRefuge.ts
Copy correct logic from PioneerSettlement
=> MinorityRefuge is unplayable.

src/server/cards/ICard.ts, src/server/cards/community/Playwrights.ts, src/server/cards/pathfinders/Odyssey.ts, src/server/cards/promo/ProjectInspection.ts, tests/cards/promo/ProjectInspection.spec.ts
=> Make Odyssey compatible with Project Inspection.

src/client/components/SelectCard.vue, src/client/components/SelectInitialCards.vue, src/server/inputs/SelectInitialCards.ts, tests/client/components/SelectInitialCards.spec.ts
This allows a player to make more choices, and tinker with the cards,
viz bug #1400.
Fixes #1400
=> Rewrite how intitial cards are selected.

src/client/components/SelectInitialCards.vue, src/server/inputs/SelectInitialCards.ts
Put the experimental behavior on SelectInitialCards.vue
=> Rollback the change to SelectInitialCards.ts.

src/server/Player.ts
=> Use tableau order for selecting how to add resources to cards.

src/server/Game.ts, src/server/Player.ts
=> Migrated corporation cards aren't getting their starting production.

src/client/components/LogPanel.vue
There's room for improvement: it doesn't use colony data from the game itself.
=> Show the colonies in the log panel.

src/common/Timer.ts, tests/EscapeVelocity.spec.ts, tests/common/Timer.spec.ts
=> Make Timer.lastStoppedAt an instance variable rather than static

src/server/Game.ts
=> Grant animal bonus on Amazonis P. map.

src/server/cards/turmoil/VoteOfNoConfidence.ts, src/server/turmoil/Turmoil.ts, tests/cards/moon/TempestConsultancy.spec.ts, tests/cards/turmoil/VoteOfNoConfidence.spec.ts
=> Make Tempest Consultancy (Moon) compatible with Vote of No Confidence.

src/common/Timer.ts, tests/EscapeVelocity.spec.ts, tests/common/Timer.spec.ts
Reverts terraforming-mars/terraforming-mars#4831
=> Revert "Make Timer.lastStoppedAt an instance variable rather than static"

src/server/database/PostgreSQL.ts, src/server/database/SQLite.ts, tests/database/databaseSuite.ts
purgeUnfinishedGames wasn't finished for SQLite, so this finishes it.
=> Fix sqlite3 async purgeUnfinishedGames.

src/client/components/PlayerHome.vue, src/client/components/SelectSpace.vue, src/client/components/waitingFor/GoToMap.vue, src/common/boards/spaces.ts, src/common/models/PlayerInputModel.ts, src/styles/waiting_for.less
=> Present user with ability to go to the map when selecting a space.

src/server/cards/base/CEOsFavoriteProject.ts, tests/cards/base/CEOsFavoriteProject.spec.ts
https://boardgamegeek.com/thread/1872479/ceos-favorite-project-and-self-replicating-robots
=> CEO's Fav. Proj. may not be used on robot cards.

src/server/Game.ts, src/server/LogHelper.ts, src/server/cards/pathfinders/Ambient.ts, src/server/cards/venusNext/ExtractorBalloons.ts, src/server/cards/venusNext/ForcedPrecipitation.ts, src/server/cards/venusNext/JetStreamMicroscrappers.ts
Meanwhile, for other cards that increase Venus, make sure it logs the amount actually raised.
=> Log Venus increase from Ambient corp.

src/client/components/DebugUI.vue, src/client/components/card/CardRenderItemComponent.vue, src/common/cards/render/CardRenderItemType.ts, src/server/cards/pathfinders/PrivateSecurity.ts, src/server/cards/render/CardRenderer.ts, src/styles/cards_v2.less
Other card refactoring, no visual changes.
Fixes #3847
=> Fix Private Security card iconography.

src/client/components/card/CardRenderItemComponent.vue
=> Minor: Vitor's iconography for award should read "award".

src/client/components/SelectPayment.vue, src/client/components/SelectProjectCardToPlay.vue, src/client/mixins/PaymentWidgetMixin.ts, src/common/inputs/Payment.ts, src/server/Player.ts, src/server/cards/colonies/StormCraftIncorporated.ts, src/server/cards/moon/LunaFirstIncorporated.ts, src/server/cards/moon/MarketCard.ts, src/server/cards/promo/EnergyMarket.ts, src/server/deferredActions/DrawCards.ts, src/server/deferredActions/SelectPaymentDeferred.ts, tests/cards/corporation/Helion.spec.ts, tests/cards/moon/SteelMarketMonopolists.spec.ts, tests/cards/moon/TitaniumMarketMonopolists.spec.ts, tests/client/components/SelectPayment.spec.ts, tests/client/components/SelectProjectCardToPlay.spec.ts
Right now I'm asking for feedback. Three things remain:
~~1. Unit tests.~~
~~2. More manual testing~~
3. Making all of this work with Dirigibles. (There is no end. ;)) (This can be resolved on its own.)
Part of #4763
=> Make Helion compatible with Stormcraft Incorporated for Merger

src/server/Game.ts, src/server/Player.ts, tests/Game.spec.ts
=> Don't place greeneries if solo victory conditions are unmet.

src/server/cards/turmoil/CulturalMetropolis.ts, tests/cards/turmoil/CulturalMetropolis.spec.ts
=> Cultural Metropolis can't be played without an available city space.

src/server/cards/promo/Merger.ts, tests/cards/promo/Merger.spec.ts
Unless _no_ cards are affordable. Odds of that happening?
=> Merger now shows which corporations were not affordable.

src/server/cards/promo/EnergyMarket.ts, tests/cards/promo/EnergyMarket.spec.ts
Introduced when making Helion compatible with Stormcraft for Merger.
Fixes #4930
=> Energy Market giving double credits.

src/locales/br/base_cards.json, src/locales/cn/community_cards.json, src/locales/de/base_cards.json, src/locales/es/base_cards.json, src/locales/it/community_cards.json, src/locales/ko/community_cards.json, src/locales/ru/preludes.json, src/server/cards/community/PoliticalUprising.ts
"Place 4 delegates" does not really describe how this card works, since each delegate may go into its own party. The existing cards tend to say "in 1 party" and so it's possible to assume the absence of "in 1 party" is enough, but I recommend this is explicit.
=> Clarify community card Political Uprising.

src/client/components/SelectAmount.vue, src/server/cards/promo/HiTechLab.ts
1. Select Amount buttons have a little space between them
2. Change Hi-Tech lab text for selecting the action to OK.
=> Minor viz changes:

src/client/components/card/Card.vue, src/client/mixins/PaymentWidgetMixin.ts, src/common/models/CardModel.ts, src/server/models/ServerModel.ts, tests/client/components/SelectPayment.spec.ts, tests/client/components/SelectProjectCardToPlay.spec.ts
resourceType is no longer necessary.
=> Replace resourceType from with isSelfReplicatingRobotsCard.

src/server/behavior/Behavior.ts, src/server/behavior/Behaviors.ts, src/server/cards/corporation/EcoLine.ts, src/server/cards/pathfinders/SoilDetoxification.ts
It's also used by Soil Detoxification.
=> Add behavior for the Ecoline greenery discount.

src/server/cards/base/ArtificialLake.ts, src/server/cards/base/CommercialDistrict.ts, src/server/cards/base/IndustrialCenter.ts, src/server/cards/base/LandClaim.ts, src/server/cards/base/Mangrove.ts, src/server/cards/base/NaturalPreserve.ts, src/server/cards/base/NuclearZone.ts, src/server/cards/base/ResearchOutpost.ts, src/server/cards/base/RestrictedArea.ts, src/server/cards/base/UrbanizedArea.ts, src/server/cards/pathfinders/EarlyExpedition.ts, src/server/cards/promo/ArcadianCommunities.ts, src/server/cards/promo/DeimosDownPromo.ts, src/server/cards/promo/GreatDamPromo.ts, src/server/cards/promo/MagneticFieldGeneratorsPromo.ts
The space isn't 'found', as it wasn't searched for, it's chosen, or selected. Simple enough to just shorten it to 'space'.
=> Rename 'foundSpace' to 'space'.

src/server/cards/prelude/NitrogenShipment.ts, src/server/cards/prelude/PreludeCardManifest.ts, tests/cards/prelude/NitrogenShipment.spec.ts
It's not a card name rename, so it's a safe change.
=> Rename NitrogenDelivery -> NitrogenShipment

src/server/Game.ts, tests/drafting.spec.ts
Based on feedback in #4928 from @pauliimmonen
=> Don't deal corporation cards to players if they're going to draft.

src/client/components/create/CreateGameForm.vue, src/client/components/create/PreludesFilter.vue
=> Preludes are not loading via JSON.

src/server/cards/pathfinders/Odyssey.ts, tests/cards/pathfinders/Odyssey.spec.ts
=> Make cards discarded with Odyssey retain their next-card behaviors.

src/server/cards/base/MarsUniversity.ts, src/server/cards/venusNext/SponsoredAcademies.ts, src/server/deferredActions/DeferredAction.ts, tests/cards/venusNext/SponsoredAcademies.spec.ts
=> Choose reasonable order when Sponsored Academies and Mars U are in effect.

src/server/cards/moon/TempestConsultancy.ts, tests/cards/moon/TempestConsultancy.spec.ts
=> Don't take Tempest Consultancy action with no delegates.

src/client/components/card/CardCorporationLogo.vue, src/common/cards/CardName.ts, src/server/Player.ts, src/server/cards/ICard.ts, src/server/cards/community/CommunityCardManifest.ts, src/server/cards/community/UnitedNationsMissionOne.ts, src/server/cards/pathfinders/Aurorai.ts, src/styles/cards_v2.less, tests/cards/community/UnitedNationsMissionOne.spec.ts
This is a near-direct copy of the Community server's version of this corp.
=> Add Community corporation United Nations Mission One

src/common/cards/CardName.ts, src/server/cards/Deck.ts, src/server/cards/community/CommunityCardManifest.ts, src/server/cards/community/JunkVentures.ts, tests/cards/community/JunkVentures.spec.ts
=> Add Community Corp Junk Ventures.

src/server/deferredActions/DrawCards.ts, tests/cards/colonies/SolarProbe.spec.ts
Also add sanity test for Solar Probe.
=> Solar Probe card draw was showing what you drew to other players.

package-lock.json, package.json
It contains the fix to a bug I discovered while trying to get rid of our own version of Multiset.
=> Upgrade to mnemonist 0.39.3.

src/server/cards/base/Decomposers.ts
=> Log details for Decomposers

src/server/cards/venusNext/SulphurEatingBacteria.ts
=> Remove superfluous log.

src/client/components/colonies/Colony.vue, src/server/colonies/ColoniesHandler.ts, tests/cards/community/Venus.spec.ts, tests/colonies/Miranda.spec.ts
First change rendering so it shows that it requires venus cards with resources. Second, change the behavior to match. Finally, add a test!
=> Adjust community Venus colony.

src/server/cards/moon/LunarMineUrbanization.ts, src/server/moon/MoonExpansion.ts, tests/cards/moon/LunarMineUrbanization.spec.ts
Also, fix a canPlay bug which made LMU easier to play than it should have been.
=> Make LMU compatible with Odyssey.

tests/cards/moon/HeavyDutyRovers.spec.ts
This was a bug report, and the test just verifies
that there's probably no issues.
Close #5065
=> Verify complicated rewards for Heavy Duty Rover.

src/server/cards/prelude/PointLuna.ts, tests/cards/moon/EarthEmbassy.spec.ts
=> Make Point Luna compatible with Earth Embassy.

src/server/cards/prelude/PointLuna.ts
=> Don't draw cards when there are no cards to draw

src/client/components/pathfinders/PlanetaryTrackReward.vue, src/server/pathfinders/PathfindersExpansion.ts
=> When Turmoil is not in play, Pathfinders delegate reward becomes 3MC.

src/client/components/Awards.vue, src/client/components/colonies/Colony.vue, src/locales/fr/colonies.json
=> Translation fix

src/server/boards/Board.ts, src/server/cards/pathfinders/Wetlands.ts, tests/cards/moon/LunaTradeStation.spec.ts, tests/cards/pathfinders/Wetlands.spec.ts
=> Make Wetlands compatible with Land Claims.

.env.sample, src/server/database/PostgreSQL.ts, src/server/requestProcessor.ts, src/server/routes/ApiStats.ts, src/server/routes/Game.ts, src/server/routes/Handler.ts, src/server/routes/IHandler.ts, src/server/routes/Route.ts, src/server/server-ids.ts, src/server/server.ts, tests/integration/PostgreSQL.spec.ts, tests/routes/RouteTestScaffolding.ts
Introduces a `STATS_ID` environment variable which can be shared with servers collecting metrics.
=> Change to stats endpoint

src/server/cards/pathfinders/PublicSponsoredGrant.ts
=> Event tag is not selectable for Public Sponsored Grants.

src/server/cards/colonies/Aridor.ts, tests/cards/colonies/Aridor.spec.ts, tests/cards/promo/Merger.spec.ts
=> Make Merger compatible with Aridor

src/server/database/PostgreSQL.ts
This has been broken for a while. Two things:
1. The early return was broken, so the operation never worked.
2. Even worse, the SQL was wrong.
=> Fix Postgres purge.

src/server/cards/base/RestrictedArea.ts
=> Don't draw the Restricted Area card before paying.

src/server/cards/community/Playwrights.ts, src/server/cards/pathfinders/Odyssey.ts
=> Add text for Playrights and Odyssey confirming that special tiles can be duplicated.

src/server/Game.ts
Reverts terraforming-mars/terraforming-mars#5174
=> Revert "Rewrite playerIsFinishedTakingActions."

src/server/PlayerInput.ts, src/server/inputs/AndOptions.ts, src/server/inputs/OrOptions.ts, src/server/inputs/SelectAmount.ts, src/server/inputs/SelectCard.ts, src/server/inputs/SelectColony.ts, src/server/inputs/SelectDelegate.ts, src/server/inputs/SelectInitialCards.ts, src/server/inputs/SelectOption.ts, src/server/inputs/SelectPartyToSendDelegate.ts, src/server/inputs/SelectPayment.ts, src/server/inputs/SelectPlayer.ts, src/server/inputs/SelectProductionToLose.ts, src/server/inputs/SelectProjectCardToPlay.ts, src/server/inputs/SelectSpace.ts, src/server/inputs/ShiftAresGlobalParameters.ts
This also includes some minor cleanup.
=> Add BasePlayerInput, which reduces some repetition.

src/server/awards/terraCimmeria/Warmonger.ts, src/server/cards/leaders/Bjorn.ts, src/server/cards/leaders/LeaderCardManifest.ts, src/server/cards/leaders/Naomi.ts, src/server/cards/leaders/Ulrich.ts, src/server/colonies/Colony.ts, tests/cards/leaders/Bjorn.spec.ts, tests/cards/leaders/Naomi.spec.ts, tests/cards/leaders/Ulrich.spec.ts
PR5.1 has Bjorn, Naomi, Ulrich.
Pretty straightfoward and self contained.  Hopefully fully covered with testing
I forgot at first that this will affect both Warmonger award and Law Suit.  
A lot of test coverage for this card.  But I'm not sure how to implement tests for Warmonger Award?  I'm not sure there actually _are_ tests for this award
Small hook when building a Colony.
The implementation itself _could_ be better in terms of UI.  It currently runs through every active colony with an increase/decrease prompt.  It's very clear what choices you're making though, so I'll leave it as-is
=> CEO PR# 5.1 - CEO Group 1 - Bjorn, Naomi, Ulrich

src/client/components/GameHome.vue, src/client/components/PlayerHome.vue, src/client/components/common/PurgeWarning.vue, src/common/models/GameModel.ts, src/common/models/SimpleGameModel.ts, src/server/Game.ts, src/server/SerializedGame.ts, src/server/database/utils.ts.ts, src/server/models/ServerModel.ts, src/styles/common.less, tests/Game.spec.ts, tests/routes/ApiGame.spec.ts
This could use a lot of work, but is a good start.
=> Add a purge warning.

src/server/Player.ts, src/server/awards/AwardScorer.ts, src/server/models/ServerModel.ts
This makes it simpler for the upcoming Asimov leader to be implemented without having to change things in every award.
=> Reorder how awards are scored.

src/client/components/Award.vue, src/client/components/Awards.vue, src/client/components/DebugUI.vue, src/client/components/GameHome.vue, src/client/components/LogPanel.vue, src/client/components/Milestone.vue, src/client/components/Milestones.vue, src/common/models/ClaimedMilestoneModel.ts, src/common/models/FundedAwardModel.ts, src/common/models/PlayerModel.ts, src/server/database/IDatabase.ts, src/server/database/LocalFilesystem.ts, src/server/database/PostgreSQL.ts, src/server/database/SQLite.ts, src/server/models/ServerModel.ts, src/server/routes/GameLogs.ts, tests/client/components/Award.spec.ts, tests/client/components/Awards.spec.ts, tests/client/components/Milestones.spec.ts, tests/testing/InMemoryDatabase.ts
1. Use ParticipantId in many places
2. Use camelCase.
=> General cleanup.

src/client/components/SelectInitialCards.vue, src/common/inputs/SelectInitialCards.ts, src/server/inputs/SelectInitialCards.ts, tests/client/components/PlayerInputFactory.spec.ts, tests/client/components/SelectInitialCards.spec.ts
Will simplify things when CEOs get added to the .vue.
=> Identify sections of SelectInitialCards by their distinct titles.

src/server/CeoExtension.ts, src/server/Player.ts, src/server/cards/ceos/CeoCardManifest.ts, src/server/cards/ceos/Xavier.ts, src/server/cards/ceos/Yvonne.ts, src/server/cards/ceos/Zan.ts, src/server/player/Tags.ts, src/server/turmoil/parties/PartyHooks.ts, tests/cards/ceo/Xavier.spec.ts, tests/cards/ceo/Yvonne.spec.ts, tests/cards/ceo/Zan.spec.ts
Pretty straight forward, a hook in [src/server/player/Tags.ts](https://github.com/terraforming-mars/terraforming-mars/compare/main...d-little:ceosXavierYvonneZan?expand=1#diff-589997eb1b5bf44b74bdb5b6ca8fab4d59981d4253d0123f66ecb4a890fe26dd) + [CeoExtension.ts](https://github.com/terraforming-mars/terraforming-mars/compare/main...d-little:ceosXavierYvonneZan?expand=1#diff-2a96143b4b90a5ed4f588de70afbb47f4e2672f268a1bff867f8e0a00d59b325)
Also straightforward, let me know if this was not the correct method to give bonuses to one player though:
`player.game.defer(new SimpleDeferredAction(player, () => colony.giveColonyBonus(player.game.getPlayerById(owner))));`
Zan will need some rendering items in the near future, for now it's text.
One hook via …
=> CEO PR# 5.4 - CEOs Xavier, Yvonne, Zan

src/server/Game.ts, src/server/deferredActions/PlaceHazardTile.ts
Hopefully fairly obvious.  Currently nothing uses this, but Caesar will.  After that there are a handful of Community Cards that interact with Hazards in Ares.
=> CEO#4.7 - DeferredAction PlaceHazardTile 

src/server/CeoExtension.ts, src/server/Player.ts, src/server/cards/ceos/Apollo.ts, src/server/cards/ceos/CeoCardManifest.ts, src/server/cards/ceos/Duncan.ts, src/server/cards/ceos/Will.ts, tests/cards/ceo/Apollo.spec.ts, tests/cards/ceo/Duncan.spec.ts, tests/cards/ceo/Will.spec.ts
Pretty straight forward
Needed some changes to Player.ts and uncommenting code in CeoExtension.ts
I _could_ have done this entirely in CeoExtension.ts, but am pretty sure that player.getCeo() will come in handy in the future.
Another easy one.
=> CEO PR# 5.3 - CEOs Apollo, Duncan, Will

src/client/components/SelectInitialCards.vue
As it says on the box.  Lets just make sure this passes tests!
Currently no CEO card is rendered if you run the CEO expansion, so you cannot actually select a CEO.  That's coming in #4.9
=>  CEO#4.8 - SelectInitialCards.vue

src/server/Game.ts, src/server/SerializedGame.ts, tests/cards/ceo/Bjorn.spec.ts, tests/cards/ceo/Will.spec.ts
No drafting, that can come later. Just the deck + hand dealing so we can get testing first.
=> CEO#4.9 - Game.ts

src/server/inputs/SelectInitialCards.ts
Small fix, but annoying that I let this slip through
=> Rename out-of-date leader vars to ceo

src/server/cards/ceos/CeoCardManifest.ts, src/server/cards/ceos/Quill.ts, src/server/cards/ceos/Rogers.ts, src/server/cards/ceos/Ryu.ts, tests/cards/ceo/Quill.spec.ts, tests/cards/ceo/Rogers.spec.ts, tests/cards/ceo/Ryu.spec.ts
Should be easy enough
Another relatively simple CEO
This is the tricky one.  It _works_ but I'm not particularly happy with the implementation.  Let me know if I should rip this one out and resubmit separately
=> CEO PR# 5.5 - CEOs Quill, Rogers, Ryu

src/common/cards/CardName.ts, src/server/cards/promo/16Psyche.ts, src/server/cards/promo/PromoCardManifest.ts, tests/cards/promo/16Psyche.spec.ts
Per https://boardgamegeek.com/thread/3026060/16-psyche-promo
(Where I wasnt allowed to start the object name with 16 I have simply dropped it.  This means that _some_ objects are named 16Psyche, some are just named Psyche.  I can standardise all of them to Psyche if desired)
=> Promo Card #44 - 16 Psyche

src/client/components/PreferencesDialog.vue, src/client/components/Sidebar.vue
This also removes the feature from the preferences dialog.
=> Promote the language icon from experimental to production.

src/client/components/GameSetupDetail.vue, src/client/components/GlobalParameterValue.vue, src/client/components/PlayerInputFactory.vue, src/client/components/card/CardRenderSymbolComponent.vue, src/client/components/card/CardResourceCounter.vue, src/styles/game_home.less
While I'm at it, turning the dependent methods into computed Vue attributes, making them slightly faster to generate.
=> Replace enum switches with Records.

src/client/components/GameEnd.vue, src/styles/game_end.less
=> Show planetary track points at game end.

src/server/cards/promo/Factorum.ts
It's a little tight, but that's OK.
=> Add asterisk to Factorum.

src/server/cards/ceos/CeoCardManifest.ts, src/server/cards/ceos/Stefan.ts, src/server/cards/ceos/Tate.ts, tests/cards/ceo/Stefan.spec.ts, tests/cards/ceo/Tate.spec.ts
Nothing unusual
`action()` is a nightmare heavily fuelled by OpenAI :(  But, I think I did okay with the testing!
=> CEO: Stefan, Tate

src/client/components/overview/PlayerTags.vue, src/common/utils/utils.ts, src/server/Game.ts, src/server/cards/ceos/Tate.ts, src/server/cards/community/AgricolaInc.ts, src/server/cards/pathfinders/EconomicHelp.ts, src/server/pathfinders/DeclareCloneTag.ts, src/server/pathfinders/PathfindersExpansion.ts, tests/Game.spec.ts, tests/cards/pathfinders/Kickstarter.spec.ts, tests/common/utils/utils.spec.ts, tests/pathfinders/DeclareCloneTag.spec.ts
This required a little bit of organization in how clone tags were declared, and I added a nice test to go with it.
=> Centralize the list of tags in the game.

src/server/cards/ceos/CeoCardManifest.ts, src/server/cards/ceos/VanAllen.ts, tests/cards/ceo/VanAllen.spec.ts
Nice and simple!
The Van Allen hook is already in place, this is just the CEO himself.
=> CEO Van Allen

src/server/cards/ceos/Karen.ts
Karen shouldnt tell people what cards they draw and _couldnt_ play
=> CEO Karen log messages private for player

src/common/Resources.ts, src/server/cards/CardRequirement.ts, src/server/cards/ceos/Ryu.ts, src/server/cards/prelude/RobinsonIndustries.ts, tests/cards/base/RoboticWorkforce.spec.ts, tests/milestones/Generalist.spec.ts
=> Make an all-resources array.

src/server/Player.ts, src/server/logs/LogBuilder.ts, src/server/logs/MessageBuilder.ts
This introduces a simple way to make Message objects, and ties it into the logging API without duplication (though it's not the most amazing class structure I've ever written.)
This simplifies some of the calls in Player.ts.
=> Make it easier to use messages in logs and things.

src/server/cards/venusNext/AirScrappingExpedition.ts, tests/cards/venusNext/AirScrappingExpedition.spec.ts
=> Air Scrapping Expedition automatically choose single resource card.

src/server/cards/ceos/Musk.ts, tests/cards/ceo/Musk.spec.ts
Problem with Musk; the test name was wrong and I never caught it before being pushed.
There's also now a problem with Musk himself, so this test will fail.
He's not drawing the cards after discarding.
=> CEO : Rename Musk tests so they actually run

src/server/cards/ceos/CeoCardManifest.ts, src/server/cards/ceos/Jansson.ts, tests/cards/ceo/Jansson.spec.ts
=> CEO Jansson

src/server/cards/ICard.ts, src/server/cards/promo/ProjectInspection.ts, src/server/cards/venusNext/Viron.ts, tests/cards/pathfinders/Odyssey.spec.ts
This really change Viron and Project Inspection, but that's fine.
=> Make Odyssey compatible with the Viron/Project Inspection pair.

src/server/Player.ts, tests/cards/ceo/VanAllen.spec.ts
=> Van Allen should claim for free

src/server/CardFinder.ts, tests/CardFinder.spec.ts
I'm not sure how to test this...
via https://discord.com/channels/737945098695999559/742721510376210583/1077021115358126080
I am not able to replicate the issue, but reading through the code+errors, I _think_ this solves the deserialization issues users have been seeing
=> getProjectCardByName includes ceoCards

src/client/components/AndOptions.vue, src/client/components/GameEnd.vue, src/client/components/GameHome.vue, src/client/components/LoadGameForm.vue, src/client/components/LogPanel.vue, src/client/components/OrOptions.vue, src/client/components/OtherPlayer.vue, src/client/components/SelectAmount.vue, src/client/components/SelectCard.vue, src/client/components/SelectColony.vue, src/client/components/SelectInitialCards.vue, src/client/components/SelectOption.vue, src/client/components/SelectPartyPlayer.vue, src/client/components/SelectPartyToSendDelegate.vue, src/client/components/SelectPayment.vue, src/client/components/SelectPlayer.vue, src/client/components/SelectProjectCardToPlay.vue, src/client/components/common/AppButton.vue, src/client/components/create/CardsFilter.vue, src/client/components/create/CreateGameForm.vue, src/client/components/overview/PlayerInfo.vue, tests/client/components/AndOptions.spec.ts, tests/client/components/OrOptions.spec.ts, tests/client/components/SelectInitialCards.spec.ts, tests/client/components/common/AppButton.spec.ts
This removes a lint warning I'm glad to be rid of.
=> Rename Button to AppButton.

src/server/cards/ceos/Caesar.ts
Just clarifying what X does on Caesar
=> Define X on Caesar

src/server/cards/ceos/Ingrid.ts, tests/cards/ceo/Ingrid.spec.ts
=> Ingrid bugfixes for #5434

src/common/cards/CardName.ts, src/server/cards/promo/PromoCardManifest.ts, src/server/cards/promo/RobotPollinators.ts, tests/cards/promo/RobotPollinators.spec.ts
... not a particularly good card, but cute lil robees
Source: https://i.redd.it/70vv0axhf2la1.jpg
=> Promo #47 - Robotic Pollinators

src/locales/de/ui.json, src/locales/pl/ui.json, src/server/milestones/amazonisPlanitia/Minimalist.ts
=> Minimalist grammar fix.

src/client/components/create/CreateGameForm.vue, src/common/game/NewGameConfig.ts, src/server/Game.ts, src/server/routes/Game.ts
=> Disable new games of corporate draft.

src/client/components/App.ts, src/client/components/vueRoot.ts, src/client/directives/i18n.ts, src/locales/de/ui.json, src/server/cards/base/HiredRaiders.ts, src/server/logs/MessageBuilder.ts
Use Hired Raiders as an example.
=> Make it possible to translate in-option Messages.

src/server/cards/promo/GreatDamPromo.ts, tests/TestingUtils.ts, tests/cards/promo/GreatDamPromo.spec.ts
It's currently applying two tiles.
=> Fix great dam.

src/server/cards/colonies/MinorityRefuge.ts, tests/cards/colonies/MinorityRefuge.spec.ts
=> Fix case where Minority Refuge is playable with Luna.

src/server/cards/ceos/Maria.ts, src/server/cards/colonies/Aridor.ts, src/server/deferredActions/RemoveColonyFromGame.ts, src/server/inputs/SelectColony.ts, src/server/models/ServerModel.ts
=> Don't show cubes on Colony tiles under certain circumstances.

src/server/awards/terraCimmeria/Urbanist.ts, tests/awards/terraCimmeria/Biologist.spec.ts, tests/awards/terraCimmeria/Urbanist.spec.ts
@nwai90 just getting started on this. Does this seem reasonable? I'll write up a test.
=> Make Urbanist support Capital and Red City.

src/client/components/create/CardsFilter.vue
=> CEO - Include CEOs in the Banned/Excluded Cards list

src/server/Player.ts, tests/Game.spec.ts, tests/cards/promo/Philares.spec.ts
=> Make final greenery placement compatible with Philares.

src/locales/cn/ares_cards.json, src/locales/de/ares_cards.json, src/locales/es/ares_cards.json, src/locales/it/ares_cards.json, src/locales/ko/ares_cards.json, src/locales/pl/ares_cards.json, src/server/cards/ares/ButterflyEffect.ts
Butterfly Effect makes more sense when playing the physical game, so hopefully this adds enough of a hint without being too wordy.
Fixes #5515
=> Clarify Butterfly Effect.

src/client/components/overview/PlayerTags.vue, src/client/components/overview/PointsPerTag.vue, src/styles/players_overview.less, tests/client/components/overview/PlayerTags.spec.ts, tests/client/components/overview/PointsPerTag.spec.ts
=> Show proper fraction when player has Cultivation of Venus and Venera Base

src/server/SerializedCard.ts, src/server/cards/CardSerialization.ts
I think this will 
* fix #5547, 
* fix #5538, 
and maybe a few other undocumented issues
I'm not sure this is correct.  Important to note that not every CEO has opgActionIsActive nor interacts with it
=> Serialize CEO card option opgActionIsActive

src/server/Game.ts, src/server/Player.ts, src/server/cards/ceos/Neil.ts, src/server/cards/corporation/SaturnSystems.ts, src/server/cards/pathfinders/MindSetMars.ts, src/server/cards/promo/Splice.ts, src/server/deferredActions/RemoveResourcesFromCard.ts, tests/Game.spec.ts
=> Fix Van Allen's CEO by making getCardPlayer explicit.

src/server/player/Tags.ts, tests/cards/pathfinders/Odyssey.spec.ts, tests/globalEvents/Diversity.spec.ts, tests/milestones/Diversifier.spec.ts
=> Make Odyssey compatible with Diversifier Global Event.

src/server/behavior/Executor.ts, tests/behavior/Executor.spec.ts
=> Don't ask a player to select cards if there are no resources to add.

tests/cards/ares/DeimosDownAres.spec.ts
These tests are failing locally, and I assume they'll fail on the server.
However, this card is behaving exactly as expected in my own manual testing, so I'm not sure what's going on... related to #5575
=> Ares Deimos Down Testing

src/server/Player.ts
=> Fix "End Turn" with Mars Maths and other 'increased/decreased actions per round'

src/server/cards/ICardFactory.ts, src/server/cards/promo/Merger.ts, tests/TestPlayer.ts, tests/cards/promo/Merger.spec.ts
These problems are mostly fan-corp induced, but these ought to work.
=> Validate outlier merger cases

src/server/cards/ceos/CoLeadership.ts, src/server/cards/ceos/Lowell.ts, src/server/inputs/SelectInitialCards.ts
This should cover all our bases
Fixes #5607
Fixes #5546
Also standardised some of the wording/language on these items
=> CEO: Add Discards where necessary

src/server/Player.ts, src/server/cards/pathfinders/MarsMaths.ts, tests/cards/pathfinders/MarsMaths.spec.ts
Makes the code a little easier to read.
=> Rename actionsThisRound to availableActionsThisRound.

src/server/Player.ts, src/server/game/calculateVictoryPoints.ts
This mostly just reduces Player.ts size a bit.
=> Move VP calcualtion to its own code.

src/client/components/board/BoardSpaceTile.vue, src/client/components/moon/MoonSpace.vue
=> Consolidate BoardSpace tile generation.

src/server/cards/moon/GeodesicTents.ts
=> Geodesic Tents: Clarify iconography

src/server/SerializedCard.ts, src/server/cards/CardSerialization.ts
=> Serialize CEO generationUsed

src/client/components/Board.vue, src/styles/board.less
How it is now
And how it will be (some string shifts)
=> Added ability to translate for geological places

src/client/components/overview/PlayerResource.vue, src/styles/resources.less
=> Tooltips for player resources

src/client/components/overview/PlayerTags.vue
=> Show discount even when no cards have that tag.

src/styles/board.less
=> Fixed hexagon form of tiles

src/client/components/common/PurgeWarning.vue
=> Ability to translate for a pair of strings

src/styles/cards_v2.less, src/styles/language_hacks.less, src/styles/player_home.less, src/styles/turmoil.less
Fixed https://github.com/terraforming-mars/terraforming-mars/pull/5655#issuecomment-1537427478
Link now looks like a link
When mouse over
=> Style fixes

src/client/components/SelectPayment.vue, src/client/components/SelectProjectCardToPlay.vue, src/client/mixins/PaymentWidgetMixin.ts, src/common/inputs/Payment.ts, src/common/models/PlayerInputModel.ts, src/server/Player.ts, src/server/cards/StandardProjectCard.ts, src/server/deferredActions/SelectPaymentDeferred.ts, src/server/models/ServerModel.ts, tests/cards/pathfinders/Aurorai.spec.ts, tests/cards/pathfinders/ValuableGases.spec.ts, tests/client/components/PaymentTester.ts, tests/client/components/PlayerInputFactory.spec.ts, tests/client/components/SelectPayment.spec.ts, tests/client/components/ShiftAresGlobalParameters.spec.ts
Also remove another type that matches Payment.
This helps dismabiguate with the upcoming Think Tank card.
=> change Payment.data to Payment.auroraiData.

src/server/cards/ares/AresCardManifest.ts, tests/cards/ares/GreatDamAres.spec.ts
I totally forgot to do this in the last PR
=> Remove MFG cards from Ares

src/client/components/Tag.vue, src/styles/language_hacks.less, src/styles/player_home.less, tests/client/components/Tag.spec.ts
=> Tooltips for player's tags

src/locales/cn/pathfinder_cards.json, src/locales/de/pathfinder_cards.json, src/locales/nl/pathfinder_cards.json, src/locales/pl/pathfinder_cards.json, src/server/cards/pathfinders/FloaterUrbanism.ts
=> Clarify Floater Urbanism

src/client/components/BugReportDialog.vue
=> Update Bug Report Dialog

src/client/components/pathfinders/PlanetaryTrackReward.vue
=> Make TR planetary reward visible

src/common/cards/CardName.ts, src/server/Game.ts, src/server/Player.ts, src/server/cards/promo/PromoCardManifest.ts, src/server/cards/promo/Supercapacitors.ts, tests/cards/promo/Supercapacitors.spec.ts
=> New promo card Supercapacitors

tests/cards/promo/OrbitalCleanup.spec.ts
A quick additional check, feel free to reject if not desired.
I just wanted to sanity check this as it works in an interesting way
=> Add check for OrbitalCleanup + Scientists Policy 4

src/server/cards/promo/Supercapacitors.ts
=> Update button text.

src/client/components/overview/PlayerTimer.vue, src/styles/players_overview.less
First PR!
Issue: https://github.com/terraforming-mars/terraforming-mars/issues/3773
=> Fix timer formatting

src/server/cards/CardSerialization.ts
=> Correctly serialize Specialized Settlement.

src/server/Game.ts, src/server/IPlayer.ts, src/server/Player.ts, src/server/ares/AresHandler.ts, src/server/behavior/Executor.ts, src/server/cards/base/TerraformingGanymede.ts, src/server/cards/community/Midas.ts, src/server/cards/community/ProjectWorkshop.ts, src/server/cards/moon/LunaEcumenopolis.ts, src/server/cards/pathfinders/SocialEvents.ts, src/server/cards/promo/PharmacyUnion.ts, src/server/cards/turmoil/Pristar.ts, src/server/colonies/Colony.ts, src/server/moon/MoonExpansion.ts, src/server/turmoil/Turmoil.ts, src/server/turmoil/globalEvents/Election.ts, src/server/turmoil/globalEvents/Revolution.ts, src/server/turmoil/globalEvents/WarOnEarth.ts, tests/cards/community/UnitedNationsMissionOne.spec.ts, tests/cards/pathfinders/Aurorai.spec.ts, tests/turmoil/Turmoil.spec.ts
Reducing the IPlayer surface area.
=> Remove duplicate TR methods.

src/locales/cn/moon_corporations.json, src/locales/de/moon_corporations.json, src/locales/it/moon_corporations.json, src/locales/ko/moon_corporations.json, src/locales/nl/moon_corporations.json, src/locales/pl/moon_corporations.json, src/server/cards/moon/TheArchaicFoundationInstitute.ts, src/server/cards/render/CardRenderer.ts, src/styles/cards_v2.less, tests/TestingUtils.ts, tests/cards/ares/GeologicalSurvey.spec.ts, tests/cards/ceo/Zan.spec.ts, tests/cards/moon/TheArchaicFoundationInstitute.spec.ts, tests/cards/pathfinders/HighTempSuperconductors.spec.ts, tests/cards/promo/OrbitalCleanup.spec.ts, tests/turmoil/parties/Greens.spec.ts, tests/turmoil/parties/Kelvinists.spec.ts, tests/turmoil/parties/MarsFirst.spec.ts, tests/turmoil/parties/Reds.spec.ts, tests/turmoil/parties/Scientists.spec.ts, tests/turmoil/parties/Unity.spec.ts
This isn't quite enough, because it should ideally reduce as many
as possible as soon as possible.
=> Update Archaic Foundation Institute to be more resilient with Reds.

src/server/cards/ICard.ts, src/server/cards/ceos/ICeoCard.ts, src/server/cards/corporation/ICorporationCard.ts, src/server/player/Tags.ts
=> Special-case Pharmacy Union when counting tagless cards.

src/client/components/Board.vue, src/styles/board.less
Reverts terraforming-mars/terraforming-mars#5697
This breaks the layout of the Tharsis map in English.
=> Revert "Added ability to translate for geological places"

src/server/IGame.ts, src/server/cards/base/EnergyTapping.ts, src/server/cards/base/PowerSupplyConsortium.ts, src/server/deferredActions/DecreaseAnyProduction.ts, src/server/deferredActions/GainProduction.ts, tests/cards/base/EnergyTapping.spec.ts, tests/cards/base/PowerSupplyConsortium.spec.ts
=> Make production stealing cards correctly when nobody has production.

src/server/boards/Board.ts, src/server/cards/turmoil/RedTourismWave.ts, tests/Game.spec.ts, tests/cards/turmoil/RedTourismWave.spec.ts
Plus, Board.getEmptySpaces isn't worth its weight.
=> Fix "empty adjacent spaces" calculation.

src/server/boards/HellasBoard.ts, src/server/boards/VastitasBorealisBoard.ts
This does not address the cost-for-global-parameter issue.
=> Propagage ares checks for Hellas and Vastitas Borealis.

src/client/components/board/BoardSpaceTile.vue
=> Fix Ares' Magnetic Field Generator rendering

src/server/boards/Board.ts, src/server/boards/HellasBoard.ts, src/server/boards/VastitasBorealisBoard.ts, tests/Game.spec.ts, tests/boards/HellasBoard.spec..ts
This will be much more accurate for predicting when a player can afford the ocean or temperature bonus.
=> Update map filtering for Hellas and V. Borealis

src/server/Game.ts, src/server/IPlayer.ts, src/server/Player.ts, src/server/behavior/Executor.ts, src/server/cards/Deck.ts, src/server/cards/ceos/Ingrid.ts, src/server/cards/ceos/Tate.ts, src/server/cards/community/JunkVentures.ts, src/server/cards/pathfinders/ReturntoAbandonedTechnology.ts, src/server/cards/promo/HiTechLab.ts, src/server/deferredActions/ChooseCards.ts, src/server/deferredActions/DeferredAction.ts, src/server/deferredActions/DrawCards.ts, tests/cards/ceo/Tate.spec.ts, tests/cards/community/JunkVentures.spec.ts, tests/cards/pathfinders/ReturntoAbandonedTechnology.spec.ts, tests/cards/venusNext/SponsoredAcademies.spec.ts, tests/deferredActions/DrawCards.spec.ts
A couple of things are hard to fix because of a) how DrawCards works and
b) how DeferredActionQueue can't be used for inputs that all players
must use.
This should facilitate a few improvements.
=> Rewrite DrawCards

src/common/pathfinders/PlanetaryTrack.ts, src/server/boards/BoardBuilder.ts, src/server/cards/render/CardRenderer.ts, src/server/cards/requirements/CardRequirements.ts, src/server/logs/LogBuilder.ts, src/server/logs/MessageBuilder.ts, src/server/moon/MoonBoard.ts
Will faciliate subclassing, an issue I had in the past.
=> Use this as return type.

src/common/utils/utils.ts, src/server/LogHelper.ts, src/server/database/PostgreSQL.ts, src/server/deferredActions/ChooseCards.ts, tests/cards/promo/OutdoorSports.spec.ts
=> Adding array difference function, adding some readonlyarrays, using partition.

src/client/components/Board.vue, src/client/components/BoardSpace.vue, src/client/components/SelectSpace.vue, src/client/components/moon/MoonBoard.vue, src/styles/board.less
Sometimes the simplest thing to do is remove code.
=> Allow Cathedral to be selected on space colonies.

src/common/cards/CardName.ts, src/server/cards/base/RoboticWorkforce.ts, src/server/cards/base/RoboticWorkforceBase.ts, src/server/cards/promo/AsteroidDeflectionSystem.ts, src/server/cards/promo/CyberiaSystems.ts, src/server/cards/promo/PromoCardManifest.ts
=> Promo card Cyberia Systems

src/common/cards/CardName.ts, src/server/Player.ts, src/server/cards/promo/GiantSolarCollector.ts, src/server/cards/promo/PromoCardManifest.ts
=> Giant Solar Collector promo card.

src/common/cards/CardName.ts, src/server/cards/promo/HermeticOrderofMars.ts, src/server/cards/promo/PromoCardManifest.ts
=> Promo card Hermetic Order of Mars

src/server/models/ServerModel.ts
=> Fix Aurorai regression

src/server/database/Database.ts, src/server/database/LocalStorage.ts, tests/integration/LocalStorage.spec.ts
This allows for one to use LocalStorage for IDatabase. When one eventually runs games with the server running in a worker this can be used for the database implementation. May also prove useful for those looking for something that doesn't need file system access.
=> Introducing LocalStorage as an IDatabase.

src/server/cards/prelude2/Sagitta.ts
https://boardgamegeek.com/thread/3154781/do-event-tags-count-sagitta
It's not definitive, but it seems that's how things are leaning.
=> Sagitta includes the event tag.

src/client/components/WaitingFor.vue, src/common/Units.ts, src/common/cards/CardName.ts, src/server/behavior/Executor.ts, src/server/boards/Board.ts, src/server/cards/prelude2/CeresTechMarket.ts, src/server/cards/prelude2/FocusedOrganization.ts, src/server/cards/prelude2/MartianLumberCorp.ts, src/server/cards/prelude2/NobelPrize.ts, src/server/cards/prelude2/PalladinShipping.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/Spire.ts, src/server/cards/promo/MarsNomads.ts, src/server/cards/promo/PromoCardManifest.ts, src/server/deferredActions/AddResourcesToCard.ts
Misc cleanup and setup for the other new cards.
=> Add card Focused Organization. Fix Applied Science.

src/server/Player.ts, src/server/cards/corporation/ICorporationCard.ts, src/server/cards/prelude2/SagittaFrontierServices.ts
=> Sagitta should respond to new corps thanks to Merger.

src/common/utils/utils.ts, src/server/IPlayer.ts, src/server/Player.ts, src/server/cards/base/MarsUniversity.ts, src/server/cards/base/standardProjects/SellPatentsStandardProject.ts, src/server/cards/ceos/Musk.ts, src/server/cards/ceos/Stefan.ts, src/server/cards/prelude2/CeresTechMarket.ts, src/server/cards/prelude2/FocusedOrganization.ts, src/server/cards/prelude2/Spire.ts, src/server/deferredActions/DiscardCards.ts
=> Fix Focused Organization discard. Generalize discard card from hand.

src/server/cards/promo/SolarLogistics.ts, tests/cards/promo/SolarLogistics.spec.ts
Should be 20, not 14.  
(I'm assuming that was a copy/paste error from Tesalaract)
=> Fix Solar Logistics Price

src/server/cards/venusNext/VenusianAnimals.ts
Small QOL addition to the log
Sidenote: Logging across the board seems arbitrary to me, is there some criteria?
=> add: log additions to venusian animals

src/server/cards/pathfinders/CommunicationCenter.ts, src/server/cards/pathfinders/DesignedOrganisms.ts, src/server/cards/pathfinders/NobelLabs.ts, src/server/cards/pathfinders/SurveyMission.ts
modified:   src/server/cards/pathfinders/CommunicationCenter.ts
modified:   src/server/cards/pathfinders/DesignedOrganisms.ts
modified:   src/server/cards/pathfinders/NobelLabs.ts
modified:   src/server/cards/pathfinders/SurveyMission.ts
=> Update to 4 Pathfinder cards

src/server/CeoExtension.ts, src/server/cards/ceos/Bjorn.ts, src/server/cards/ceos/Rogers.ts, src/server/cards/ceos/Xavier.ts, src/styles/cards_v2.less, tests/cards/ceo/Bjorn.spec.ts, tests/cards/ceo/Xavier.spec.ts
Couple of small balance changes to bring these into line with the tfm-community branch
=> Ceo balance update

src/client/components/BoardSpace.vue, src/client/components/board/BoardSpaceTile.vue, src/client/components/card/CardRenderTileComponent.vue, src/common/TileType.ts, src/common/models/SpaceModel.ts, src/server/Game.ts, src/server/IGame.ts, src/server/SerializedGame.ts, src/server/boards/Board.ts, src/server/cards/promo/KaguyaTech.ts, src/server/cards/promo/MarsNomads.ts, src/server/deferredActions/RemoveOceanTile.ts, src/server/models/ServerModel.ts, tests/cards/pathfinders/ThinkTank.spec.ts
=> Make Mars Nomads a fake special tile that only renders as a cube.

src/server/CeoExtension.ts, src/server/cards/CardSerialization.ts, src/server/cards/ceos/Xavier.ts, src/server/player/Tags.ts, tests/cards/ceo/Xavier.spec.ts
=> Make Xavier work with milestones.

src/server/cards/CardSerialization.ts, src/server/cards/ProxyCard.ts, src/server/cards/community/ScienceTagCard.ts, src/server/cards/community/SpecialDesignProxy.ts
I hope we don't have a lot more, but this is a good reduction.
=> Add ProxyCard as a type.

src/client/components/BoardSpace.vue, src/client/components/board/BoardSpaceTile.vue, src/client/components/card/CardRenderTileComponent.vue, src/common/TileType.ts, src/common/models/SpaceModel.ts, src/server/Game.ts, src/server/IGame.ts, src/server/SerializedGame.ts, src/server/boards/Board.ts, src/server/cards/promo/KaguyaTech.ts, src/server/cards/promo/MarsNomads.ts, src/server/deferredActions/RemoveOceanTile.ts, src/server/models/ServerModel.ts, tests/cards/pathfinders/ThinkTank.spec.ts
This rollback will restore the prior behavior.
=> Revert "Make Mars Nomads a fake special tile that only renders as a cube. (#6014)"

src/client/components/card/CardContent.vue, src/client/components/card/CardRequirementsComponent.vue
This only had an effect on dev and test.
=> Fix Vue types with change of requirements structure.

src/client/components/card/CardRenderItemComponent.vue, src/server/cards/promo/KuiperCooperative.ts, src/server/cards/render/CardRenderer.ts, src/styles/cards_v2.less
=> Tweak viz for Kuiper Asteroids.

src/client/components/GameEnd.vue, src/client/components/GlobalParameterValue.vue, src/client/components/gameend/VictoryPointChart.vue, src/common/GlobalParameter.ts, src/common/models/GameModel.ts, src/common/models/PlayerModel.ts, src/server/Game.ts, src/server/IGame.ts, src/server/SerializedGame.ts, src/server/models/ServerModel.ts
=> End game global parameter chart

src/server/Game.ts
Picking hazard locations shares the same code for placing cities, which is OK I guess? But hazard placement next to cities is allowed! Plus, when the map gets full, hazard placement becomes impossible, messing up the game.
=> Fix Ares placement with a near full map.

src/client/components/LogPanel.vue, src/client/components/board/BoardSpaceTile.vue, src/client/components/card/CardRenderTileComponent.vue, src/client/directives/i18n.ts, src/common/TileType.ts, src/common/boards/SpaceBonus.ts, src/common/logs/LogMessageData.ts, src/locales/de/starwars_cards.json, src/server/Game.ts, src/server/LogHelper.ts, src/server/ares/AresHandler.ts, src/server/ares/AresHazards.ts, src/server/cards/starwars/ReySkywalker.ts, src/server/moon/MoonExpansion.ts, tests/cards/starwars/ReySkywalker.spec.ts
Clean some of the string renderings for tiles.
=> Update Rey Skywalker, and add test.

src/server/cards/community/ByElection.ts, src/server/cards/pathfinders/TheNewSpaceRace.ts, src/server/turmoil/ChooseRulingPartyDeferred.ts, src/server/turmoil/Turmoil.ts
This enables an .andThen behavior if necessary.
=> Move selecting a new ruling party to its own deferred action.

src/server/behavior/Behavior.ts, src/server/behavior/Executor.ts, src/server/cards/base/Virus.ts, src/server/cards/colonies/AirRaid.ts, src/server/cards/pathfinders/SolarStorm.ts, src/server/cards/render/CardRenderer.ts, src/server/cards/underworld/ArtesianAquifer.ts, src/server/cards/underworld/MicroGeodesics.ts, src/server/cards/underworld/Microgravimetry.ts, src/server/cards/underworld/NarrativeSpin.ts, src/server/cards/underworld/PersonalSpacecruiser.ts, src/server/cards/underworld/PrivateMilitaryContractor.ts, src/server/cards/underworld/StemFieldSubsidies.ts, src/server/cards/underworld/UnderworldCardManifest.ts, src/server/cards/venusNext/StratosphericBirds.ts, src/server/deferredActions/PlaceOceanTile.ts, src/server/deferredActions/RemoveResourcesFromCard.ts, src/server/underworld/IdentifySpacesDeferred.ts, src/server/underworld/UnderworldExpansion.ts, tests/cards/underworld/ArtesianAquifer.spec.ts, tests/cards/underworld/MicroGeodesics.spec.ts, tests/cards/underworld/Microgravimetry.spec.ts, tests/cards/underworld/NarrativeSpin.spec.ts, tests/cards/underworld/PersonalSpacecruiser.spec.ts, tests/cards/underworld/PrivateMilitaryContractor.spec.ts, tests/cards/underworld/StemFieldSubsidies.spec.ts, tests/underworld/UnderworldExpansion.spec.ts, tests/underworld/UnderworldTestHelper.ts
Artesian Aquifer
Microgeodesics
Personal Spacecruiser
=> More Underworld cards

src/server/cards/promo/MagneticFieldGeneratorsPromo.ts
Card lets you place a special tile, but description does not state that.
Updated description to match that of the official promo card.
=> Text fix magnetic field generators promo

src/client/components/GameSetupDetail.vue, src/locales/de/ui.json, src/locales/es/UI.json, src/locales/fr/ui.json, src/locales/hu/UI.json, src/locales/jp/UI.json, src/locales/ko/UI.json, src/locales/nl/ui.json, src/locales/pl/ui.json, src/locales/ru/ui.json
**AC**
- display the EV bonus time on the Game settings page
=> Bonus time displayed on settings page

src/server/cards/pathfinders/GagarinMobileBase.ts, tests/cards/pathfinders/GagarinMobileBase.spec.ts
=> Fix bonus for Gagarin Mobile Base player

src/server/Game.ts, src/server/IPlayer.ts, src/server/Player.ts, src/server/SerializedPlayer.ts, src/server/cards/corporation/UnitedNationsMarsInitiative.ts, src/server/cards/turmoil/Pristar.ts, tests/Player.spec.ts
There are some issues. For now, undo is the right choice.
=> Undo the card-local data.

src/server/Player.ts, src/server/cards/ICard.ts, src/server/cards/colonies/Aridor.ts, src/server/cards/corporation/ICorporationCard.ts, src/server/cards/corporation/SaturnSystems.ts, src/server/cards/moon/IntragenSanctuaryHeadquarters.ts, src/server/cards/pathfinders/Ambient.ts, src/server/cards/pathfinders/CollegiumCopernicus.ts, src/server/cards/pathfinders/Ringcom.ts, src/server/cards/prelude/PointLuna.ts, src/server/cards/prelude2/SagittaFrontierServices.ts, src/server/cards/prelude2/Spire.ts, src/server/cards/promo/PharmacyUnion.ts, src/server/cards/promo/Splice.ts
=> Make Spire reward Corporation cards played with Merger.

src/server/cards/promo/IcyImpactors.ts
=> Reorder Icy Impactors actions.

.github/workflows/main.yml, package-lock.json, package.json
#6305 points out that 16 is about to EOL. Adding 18 and 20, and removing 14, which is farther out of support than 16. Looks like 18 and 20 should work.
=> Disable Node 14, enable Node 18 and Node 20

src/server/IPlayer.ts, src/server/Player.ts, src/server/cards/base/HiredRaiders.ts, src/server/cards/ceos/Bjorn.ts, src/server/cards/moon/AncientShipyards.ts, src/server/cards/moon/RoadPiracy.ts, src/server/cards/moon/TheDarksideofTheMoonSyndicate.ts, src/server/cards/promo/LawSuit.ts, src/server/cards/starwars/CloneTroopers.ts, src/server/cards/underworld/HiredRaiders.ts, src/server/cards/underworld/SpacePrivateers.ts, src/server/cards/underworld/SubnauticPirates.ts, src/server/cards/underworld/UnderworldCardManifest.ts, src/server/cards/venusNext/CometForVenus.ts, src/server/deferredActions/DecreaseAnyProduction.ts, src/server/deferredActions/RemoveAnyPlants.ts, src/server/deferredActions/RemoveResources.ts, src/server/deferredActions/StealResources.ts
It simplifies calls and reduces the risk of errors.
=> Add a maybeBlock to IPlayer.

src/client/components/create/PreludesFilter.vue, src/server/cards/community/CommunityCardManifest.ts
Pathfinders' Venus First is pretty much the same card.
=> Remove Community Venus First from new games.

src/server/turmoil/ChooseRulingPartyDeferred.ts, tests/cards/pathfinders/TheNewSpaceRace.spec.ts
=> Make The New Space Race playable mid-game

src/client/components/card/CardRenderItemComponent.vue
=> Fix MC rendering, show a number inside.

src/server/CardFinder.ts, src/server/SerializedCard.ts, src/server/cards/CardSerialization.ts, src/server/cards/pathfinders/SmallComet.ts, src/server/cards/underworld/PlantTax.ts, src/server/cards/underworld/PriceWars.ts, src/server/deferredActions/RemoveResources.ts, src/server/underworld/UnderworldExpansion.ts, tests/cards/underworld/PriceWars.spec.ts, tests/deferredActions/RemoveResources.spec.ts
=> Fix some Underworld bugs (Price Wars, Plant Tax.)

src/client/components/PaymentUnit.vue
=> Fix asteroid rendering in PaymentUnit

src/client/components/SelectCard.vue, src/client/components/WarningsComponent.vue, src/common/cards/Warning.ts, src/common/models/CardModel.ts, src/server/preludes/PreludesExpansion.ts
=> Add warning when a prelude will fizzle

src/server/cards/moon/RoadPiracy.ts, tests/cards/moon/RoadPiracy.spec.ts
=> Make Road Piracy compatible with  Pathfinders

src/client/components/OrOptions.vue, src/common/models/PlayerInputModel.ts, src/server/Player.ts, src/server/PlayerInput.ts, src/server/inputs/OrOptions.ts
=> Skip the spend heat action if heat is already at its goal.   @kberg

.gitignore, src/client/components/LogPanel.vue, src/client/components/OtherPlayer.vue
=> Fix SRR card viz

src/server/cards/base/Flooding.ts, src/server/cards/promo/IcyImpactors.ts, src/server/cards/underworld/CentralReservoir.ts, src/server/cards/underworld/SubterraneanSea.ts, src/server/cards/underworld/UnderworldCardManifest.ts, src/server/cards/underworld/Whales.ts, src/server/deferredActions/DeferredAction.ts, src/server/deferredActions/PlaceOceanTile.ts, src/server/inputs/OrOptions.ts, tests/cards/base/Flooding.spec.ts, tests/cards/promo/IcyImpactors.spec.ts, tests/cards/underworld/CentralReservoir.spec.ts, tests/cards/underworld/SubterraneanSea.spec.ts, tests/cards/underworld/Whales.spec.ts
=> Underworld card Whales

src/locales/de/log_messages.json, src/server/cards/underworld/AnubisSecurities.ts
=> Fix Anubis Securities log

src/client/components/WarningsComponent.vue, src/common/cards/Warning.ts, src/common/utils/utils.ts, src/server/cards/Deck.ts, src/server/cards/ceos/CoLeadership.ts, src/server/cards/ceos/Karen.ts, src/server/cards/ceos/Lowell.ts, src/server/cards/prelude/ValleyTrust.ts, src/server/cards/promo/Merger.ts, src/server/cards/promo/NewPartner.ts, tests/cards/Deck.spec.ts, tests/cards/community/JunkVentures.spec.ts, tests/cards/moon/LunarPlanningOffice.spec.ts, tests/common/utils/utils.spec.ts
=> Remove some uses of drawLegacy

src/common/cards/CardName.ts, src/server/cards/promo/PromoCardManifest.ts, src/server/cards/promo/SoilEnrichment.ts, tests/cards/promo/SoilEnrichment.spec.ts
=> Spring 2024 promo card Soil Enrichment.

src/client/mixins/PaymentWidgetMixin.ts, src/server/Player.ts, src/server/tools/read_turmoil.ts, tests/client/components/SelectProjectCardToPlay.spec.ts, tmp, tmp2
=> Make Soil Enrichment compatible with Psychophriles

src/server/cards/moon/DarksideSmugglersUnion.ts, src/server/cards/pathfinders/HuygensObservatory.ts
=> Make Huygens Observatory and Darkside Smugglers Union compatible with Trade Embargo

src/server/boards/Board.ts, src/server/cards/promo/MarsNomads.ts, tests/cards/promo/MarsNomads.spec.ts
=> Make Mars Nomads compatible with ocean and temperature bonuses.

package-lock.json, package.json, src/common/game/NewGameConfig.ts, src/server/routes/Game.ts, tests/routes/Game.spec.ts, tests/routes/RouteTestScaffolding.ts
This can work for serialization and HTTP requests.
=> Introducing Zod to validate external JSON inputs.

src/client/components/create/CreateGameForm.vue, src/common/game/NewGameConfig.ts
=> Remove superfluous "index" from NewGameConfig.

src/client/components/Board.vue
=> Add line for Albor Tholus on Terra Cimmeria

package.json, src/common/game/NewGameConfig.ts, src/server/routes/Game.ts, tests/routes/Game.spec.ts
Great idea, but it might have taken too much memory. It's not entirely clear how much Zod took up, but it caused Heroku to stop compiling our app. It also introduced a couple of errors that were going to be fun to fix.
This breaks the red-rover bot, but that's also in development, and can be addressed later.
Fixes #6528
=> Remove Zod.

src/server/cards/moon/LunaEcumenopolis.ts, src/server/cards/moon/LunarMineUrbanization.ts, src/server/cards/moon/SmallDutyRovers.ts, src/server/moon/MoonExpansion.ts, tests/cards/moon/LunaEcumenopolis.spec.ts, tests/cards/moon/SmallDutyRovers.spec.ts
Based on Discord feedback: https://discord.com/channels/737945098695999559/742826825922904225/1224417816959254680
=> Two moon tweaks

src/client/components/moon/MoonBoard.vue, src/client/components/moon/MoonSpace.vue, src/common/models/SpaceModel.ts, src/common/utils/utils.ts, src/server/boards/Board.ts, src/server/boards/SerializedBoard.ts, src/server/boards/Space.ts, src/server/cards/moon/HostileTakeover.ts, src/server/cards/moon/MoonCardManifest.ts, src/server/cards/promo/AstraMechanica.ts, src/server/models/ServerModel.ts, src/server/moon/MoonData.ts, src/server/moon/MoonExpansion.ts, src/styles/board.less, tests/cards/moon/HostileTakeover.spec.ts
=> Moon project card Hostile Takeover

src/server/routes/Game.ts
=> Make warnings when Quota is absent much less severe.

src/client/components/card/Card.vue, src/client/components/card/CardHelp.vue, src/common/cards/ICardMetadata.ts, src/locales/de/promo_cards.json, src/locales/jp/promo_cards.json, src/server/cards/base/RoboticWorkforce.ts, src/server/cards/corporation/MiningGuild.ts, src/server/cards/moon/LunaEcumenopolis.ts, src/server/cards/moon/TheArchaicFoundationInstitute.ts, src/server/cards/pathfinders/BotanicalExperience.ts, src/server/cards/prelude2/SagittaFrontierServices.ts, src/server/cards/promo/AstraMechanica.ts, src/server/cards/promo/FloydContinuum.ts, src/server/cards/promo/Philares.ts, src/server/cards/underworld/PriceWars.ts, src/styles/cards.less
1. Shows on hover
2. Smaller
3. Move out of experimental
4. Add more cards
5. Move behavior for deciding whether to include the icon to the cards themselves.
=> Updating the help icon viz & behavior

src/client/components/GameSetupDetail.vue, src/client/components/create/CreateGameForm.vue, src/common/boards/BoardName.ts, src/server/GameSetup.ts, src/server/awards/Awards.ts, src/server/boards/UtopiaPlanitiaBoard.ts, src/server/ma/MilestoneAwardSelector.ts, src/server/ma/MilestoneAwardSynergies.ts, src/server/milestones/Milestones.ts, tests/routes/Game.spec.ts
No milestones and awards at this time. If you choose this board, you get random milestones and awards unless otherwise selected.
=> Utopia Planitia Board

src/server/boards/HellasBoard.ts, src/server/boards/TharsisBoard.ts
=> Remove TWO_PLANTS. It doesn't actually help.

src/server/boards/BoardBuilder.ts, src/server/boards/Space.ts, src/server/moon/MoonBoard.ts
=> Inline method newSpace

src/server/awards/terraCimmeria/Warmonger.ts, tests/awards/terraCimmeria/Warmonger.spec.ts
=> Fix Warmonger again

src/server/cards/underworld/AeronGenomics.ts, tests/cards/underworld/AeronGenomics.spec.ts
=> Aeron Genomics is supposed to pay for its action

src/server/inputs/AndOptions.ts, src/server/inputs/InputError.ts, src/server/inputs/OrOptions.ts, src/server/inputs/SelectAmount.ts, src/server/inputs/SelectCard.ts, src/server/inputs/SelectColony.ts, src/server/inputs/SelectDelegate.ts, src/server/inputs/SelectGlobalEvent.ts, src/server/inputs/SelectInitialCards.ts, src/server/inputs/SelectOption.ts, src/server/inputs/SelectParty.ts, src/server/inputs/SelectPayment.ts, src/server/inputs/SelectPlayer.ts, src/server/inputs/SelectProductionToLose.ts, src/server/inputs/SelectProjectCardToPlay.ts, src/server/inputs/SelectResources.ts, src/server/inputs/SelectSpace.ts, src/server/inputs/ShiftAresGlobalParameters.ts, src/server/routes/PlayerInput.ts
=> Don't log user errors from player input

src/client/components/WarningsComponent.vue, src/common/cards/Warning.ts, src/server/deferredActions/RemoveAnyPlants.ts, src/server/inputs/SelectOption.ts, tests/cards/underworld/Deepnuking.spec.ts, tests/deferredActions/RemoveAnyPlants.spec.ts
=> Make it possible in the rare case to remove plants from self.

src/server/boards/AmazonisBoard.ts, src/server/boards/ArabiaTerraBoard.ts, src/server/boards/Board.ts, src/server/boards/BoardBuilder.ts, src/server/boards/ElysiumBoard.ts, src/server/boards/HellasBoard.ts, src/server/boards/MarsBoard.ts, src/server/boards/TerraCimmeriaBoard.ts, src/server/boards/TharsisBoard.ts, src/server/boards/UtopiaPlanitiaBoard.ts, src/server/boards/VastitasBorealisBoard.ts, src/server/boards/VastitasBorealisNovusBoard.ts, src/server/cards/base/NoctisCity.ts, src/server/models/ServerModel.ts, src/server/moon/MoonBoard.ts, tests/ares/EmptyBoard.ts, tests/boards/Board.spec.ts, tests/boards/BoardBuilder.spec.ts, tests/utils/shuffle.spec.ts
Board randomization was pretty broken in most cases. This fixes most of it.
=> Many incremental PRs for cleaning up board specification and randomization

src/common/cards/CardName.ts, src/server/cards/promo/CityPark.ts, src/server/cards/promo/PromoCardManifest.ts, tests/cards/promo/CityPark.spec.ts
=> 2024 promo City Park

src/client/components/create/CreateGameForm.vue
Fixes #6577 while waiting for #6586 to be finished.
=> Temporarily disable the included cards feature from the UI.

src/locales/it/start_screen.json, src/locales/it/ui.json
Added most missing translations to Italian in start screen and game setup screen
=> Italian translations for start and game setup screens

src/server/boards/BoardBuilder.ts, tests/boards/BoardBuilder.spec.ts
=> Don't shuffle bonuses on restricted spaces.

src/server/cards/pathfinders/SecretLabs.ts, tests/cards/pathfinders/SecretLabs.spec.ts
=> Make Secret Labs compatible with Whales

tests/boards/HellasBoard.spec.ts
=> Add test verifying that bug #931 is still a valid issue

src/client/components/create/CreateGameForm.vue
Reverts terraforming-mars/terraforming-mars#6588
#6586 looks pretty good and I think it's good to restore the feature.
=> Revert "Temporarily disable the included cards feature from the UI."

src/server/colonies/Colony.ts, tests/colonies/Pluto.spec.ts
=> Make Pluto compatible with Research Colony and Space Port Colony.

src/client/components/CardListSearchIndex.ts, src/client/components/DebugUI.vue
Each fix is in its own commit.
=> Move card list index searching to its own file, fix some bugs

src/client/components/card/CardContent.vue, src/client/components/card/CardVictoryPoints.vue, src/common/cards/render/ICardRenderDynamicVictoryPoints.ts, src/locales/bg/preludes.json, src/locales/br/prelude.json, src/locales/cn/preludes.json, src/locales/de/prelude.json, src/locales/es/prelude.json, src/locales/fr/prelude_cards.json, src/locales/hu/prelude.json, src/locales/it/preludes.json, src/locales/jp/prelude.json, src/locales/ko/prelude.json, src/locales/nb/prelude.json, src/locales/pl/prelude.json, src/locales/ru/preludes.json, src/server/cards/base/CommercialDistrict.ts, src/server/cards/prelude/EcologyExperts.ts, src/server/cards/render/CardRenderDynamicVictoryPoints.ts
=> Fix card renderings

src/server/IPlayer.ts, src/server/Player.ts, src/server/behavior/Executor.ts, src/server/cards/CardSerialization.ts, src/server/cards/promo/SelfReplicatingRobots.ts, src/server/deferredActions/AddResourcesToCard.ts, src/server/models/ServerModel.ts, tests/Player.spec.ts, tests/cards/base/CEOsFavoriteProject.spec.ts, tests/cards/pathfinders/CommunicationCenter.spec.ts
Good observation by @EthanDobbs. This just slices off a piece of the larger change Ethan implemented.
=> Remove robot card interface

src/server/cards/pathfinders/NewVenice.ts, src/server/cards/pathfinders/Wetlands.ts, src/server/moon/MoonExpansion.ts, tests/cards/pathfinders/NewVenice.spec.ts, tests/cards/pathfinders/Wetlands.spec.ts
=> Made New Venice compatible with Martian Lumber Corp

src/server/turmoil/Turmoil.ts, tests/cards/starwars/BeholdTheEmperor.spec.ts
=> Fix BeholdTheEmperor granting extra delegate

src/common/cards/CardName.ts, src/server/cards/prelude/PreludeCard.ts, src/server/cards/prelude2/CloudTourism.ts, src/server/cards/prelude2/CorridorsOfPower.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/SpaceCorridors.ts, src/server/player/Tags.ts, src/server/turmoil/parties/Party.ts, tests/cards/prelude2/CloudTourism.spec.ts, tests/cards/prelude2/CorridorsOfPower.spec.ts, tests/cards/prelude2/SpaceCorridors.spec.ts
Source: https://boardgamegeek.com/thread/3151170/coherent-summary-of-all-new-cards-weve-learned-abo
=> Three Prelude2 cards

src/common/cards/CardName.ts, src/server/behavior/Countable.ts, src/server/cards/prelude2/GhgShipment.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/SponsoringNation.ts, src/server/cards/venusNext/floaterCards.ts, tests/cards/pathfinders/LobbyHalls.spec.ts, tests/cards/prelude2/GhgShipment.spec.ts, tests/cards/prelude2/SponsoringNation.spec.ts, tests/turmoil/TurmoilTestHelper.ts
Share test code from Lobby Halls
=> Add 2 Prelude 2 cards.

src/server/Player.ts, src/server/cards/Card.ts, src/server/cards/base/IndustrialCenter.ts, src/server/cards/prelude2/AtmosphericEnhancers.ts, tests/cards/prelude2/AtmostphericEnhancers.spec.ts
=> Fix Atmospheric Enhancers, Make bespokeCanPlay's canAffordOptions non-optional.

src/server/cards/prelude2/CorridorsOfPower.ts
=> Update Corridors of Power viz

src/client/components/OtherPlayer.vue, src/client/components/PlayerHome.vue, src/locales/bg/ui.json, src/locales/br/UI.json, src/locales/br/promo.json, src/locales/de/ui.json, src/locales/fr/ui.json, src/locales/hu/UI.json, src/locales/hu/promo.json, src/locales/hu/promo_cards.json, src/locales/jp/UI.json, src/locales/ko/UI.json, src/locales/nb/ui.json, src/locales/ru/ui.json, src/server/cards/promo/SelfReplicatingRobots.ts, src/server/deferredActions/AddResourcesToCard.ts
This was lost when consolidating the SRR behavior with regular behavior.
Fixes #6633
=> Restore the more expressive message when adding resources to a card.

src/server/models/ModelUtils.ts
=> Show SRR resource counts when offering to play an SRR card.

src/common/cards/CardName.ts, src/locales/cn/moon_cards.json, src/locales/de/moon_cards.json, src/locales/jp/moon_cards.json, src/locales/ko/moon_cards.json, src/locales/nb/moon_cards.json, src/locales/nl/moon_cards.json, src/locales/pl/moon_cards.json, src/server/cards/moon/MoonCardManifest.ts, src/server/cards/moon/NewColonyPlanningInitiatives.ts, src/server/cards/moon/SinusIrdiumRoadNetwork.ts, src/server/createCard.ts, tests/cards/moon/NewColonyPlanningInitiatives.spec.ts, tests/cards/moon/SinusIrdiumRoadNetwork.spec.ts
https://discord.com/channels/737945098695999559/742826825922904225/1235057159696285717
=> Fix typos in two card names

src/common/utils/utils.ts, src/server/Player.ts, tests/cards/community/Leavitt.spec.ts
=> Fix regression with Self-Replicating Robots + Leavitt

src/client/components/CardListSearchIndex.ts, src/client/components/card/CardRenderItemComponent.vue, src/client/components/card/CardRenderSymbolComponent.vue, src/common/cards/render/Types.ts, src/server/cards/base/AquiferPumping.ts, src/server/cards/base/WaterImportFromEuropa.ts, src/server/cards/pathfinders/LastResortIngenuity.ts, src/server/cards/pathfinders/PrefabricationofHumanHabitats.ts, src/server/cards/prelude2/SagittaFrontierServices.ts, src/server/cards/promo/DirectedImpactors.ts, src/server/cards/promo/IcyImpactors.ts, src/server/cards/promo/NeptunianPowerConsultants.ts, src/server/cards/promo/StJosephOfCupertinoMission.ts, src/server/cards/render/CardRenderItem.ts, src/server/cards/render/CardRenderSymbol.ts, src/server/cards/render/CardRenderer.ts, src/server/cards/underworld/ExcavateStandardProject.ts, src/server/cards/underworld/GaiaCity.ts, src/server/cards/underworld/ManMadeVolcano.ts, src/server/cards/venusNext/RotatorImpacts.ts, src/styles/cards_v2.less
=> Add superscript, fix Sagitta.

README.md
Hello 👋
Congrats for your work here!
Install is quite easy and I’ve managed to make a package for [Yunohost](https://yunohost.org/) (a debian based OS that aims to simplifying self-hosting).
Feel free to merge this if you find it useful.
We have an "automatic updater" which makes a PR to the package once a day if a commit has been made upstream, so the package stays relatively well updated.
=> Add Yunohost to the list of possible installations

src/server/boards/VastitasBorealisBoard.ts, src/server/boards/VastitasBorealisNovusBoard.ts, tests/boards/VastitasBorealisNovusBoard.spec.ts
=> Fix Vastitas Borealis temperature costs

src/common/cards/CardName.ts, src/server/cards/promo/PromoCardManifest.ts, src/server/cards/promo/Supermarkets.ts, tests/cards/promo/Supermarkets.spec.ts
=> New Promo card Supermarkets

src/client/components/WaitingFor.vue, src/common/app/paths.ts, src/common/models/PlayerModel.ts, src/server/IPlayer.ts, src/server/Player.ts, src/server/SerializedPlayer.ts, src/server/models/ServerModel.ts, src/server/routes/Autopass.ts, src/server/routes/PlayerInput.ts, src/server/server/requestProcessor.ts, tests/Player.spec.ts, tests/routes/Autopass.spec.ts
Autopass is only available when you are taking actions because of how autopass is stored. It's connected with when the player takes actions, and is saved along with the rest of the game. This means that if you are waiting for someone else to take actions, you can't change your autopass setting.
If there was another database table that stored autopass and other settings, this could be changed to be available at all times.
=> First implementation of autopass

src/server/Draft.ts, tests/drafting.spec.ts
=> Fix draft ordering. Add test for 3-player draft

src/client/components/card/CardCorporationLogo.vue, src/common/cards/CardName.ts, src/common/cards/render/AltSecondaryTag.ts, src/server/ares/AresHandler.ts, src/server/boards/Board.ts, src/server/cards/ceos/Caesar.ts, src/server/cards/community/Athena.ts, src/server/cards/community/CommunityCardManifest.ts, src/server/cards/community/Eris.ts, src/server/deferredActions/PlaceHazardTile.ts, src/styles/cards_v2.less, tests/cards/community/Athena.spec.ts, tests/cards/community/Eris.spec.ts
=> Community Ares corps h/t tfm-community

src/client/components/card/CardRenderItemComponent.vue
=> Fix tag rendering on cards.

src/server/ares/AresHandler.ts, src/server/cards/ares/EcologicalSurvey.ts, src/server/cards/ares/GeologicalSurvey.ts, src/server/cards/ares/SurveyCard.ts, src/server/cards/corporation/MiningGuild.ts, tests/cards/corporation/MiningGuild.spec.ts
=> Make Mining Guild compatible with Ares.

src/server/cards/ceos/Neil.ts, tests/cards/ceo/Neil.spec.ts
=> Make Neil work when any player plays a moon card

src/common/inputs/InputResponse.ts, src/server/inputs/AndOptions.ts, src/server/inputs/SelectInitialCards.ts, tests/cards/promo/Splice.spec.ts, tests/inputs/SelectInitialCards.spec.ts
That's what happens when you subclass a player input
=> Select Initial Cards isn't storing the type correctly.

src/client/components/SelectInitialCards.vue, tests/client/components/SelectInitialCards.spec.ts
Updated the front end to send the right object type.
=> Fixes #6755 by returning correct object in initial card selection client side

src/server/cards/underworld/RecklessDetonation.ts
=> Make Reckless Detonation effects blockable.

src/common/cards/CardMetadata.ts, src/server/cards/prelude/LavaTubeSettlement.ts, src/server/cards/prelude/SelfSufficientSettlement.ts, tests/TestingUtils.ts, tests/cards/ares/GeologicalSurvey.spec.ts, tests/cards/ares/LavaFlowsAres.spec.ts, tests/cards/base/LavaFlows.spec.ts, tests/cards/base/RoboticWorkforce.spec.ts, tests/cards/prelude/LavaTubeSettlement.spec.ts, tests/cards/prelude/SelfSufficientSettlement.spec.ts
Plus it makes Lava Tube Settlement compatible with Utopia Planitia
=> several fixes and cleanups

src/server/Player.ts, tests/cards/promo/Merger.spec.ts
=> All corp first action comprise one action.

src/server/boards/TerraCimmeriaNovusBoard.ts
=> Update volcanic spaces for Terra Cimmeria Novus

src/client/components/card/CardRenderItemComponent.vue
=> Fix rendering resource cubes on cards

src/server/Game.ts
=> Remove duplicate eviction and maintenance code.

src/server/cards/underworld/PublicSpaceline.ts, tests/cards/underworld/PublicSpaceline.spec.ts
=> Fix Public Spaceline, completely missing MC production

src/server/behavior/Behavior.ts, src/server/behavior/Executor.ts, src/server/cards/underworld/GreyMarketExploitation.ts, src/server/cards/underworld/UndergroundSmugglingRing.ts, tests/behavior/Executor.spec.ts, tests/cards/prelude2/FocusedOrganization.spec.ts
Slightly modifies FocusedOrganization.
=> Rewrite standardResource behavior (default is same)

src/client/components/LogPanel.vue, src/common/models/ColonyModel.ts, src/server/SerializedGame.ts, src/server/cards/StandardProjectCard.ts, src/server/cards/ceos/CoLeadership.ts, src/server/cards/ceos/Lowell.ts, src/server/deferredActions/DrawCeoCardFromDeck.ts, tests/cards/ceo/CoLeadership.spec.ts, tests/cards/ceo/Lowell.spec.ts, tests/cards/ceo/Stefan.spec.ts, tests/cards/ceo/Will.spec.ts, tests/deferredActions/DrawCeoCardFromDeck.spec.ts
This actually does a meaningful bit of work centralizing CoLeadership and Lowell, too. And adds tests, even though it's a bit on the outside since all CEOs are currently playable.
=> Remove TODOs

src/server/cards/community/Playwrights.ts
=> Show discounts on cards when using the Playwrights action.

src/client/components/LanguageSelectionDialog.vue, src/client/components/WaitingFor.vue, src/common/models/WaitingForModel.ts, src/server/routes/ApiWaitingFor.ts, tests/routes/ApiWaitingFor.spec.ts
=> When waiting for other players, show which player you're waiting for.

tests/TestingUtils.ts, tests/behavior/Executor.spec.ts, tests/deferredActions/DrawCards.spec.ts, tests/deferredActions/DrawCeoCardFromDeck.spec.ts, tests/player/Stock.spec.ts, tests/utils/log-the-log.ts
This provides the name (if the message whispered to one player)
Also converted the two formatLogMessage functions into one.
=> Improved log message formatting in tests.

src/server/cards/colonies/BuildColonyStandardProject.ts, src/server/player/Colonies.ts, tests/cards/community/Venus.spec.ts, tests/colonies/Colony.spec.ts, tests/colonies/Europa.spec.ts
This validates reds costs for any case where a player wants to build a colony and not just the standard project.
=> Improve reds compatibility with colonies Venus and Europa.

src/server/player/Colonies.ts, tests/cards/promo/PharmacyUnion.spec.ts
=> Make Pharmacy Union Compatible with Reds + Leavitt Colony

src/client/components/card/CardResourceCounter.vue, src/common/CardResource.ts, src/server/cards/prelude2/ActivePreludeCard.ts, src/server/cards/prelude2/BoardOfDirectors.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/preludes/PreludesExpansion.ts, src/styles/cards_v2.less, tests/cards/prelude2/BoardOfDirectors.spec.ts
=> Board of Directors

src/server/cards/pathfinders/PathfindersCardManifest.ts, src/server/cards/promo/PromoCardManifest.ts, src/server/cards/promo/StrategicBasePlanning.ts, tests/cards/promo/StrategicBasePlanning.spec.ts
There's no strong reason for two.
=> Move Strategic Base Planning to promo, and update.

src/server/Draft.ts, src/server/createCard.ts, src/server/database/GameLoader.ts, tests/drafting.spec.ts, tests/drafting2.spec.ts
=> Fix deserialization behavior part way through a draft round

src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/VenusOrbitalSurvey.ts, tests/cards/prelude2/VenusOrbitalSurvey.spec.ts
Not sure whether the chosen bought cards should be known (if one of two non-venus cards is bought). For now I left it unknown because it was easier this way.
=> [Prelude 2]: VenusOrbitalSurvey

src/server/cards/prelude2/PlanetaryAlliance.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, tests/cards/prelude2/PlanetaryAlliance.spec.ts
=> [Prelude 2]: Planetary Alliance

src/client/components/WarningsComponent.vue, src/common/cards/Warning.ts, src/server/cards/prelude2/BoardOfDirectors.ts
=> Add warnings and logging when someone cannot act on Board of Directors

src/server/cards/prelude2/VenusOrbitalSurvey.ts
=> Improve VenusOrbitalSurvey text size

src/server/cards/prelude2/MainBeltAsteroids.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, tests/cards/prelude2/MainBeltAsteroids.spec.ts
=> [Prelude 2]: MainBeltAsteroids

src/server/boards/MarsBoard.ts, src/server/boards/PlacementType.ts, src/server/cards/promo/DeimosDownPromo.ts, tests/cards/promo/DeimosDownPromo.spec.ts
=> Make Deimos Down Promo compatible with Kingdom of Tauraro

src/server/cards/prelude2/UnexpectedApplication.ts, tests/cards/prelude2/UnexpectedApplication.spec.ts
=> Can't play Unexpected Application when it's the only card in hand.

src/server/Player.ts, src/server/cards/ceos/CoLeadership.ts, tests/cards/ceo/CoLeadership.spec.ts, tests/cards/ceo/Gaia.spec.ts, tests/cards/ceo/Stefan.spec.ts, tests/cards/ceo/Xavier.spec.ts, tests/cards/promo/Merger.spec.ts, tests/turmoil/parties/Reds.spec.ts
This makes it compatible with Prelude 2, specifically Board of Directors.
=> Make Co-leadership playable during the Action Phase.

src/server/Draft.ts, tests/drafting2.spec.ts
=> Fix drafting regression during server restore.

src/server/cards/prelude2/EarlyColonization.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/SoilBacteria.ts, src/server/cards/prelude2/VenusL1Shade.ts, tests/cards/prelude2/EarlyColonization.spec.ts, tests/cards/prelude2/SoilBacteria.spec.ts, tests/cards/prelude2/VenusL1Shade.spec.ts
[Prelude 2] Soil Bacteria
[Prelude 2] Early Colonization
[Prelude 2] Venys L1 Shade
=> [Prelude 2] - 3 new cards

src/server/moon/LunarMagnate.ts, tests/moon/LunarMagnate.spec.ts
=> Make Lunar Magnate compatible with Hostile Takeover

src/server/cards/prelude2/SoilBacteria.ts, tests/cards/prelude2/SoilBacteria.spec.ts
Update SoilBacteria.ts to give 3 plants initlaly instead of 4 and then 1 plant from own tag
Update SoilBacteria.spec.ts to check for 3 and 4 plants
=> [Prelude 2] Soil Bacteria fix

src/server/cards/prelude2/HighCircles.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/RiseToPower.ts, tests/cards/prelude2/HighCircles.spec.ts, tests/cards/prelude2/RiseToPower.spec.ts
[Prelude 2] Rise To Power
[Prelude 2] High Circles
=> [Prelude 2] Rise To Power and High Circles

src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/WGProject.ts, tests/cards/prelude2/WGProject.spec.ts
=> [Prelude 2] WG Project

src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/VenusTradeHub.ts, src/server/colonies/Colony.ts, src/server/colonies/IColonyTrader.ts, tests/cards/prelude2/VenusTradeHub.spec.ts
=> Prelude Venus Trade Hub

src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/Recession.ts, src/server/cards/prelude2/VenusTradeHub.ts, tests/cards/prelude2/Recession.spec.ts
=> Prelude 2 card Recession

src/server/Game.ts, src/server/IPlayer.ts, src/server/Player.ts, src/server/SerializedPlayer.ts, src/server/behavior/Executor.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/PreservationProgram.ts, src/server/cards/render/CardRenderItem.ts, src/server/turmoil/TurmoilHandler.ts, tests/Player.spec.ts, tests/cards/prelude2/PreservationProgram.spec.ts
=> Prelude2 Prelude Preservation Program

src/server/Player.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/TerraformingDeal.ts, tests/cards/prelude2/TerraformingDeal.spec.ts
=> Prelude 2 Prelude Terraforming Deal

src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/VenusAllies.ts, tests/cards/prelude2/VenusAllies.spec.ts
=> [Prelude 2] Venus allies

src/server/Game.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/VenusContract.ts, tests/cards/prelude2/VenusContract.spec.ts
=> Prelude 2 prelude Venus Contract

src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/SuitableInfrastructure.ts, tests/cards/prelude2/SuitableInfrastructure.spec.ts
=> Prelude 2 Prelude Suitable Infrastructure

src/server/Game.ts, src/server/IGame.ts, src/server/cards/prelude2/FrontierTown.ts, src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/promo/MarsNomads.ts, src/server/cards/underworld/GaiaCity.ts, tests/cards/prelude2/FrontierTown.spec.ts
=> Prelude 2 prelude Frontier Town

src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/VenusShuttles.ts, src/server/cards/venusNext/floaterCards.ts, tests/cards/prelude2/VenusShuttles.spec.ts
=> [Prelude 2] Venus Shuttles

src/server/cards/prelude2/Prelude2CardManifest.ts, src/server/cards/prelude2/ProjectEden.ts, src/server/deferredActions/PlaceGreeneryTile.ts, tests/assertions.ts, tests/cards/prelude2/ProjectEden.spec.ts
=> Prelude 2 card Project Eden

src/locales/pl/log_messages.json, src/locales/pl/pathfinder_cards.json, src/locales/pl/pathfinder_preludes.json, src/locales/pl/prelude.json, src/locales/pl/prelude_cards.json, src/locales/pl/prelude_corporations.json, src/locales/pl/promo_cards.json, src/locales/pl/promo_corporations.json
- Fix broken translations in Pathfinder expansion
- Add missing translations for Prelude 2 and Promo Cards expansions
- Some small adjustments and fixes of PL translation
As always - tested on my local instance and it was working fine.
=> More Polish Translations

src/client/components/GameSetupDetail.vue, src/locales/bg/ui.json, src/locales/de/ui.json, src/locales/es/UI.json, src/locales/fr/ui.json, src/locales/hu/UI.json, src/locales/jp/UI.json, src/locales/ko/UI.json, src/locales/nb/ui.json, src/locales/nl/ui.json, src/locales/pl/ui.json, src/locales/ru/ui.json, src/locales/ua/ui.json
I can't fix the Japanese or Korean translations. Too tricky.
@nasubi-land and @derornos can you help?
=> Correct language in setup detail / seconds per action.

src/server/cards/underworld/PatentManipulation.ts, tests/cards/underworld/PatentManipulation.spec.ts
=> Fix Patent Manipulation - remove resources from the card before putting it back into the hand.

src/common/underworld/UndergroundResourceToken.ts
=> Fix underworld logging message.

src/server/Game.ts, src/server/PlayerInput.ts, tests/Game.spec.ts, tests/turmoil/Turmoil.spec.ts
Reverts terraforming-mars/terraforming-mars#6921
=> Revert "Reduce use of setWaitingFor"

src/client/components/WaitingFor.vue, src/locales/de/ui.json, src/locales/fr/ui.json, src/locales/jp/UI.json, src/locales/ko/UI.json
Hi,
Here is a suggestion to improve the auto pass message. Based on what I've seen in the code, it only passes once on your next action when you perform an action with the checkbox checked.
If that's correct, I suggest this change. I was confused myself when I saw it for the first time and I kinda feared checking it, in case it just passed until the end of the game.
If I'm wrong about this feature then I apologize.
=> Update auto pass message

src/client/components/WaitingFor.vue, src/locales/de/ui.json, src/locales/fr/ui.json, src/locales/jp/UI.json, src/locales/ko/UI.json
Hi, after testing the auto pass I realised this was actually immediate, and not waiting for our next action to pass.
Here is a suggestion to udpate (again, sorry) the message to make it clear it will pass immediately after doing the action.
=> Improve auto pass message again

src/server/cards/moon/RoadPiracy.ts
=> Don't ask players to block Road Piracy when unnecessary.

src/locales/pl/base_cards.json, src/locales/pl/colonies.json, src/locales/pl/colonies_cards.json, src/locales/pl/promo_cards.json, src/locales/pl/venusnext_cards.json
fix: few inaccurate translations
chore: remove duplicate translations
fix: small fixes in the PL translations
Tested locally
=> Fixes for Polish translations

src/server/cards/moon/LunarMineUrbanization.ts, tests/cards/moon/LunarMineUrbanization.spec.ts
=> Make Lunar Mine Urbanization compatible with Hostile Takeover

src/server/database/PostgreSQL.ts, tests/integration/PostgreSQL.md, tests/integration/PostgreSQL.spec.ts
This should drop database sizes pretty quickly. Estimated drop in the amount of stored characters is approximately 85%. If that matches estimated database size drop, it would put us far within storage limits.
=> Remove everything but the last 10 rows in PostgreSQL.

src/common/cards/CardName.ts, src/server/cards/promo/Casinos.ts, src/server/cards/promo/PromoCardManifest.ts, tests/cards/promo/Casinos.spec.ts
=> Add Promo card Casinos

package-lock.json, src/server/cards/promo/NeptunianPowerConsultants.ts, tests/cards/promo/NeptunianPowerConsultants.spec.ts
Fixes https://github.com/terraforming-mars/terraforming-mars/issues/6996
=> Fix priority order for Neptunian Power Consultants.

src/server/turmoil/Turmoil.ts
=> Add log message indicating that all players lose TR during turmoil phase

src/server/cards/promo/MarsNomads.ts, tests/cards/promo/MarsNomads.spec.ts
=> Make Mars Nomads' movement compatible with Land Claim and Arcadian Communities.

src/client/components/create/CardsFilter.vue, src/client/components/create/CreateGameForm.vue
=> Fix text box hint when including cards in a game.

src/client/components/create/CreateGameForm.vue, src/client/components/create/PreludesFilter.vue
=> Make Prelude2 selection work with prelude filter.

src/server/Game.ts, src/server/IGame.ts, tests/Game.spec.ts, tests/turmoil/Turmoil.spec.ts
=> Resolve WGT effects before finishing the generation.

src/server/cards/ceos/Gordon.ts
=> Make CEO Gordon compatible with Ocean City.

src/client/components/WaitingFor.vue
=> Show 'black' player's icon in waitingfor

src/client/components/PlayerHome.vue, src/common/cards/ClientCard.ts, src/server/tools/export_card_rendering.ts
=> Show active preludes in the active card area.

src/server/IGame.ts, src/server/IPlayer.ts, src/server/Player.ts, src/server/deferredActions/RemoveAnyPlants.ts, tests/cards/promo/MonsInsurance.spec.ts
=> Ask if Solo Mons Insurance owner wants to remove plants.

src/server/IPlayer.ts, src/server/Player.ts, src/server/awards/terraCimmeria/Urbanist.ts, src/server/cards/base/Moss.ts, src/server/cards/base/NitrophilicMoss.ts, src/server/cards/base/Sabotage.ts, src/server/cards/base/Virus.ts, src/server/cards/base/standardProjects/CityStandardProject.ts, src/server/cards/colonies/TitanFloatingLaunchPad.ts, src/server/cards/community/Playwrights.ts, src/server/cards/moon/DarksideSmugglersUnion.ts, src/server/cards/moon/MoonHabitatStandardProject.ts, src/server/cards/moon/MoonMineStandardProject.ts, src/server/cards/moon/MoonRoadStandardProject.ts, src/server/cards/promo/CometAiming.ts, src/server/cards/promo/Potatoes.ts, src/server/cards/requirements/CardRequirements.ts, src/server/deferredActions/PlaceOceanTile.ts, src/server/underworld/UnderworldExpansion.ts, tests/cards/promo/CometAiming.spec.ts, tests/cards/underworld/CorporateTheft.spec.ts
This also makes Comet Aiming compatible with Whales, so, Fixes https://github.com/terraforming-mars/terraforming-mars/issues/7024
=> Allow Comet Aiming to take an action when oceans are at maximum.

src/server/behavior/Executor.ts, src/server/boards/MarsBoard.ts, src/server/deferredActions/PlaceGreeneryTile.ts, tests/cards/pathfinders/RedCity.spec.ts
=> Make Mangrove compatible with Red City.

src/client/components/SelectCard.vue, src/server/cards/prelude2/BoardOfDirectors.ts
=> Warn when you can't play Board of Directors prelude.

src/locales/de/ceo_cards.json, src/locales/de/prelude_corporations.json, src/locales/jp/ceo_cards.json, src/locales/jp/prelude_corporations.json, src/locales/ko/ceo_cards.json, src/locales/ko/prelude_corporations.json, src/locales/nb/ceo_cards.json, src/locales/pl/prelude_corporations.json, src/locales/ua/ceo_cards.json, src/locales/ua/prelude_corporations.json, src/server/cards/ceos/Asimov.ts, src/server/cards/ceos/Gordon.ts, src/server/cards/ceos/Naomi.ts, src/server/cards/ceos/Neil.ts, src/server/cards/ceos/Oscar.ts, src/server/cards/ceos/VanAllen.ts, src/server/cards/ceos/Xu.ts, src/server/cards/ceos/Zan.ts, src/server/cards/prelude2/NirgalEnterprises.ts
=> Card text cleanup

src/client/components/WaitingFor.vue
=> Fix regression from #7021

src/server/cards/pathfinders/PathfindersCardManifest.ts
=> Temporarily disable Mars Frontier Alliance.

src/server/cards/prelude2/BoardOfDirectors.ts
=> Have Board of Directors privately inform player which prelude they are drawing and discarding.

src/server/cards/pathfinders/MarsFrontierAlliance.ts, src/server/cards/pathfinders/PathfindersCardManifest.ts
=> Re-enable Mars Frontier Alliance

src/client/components/PlayerHome.vue, src/client/components/SelectInitialCards.vue, src/client/components/SpectatorHome.vue, src/client/components/colonies/Colony.vue, src/styles/player_home.less
=> Make inactive colonies easier to see.

src/styles/players_overview.less
=> Fix viz when merger is in play

src/server/cards/prelude2/SuitableInfrastructure.ts, tests/cards/prelude2/SuitableInfrastructure.spec.ts
=> Don't invoke Suitable Infrastructure for reducing production.

src/server/cards/prelude2/ProjectEden.ts, tests/cards/prelude2/ProjectEden.spec.ts
=> Don't ask to place ocean for Project Eden when oceans are at max.

src/client/components/colonies/Colony.vue
It breaks the colony selection viz.
=> Roll back the inactive view, for now.

src/server/cards/underworld/EarthquakeMachine.ts, src/server/cards/underworld/UndergroundSettlement.ts, src/server/underworld/ExcavateSpacesDeferred.ts, src/server/underworld/UnderworldExpansion.ts, tests/cards/underworld/ServerSabotage.spec.ts, tests/cards/underworld/UndergroundSettlement.spec.ts, tests/underworld/underworldAssertions.ts
Fixes https://github.com/terraforming-mars/terraforming-mars/issues/7073
=> Fix outlier case for Underground Settlement.

src/server/cards/base/Sabotage.ts
=> Make Sabotage compatible with Underworld

src/locales/de/underworld_cards.json, src/locales/jp/underworld_cards.json, src/locales/ko/underworld_cards.json, src/locales/ua/underworld_cards.json, src/server/cards/underworld/GaiaCity.ts
Fixes #6854
(ref: https://boardgamegeek.com/thread/2907313/article/45289733#45289733)
=> Add additional notation to Gaia City

src/client/components/create/CreateGameForm.vue
I'm not clear how Vue 2 does subfield watching.
=> Restore watch behavior.

src/server/cards/underworld/PublicSpaceline.ts
=> Public Spacelane is not a blue card

tests/cards/prelude2/SuitableInfrastructure.spec.ts
This is in response to an [issue report](https://github.com/terraforming-mars/terraforming-mars/issues/7140) that Suitable Infrastructure's effect didn't work with Manutech.
I attempted to repro and the effect worked. Nonetheless, I thought a test would add protection for this scenario.
=> Add test to Suitable Infrastructure to ensure it's effect works with Manutech

src/server/LogHelper.ts, src/server/cards/moon/TheDarksideofTheMoonSyndicate.ts, tests/cards/moon/TheDarksideofTheMoonSyndicate.spec.ts
=> Make Darkside of The Moon Syndicate solo-friendly

src/server/cards/base/RoboticWorkforce.ts, src/server/cards/base/RoboticWorkforceBase.ts, src/server/cards/promo/CyberiaSystems.ts
Now it will just count the number of cards with building tags and production boxes, and hope there are 2. Are they playable? Can the player afford any costs? Unknown.
=> Partially adjust how Cyberia Systems works.

src/server/awards/amazonisPlanitia/Tourist.ts, src/server/cards/turmoil/RedTourismWave.ts
=> Fixes to Tourist and Red Tourism Wave

src/server/cards/venusNext/RotatorImpacts.ts, tests/cards/venusNext/RotatorImpacts.spec.ts
=> Fix bug in Rotator Impacts.

src/locales/de/underworld_cards.json, src/locales/jp/underworld_cards.json, src/locales/ua/underworld_cards.json, src/server/cards/underworld/ServerSabotage.ts
Fixes spelling error and behavior.
=> Fix Server Sabotage.

src/common/models/PlayerModel.ts, src/server/models/ServerModel.ts
I am starting to collect the player's game data at the end of the match to help determine the best handicap for my friends when we play. Can we add their handicap to the response data please? :)
Reordered a few things because alphabet.
=> Add handicap to the player view model

src/client/components/card/CardRenderItemComponent.vue, src/server/cards/ceos/CeoCardManifest.ts, src/server/cards/ceos/Huan.ts, src/server/cards/render/CardRenderer.ts, src/server/colonies/Colony.ts, src/server/player/Colonies.ts, src/styles/cards_v2.less, tests/cards/ceo/Huan.spec.ts
=> CEO Huan & Update Syndicate Pirate Raids viz.

src/common/cards/CardName.ts, src/server/cards/promo/PromoCardManifest.ts, src/server/cards/promo/ProtectedGrowth.ts
=> Promo card Protected Growth

src/server/models/ServerModel.ts
=> Show VP in solo games

src/client/components/WarningsComponent.vue, src/common/cards/Warning.ts, src/server/IPlayer.ts, src/server/cards/prelude2/L1TradeTerminal.ts, src/server/createCard.ts, tests/cards/prelude2/L1TradeTerminal.spec.ts
Add warning of no cards meet requirements.
Include self-replicating robots cards.
Better automatic card selection.
Unit test.
=> Make L1 Trade Terminal work generally better

src/server/IPlayer.ts, src/server/Player.ts, src/server/cards/colonies/TitanFloatingLaunchPad.ts, src/server/cards/moon/DarksideSmugglersUnion.ts, src/server/cards/pathfinders/Ambient.ts, src/server/cards/pathfinders/CollegiumCopernicus.ts, src/server/cards/promo/ProjectInspection.ts, src/server/cards/underworld/HecateSpeditions.ts, src/server/cards/underworld/LaborTrafficking.ts, src/server/cards/venusNext/Viron.ts, src/server/models/ServerModel.ts, tests/cards/ceo/Xavier.spec.ts, tests/cards/pathfinders/Odyssey.spec.ts, tests/cards/promo/Merger.spec.ts, tests/cards/promo/ProjectInspection.spec.ts, tests/cards/underworld/LaborTrafficking.spec.ts, tests/cards/venusNext/Viron.spec.ts
Fixes https://github.com/terraforming-mars/terraforming-mars/issues/7280
=> Visual cue that Labor Trafficking's effect was used

src/server/cards/base/Ants.ts, src/server/deferredActions/RemoveResourcesFromCard.ts
=> Log the card Ants removes from.

src/client/components/create/CreateGameForm.vue
Fixes https://github.com/terraforming-mars/terraforming-mars/issues/7295
=> Warn players about the infinite energy issue

src/client/components/WarningsComponent.vue, src/common/cards/Warning.ts, src/server/cards/promo/AstraMechanica.ts
=> Give a warning that card-returning events cannot be returned with Astra Mechanica. 

src/locales/de/promo_cards.json, src/locales/de/ui.json
=> Update promo cards

src/server/cards/underworld/AeronGenomics.ts, tests/cards/underworld/AeronGenomics.spec.ts
=> Aeron Genomics not charging 1 MC when multiple cards are selectable.

src/server/Game.ts, src/server/GameSetup.ts, src/server/Player.ts, src/server/cards/ICard.ts, src/server/cards/underworld/DemetronLabs.ts, src/server/underworld/UnderworldExpansion.ts, tests/cards/underworld/Neutrinograph.spec.ts, tests/cards/underworld/SeismicPredictions.spec.ts
Fixes https://github.com/terraforming-mars/terraforming-mars/issues/7273
=> Neutrinograph ignored when placing tiles

src/server/awards/terraCimmeria/Warmonger.ts
Adapt description to the newest change, as happened for the translations (all language) but not for description
=> Update Warmonger to match its effect. Translations already handled.

src/client/components/create/CardsFilter.vue, src/client/components/create/CreateGameForm.vue
Provide some slightly better UI and visualizations for the card filter.
=> Clean up and expand Card Filter.

src/server/cards/underworld/HecateSpeditions.ts, src/server/player/Colonies.ts, tests/cards/underworld/HecateSpeditions.spec.ts, tests/colonies/coloniesAssertions.ts
=> Update Hecate Speditions to match described behavior

src/client/components/colonies/BuildBenefit.vue, src/client/components/colonies/Colony.vue, src/client/components/colonies/ColonyRow.vue, src/client/components/colonies/ColonySpace.vue, src/common/colonies/IColonyMetadata.ts, src/server/cards/community/Hygiea.ts, src/server/cards/community/Iapetus.ts, src/server/cards/community/Leavitt.ts, src/server/cards/community/Mercury.ts, src/server/cards/community/Pallas.ts, src/server/cards/community/Titania.ts, src/server/cards/community/Venus.ts, src/server/cards/pathfinders/IapetusII.ts, src/server/cards/pathfinders/LeavittII.ts, src/server/colonies/Callisto.ts, src/server/colonies/Ceres.ts, src/server/colonies/Deimos.ts, src/server/colonies/Enceladus.ts, src/server/colonies/Europa.ts, src/server/colonies/Ganymede.ts, src/server/colonies/Io.ts, src/server/colonies/Luna.ts, src/server/colonies/Miranda.ts, src/server/colonies/Pluto.ts, src/server/colonies/Titan.ts, src/server/colonies/Triton.ts, src/styles/board.less, src/styles/colonies.less, tests/cards/pathfinders/CoordinatedRaid.spec.ts
Removes a lot of unnecessary fiddling and lines up all the rows.
Fixes #7141
Fixes #6796
=> Restructure colony rendering.

src/client/components/create/CardsFilter.vue
=> Fix card filter bug. Good opportunity for a test

src/client/components/moon/MoonSpace.vue
Including the coowned space from Hostile Takeover
=> Add symbol overlay to moon spaces.

src/server/cards/moon/IntragenSanctuaryHeadquarters.ts, tests/cards/moon/IntragenSanctuaryHeadquarters.spec.ts
=> compat. fix. w Intragen Sanctuary HQ + Meat Industry

src/server/cards/prelude2/FloatingTradeHub.ts
=> Fix Action arrow rendering in Floating Trade Hubs card

src/locales/fr/ares_cards.json
Advance french ares cards on behalf of @ramdog
=> Update ares_cards french

src/locales/de/base_cards.json, src/locales/de/prelude_cards.json
correct a recent change (add missing verb)
=> Addendum to prelude2_card L1 terminal

src/locales/de/underworld_cards.json, src/locales/fr/underworld_cards.json, src/locales/hu/underworld_cards.json, src/locales/jp/underworld_cards.json, src/locales/ko/underworld_cards.json, src/locales/ua/underworld_cards.json, src/server/Game.ts, src/server/IGame.ts, src/server/Player.ts, src/server/cards/ICard.ts, src/server/cards/underworld/LaborTrafficking.ts, src/server/cards/underworld/SearchforLifeUnderground.ts, src/server/cards/underworld/StandardTechnology.ts, src/server/cards/underworld/UnderworldCardManifest.ts, src/server/underworld/UnderworldExpansion.ts, tests/cards/ceo/Xavier.spec.ts, tests/cards/underworld/StandardTechnology.spec.ts
=> Restore Underworld Standard Technology

src/server/IPlayer.ts, src/server/Player.ts, src/server/SerializedPlayer.ts, src/server/cards/StandardProjectCard.ts, src/server/cards/base/standardProjects/CityStandardProject.ts, src/server/cards/base/standardProjects/PowerPlantStandardProject.ts, src/server/cards/colonies/BuildColonyStandardProject.ts, src/server/cards/corporation/Thorgate.ts, src/server/cards/moon/MoonHabitatStandardProject.ts, src/server/cards/moon/MoonMineStandardProject.ts, src/server/cards/moon/MoonRoadStandardProject.ts, src/server/cards/moon/MooncrateBlockFactory.ts, src/server/cards/pathfinders/AdhaiHighOrbitConstructions.ts, src/server/cards/pathfinders/HighTempSuperconductors.ts, src/server/cards/pathfinders/PrefabricationofHumanHabitats.ts, src/server/cards/underworld/LaborTrafficking.ts, src/server/cards/underworld/StandardTechnology.ts, tests/Player.spec.ts, tests/cards/corporation/Thorgate.spec.ts, tests/cards/pathfinders/PrefabricationofHumanHabitats.spec.ts, tests/cards/underworld/LaborTrafficking.spec.ts, tests/cards/underworld/StandardTechnology.spec.ts
Standard Technology works when standard technology projects are played before the card is played.
=> Fix Standard Technology Underworld

src/server/cards/pathfinders/AdhaiHighOrbitConstructions.ts, src/server/cards/pathfinders/Ambient.ts, src/server/cards/pathfinders/CollegiumCopernicus.ts, src/server/cards/pathfinders/MicrobiologyPatents.ts, src/server/cards/pathfinders/MindSetMars.ts, src/server/cards/pathfinders/Ringcom.ts, src/server/cards/pathfinders/RobinHaulings.ts, src/server/cards/pathfinders/SpaceRelay.ts
ref: https://discord.com/channels/737945098695999559/742721510376210583/1378412326864162857
=> Add asterisks on cards with special tag behvaior.

src/server/database/GameLoader.ts
=> Fix condition to take GAME_CACHE's sweep_freq into account when it is set

src/client/components/card/CardVictoryPoints.vue
=> Update Vermin viz

src/client/components/card/Card.vue, src/client/components/card/CardContent.vue, src/client/components/card/CardExpansion.vue, src/styles/cards_v2.less
This requires moving some of the card CSS out some of the class heirarchy. It generally looks OK but there may still be issues.
=> Take VP out of the scroll.

src/server/cards/pathfinders/PublicSponsoredGrant.ts, tests/cards/pathfinders/PublicSponsoredGrant.spec.ts
All players lose 2MC.
Don't show crime tag unless there are crime tags.
=> Update Public Sponsored Grants.

src/server/Player.ts, src/server/deferredActions/ChooseCards.ts, tests/Player.spec.ts
=> Underworld 2 feature: discard corruption to exchange 2 research cards.

src/server/Player.ts
I am being completely serious. The warning for playing a microbe tag appears when the card is disabled
=> This issue appeared to me in a dream

src/locales/de/log_messages.json, src/locales/fr/log_messages.json, src/locales/hu/log_messages.json, src/locales/jp/log_messages.json, src/locales/ko/log_messages.json, src/locales/ua/log_messages.json, src/server/Game.ts, src/server/IGame.ts, src/server/Player.ts, src/server/cards/colonies/Aridor.ts, src/server/cards/prelude2/SuitableInfrastructure.ts, src/server/cards/underworld/DemetronLabs.ts, src/server/cards/underworld/MiningMarketInsider.ts, tests/cards/prelude2/SuitableInfrastructure.spec.ts, tests/cards/promo/HeadStart.spec.ts
=> Fix Suitable Infrastructure a little

src/server/cards/community/AerospaceMission.ts, src/server/cards/moon/MiningComplex.ts, src/server/cards/prelude/AquiferTurbines.ts, src/server/cards/prelude/BusinessEmpire.ts, src/server/cards/prelude/GalileanMining.ts, src/server/cards/prelude/HugeAsteroid.ts, src/server/cards/prelude2/IndustrialComplex.ts, src/server/cards/prelude2/MainBeltAsteroids.ts, src/server/cards/promo/StrategicBasePlanning.ts, src/server/cards/underworld/Prospecting.ts, tests/cards/ceo/Prospecting.spec.ts, tests/cards/moon/MiningComplex.spec.ts, tests/cards/promo/StrategicBasePlanning.spec.ts
They now all invoke Sol Bank and will warn if there's not enough money.
=> Fix all preludes that require you to give up money.

src/server/underworld/UnderworldExpansion.ts
Fixes bug report from Discord: https://discord.com/channels/737945098695999559/1157191624045117551/1393271595690098771
=> Don't allow identifying spaces if the tile has an excavator.

src/server/cards/pathfinders/CommunicationCenter.ts, tests/cards/pathfinders/CommunicationCenter.spec.ts
Let me know what you think, and if I should change this to a traditional if statement.
=> Communication Center II: Attack of the Solar Storm

src/server/deferredActions/AddResourcesToCard.ts, tests/cards/venusNext/MaxwellBase.spec.ts
=> Make Maxwell Base compatible with Applied Science

src/server/cards/base/Flooding.ts, src/server/cards/prelude2/ProjectEden.ts, src/server/cards/underworld/CentralReservoir.ts, src/server/deferredActions/PlaceOceanTile.ts, tests/cards/prelude2/ProjectEden.spec.ts
=> Make Project Eden compatible with Whales

src/client/components/card/CardRowComponent.vue, src/client/components/cardlist/SearchIndex.ts, src/common/cards/render/CardComponent.ts, src/common/cards/render/Types.ts, src/server/cards/prelude2/PalladinShipping.ts, src/server/cards/render/CardRenderer.ts
Opening this PR for discussion on this. The change works (as shown below) and does not create an overflow on Palladin Shipping. Should I attempt a refactor on how corp boxes are implemented?
=> Add effect action corp box and implement it on Palladin Shipping

src/locales/fr/base_cards.json
Little contribution fixing a small typo in french translation.
On another note, thank you very for creating this app and maintaining it, that's really awesome 🙇 .
=> [French translation] Fix tiny typo for French translation

src/server/LogHelper.ts, src/server/player/Production.ts, src/server/player/Stock.ts, src/server/player/StockBase.ts, tests/player/Production.spec.ts, tests/player/Stock.spec.ts
=> Fix stolen production logging

src/common/cards/CardName.ts, src/server/cards/promo/PromoCardManifest.ts, src/server/cards/promo/StaticHarvesting.ts
=> Promo card Static Harvesting

src/locales/ru/cards.json, src/locales/ru/corporations.json, src/locales/ru/prelude2.json, src/locales/ru/prelude_cards.json, src/locales/ru/promo.json
Hello!
This PR contains translations of 40 new cards to Russian. I prepared them in a single group of commits, as testing each one individually would be cumbersome.
Thank you for your time!
=> ru(cards): translate next 40 cards to Russian

src/client/components/WarningsComponent.vue, src/common/cards/Warning.ts, src/server/Player.ts
=> Give warning when a player selects "Pass".

src/locales/ru/cards.json, src/locales/ru/corporations.json, src/locales/ru/prelude2.json, src/locales/ru/prelude_cards.json, src/locales/ru/ui.json
Good afternoon! 
Added a transfer of one card and made minor adjustments to the UI and some cards.
=> Add Russian translations for cards 

src/server/awards/Landlord.ts, src/server/moon/Lunarchitect.ts, tests/awards/Landlord.spec.ts, tests/moon/Lunarchitect.spec.ts
=> Make Landlord and Lunarchitect compatible with Lunar Mine Urbanization
