src/Game.ts

If a player ever passed while all other players did not pass the game would get stuck. Players who have already passed are now skipped when we look for the next player to play.

Prevent game from getting stuck with multiple players for #41

---

src/cards/prelude/IoResearchOutpost.ts

The IoResearchOutpost card was missing a Tags.SCIENCE from it's metadata. It was being displayed fine but not included in game logic.

Add science tag to IoResearchOutput #94

---

src/Player.ts

Actions were not being displayed in the game log for actions which had subsequent actions such as  `AndOptions`. This is now resolved by always logging the action in the `whenDone` function.

Show game log for all actions #96

---

src/Player.ts
src/cards/Shuttles.ts

- Shuttles tag was science instead of space
- Bug with standard city project (this one was funny, I only had a tile on Phobos, so the game did not let me put a greenery / city on the board). I think getAvailableSpacesOnLand should not take Phobos and Ganymede into account...

2 bug fixes

---

server.ts
src/Player.ts
src/components/SelectHowToPay.ts
src/components/SelectHowToPayForCard.ts
src/components/WaitingFor.ts
src/inputs/SelectHowToPay.ts
src/models/PlayerInputModel.ts

This will take more work to add `amount` for every situation. It will not be possible to add for every `SelectHowToPay` but the client side validation that there is enough amount available will work for every situation. Will do this in parts.

Add client side validation for SelectHowToPay

---

src/Game.ts
src/VictoryPointsBreakdown.ts
src/cards/prelude/Vitor.ts
src/components/GameEnd.ts

Now that we have getVictoryPoints, we can remove nonNegativeVPIcon variable and add this function to all cards using this variable. This will also add those cards in the breakdown VP details list.
Vitor is updated in this PR to reflect this change.
Please leave this branch up for the time I update all cards with nonNegativeVPIcon variable.

issue #138

---

src/Player.ts
src/components/OrOptions.ts

When `OrOptions` was an option within `AndOptions` we would lose some of the selected items. This change to `OrOptions` should ensure data is not lost when using `OrOptions` inside an `AndOptions`.

Better OrOptions for use within AndOptions for #148

---

src/Player.ts
src/cards/AquiferPumping.ts
src/cards/BusinessNetwork.ts
src/cards/IndustrialCenter.ts
src/cards/InventorsGuild.ts
src/cards/RestrictedArea.ts
src/cards/SearchForLife.ts
src/cards/SpaceMirrors.ts
src/cards/UndergroundDetonations.ts
src/cards/WaterImportFromEuropa.ts
src/inputs/SelectHowToPay.ts

Right now amount parameter in SelectHowToPay has a default value of 0 and some constructor calls use this value. (see Aquifer Pumping for instance)
This value disables amount checking on client side, I think it should not have a default value, and it should be placed before cb parameter.

SelectHowToPay refactor

---

src/Game.ts

The prelude extension was duplicating a lot of code for initial game setup. This removes the code duplication. I want to eventually make a custom `PlayerInput` for selecting the initial cards to avoid the duplicate clicking of save. All of the `AndOptions` really need to be custom written.

Remove duplicated code for initial card selection

---

package-lock.json
package.json
src/cards/Birds.ts
src/cards/Decomposers.ts
src/cards/EcologicalZone.ts
src/cards/Fish.ts
src/cards/Herbivores.ts
src/cards/Livestock.ts
src/cards/PhysicsComplex.ts
src/cards/SecurityFleet.ts
src/cards/SmallAnimals.ts
src/cards/Tardigrades.ts

Without the package-lock file after an `npm install` the build could fail. These small typing changes get the build to pass for the scenario.

Upgrade dependencies for #222

---

src/Player.ts
src/inputs/SelectOption.ts
tests/Player.spec.ts

If an action has an `onend` and the following action then also has an `onend` this change now chains the `onend` functions into a lambda function. I added `onend` as a quick work around when finishing up the original deck. This change should cover the last branch of processing an input. This missing logic was most likely causing other bugs but we only spotted the issue with `ValleyTrust`. Should be a nice improvement! I added a regression test which fails without the change.

Fix for subsequent on subsequent onend for #215

---

src/Player.ts
src/components/AndOptions.ts
src/components/Board.ts
src/components/OrOptions.ts
src/components/PlayerInputFactory.ts
src/components/SelectAmount.ts
src/components/SelectCard.ts
src/components/SelectHowToPay.ts
src/components/SelectHowToPayForCard.ts
src/components/SelectOption.ts
src/components/SelectPlayer.ts
src/components/SelectSpace.ts
src/components/WaitingFor.ts
src/styles/board.less

I have been keeping this work on my computer and haven't had as much time to work on it. The overall pattern is in place of hiding the save button for children of `AndOptions`. The only work left is calling the save method of each child when the save button of the `AndOptions` is clicked. For `SelectSpace` we will have to store the selected space on the data model so that the parent `AndOptions` can call the save method for the situation where `SelectSpace` is a child of `AndOptions`. This makes the initial selection of corporation and project cards much simpler as it only involves one click.

Better AndOptions with only one save button!

---

server.ts
src/Game.ts
src/components/CreateGameForm.ts

Corporation cards were not being shuffled when custom corporations were used. We also were not passing in instances of `CorporationCard` to the `Game` constructor but POJO corporation card representations from `server`. The mapping to `CorporationCard` is now performed in `server` to not introduce an invalid type.

Shuffle custom corporation cards and map CorporationCards from server

---

src/cards/RoboticWorkforce.ts

For Robotic Workforce , will only be playable if you have at least 1 card to copy.

Robotic Workforce canPlay

---

src/components/OrOptions.ts

When an `OrOptions` component is first displayed all of the child options are set to `display: none`. This update sets the initial display for the initial selected item.

Set initial OrOption to visible for #244

---

src/cards/DomedCrater.ts
src/cards/EcologicalZone.ts
src/cards/ViralEnhancers.ts
tests/cards/EcologicalZone.spec.ts

Fix a bug in Domed crater requirements
Fix Ecological zone
Quick and dirty fix for Viral Enhancers, if x tags are played, you either choose to add x resource to card or gain x plants.
The only card impacted by this is Ecological zone. All other cards either have only one tag or cannot hold resources.

Issue #254

---

src/Board.ts
tests/Board.spec.ts
tsconfig-test.json

Updates greenery placement logic for the situation where every adjacent tile is blocked or an ocean.

Fix for greenery placement when player tiles are all blocked

---

src/Game.ts

Every time corporation cards were being dealt we were modifying the master copy of `ALL_CORPORATION_CARDS`. This change uses a copy of the array so that we don't constantly alter the array!

Work on copy of corporation cards when dealing cards for #259

---

src/Player.ts
src/cards/IndenturedWorkers.ts
src/cards/LocalHeatTrapping.ts
src/cards/SpecialDesign.ts
src/cards/colonies/Conscription.ts
src/cards/prelude/EccentricSponsor.ts
src/cards/prelude/EcologyExperts.ts
tests/cards/prelude/EccentricSponsor.spec.ts
tests/cards/prelude/EcologyExperts.spec.ts

Simplify `lastCardPlayed `logic and remove `lastCardPlayedThisGeneration` method
`lastCardPlayed `is now the last card played for current generation as there is no need to track played cards between turns.
Fix Eccentric Sponsor bug
Switch `generationPlayed` to private, not used anymore but could be used for statistics in the future
Remove `addAnimalsToCard `method

lastCardPlayed rework

---

.github/workflows/main.yml

I am attempting to add `eslint` rules to the project to enforce some sort of standards within the repository. These checks are not running and wont block a build. This adds the `npm run build` command to the github actions to ensure that with any change we can still run a build.

Run build during build for linting

---

src/cards/ImmigrantCity.ts
tests/cards/ImmigrantCity.spec.ts
tests/cards/prelude/Vitor.spec.ts

Fixed erroneous MC production change for Immigrant City. The card effect (+1 MC production) was apparently awarded in the `play()` method and then triggered again in the `onTilePlaced()` method resulting in a MC production change of _0_ instead of _-1_.

Fixed erroneous MC production change (#402)

---

.github/workflows/main.yml

Builds are not running from users on forks. I _think_ this is because the `pull_request` option is missing in the github action configuration file. 
https://github.community/t5/GitHub-Actions/Run-a-GitHub-action-on-pull-request-for-PR-opened-from-a-forked/td-p/15426
Hoping to get builds running from forks to help enforce what linting rules and unit tests exist.

Run build from forks

---

server.ts
src/Player.ts
src/cards/venusNext/Viron.ts
src/components/Card.ts
src/components/OtherPlayer.ts
src/components/PlayerHome.ts
src/models/PlayerModel.ts
src/styles/cards.less

When using the action of a blue card the card is now grayed out so all players can easily see which action was already used and which is still available.
To realize this feature, the `Set<string> actionsThisGeneration` had to be turned into an `Array` as `Set`s are not reactive so the views could not react to changes when an action was used.

Visualize used actions from blue cards (#400)

---

src/components/PaymentWidgetMixin.ts
src/components/SelectHowToPayForCard.ts

This change ensures that it's not possible to attempt to pay more MC than the player actually has. It also prevents the player from accidentally overpaying in MC when decrementing resources from a payment choice.

Fix resource decrement

---

src/Game.ts

When I put in the card factory I stopped clearing the corporations list prior to using the custom list.

Clear corporation cards before adding custom list

---

src/components/PaymentWidgetMixin.ts
src/components/SelectHowToPay.ts
src/components/SelectHowToPayForCard.ts

When choosing a card or ability, cache the cost for more accurate calculation of remaining MC. Without this, current code is using the card cost _even for payments on cards_ e.g. aquifer pumping.

For payment, cache card/ability cost for accurate setting of remaining MC.

---

src/components/PaymentWidgetMixin.ts

One more fixup. This prevents the remaining MC calculation from suggesting an MC value greater than the player has.

Don't calculate an MC value larger than the player possesses.

---

src/milestones/Diversifier.ts
tests/milestones/Diversifier.spec.ts
tsconfig-test.json

This is the first part of issue #528 . This counts all wild card tags as a unique count.

Update Diversifier milestone to support wildcards

---

src/cards/OlympusConference.ts
tests/cards/OlympusConference.spec.ts

Part one of the bug reported in #453 where multiple science tags were not considered. This half is for `OlympusConference`. I added a unit test for the case as well.

Run OlympusConference for each science tag

---

src/Game.ts

Many cards with "other players production reduction" was unplayable in solo mode

Mute production reduce interupt for solo mode; #587

---

src/CardName.ts
src/Dealer.ts
src/HTML_data.ts
src/cards/promo/HiTechLab.ts
src/interrupts/SelectFromCards.ts
tests/cards/promo/HiTechLab.spec.ts
tsconfig-test.json

Please double check if using a (new) interrupt in the card is the best/correct way of implementing the two step card selection. 
I am also not sure if this shouldn't be tested better. The test implemented only respects the first step (energy spending) not the second one (card selection). I looked around in the code but couldn't find anything better, _Titan Floating Launch-Pad_ is doing it the same way.

Added promo card Hi-Tech Lab (#539)

---

src/cards/Virus.ts
tests/cards/Virus.spec.ts

For the scenario where no other player has resources to remove in multi-player games this modification does nothing and assumes the player wanted to play on themselves with removing nothing.

Better Virus implementation when no other players have resources

---

src/Player.ts

When I first wrote this game I paid for the card after playing it. I did this in case an error was thrown while playing the card. If an error were thrown while playing the card then I would have had to handle reverting the payment for the card. I don't think this is an actual issue. As the saying goes, you have to PAY to PLAY. This change moves the payment of the card before playing the card. It should fix the issue reported in #625 as well as others that haven't been reported.

Pay for card before playing it

---

src/cards/colonies/GalileanWaystation.ts

This doesn't include wild cards for jovian tag count.

Omit wild tags from jovian count

---

src/cards/Capital.ts
src/cards/CommercialDistrict.ts
src/cards/CorporateStronghold.ts
src/cards/CupolaCity.ts
src/cards/DomedCrater.ts
src/cards/ImmigrantCity.ts
src/cards/NoctisCity.ts
src/cards/OpenCity.ts
src/cards/RestrictedArea.ts
src/cards/UndergroundCity.ts
src/cards/colonies/MinorityRefuge.ts
src/cards/colonies/RefugeeCamps.ts
tests/cards/CommercialDistrict.spec.ts
tests/cards/NoctisCity.spec.ts

**Context:**
1. City cards should not be selectable for play if there are no more valid city spots remaining. It currently logs an error message: `Error processing input from player No available spaces`
2. Cards like Restricted Area should not be selectable for play if there are no more valid tile placement spots remaining
3. Refugee Camps should still be usable at -4 MC production
4. Minority Refuge should not be playable at less than -3 MC production

Fix logic on some tile placement and Colony cards

---

src/cards/BusinessNetwork.ts
src/cards/InventorsGuild.ts
tests/cards/BusinessNetwork.spec.ts
tests/cards/InventorsGuild.spec.ts

Context:
- **Business Network** action currently cannot be used if player cannot afford to buy the card
- Player should always be allowed to take the action to look at the top card, but can only buy it if he can afford to pay (identical to **Inventor's Guild**)
- If the player cannot pay, the viewed card is simply discarded

Fix: Always allow Business Network scry action

---

src/Game.ts
src/Player.ts
src/cards/colonies/Aridor.ts
src/cards/colonies/Poseidon.ts
src/cards/prelude/ValleyTrust.ts
src/cards/venusNext/Celestic.ts
src/cards/venusNext/MorningStarInc.ts

**Scope:**
- Handle edge cases causing game to crash by not triggering corp's first action if the required expansion is not selected
- Affected corps: Aridor, Celestic and MSI 
- Don't increment turn action counter if corp could not take its first action - player should still be able to do two actions on turn 1 in this case

Fix crashes if certain corps are selected without required expansions

---

src/Player.ts

**Context:**
- We can save one click for the user by making the default selection for final greenery placement to be "Select space for greenery" instead of "Don't place a greenery"
- There are hardly any scenarios where a player would not want to place final greenery if they are able to do so

Swap final greenery placement options

---

src/components/PlayerHome.ts

Looking at the console logs today I discovered we log an error that `turmoil` is `undefined`. We attempt to pass `undefined` to the turmoil component when we shouldn't.

Check that turmoil is defined before mounting turmoil component

---

src/components/SelectSpace.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/494
**Context:**
- Go straight to allowing player to select an available space when the next step is to place a tile
- This saves a lot of unnecessary clicks and scrolling

Remove select space button to save clicks

---

src/cards/colonies/RedSpotObservatory.ts
src/cards/venusNext/LocalShading.ts
tests/cards/venusNext/LocalShading.spec.ts

**Context:**
- Most cards that collect resources (e.g. Deuterium Exports) automatically add a resource to the card if it is the only valid target, and the card has 0 resources
- This behaviour can also be implemented for **Red Spot Observatory** and **Local Shading**

Improvement: Auto add resources if card has no resources

---

src/components/OrOptions.ts

**Context:** Move the "Save" button for taking player actions to directly below the selected action
**Ref:**
https://github.com/bafolts/terraforming-mars/issues/360
https://github.com/bafolts/terraforming-mars/issues/749

Move Save button to directly below selected action

---

src/components/AndOptions.ts
src/components/OrOptions.ts
src/components/SelectCard.ts
src/components/SelectHowToPayForCard.ts

We run vuejs in development mode which is slower and outputs a lot of warnings. I want to eventually run this in production mode. If you look at the console while playing a game you will see warnings logged that we recursively make calls to render from `AndOptions` and `OrOptions`. A data property is being updated which existed when the vue instance was instantiated. When these properties are updated vue renders the component. To resolve this warning the properties we use during render are added at the time of render so they do not trigger subsequent updates. In production mode the app currently gets stuck in an infinite loop, it works in develop mode since vuejs prevents the looping.
The other warning resolved is our usage of the `:key` property which is unnecessary since we have …

Component updates for vuejs warnings

---

package.json

We added a local database on disk for storing games that are being played for the undo operation. When the app starts we attempt to repopulate games from that database. The idea was on our heroku server we would load any games which were ongoing. Reading through the heroku documentation today I believe we have to define our `db` directory as a `cacheDirectories` in our top level `package.json` to keep the database file around.
Eventually this database will grow too large to be stored on disk and we will need to consider pruning it in some way. For the time being this should allow games to be played while we update `master` without losing the games.
https://devcenter.heroku.com/articles/nodejs-support#custom-caching

Cache db directory for heroku

---

src/database/SQLite.ts

Heroku supports free postgres databases which I have propped up. All of our SQL should port over. I noticed one query where we are relying on the database to parse JSON. To simplify this between database servers I moved this JSON parsing to node.
When running the app locally the SQLite database will still be used. Heroku will connect to a postgres database. The same SQL can be used between both.

Parse json outside of database

---

src/Player.ts
src/cards/IProjectCard.ts
src/cards/prelude/AlliedBanks.ts
src/cards/prelude/AquiferTurbines.ts
src/cards/prelude/BusinessEmpire.ts
src/cards/prelude/Donation.ts
src/cards/prelude/GalileanMining.ts
src/cards/prelude/HugeAsteroid.ts
src/cards/prelude/Loan.ts
src/cards/prelude/MartianIndustries.ts
src/cards/prelude/NitrogenDelivery.ts
src/cards/prelude/PreludeCard.ts
tests/cards/prelude/AquiferTurbines.spec.ts
tests/cards/prelude/BusinessEmpire.spec.ts
tests/cards/prelude/GalileanMining.spec.ts
tests/cards/prelude/HugeAsteroid.spec.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/761
Worst edge case is Manutech keeping 10 cards with Galilean Mining and Business Empire. Both Preludes should be playable due to Manutech's effect.
**Note:** MC can temporarily show as negative after playing first Prelude if it deducts MC, but will always be 0 or net positive after both Preludes are played.

Fix: Preludes should be playable if player can afford by playing the other prelude first

---

src/Game.ts

**Scenario:**
- Custom corps option is enabled
- Player selects only 1 corporation (e.g. Credicor in below screenshot)
- Starting corps quantity is set to 1
**Expected:** Player should be dealt the selected custom corporation
**Actual:** Player is dealt a random corporation

Fix bug with custom corps option and 1 starting corp

---

src/components/SelectHowToPay.ts
src/components/SelectHowToPayForCard.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/749
If a player cannot pay for a card using only MC, other valid and available resources will be used for payment in the following order:
1. Microbes from Psychrophiles for Plant cards (first priority since they can be removed by Ants)
2. Floaters from Dirigibles
3. Steel ("greedy" implementation, use as much as possible without overpaying by default)
4. Titanium ("greedy" implementation, use as much as possible without overpaying by default)
5. Heat (last priority since it can be used for temperature raise)

Improvement: Payment UI automatically uses other available resources

---

src/database/PostgreSQL.ts
src/database/SQLite.ts

Add a created_time that default to now() to the table. It will be useful for housekeeping.
If the postgres database is already up and running it will not do anything, the table could be modified from the command line. I can take care of this if needed.

Add created_time to games table

---

src/cards/turmoil/CulturalMetropolis.ts
src/cards/turmoil/MartianMediaCenter.ts
src/interrupts/SelectParty.ts
src/turmoil/Turmoil.ts

Free delegate will not be lost if MARTIAN MEDIA CENTER action is used or CULTURAL METROPOLIS is player before free delegate is used.

Fix issue 694

---

src/styles/board.less

Fixed CSS to display ocean bonus on Hellas as described in issue #780.

Fixed CSS to display ocean bonus on Hellas (Issue #780)

---

src/CardName.ts
src/Game.ts
src/Player.ts
src/cards/SearchForLife.ts
src/cards/colonies/Aridor.ts
src/cards/colonies/Poseidon.ts
src/cards/corporation/Inventrix.ts
src/cards/corporation/OriginalCorporation.ts
src/cards/corporation/TharsisRepublic.ts
src/cards/prelude/AcquiredSpaceAgency.ts
src/cards/prelude/ExperimentalForest.ts
src/cards/promo/ArcadianCommunities.ts
src/cards/promo/Philares.ts
src/cards/promo/Splice.ts
src/cards/venusNext/Celestic.ts
src/cards/venusNext/MorningStarInc.ts
src/colonies/Colony.ts
src/components/LogPanel.ts
src/interrupts/SelectColony.ts
tests/cards/corporation/Inventrix.spec.ts

**Context:**
- Add missing logs for several corporations' first actions
- For actions that explicitly reveal cards, the cards drawn into hand should be made known to other players
- Also removes Inventrix's unnecessary first action click in https://github.com/bafolts/terraforming-mars/issues/749 and logs Prelude revealed draws

Improvement: Log revealed cards and discarded cards

---

src/cards/ExtremeColdFungus.ts
src/cards/SymbioticFungus.ts
tests/cards/ExtremeColdFungus.spec.ts
tests/cards/SymbioticFungus.spec.ts

**Scope:** Remove target selection step if "Add microbe" option is selected for Extreme Cold Fungus and Symbiotic Fungus and there is only one valid target

Remove target selection step if there is only 1 valid microbe card

---

src/cards/venusNext/AerialMappers.ts
tests/cards/venusNext/AerialMappers.spec.ts

**Scope:**
- Automatically add floater if there is only one possible valid action (i.e. this card is the only floater card, and it has no floaters on it)
- Replace "Select card" step with SelectOption if this card is the only possible target

Improvement for Aerial Mappers

---

src/cards/ImportedHydrogen.ts
tests/cards/ImportedHydrogen.spec.ts

**Context:** Currently, Imported Hydrogen always shows options to add microbes and animals even if the player has no microbe cards or animal cards. This PR improves the card's behaviour to only show valid options to the player.

Improve Imported Hydrogen: Don't show invalid options

---

src/Player.ts
src/turmoil/globalEvents/AquiferReleasedByPublicCouncil.ts
src/turmoil/globalEvents/AsteroidMining.ts
src/turmoil/globalEvents/CelebrityLeaders.ts
src/turmoil/globalEvents/CorrosiveRain.ts
src/turmoil/globalEvents/Diversity.ts
src/turmoil/globalEvents/EcoSabotage.ts
src/turmoil/globalEvents/GenerousFunding.ts
src/turmoil/globalEvents/GlobalDustStorm.ts
src/turmoil/globalEvents/HomeworldSupport.ts
src/turmoil/globalEvents/ImprovedEnergyTemplates.ts
src/turmoil/globalEvents/InterplanetaryTrade.ts
src/turmoil/globalEvents/JovianTaxRights.ts
src/turmoil/globalEvents/MinersOnStrike.ts
src/turmoil/globalEvents/MudSlides.ts
src/turmoil/globalEvents/Pandemic.ts
src/turmoil/globalEvents/ParadigmBreakdown.ts
src/turmoil/globalEvents/Productivity.ts
src/turmoil/globalEvents/RedInfluence.ts
src/turmoil/globalEvents/Riots.ts
src/turmoil/globalEvents/Sabotage.ts
src/turmoil/globalEvents/ScientificCommunity.ts
src/turmoil/globalEvents/SolarFlare.ts
src/turmoil/globalEvents/SolarnetShutdown.ts
src/turmoil/globalEvents/SpinoffProducts.ts
src/turmoil/globalEvents/StrongSociety.ts
src/turmoil/globalEvents/SucessfulOrganisms.ts
src/turmoil/globalEvents/VenusInfrastructure.ts
src/turmoil/globalEvents/VolcanicEruptions.ts

**Scope:**
- Log resource and production changes as "increased" or "decreased" instead of "modified"
- Fix missing GlobalEvent logs (due to `game` not being passed in)
- Log decreased production from Global Events
- Log increased production and increased resources from Global Events

Improve logging

---

src/components/LogPanel.ts
src/styles/log.less

Changed the bullet in front of log level entries to a clock face which shows the timestamp for the log message on hover.

Added timestamps to log entries

---

src/Game.ts

Will check if there is enough corporations in the deck instead of fixed value of 12 corporations.

Use corp amount instead of fixed value

---

src/HTML_data.ts

Change "Science Science" 
to "2 Science" 
like with the other cards. Maybe @ssimeonoff wants to update this in his cards list too?

Minor fix: change display of required tags from "<required tag> <required tag>" to "<amount> <required tag>"

---

src/cards/ArtificialPhotosynthesis.ts
tests/cards/ArtificialPhotosynthesis.spec.ts

Increasing 2 Energy production is usually preferred in most cases; it's rarer to pick the other option of increasing 1 plant production

Switch default selected option for Artificial Photosynthesis

---

src/HTML_data.ts

"Jovian Jovian" should be "2 Jovian"

Minor Fix: Jovian tag requirements on Impactor Swarm

---

src/cards/promo/DeimosDownPromo.ts

**Ref:** https://www.kickstarter.com/projects/strongholdgames/terraforming-mars-big-box/posts/2869228
When played, you gain 4 steel and bring the moon Deimos Down to the surface creating a massive crater and raising the temperature by 3. You **cannot place this next to a city tile** and it will cost 6 plants from any player.

Update placement restriction for Deimos Down promo

---

src/cards/Moss.ts
src/cards/NitrophilicMoss.ts
tests/cards/Moss.spec.ts
tests/cards/NitrophilicMoss.spec.ts

**Context:** If player has Viral Enhancers in play, he should be able to play **Moss** with 0 plants and **Nitrophilic Moss** with 1 plant. Due to the bonus plant gained from Viral Enhancer's effect.

Fix edge cases for Moss and Nitrophilic Moss

---

src/cards/LocalHeatTrapping.ts
tests/cards/LocalHeatTrapping.spec.ts

**Context:** Local Heat Trapping should give 4 plants directly if player has no animal cards; this does not need to be a click.

Local Heat Trapping should give 4 plants directly if player has no animals

---

src/cards/venusNext/Celestic.ts

When the server is starting up errors while populating games are ignored but logged. There is an error logged for a game with the celestic card. Two resource cards were not found in the hand and an error that `name` can not be read from `undefined` was logged. I have updated the card to log the cards that it added. I also saw we weren't discarding the drawn cards so I also updated the card to discard the drawn cards so they are not lost.

Fixes to Celestic

---

src/cards/AerobrakedAmmoniaAsteroid.ts
src/cards/CEOsFavoriteProject.ts
src/cards/EOSChasmaNationalPark.ts
src/cards/ElectroCatapult.ts
src/cards/ExtremeColdFungus.ts
src/cards/GHGProducingBacteria.ts
src/cards/Greenhouses.ts
src/cards/ImportedHydrogen.ts
src/cards/ImportedNitrogen.ts
src/cards/LargeConvoy.ts
src/cards/LocalHeatTrapping.ts
src/cards/NitriteReducingBacteria.ts
src/cards/RegolithEaters.ts
src/cards/SymbioticFungus.ts
src/cards/TerraformingGanymede.ts
src/components/LogHelper.ts
tests/cards/AerobrakedAmmoniaAsteroid.spec.ts
tests/cards/CEOsFavoriteProject.spec.ts
tests/cards/EOSChasmaNationalPark.spec.ts
tests/cards/ElectroCatapult.spec.ts
tests/cards/ExtremeColdFungus.spec.ts
tests/cards/LocalHeatTrapping.spec.ts
tests/cards/SymbioticFungus.spec.ts

Part of https://github.com/bafolts/terraforming-mars/issues/428#issuecomment-608305941
This change covers only cards in the base game.

Add more detailed logs for base game

---

src/styles/globs.less

**Ref:** https://github.com/bafolts/terraforming-mars/issues/777
**Suggestion:** Use a different color plus text-shadow instead of opacity, so that it's clearer what the current level for each parameter is.

Improve visibility of global parameter current levels

---

src/components/SelectHowToPay.ts

**Example:** Water Import from Europa always shows default value of 12 for MC. The default MC value that is set should take Steel and Titanium into account.

Fix wrong default MC value in SelectHowToPay

---

src/Game.ts
src/Player.ts
tests/Game.spec.ts

**Context:** A solo game today finished two oxygens short, with 5 plants and 9 plant production. In the greenery conversion phase, two TR was awarded for the two greeneries placed and the game was wrongly counted as a "win." This game id was **cf9acd27f381**.
**Fix:** According to rulebook pg 13, final greenery placements should not raise the oxygen level or award TR for solo games.
_"After generation 14, you may convert plants into greenery tiles, following normal rules but without raising the oxygen"_

Fix: Don't raise oxygen or give TR for final greeneries

---

src/CardName.ts
src/Dealer.ts
src/HTML_data.ts
src/cards/promo/DiversitySupport.ts
tests/cards/promo/DiversitySupport.spec.ts

**Note:** This has at least two possibilities:
- Total of 9 resources collected on cards
- 9 different cards with resources on them
It is not entirely clear at the moment which one is the actual card effect

Add Diversity Support promo card (?)

---

server.ts
src/Game.ts
src/components/CreateGameForm.ts
tests/Game.spec.ts
tests/Turmoil.spec.ts
tests/cards/turmoil/AerialLenses.spec.ts
tests/cards/turmoil/BannedDelegate.spec.ts
tests/cards/turmoil/CulturalMetropolis.spec.ts
tests/cards/turmoil/DiasporaMovement.spec.ts
tests/cards/turmoil/EventAnalysts.spec.ts
tests/cards/turmoil/GMOContract.spec.ts
tests/cards/turmoil/MartianMediaCenter.spec.ts
tests/cards/turmoil/PROffice.spec.ts
tests/cards/turmoil/ParliamentHall.spec.ts
tests/cards/turmoil/PublicCelebrations.spec.ts
tests/cards/turmoil/Recruitment.spec.ts
tests/cards/turmoil/RedTourismWave.spec.ts
tests/cards/turmoil/SeptumTribus.spec.ts
tests/cards/turmoil/SponsoredMohole.spec.ts
tests/cards/turmoil/SupportedResearch.spec.ts
tests/cards/turmoil/VoteOfNoConfidence.spec.ts
tests/cards/turmoil/WildlifeDome.spec.ts
tests/cards/venusNext/DawnCity.spec.ts
tests/cards/venusNext/LunaMetropolis.spec.ts
tests/cards/venusNext/MaxwellBase.spec.ts
tests/cards/venusNext/Stratopolis.spec.ts

**Scope:**
- Add option to randomize milestones and awards (default: OFF)
- Without Venus Next: Randomize all 5 milestones and awards
- With Venus Next: Randomize all 6 milestones and awards
- Milestones and awards set for each game will persist across reloads and predefined cloned games. Thanks @vincentneko for help!

Add game option to randomize milestones and awards

---

src/components/Board.ts
src/components/GameEnd.ts
src/components/PlayerHome.ts
src/components/Preferences.ts
src/components/PreferencesManger.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/777
- Show an alert only once when Mars is fully terraformed
- Don't show the alert on game_end screen
- Basic alert for now, in future this can be a nicer styled onscreen animation with sound

Add one-time alert when Mars is terraformed

---

src/Phase.ts
src/Player.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/900
As per rules, party ruling policies are only triggered during action phase, not during playing of initial preludes.

Fix: Experimental Forest should not trigger Greens policy

---

src/database/PostgreSQL.ts

When using postgres with `socket` connections the inclusion of the `ssl` property is causing errors. The heroku instance uses self signed certificates. This should resolve #910 .

Don't require ssl with socket connections

---

src/Game.ts

Cards discarded during the initial research phase are not actually going into the discard pile.
This means that players do not have access to initially discarded cards even after the deck cycles through, and also causes unintended errors when the deck runs out of cards.
For testing:
- I replaced `src/Dealer.ts:996` with this line: `this.deck = [];`
- And set "Use promo cards" to true, "Corporate Era" to false.

Fix: Unpurchased cards in initial research phase should enter discard pile

---

src/Game.ts
tests/cards/Comet.spec.ts
tests/cards/DeimosDown.spec.ts
tests/cards/Virus.spec.ts
tests/cards/promo/SmallAsteroid.spec.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/930
This change introduces an additional option to "Do nothing", and also clearly shows how many plants will be removed from each player.

Make removing Plants optional

---

tests/cards/Asteroid.spec.ts
tests/cards/BigAsteroid.spec.ts
tests/cards/Comet.spec.ts
tests/cards/GiantIceAsteroid.spec.ts
tests/cards/MiningExpedition.spec.ts
tests/cards/Virus.spec.ts
tests/cards/colonies/ImpactorSwarm.spec.ts
tests/cards/promo/SmallAsteroid.spec.ts
tests/cards/turmoil/AerialLenses.spec.ts

Update tests to properly cover scenarios:
- No plants available to remove
- One opponent has plants
- Multiple opponents have plants
- Player chooses not to remove any plants

Update tests for plant removal cards

---

src/Player.ts

Ref: https://github.com/bafolts/terraforming-mars/issues/946
This issue happened because `hasIncreasedTerraformRatingThisGeneration` was not being set for Turmoil games

Always set hasIncreasedTerraformRatingThisGeneration when raising TR

---

src/Game.ts
src/interrupts/SelectResourceProductionDecrease.ts
tests/cards/AsteroidMiningConsortium.spec.ts
tests/cards/BiomassCombustors.spec.ts
tests/cards/CloudSeeding.spec.ts
tests/cards/EnergyTapping.spec.ts
tests/cards/Fish.spec.ts
tests/cards/GreatEscarpmentConsortium.spec.ts
tests/cards/HeatTrappers.spec.ts
tests/cards/Herbivores.spec.ts
tests/cards/PowerSupplyConsortium.spec.ts
tests/cards/SmallAnimals.spec.ts

**Scope:**
- Make `addResourceProductionDecreaseInterrupt` behaviour consistent with `addResourceDecreaseInterrupt`; there is no need to select a player if only one choice is possible.
- Update tests to cover the new logic

Update resource production decrease

---

src/cards/venusNext/Atmoscoop.ts
tests/cards/venusNext/Atmoscoop.spec.ts

- Player should not see raise Venus or raise temperature option if that parameter is already maxed out
- If there is only one parameter that can be raised, it should happen automatically, no need to click

Improve Atmoscoop: Don't show raise temp/Venus option if parameter is maxed

---

src/cards/promo/PharmacyUnion.ts
tests/cards/promo/PharmacyUnion.spec.ts

This commit fixes a bug where Pharmacy Union's effect incorrectly removes 4 MC from the player who played the microbe tag.
The 4 MC should be removed from the player who has the Pharmacy Union corporation.

Fix: Pharmacy Union should remove 4 MC from corp owner

---

src/Game.ts
src/Player.ts
src/turmoil/parties/PartyHooks.ts
tests/cards/turmoil/BannedDelegate.spec.ts

Minor groundwork for future variants like https://boardgamegeek.com/thread/2411719/turmoil-20-political-agendas which the designer has already given permission to include here.
Also fixes a flaky BannedDelegate test caused by random factor during game setup. Sometimes `BannedDelegate.play()` returns `Array<SelectDelegate>` with multiple parties instead of just `SelectDelegate` with one party.

Refactor some code into PartyHooks

---

src/CardName.ts
src/Dealer.ts
src/HTML_data.ts
src/cards/turmoil/PoliticalAlliance.ts
src/constants.ts
tests/cards/turmoil/PoliticalAlliance.spec.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/985
Add missing Political Alliance card from Turmoil expansion.

Add missing Turmoil card Political Alliance

---

src/Player.ts

The default value for `fromLobby` in `SelectParty` is true. It seems that it should be false here when paying 5 MC to send a delegate from the reserve, not from the lobby.

Fix SelectParty when sending delegate from reserve

---

src/Player.ts

Players should not be able to go into negative MC when purchasing cards during research phase. The max number of cards that can be selected for purchase should be restricted based on the player's available MC (+heat if Helion).

Fix: Restrict no. of cards player can purchase during Research phase

---

src/Player.ts
src/cards/AquiferPumping.ts

Ref: https://github.com/bafolts/terraforming-mars/issues/1011
This change ensures that the Reds 3 MC tax is always removed from the player, but it can temporarily give rise to negative MC before the next production phase. Possible exploit is as follows:
Player can afford Aquifer pumping action (cost 11) when Reds are in play.
Pay for action using all available MC.
The Reds tax will still deduct 3 MC from the player in this scenario to prevent tax avoidance.

Add workaround for Reds tax avoidance

---

server.ts
src/Player.ts
src/awards/Excentric.ts
src/components/Card.ts
src/components/Colony.ts
src/components/OtherPlayer.ts
src/components/PlayerHome.ts
src/components/PlayerMixin.ts
src/components/SelectCard.ts
src/milestones/Hoverlord.ts
src/models/CardModel.ts

- Cards with 0 resources on it will show RES : 0 instead of nothing.
- Rework card component so there is no need to pass the full player object to it. This should save some server resources.
- Resources on cards will be displayed when prompting cards for selection, like this:

Show ressources on cards

---

src/cards/promo/Astrodrill.ts
tests/cards/promo/Astrodrill.spec.ts

Ref: https://github.com/bafolts/terraforming-mars/issues/1026
Astrodrill always has at least two action choices available: Add an asteroid resource to a card, or gain a standard resource.

Fix available actions for Astrodrill

---

src/components/Award.ts
src/components/Milestone.ts
src/styles/player_home.less

- css tweaks
- MA descriptions are hidden
- clicking a MA toggles its description (show/hide)
- added a tooltip to mention that
The ma-description divs are targeted with css selectors. 
Implement a proper way to toggle their show/hide states.

ma css rework

---

src/Board.ts
src/ElysiumBoard.ts
src/OriginalBoard.ts
tests/Board.spec.ts

We can not have `while (true)` loops running as they can potentially take over the node process. One of these I assume looped indefinitely yesterday and took down the heroku instance. I have put in guards around every usage of `while (true)` and consolidated some of the code which was using this pattern.

throw error if infinite loops are blocking node process

---

README.md
src/Game.ts

Bypass beginner corp choice if any extension is selected (along with initial draft)
Fix a bug where game was struck if a beginner corp was selected
Update discord link with a non expiring invitation
Some work is still needed on the UI to disable beginner corp selector if any extension is selected (along with initial draft)

Disable beginner corp if option selected

---

src/turmoil/globalEvents/SnowCover.ts
src/turmoil/parties/Reds.ts

RULING BONUS: The player with lowest TR gains 1 TR. Ties are friendly. In solo, you receive 1 TR if you **have TR 20 or below**.

Reds' ruling bonus  for solo

---

src/components/GameEnd.ts
src/locales/de/game_end.json
src/locales/ru/game_end.json

Some users pointed out that the displayed target is always a static value of 90+. Minor improvement to show a dynamic target based on the player's actual score (arbitrary value of player's score + 10)

Display dynamic target score at game end

---

src/cards/promo/Factorum.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/1114
Official clarification from the designer is here: https://boardgamegeek.com/thread/2351530/article/34083951#34083951

Add missing log for Factorum's drawn building card

---

src/Game.ts
src/Player.ts
tests/cards/promo/CrashSiteCleanup.spec.ts

The card should be playable after any card that removes plants is played, as you can always target neutral opponent in solo mode.

Fix: CrashSiteCleanup should be playable in solo mode

---

src/Game.ts
src/Player.ts
src/cards/AquiferPumping.ts
src/cards/BusinessNetwork.ts
src/cards/IndustrialCenter.ts
src/cards/InventorsGuild.ts
src/cards/RestrictedArea.ts
src/cards/SearchForLife.ts
src/cards/SpaceMirrors.ts
src/cards/UndergroundDetonations.ts
src/cards/WaterImportFromEuropa.ts
src/cards/venusNext/ForcedPrecipitation.ts
src/cards/venusNext/RotatorImpacts.ts
tests/cards/AquiferPumping.spec.ts
tests/cards/BusinessNetwork.spec.ts
tests/cards/SpaceMirrors.spec.ts
tests/cards/WaterImportFromEuropa.spec.ts
tests/cards/venusNext/RotatorImpacts.spec.ts

This one is quite big and could have some impact on the game...
It also removes more than 300 lines of code !
All calls to `SelectHowToPay `have been removed and will now use the `addSelectHowToPayInterrupt `mechanism which is consistent with Helion pay with heat.
This is also true for the research phase.
Some extra testing would be appreciated along with the review !

Select how to pay cleanup

---

src/cards/turmoil/VoteOfNoConfidence.ts
tests/cards/promo/CuttingEdgeTechnology.spec.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/1149
Card should be discounted 2 MC by CuttingEdgeTechnology as it has requirements.

Fix hasRequirements for VoteOfNoConfidence

---

src/HTML_data.ts
src/cards/EarthOffice.ts
src/cards/corporation/Teractor.ts
src/locales/cn/cards.json
src/locales/de/cards.json
src/locales/ru/cards.json
tests/cards/EarthOffice.spec.ts
tests/cards/corporation/Teractor.spec.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/1161
Luna Governor should be discounted by 6 MC as confirmed by the game designer.
We could also consider to reword the effect text on Earth Office and Teractor to state the correct effect clearly, since this is not possible on the physical print version.

Fix discount for Earth Office and Teractor

---

src/Player.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/1170
`title` is incorrectly assigned twice on lines 2121 and 2122

Fix incorrect double assignment of milestones option title

---

server.ts
src/Game.ts

Fix:
1、when a player with corp MiningGuild places an ocean act as the WG (when he is the first palyer), his STEEL prod increase one by mistake
2、when create a new game , the players can't get  promo corps for choose  even if the "Promos" option has been checked

Fix:when a player with corp MiningGuild places an ocean act as the WG

---

src/Player.ts
tests/Turmoil.spec.ts

Ref: https://github.com/bafolts/terraforming-mars/issues/1190

Fix: Don't add Reds tax for SP greenery if oxygen is maxed

---

src/components/PlayerHome.ts
src/components/TagOverview.ts
src/locales/ru/ui.json
src/styles/player_home.less

1) Fix tag overview to not hide when page is updated due to other player actions
2) Better fit milestones and awards look and feel
3) Add column with current RT

Tag overview UI modifications

---

src/Player.ts
src/cards/Mangrove.ts
src/cards/Plantation.ts
src/cards/ProtectedValley.ts
src/cards/turmoil/WildlifeDome.ts
src/cards/venusNext/AirScrappingExpedition.ts
src/cards/venusNext/GHGImportFromVenus.ts
src/cards/venusNext/GiantSolarShade.ts
src/cards/venusNext/NeutralizerFactory.ts
src/cards/venusNext/OrbitalReflectors.ts
src/cards/venusNext/SulphurExports.ts
src/cards/venusNext/VenusSoils.ts
src/cards/venusNext/VenusianPlants.ts
tests/cards/venusNext/GiantSolarShade.spec.ts

- Add Floaters and Microbes to CanAfford method (fix Reds policy bug)
- Fix a bug where MC could go negative
Edge case : If I'm able to play a card because of microbes or floaters (with dirigibles) with Reds ruling but I did not spend them and therefore I lack MC after to pay Red, TR will not be increased and MC will not be spent.

issue_1195

---

src/colonies/Callisto.ts
src/colonies/Ceres.ts
src/colonies/Colony.ts
src/colonies/Enceladus.ts
src/colonies/Europa.ts
src/colonies/Ganymede.ts
src/colonies/Io.ts
src/colonies/Luna.ts
src/colonies/Miranda.ts
src/colonies/Pluto.ts
src/colonies/Titan.ts
src/colonies/Triton.ts
src/components/LogHelper.ts
src/constants.ts

**Ref:** https://github.com/bafolts/terraforming-mars/issues/1211
- Add option to increase colony track for Europa or do nothing
- Add log to show actual number of increased steps (1 or 2)

Make colony track increase from card effects optional for Europa

---

src/Player.ts
src/cards/Flooding.ts

1. Fix :  monsInsuranceOwner  needn't  pay 3mc when someone removes his own resources (red-bordered resource icons cards ,such as  fish  )
2. Improvement: merge duplicate targets of  flooding

1. Fix :  Mons Insurance

---

src/cards/HiredRaiders.ts
src/cards/Sabotage.ts
tests/cards/HiredRaiders.spec.ts
tests/cards/Sabotage.spec.ts
tests/cards/promo/MonsInsurance.spec.ts

Ref: https://github.com/bafolts/terraforming-mars/issues/1225
- Reduce from two clicks to one by directly showing all available options with exact quantities

Improve Hired Raiders and Sabotage

---

src/Player.ts
src/components/OrOptions.ts

@vincentneko I believe this will fix the issue of an `AndOptions` not being supported as a child of `OrOptions`. There was no real reason I used to limit this to one option other than there was never a need for this complexity. I believe this change will work. I gave this a try through a few `OrOptions` and it didn't seem to break anything.

add support for AndOptions as child of OrOptions

---

src/components/Preferences.ts
src/styles/preferences.less

1. Preferences dialog is usable on not-that-height screens (added scroll)
2. Slightly changed references dialog design

Better fit preferences dialog

---

package.json

`eslint` was added to `npm start` but `eslint` is only a `devDependency`. If the `start` command is going to run `eslint` it will need to be a dependency as heroku doesn't install `devDependency`. Since `eslint` is a development tool it doesn't make sense to include with `start` which is the command heroku or anyone installing locally to run would use. Only someone developing needs `eslint`.

remove eslint from start command

---

server.ts

If you happen to append extra query string arguments to the player link the `/api/player` route ends up with the parameters. This change allows for the extra values to be passed to the route. The extra arguments are ignored. Internally the game does not append these query string arguments. These will get appended by third party applications but we should support them.

allow for extra query params to /api/player route

---

src/styles/cards.less

The current blurry box-shadow selection is barely visible on mobile. 
A label is much better. 
Instead of using .js to add/remove the label, a pseudo ::after background is used for it.
Suggested design:

Selected card css

---

src/components/PlayerHome.ts

Fixed no color for initial draft on player turn order

---

src/SoundManager.ts
src/components/Preferences.ts
src/components/PreferencesManager.ts
src/components/WaitingFor.ts

First-cut attempt at cleaning up and fixing an issue in the previous PR by @jijiqw in https://github.com/bafolts/terraforming-mars/pull/1219.
This is a POC for adding a sound when it is the active player's turn. If this approach is viable we can gradually introduce more sounds that can be customised and exported as individual functions.

Add sound for active player notification

---

src/Game.ts
tests/cards/colonies/NitrogenFromTitan.spec.ts
tests/globalEvents/CloudSocieties.spec.ts

addResourceInterrupt will automatically add resource to card if there is only one card. (and put a message in the log)
Add` addSelectResourceCardInterrupt(player: Player, count: number = 1, resourceType: ResourceType, resourceCards: Array<ICard>, title?: string): void {`
for future rework and maybe to support Ares development

Improve addResourceInterrupt

---

server.ts

As this repository gains game options and contributors we have had short term errors show up which crash the node process. Since every game runs on one node process if there is any uncaught exception the node process has to be manually restarted. This change wraps all external requests and returns a 500 response if there is an error processing the exception.

return 500 response on server error

---

src/styles/common.less
src/styles/create_game_form.less
src/styles/mixins.less
src/styles/player_home.less
src/styles/variables.less

I started doing some work on the new Log visuals and decided to cleanup something that has been bothering me first:
+ added `variables.less` - a file holding values such as player colors, default action color, warning color, etc.
+ added `mixins.less` - similar to variables but for more complex combinations (like color and opacity)
+ started replacing some of the css values with their variable representation
Note: Should we accept this change we can try to use and replace color, shrift, etc. with variables whenever possible. I'd also suggest we do spacing in increment of 4px / 8px / 16px.
Reasoning: Control over the app outlook with a single source of truth (similar to theming).
Food for though: We have been discussing the change of colors in discord to a different palette. We could …

Added variables.less and mixins.less and setup inital values

---

src/HTML_data.ts

Ref: https://github.com/bafolts/terraforming-mars/issues/1303

Fix iconography for Mining Expedition

---

src/Player.ts

Ref: https://github.com/bafolts/terraforming-mars/issues/1375

Fix: Prevent Helion from using heat to raise temp if can't pay for Reds

---

src/components/App.ts
src/components/OtherPlayer.ts
src/components/PlayerHome.ts
src/components/overview/PlayerInfo.ts
src/components/overview/PlayerStatus.ts
src/components/overview/PlayersOverview.ts
src/utils/utils.ts

Concerning #1316
The problem was that `playerkey++` on `setVisibilityState` refreshes the whole Vue state which subsequently "resets" all child components that have local "data" to thier defaults. That is why on any toggle for milestone or award the cards got deselected or anything that has a local state actually. The solution was to remove the increment of `playerkey` from `setVisibiltyState` which led to some changes that need to be considered whenever global state is used in `componentsVisibility`. In order for everything to work, any item that is added to `componentVisibilty` needs to be initialized. By doing that I had to refactor the way `pinPlayer` works so now it uses indices which are initialized to be 0 to 5 (since its max 6 players and we can only pin all other players so its …

+fixed issue #1316 and refactored the way setVisibilityState works

---

src/HTML_data.ts
src/styles/cards.less
src/styles/common.less

This is the next step of the work to improve cards HTML markup
1) Unified colonies icons
2) Fixed alignment of resource tags inside prod boxes
3) Image based plus and minus signs inside prod boxes to fix their grayish look on MacOS
4) Lakefront Resorts corporation fix

Moar ui fixes

---

src/cards/community/Playwrights.ts
tests/cards/community/Playwrights.spec.ts

This addresses #1388 
The failed run:
https://github.com/bafolts/terraforming-mars/pull/1442/checks?check_run_id=1196738089
Was failing on:
```
1) Playwrights
Can replay own event:
AssertionError: expected 3 to equal 4
+ expected - actual
-3
+4
```
This would fail if when playing `TechnologyDemonstration` the first time a `TechnologyDemonstration` card were drawn. When repeating the playing of the card the `TechnologyDemonstration` card would be removed from hand so the final count would be 3 instead of 4. I modified the test to use an action that increases terraform rating instead as it should avoid these side effects.

fix: flaky playwright unit test

---

.eslintrc.js
src/Board.ts
src/Dealer.ts
src/Game.ts
src/HellasBoard.ts
src/MASynergy.ts
src/Player.ts

I noticed a pull request yesterday that was using `var`. The usage of `var` can lead to bugs. This requires `let` or `const`. Only `src/*.ts` is being linted. I will include other PRs to put every file under the linter. This should help us catch bugs.

chore: add no-var and prefer-const eslint rules

---

src/components/Board.ts
src/styles/globs.less

- Count up the ocean value in ? / 9. 
- I believe it is better this way. Easier to understand cards with ocean requirement as well. You don't need to do math in your head to see there are six oceans to play Artic algae.
From #1456

count up oceans

---

src/components/PaymentWidgetMixin.ts

From this issue #1367 , the max button should not overpay. Currently it spends all available resources, not taking the card price into account.
This PR fixes that issue.
Before clicking max:
After clicking max:

fixing max button to not overspend

---

src/components/common/DynamicTitle.ts

This needs a quick merge. Fixes warning in console for incompatible type Int vs String

Fixed dynamic title wrong type validation warning

---

index.html
server.ts
src/components/StartScreen.ts
src/styles/start_screen.less
webpack.config.js

This has a few changes related to how the server operates. 
Included with the `StartScreen` component is now the commit hash to display some form of version for users. It will appear as:
`e48ba89a Sun, 4 Oct 2020 15:40:43 -0600`
This should be a simple solution and not get in the way of contributors while allowing users to know which version of the application they are using. If we decide to update what this displays in the future the mechanism will be in place for displaying the value.
I also updated the webpack configuration to link to the source map. I noticed that all of our javascript was attempting to reach the source map through `webpack://` when the developer console was open. With this change the developer console should now link back to out typescript.
I also updated webpack to …

refactor: include git log information for version

---

server.ts

The heroku plan being used which stays up is the cheapest available plan. There is a heroku buildpack which can provide the git hash through SOURCE_VERSION environment variable. Heroku removes the git directory before the node buildpack is used. I verified this change can work from:
http://terraforming-mars-dev.herokuapp.com/
Since we can't pull the git information with ease I included the date the change was deployed. With this string included in bug reports it should help us to know what version of the code was running.

refactor: pull version from SOURCE_VERSION

---

src/cards/Virus.ts
tests/cards/Virus.spec.ts

Virus should always be playable even when it does have a target. (You may want to play it to gain mc back from Media Group.) Current code prevents that.

virus should always be playable

---

src/components/overview/PlayersOverview.ts

The client side components will only have `PlayerModel` and not `Player`. This is purely a typing update ensuring we have the appropriate type listed.

refactor: only use PlayerModel on client

---

server.ts
src/Game.ts
src/components/GameEnd.ts
src/components/LogPanel.ts
src/components/PlayerHome.ts
src/components/overview/PlayerTags.ts
src/routes/GameLogs.ts
src/routes/Route.ts
tsconfig.json

We have had an arbitrary limit placed on how much we log for game log entries. With #1110 there are users that want to see the entire log. I am curious to see how our memory will run on the heroku instance if we remove this limit. As long as this doesn't put us above the heroku memory limit it could be fine. I can keep an eye on the memory usage on heroku and remove if it is a problem.

refactor: show all log entries

---

src/HTML_data.ts
src/styles/cards.less

- Update two preludes with new icon tags
- Move eco expert inline css to card.less
- Change Splice to tag-microbe instead of just microbe
Left new, right old

Update some prelude with new icons and minor adjustment on eco expert

---

src/styles/log.less

With the log messages now loading asynchronously the log-panel component ends up growing once the messages are available. To avoid this div growing after the base page has loaded the height is set to the max-height. Once a few log messages are logged the max-height is reached anyway so this should only make the height larger during the first few actions of the first generation when nothing is logged. Eventually this separation of log messages from the main response should allow this log-panel component to filter messages.

use height for log-panel

---

src/components/GameEnd.ts

Removes the link to the player that no longer exists as game has ended. It might make sense to add this back in if we add a replay option from the perspective of a player, like in Board Game Arena.

Fixes #1518

---

src/components/LogPanel.ts
src/components/OtherPlayer.ts
src/styles/log.less

In connection to #1533 
+ no need for close buttons in hidden elements to have a loading indicator as they only influence non-server actions
+ also x was floating too wide

Fixed close button for Log and OtherPlayer

---

src/components/CreateGameForm.ts
src/styles/create_game_form.less

Because of absolute positioning of the "Color" label it currently looks like this when translated:
Also since it has a defined height, it looks like this with too many options (last option is out of the box):
-----
This aims to fix both issues:

Fix create game players form CSS

---

src/Game.ts
src/LogBuilder.ts
src/LogMessageDataType.ts
src/components/LogPanel.ts

This will translate every parameters of the log messages except if their type is set as either `PLAYER` or `RAW_STRING` (new type currently only used for the game id).
Tested it both in English and in French, seems to work without issues.

Add translation to log messages parameters 

---

tests/cards/community/Playwrights.spec.ts

I originally fixed an issue in `Can replay own event` and didn't think `Can replay other player's event` would have the same issue. Turns out that it does have the same issue. If while playing `TechnologyDemonstration` you happen to draw a `TechnologyDemonstration` card it will get removed from your hand. This should only be a bug for unit tests as if you were to copy an event the card would not be available to draw and would not be in a players hand. I put in the same fix for this test with using `ReleaseOfIntertGases` to avoid the conflict with drawing cards.

tests: fix playwrights unit tests

---

src/Player.ts
src/cards/IProjectCard.ts
src/cards/community/ByElection.ts
src/cards/community/VenusFirst.ts

The heroku application crashed this morning after the introduction of the new community cards. Unfortunately the cheap hosting plan used only allows me to go back 1500 log entries which isn't including the runtime exception which caused the crash. I have added defensive coding measures to protect the new cards from taking down the server. One of the cards when played without turmoil would have crashed the server then `turmoil` was not defined.

defensive coding measures on new cards

---

server.ts

During the transition to the separate game log route I kept the `gameLog` property coming back on the `PlayerModel`. Anyone who had a copy of `main.js` during the change would have needed this to come through that method. At this point it has been long enough from the change that most people should have a new `main.js` or they have had a game running for multiple days without ever requesting a copy of `main.js` through either browser refresh or some other method.

chore: remove gameLog sent with PlayerModel

---

src/Game.ts
src/SerializedColony.ts
src/SerializedGame.ts
src/colonies/Colony.ts

This fixes #1364 . On `SerializedGame` we only store values which can be stored in JSON and not `IColony`. This introduces a `SerializedColony` interface which represents what we store on the database. We were loading `colonies` but not `discardedColonies`. This updates both with a new function which maps `Array<SerializedColony>` to `Array<IColony>`.

fix: map serialized discarded colonies to IColony

---

src/cards/AquiferPumping.ts
src/cards/SymbioticFungus.ts
src/cards/promo/DirectedImpactors.ts
tests/cards/AquiferPumping.spec.ts
tests/cards/SymbioticFungus.spec.ts
tests/cards/promo/DirectedImpactors.spec.ts

Ref: https://github.com/bafolts/terraforming-mars/issues/1474
Minimal change. Exit condition for max is already handled in `game.addOceanInterrupt` and `game.increaseTemperature`.

Permit stall actions for some cards

---

src/components/card/CardTitle.ts
src/styles/cards.less

- Set cardTitle width dynamically based on title length
- Drop "Promo" text from promo card titles
- Fix CSS for ProjectWorkshop

Dynamically set cardTitle widths and trim Promo text from titles

---

src/Game.ts
src/HTML_data.ts
src/cards/community/AerospaceMission.ts
src/cards/community/ValuableGases.ts
src/cards/corporation/MiningGuild.ts
tests/cards/community/ValuableGases.spec.ts
tests/cards/corporation/MiningGuild.spec.ts

This fixes https://github.com/bafolts/terraforming-mars/issues/1564 caused by incorrect timing of setting `space.player` to `undefined` and adds a unit test for WGT placements not triggering Mining Guild's effect.

Fix: Mining Guild placement bonus for WGT

---

src/components/CreateGameForm.ts
src/locales/cn/ui.json
src/locales/de/ui.json
src/locales/fr/ui.json
src/locales/ru/ui.json
src/styles/common.less
src/styles/create_game_form.less
src/styles/mixins.less
src/styles/player_home.less
src/utils/utils.ts

- Color boxes instead of radio buttons for picking colors.
- The entire player box changes color to match, making it easier to tell who is playing what color.
- Hiding TR boost and Beginner Corp option under Beginner Options

Improve player color selection

---

package-lock.json
package.json
server.ts
webpack.config.js

Well our javascript seems to like being compressed.
```
Built at: 10/13/2020 6:12:38 PM
Asset      Size  Chunks                          Chunk Names
main.js  1.33 MiB       0  [emitted]        [big]  main
main.js.gz   275 KiB          [emitted]        [big]  
main.js.map  2.81 MiB       0  [emitted] [dev]         main
main.js.map.gz   524 KiB          [emitted]        [big]  
```
Now users will only need to download 275kb to load the app.

refactor: use gzip for main.js

---

src/cards/EnergyTapping.ts
src/cards/PowerSupplyConsortium.ts
tests/cards/EnergyTapping.spec.ts
tests/cards/PowerSupplyConsortium.spec.ts

You can increase your own energy production and then decrease it.
There's really little reasons you would do that (maybe playing Energy Tapping into Magnetic Field or delaying your action late game) but it would be valid. So there we go.

Fix Energy Tapping and Power Supply Consortium play requirements

---

.gitignore
README.md
index.html
make_static_json.js
package.json
server.ts
src/components/App.ts
src/components/PlayerHome.ts
src/components/WaitingFor.ts

During the recent change to display the server version on the client I took a rudimentary approach. There was a request to pass another server variable to the client to configure how often the client checks for updates. This change creates a `settings.json` similar to the `translations.json`. This file is then passed to the `App` component making it available on the client. In the future if we need to pass more data from server to client we can add it here.

create settings.json for passing server settings to client

---

src/Player.ts

Card shows up as playable, since it is, but when validating the play, `howToPay.floaters` is set to 0, not undefined, so it triggers a check, and if you have only 1 cards with floaters, you can't play Stratospheric Birds.
This fix makes sure that `howToPay.floaters` is greater than 0 to process the check, fixing the issue.

Fix not being able to play Stratospheric Birds

---

src/components/CreateGameForm.ts
src/styles/create_game_form.less

Changes
- players inputs are above the submit form button 
- input fields similar to the player boards in the game (colourful background with white text)
- selected colour highlight matches the input background

New game form - player colours minor changes

---

src/cards/community/Hygiea.ts

Similar to Europa colony. If the player has Trade Envoys, they should be able to choose whether to raise the colony track or not before trading.

Fix: Player choice for Hygiea with Trade Envoys

---

src/cards/community/ValuableGases.ts

`player.getPlayableCards(game)` should be called instead of `player.cardsInHand`

Fix: Only show cards that player can afford for ValuableGases

---

src/database/PostgreSQL.ts

In most places we catch errors so that we don't take down the server. When loading cloned games we were not catching errors when loading game from JSON. This led to an uncaught error which crashed the node process. This change catches the error for now. There is some issue where the final community card manifest in `decks` is always `undefined`.
If you log this value it is `undefined`.
https://github.com/bafolts/terraforming-mars/blob/master/src/Dealer.ts#L27
Anytime we can't find a card we will error. If you use community cards you are most likely screwed.

catch errors loading reference games

---

src/database/SQLite.ts

Fix which was put in for postgres for sqlite. We most likely need to migrate our database towards some shared logic once we get the response. For the time being this will catch the error and prevent crash for postgres parity.

catch errors restoring reference games for SQLite

---

src/CardFinder.ts
src/Dealer.ts
src/Player.ts
src/components/LogPanel.ts
tests/CardFinder.spec.ts
tests/Game.spec.ts

Proper fix for #1707 . Self executing javascript complicates module loading. This moves the self executing `decks` into a `CardFinder` class. Unit tests added to find a prelude card and a project card. I also added a warning for when cards are not found. On older games seeing:
```
card not found Magnetic Field Generators Promo
card not found Great Dam Promo
card not found Deimos Down Promo
```
which I believe we expect from the suffix change to `:promo`.

create singleton to get decks

---

src/cards/ares/SolarFarm.ts
tests/cards/ares/SolarFarm.spec.ts

- Solar Farm should not be playable if there is no spot to place tile (mandatory effect)
- `space` and `citySpace` in the test are not always equivalent if `space` happens to have a hazard tile on it

Fix: SolarFarm test and playability check

---

src/cards/community/TradeAdvance.ts

The change to interrupts broke the way this behaved with Europa and Hygiea, ending up decreasing the colony track before the player is asked if they want to increase it and trade.

Fix Trade Advance issue with Europa and Hygiea

---

README.md
make_static_json.js
server.ts

Since the app is still in constant development, the default value is still 0.
But this will allow server admins to set a different value to prevent multiple refreshes (like when streaming a game) to burn through bandwidth :)
This also fixes WAITING_FOR_TIMEOUT not working (missing dotenv in make_static_json.js file).

Add browser cache to assets via .env variable

---

src/components/GameEnd.ts
src/styles/game_end.less

This PR can close #1298 and close #1732 .
- Change color of row each to match player color.
- Report score in columns that wrap around
- Move log to be in the same row as board
- Announce who is the winner
Wrap around if all columns don't fit in one row.
If two winners, say both. Rare to happen.

end game ui improvement

---

src/Game.ts
tests/TestingUtils.ts

Closes https://github.com/bafolts/terraforming-mars/issues/1771. Ares `initialData` should be set up before calling `boardConstructor`

Fix console warnings for undefined aresData

---

src/styles/cards.less

Left without border, right with border.
No need for border in Turmoil policy either.
@ssimeonoff

remove white border around the card icon

---

src/Player.ts
src/cards/prelude/AlliedBanks.ts
src/cards/prelude/AquiferTurbines.ts
src/cards/prelude/BusinessEmpire.ts
src/cards/prelude/Donation.ts
src/cards/prelude/GalileanMining.ts
src/cards/prelude/HugeAsteroid.ts
src/cards/prelude/Loan.ts
src/cards/prelude/MartianIndustries.ts
src/cards/prelude/NitrogenDelivery.ts
src/cards/prelude/PreludeCard.ts
tests/cards/prelude/AquiferTurbines.spec.ts
tests/cards/prelude/BusinessEmpire.spec.ts
tests/cards/prelude/GalileanMining.spec.ts
tests/cards/prelude/HugeAsteroid.spec.ts

This properly only allows you to play preludes that you can afford to.
It is properly computed at the time you need to play the card.
Which means you can now play **Interplanetary Cinematics**, buy 9 cards (end with 3 MC), pick **Eccentric Sponsor (ES)** and **Huge Asteroid (HA)** preludes, play **ES** into **Lava Flows**, get 2 MC from your corp (now at 5 MC) and then play **HA** (leaving you at 0 MC).
_Note: If you don't get at least 5 MC before having only **HA** left in your hand, you won't be able to play it, of course._
**Helion** can also now lose heat (if gotten any from placing a tile or from a prelude card) when asked to lose MC from a prelude card.

Fix Preludes play order + allow Helion to pay with heat

---

src/components/Colony.ts
src/components/Turmoil.ts
src/styles/cards.less

Removing the white border on the cards make them look better on project cards but hard to see on Turmoil and Colonies. This PR specifically add white border back just to Turmoil and Colonies.

add card white border to colony and turmoil

---

src/Board.ts
src/cards/MiningCard.ts
tests/cards/MiningRights.spec.ts
tests/cards/ares/MiningRightsAres.spec.ts

This is a regression that occurred after moving content to the main branch.

Spaces under hazards may not be selected as part of MiningRights and Mining Area.

---

src/cards/NitriteReducingBacteria.ts
src/cards/promo/PharmacyUnion.ts
src/cards/turmoil/GMOContract.ts
tests/cards/NitriteReducingBacteria.spec.ts
tests/cards/promo/PharmacyUnion.spec.ts
tests/cards/turmoil/GMOContract.spec.ts

As stated in the title, makes **Pharmacy Union** losing MC a priority so that subsequent effects that can give you MC (GMO, Topsoil, getting money from Mons) happens after that.
Closes #1179

Priority to PU effects to lose MC before getting any

---

compile-vue-templates.js
src/components/SelectAmount.ts

@bafolts Reverting that change from https://github.com/bafolts/terraforming-mars/pull/1795 that broke SelectAmount.
It's probably just a matter of removing the `.data` from the methods but I don't know that part of the code and I don't have enough time to check that everything will still work afterwards, hence the simple revert.
Fixes https://github.com/bafolts/terraforming-mars/issues/1802

Fix SelectAmount not working

---

src/HTML_data.ts
src/cards/community/ValuableGases.ts
src/styles/cards.less

Addresses an edge case: You should be allowed to play a Venus card from hand even if it does not collect floaters, as adding resources to a card is one of the allowed three exceptions.

Update css for community cards and logic for ValuableGases

---

src/Player.ts
src/cards/colonies/Aridor.ts
src/cards/colonies/Poseidon.ts
src/cards/community/Incite.ts
src/cards/community/ProjectWorkshop.ts
src/cards/corporation/CorporationCard.ts
src/cards/corporation/Inventrix.ts
src/cards/corporation/TharsisRepublic.ts
src/cards/prelude/ValleyTrust.ts
src/cards/prelude/Vitor.ts
src/cards/promo/ArcadianCommunities.ts
src/cards/promo/Philares.ts
src/cards/promo/Splice.ts
src/cards/venusNext/Celestic.ts
src/cards/venusNext/MorningStarInc.ts

This change prompts the player to actually play the first action of their corporation if they have one (Tharsis, Inventrix, etc).
It also gives them the right to pass the generation instead if they prefer. They will still have to take that action as their first before they are allowed to do anything else than pass.
While it is a correct implementation of the rules since delaying that first action is [a legal move](https://boardgamegeek.com/thread/1784175/article/25942959#25942959), some might say that it adds 1 extra click per game (if you have one of those corps) while you would have near 0 reason to ever not take it.
I'll let you guys be the judge of that.
Closes https://github.com/bafolts/terraforming-mars/issues/1576

Prompt player for corporation's first action

---

src/cards/prelude/ValleyTrust.ts

Closes https://github.com/bafolts/terraforming-mars/issues/1829. Player is shown an error message and asked to select a different prelude card to play.

Fix: Don't allow Valley Trust to play preludes it cannot afford

---

src/Game.ts

Fix from @Lynesth that closes https://github.com/bafolts/terraforming-mars/issues/1830. Game phase should always be set to `Phase.SOLAR` even if solar phase option is not selected or global parameters are maxed, as a lot of core logic checks for this specific phase.

Fix: Ocean from global event should not give TR or placement bonus

---

src/Player.ts
src/cards/Ants.ts
src/cards/Predators.ts
src/cards/Virus.ts
src/cards/colonies/AirRaid.ts
src/cards/venusNext/StratosphericBirds.ts
src/deferredActions/RemoveResourcesFromCard.ts
tests/cards/Ants.spec.ts
tests/cards/Predators.spec.ts
tests/cards/Virus.spec.ts
tests/cards/colonies/AirRaid.spec.ts
tests/cards/venusNext/StratosphericBirds.spec.ts

Adds a new deferred action called **RemoveResourcesFromCard** that is used by cards or actions that can remove resources from other cards.
It is now used by **Ants**, **Predators**, **Virus**, **Stratospheric Birds** and **Air Raid**.
Also added an argument to `player.getCardsWithResources()` to allow filtering what kind of cards we're looking for.
First commit is functional, second is for tests.

Reduce code duplication in cards that remove resources from other cards and allow self removal on Ants and Predators.

---

src/Player.ts
src/cards/IProjectCard.ts
src/cards/community/AerospaceMission.ts
src/cards/community/ByElection.ts
src/cards/community/ValuableGases.ts
tests/cards/community/ValuableGases.spec.ts

Checking community preludes I ended up doing:
- Split `player.playProjectCard` in two to be able to use `SelectHowToPayForCard` outside of it (in **Valuable Gases** in this case).
- Finished removing bonusMc from cards since it's not used anymore.

Use SelectHowToPayForCard in Valuable Gases + remove remains of bonusMc

---

src/cards/prelude/PointLuna.ts

Closes https://github.com/bafolts/terraforming-mars/issues/1847 - Point Luna currently starts with 3 MC extra every game. The additional 3 MC may be due to legacy code and is no longer needed.

Fix: Point Luna is starting with 3 MC extra

---

src/Player.ts
src/cards/colonies/IceMoonColony.ts
src/cards/colonies/InterplanetaryColonyShip.ts
src/cards/colonies/MiningColony.ts
src/cards/colonies/MinorityRefuge.ts
src/cards/colonies/TradingColony.ts

Closes https://github.com/bafolts/terraforming-mars/issues/1845. Also adds missing Reds tax check for IceMoonColony which places an ocean.

Fix: Cards placing colonies should check for available colony tile

---

src/cards/turmoil/UtopiaInvest.ts

There is already a log `"PLAYER used Utopia Invest action"` so the action log can be more concise. Also fixes syntax error in current log.

Update Utopia log for brevity

---

package-lock.json
package.json

Something with eslint change makes sqlite3 required as a dependency. This will bring the heroku server back online.

move sqlite3 to dependency

---

package-lock.json
package.json

The heroku instance, or any system only _running_ the app versus _developing_ the app will run `npm install --production`. The total of all the `dependencies` today is:
```
125M	node_modules/
```
With this change:
```
112M	node_modules/
```
The cheapest and free heroku instance only allots 500M total of storage.
https://devcenter.heroku.com/changelog-items/1145
This will buy us a 10M. With the pain the demo site with heroku has been causing I am going to start manually deploying in the morning when I can watch it run successfully. For those playing games it will be around 8AM Denver time. I also plan to add another github action to ensure that an:
```
npm install --production
npm start
```
does not fail.

move devDependencies accordingly

---

package.json
webpack.config.js

In a quest to speed up the local build process. This will cut down the time webpack takes for local builds.
Before: 
```
Hash: c773998b9e687a6242f8
Version: webpack 4.44.2
Time: 7700ms
```
After:
```
Hash: a4c68bf5f2073b038919
Version: webpack 4.44.2
Time: 1874ms
```
This also enables the vue warnings in console. Seems I have the typing information wrong on `props`. Will address in subsequent PR. Those are littering vue debug logs.

separate webpack command and faster builds for local

---

src/HTML_data.ts
src/cards/AcquiredCompany.ts
src/cards/AdaptedLichen.ts
src/cards/AdvancedEcosystems.ts
src/cards/AerobrakedAmmoniaAsteroid.ts
src/cards/ArchaeBacteria.ts
src/cards/ArtificialLake.ts
src/cards/ArtificialPhotosynthesis.ts
src/cards/Asteroid.ts
src/cards/AsteroidMiningConsortium.ts
src/cards/BigAsteroid.ts
src/cards/BiomassCombustors.ts
src/cards/BreathingFilters.ts
src/cards/GiantIceAsteroid.ts
src/cards/render/CardRenderItem.ts
src/cards/render/CardRenderItemType.ts
src/cards/render/CardRenderSymbol.ts
src/cards/render/CardRenderer.ts
src/cards/turmoil/AerialLenses.ts
src/components/card/CardRenderItemComponent.ts
src/components/card/CardRenderSymbolComponent.ts
src/components/card/CardRowComponent.ts

Some improvements on the card rendering following the advice from @kberg and @Lynesth 
+ Simplified getter / setter methods for CardRenderItem
+ Simplified API builder functions that don't require parameters to not use `()`
+ Added `asterix`, `plus` and `or` to builder functions
+ Added microbes and megacredits
+ Megacredits should have a digit inside by default
+ Refactored some repeating code and improved CardRenderSymbol static builders
+ Added microbes and symbols to vue rendering components
+ Added 10 more cards that use metadata (+ formatting to 2 spaces)

Card render api improvements

---

src/styles/log.less

A `log-player` element was being used that was never registered. I changed this to `span` yesterday. The CSS styling receives two `background-color` both through class name before. Previously I believe the class name was taking priority over the element name based selector. After my change they were conflicting. As far as I can tell we always provide the background color so we shouldn't need it on the span element.

show log-player provided color

---

src/components/SelectCard.ts

Orders the cards displayed on `SelectCard` using any pre-defined user order first. This should not impact situations where a player is selecting an opponents card. Those will be displayed in default order.

use card order for SelectCard component

---

src/components/CreateGameForm.ts

Warning seen on `CreateGameForm` with duplicate `change` event listeners. The `CreateGameForm` is not running through the vue type checker yet which would catch this.

fix: warning for two change events on element

---

package-lock.json
package.json

pre-built binaries for sqlite3 seem to be missing for some build environments. Upgrading to latest hoping for better support.

chore: upgrade sqlite3 to 5.0.0

---

tests/cards/LandClaim.spec.ts

The recently added `LandClaim` change failed once merged and not while I was developing. The solo mode tile placement was placing a tile on the space used in assertion. Using two player game to avoid random tile placement.

fix: use 2 player game to avoid random tile placements

---

src/components/card/CardRequirementsComponent.ts

It actually gives a warning when running the tests but doesn't show up in the recap. Could we get those summarized at the bottom as well somehow @bafolts ?

Fix typo closing tag

---

src/HTML_data.ts
src/cards/AdvancedAlloys.ts
src/cards/AntiGravityTechnology.ts
src/cards/ArcticAlgae.ts
src/cards/Asteroid.ts
src/cards/AsteroidMiningConsortium.ts
src/cards/BigAsteroid.ts
src/cards/BiomassCombustors.ts
src/cards/GiantIceAsteroid.ts
src/cards/OptimalAerobraking.ts
src/cards/colonies/CryoSleep.ts
src/cards/promo/Advertising.ts
src/cards/render/CardRenderItem.ts
src/cards/render/CardRenderItemType.ts
src/cards/render/CardRenderer.ts
src/cards/turmoil/AerialLenses.ts
src/cards/turmoil/EventAnalysts.ts
src/cards/turmoil/GMOContract.ts
src/components/card/CardContent.ts
src/components/card/CardRenderData.ts
src/components/card/CardRenderEffectBoxComponent.ts
src/components/card/CardRenderItemComponent.ts
src/components/card/CardRowComponent.ts
src/components/card/CardRowData.ts
src/styles/cards_v2.less

* CardRenderEffect implementation following the builder pattern. A card effect has 4 parts `cause - delimiter - effect - description`
* Implemented some effect cards and added some new builder functions
I tried to reduce boilerplate and focused on clean API, just not sure about the `startEffect` function. I wanted to announce end of cause and start of effect part with a function that also generates two new arrays which then can be fetched via getters in the Vue component. It does do the job and hopefully it's intuitive.
```
public get startEffect(): Builder {
this.br;
this._addSymbol(CardRenderSymbol.colon());
this.br;
return this;
}
```
```
...
public get cause(): Array<ItemType> | undefined {
this._validate();
return this.rows[0];
}
public get delimiter(): ItemType {
this._validate(); …
```

Card effect to Vue

---

compile-vue-templates.js
src/components/DebugUI.ts

To make this work I pre-fetch all the cards, and store data in memory.
This turns out to make searching MUCH faster!
Incidentally, most of the cards do not have text, so while this will seem broken, it surely isn't.

Search for cards in the debug-ui using the description as a filter.

---

src/cards/colonies/IceMoonColony.ts
src/cards/colonies/InterplanetaryColonyShip.ts
src/cards/colonies/MiningColony.ts
src/cards/colonies/TradingColony.ts

Bug reported by Simon. 4 of the colony cards incorrectly count as cards with requirements

Fix: Missing property for colony placement cards

---

server.ts

This will fix #1941 . The unit tests create games that were at one point inadvertently saved to the sqlite database. Users of that database will have these games listed. These games aren't using the generated game id. This change makes the check for game id more lenient as it isn't crucial that this game id matches the generated format.

more lenient on game id check

---

src/components/card/Card.ts

Fix actionUsed type

---

src/Player.ts
src/cards/venusNext/Atmoscoop.ts
src/inputs/OrOptions.ts
tests/cards/venusNext/Atmoscoop.spec.ts

Couldn't reproduce the issue mentioned on Discord but this will hopefully reduce user mistake to have Heat/Venus increase uncoupled from the floaters addition (and may help debugging said bugs).
Also made it so that when a OrOptions has a callback, it will be run after the selected option's callback.

Atmoscoop: Heat/Venus increase before adding floaters

---

src/cards/ImportedNitrogen.ts
tests/cards/ImportedNitrogen.spec.ts

Reduce code duplication and split the action in two. Add microbes to card, then add animals.
Here's the reason for that choice:
Because of how `AndOptions` is implemented, a failsafe (using microbesAdded and animalsAdded) had to be implemented to prevent adding multiple microbes if an error occured (if you didn't select an animal card for example).
But because of that failsafe, it also means that, in case of an error, you cannot change your mind and select another microbe card, as microbes were already added to the card you previously selected.

Rewrite Imported Nitrogen

---

src/Game.ts
src/cards/colonies/Polyphemos.ts
src/cards/corporation/CorporationCard.ts
src/cards/turmoil/TerralabsResearch.ts

The issue it fixes has a couple of ways to be exploited. I'll give one example below.
**Steps to reproduce the issue:**
- Create a 2 players game
- Make sure one of the player has Phobolog
- Select 8+ cards with Phobolog player and confirm the selection [_No error_]
- Confirm the other player selection, you get an error saying you took too many cards [_But that's really for Phobolog_]
- Change the other player selection (or not) and validate again
**Consequences:**
- The other player has more/duplicated cards [_You get cards from the first and the second selections you made_]
- Phobolog player has no cards [_Yay_]
- If the other player is the first in turn order, its corporation is played twice
- All cards not selected during other player both elections were added to the discard pile, so …

Fix first cards pick when an error occur

---

src/Player.ts
tests/Player.spec.ts

Removed unnecessary variables.
Removed duplicated code by adding a `checkInputLength` method.
Removed unnecessary checks from `SelectHowToPayForCard` since those are performed in the callback.
Text for errors that should not happen (like incorrect input length) was kept "simple".
Didn't touch Ares inputs @kberg, but you can probably just add `this.checkInputLength(input, 1, 1);` for both of them.

Refactor Player's runInput method

---

tests/milestones/Tactician.spec.ts

While reviewing some test cases, I noticed that the case for claiming this milestone with more than 5 valid cards was missing.

Case with 6 cards with requirements and milestone not yet claimed.

---

README.md
server.ts

I am always losing that random pass phrase for /games-overview?serverId=**90bff6c48f8c**
This PR allows to set it to fixed value

Ability to set static pass phrase for admin routes via env variable

---

compile-vue-templates.js
src/components/overview/PlayerStatus.ts
tsconfig-vue.json

The vue type checking was not checking directories two deep. Updated the blob to catch more of the components and updated issues. Fixing the `player.corporationCard` which can be `undefined` which ended up being an error from the vue type checker fixed the bug in #2010

update vue type checking for all directories

---

src/cards/base/RoboticWorkforce.ts
tests/cards/base/RoboticWorkforce.spec.ts

Added Sponsored Mohole and Asteroid Deflection System to Robotic Workforce.
Tried to make `getAvailableCards` a bit faster and added a small (kinda bruteforcish) test to check that Robotic Workforce has all applicable cards.

Add missing cards to Robotic Workforce + test

---

src/styles/players_overview.less

Current behaviour: Long player names will spill over into 2nd row or more, resulting in uneven heights for player bars.
Change: Add missing property so that `text-overflow: ellipsis` works correctly and keeps all heights constant

Minor CSS fix for long player names

---

server.ts
src/Player.ts
src/cards/base/CaretakerContract.ts
src/cards/base/Insulation.ts
src/cards/base/LocalHeatTrapping.ts
src/cards/base/PowerInfrastructure.ts
src/cards/colonies/StormCraftIncorporated.ts
src/cards/colonies/TitanShuttles.ts
src/cards/promo/EnergyMarket.ts
src/cards/promo/HiTechLab.ts
src/cards/promo/Meltworks.ts
src/cards/promo/Philares.ts
src/cards/venusNext/SulphurEatingBacteria.ts
src/components/SelectAmount.ts
src/deferredActions/DryDesertsDeferredAction.ts
src/inputs/SelectAmount.ts
src/models/PlayerInputModel.ts
tests/cards/base/Insulation.spec.ts
tests/components/ShiftAresGlobalParameters.spec.ts

This adds a `min` property to `SelectAmount` and makes sure that the following cards can only be played/acted upon if you have resource/production to spend (no more 0 for 0):
- Energy Market
- Insulation
- Hi-Tech Lab
- Power Infrastructure
- Sulphur-eating Bacteria
- Titan Shuttles

X (any number of) means greater than or equal to 1

---

.gitattributes

I don't use windows but I believe this will address issue reported in #2062 . New linting rule is checking for lines ending in LF.

add gitattributes file for windows users

---

src/turmoil/SerializedTurmoil.ts
src/turmoil/Turmoil.ts

Is this safe to do? I had a discussion on discord about whether there is a time where there is no ruling party, and the answer I got was
> There is always a ruling party during the gen. Even in gen 1, greens are ruling, although I don't think the green's ability is in play during the prelude play. During preludes and the solar phase, ruling party effects do not apply.
I know already that the solar phase won't take ruling effects into account, but what about preludes? Does this change cause breaking behavior during an, um, prelude phase?

There is always a ruling party and a dominant party.

---

src/turmoil/Turmoil.ts
tests/Turmoil.spec.ts

Added regression test. when deserializing a `Turmoil` the usage of `Object.assign` we setting `players` to a type we aren't enforcing with typescript!

set properties without Object.assign

---

src/turmoil/Turmoil.ts
src/turmoil/globalEvents/GlobalEventDealer.ts
tests/GlobalEventsDealer.spec.ts

This lets me put its behavior in one place. This is going to make it easier as I continue to adjust serialization behavior. Also added a sanity serialization/deserialization test, which will come in handle once I add a SerializedGlobalDealer.
@chstoa you asked why this style is better, and here's another example of why: first, by adding a fully-built dealer into Turmoil, Turmoil is no longer responsible for figuring out anything about how to make a deck. Second, Turmoil makes GlobalEventDealer readonly. Which meanse that I can't just do
turmoil.globalEventDealer = blah
once the object is constructed. So, fine, instead, just feed it into its constructor.

Make GlobalEventDealer serializable on its own.

---

src/Player.ts
tests/cards/base/IndenturedWorkers.spec.ts
tests/cards/colonies/Conscription.spec.ts

This meant having to pull the hard work of passing out of a callback and into a first-class method. No biggie.

Add meaningful tests to IndenturedWorkers and Conscription.

---

src/Player.ts
src/SerializedPlayer.ts

This seems like an acceptable change. I cannot find a single use for it.

Remove unused field Player.generationPlayed.

---

src/Player.ts
src/SerializedPlayer.ts
src/cards/base/ImmigrantCity.ts
src/cards/corporation/TharsisRepublic.ts

This was only used by Immigrant City in case you either played it with **-4** MC production or with **-5** as Tharsis Republic.
Since the tile placement is the first effect of the card, the increases in MC production take place before the decrease so it works as intended, and we can remove that strange property :)

Get rid of player.shouldTriggerCardEffect

---

src/components/CorporationsFilter.ts

Automatically select/unselect community corps when community module is selected/deselected.
Also remove corps columns if there's no corp in the module (ie. Ares).

Fix custom corps list on create game form

---

tests/Timer.spec.ts

Noticed today a new unit test for `Timer` was taking a second to run and relying on `setTimeout` to take a second. I had this test fail on me. The `setTimeout` function can not guarantee that the callback will be called at exactly 1000ms. When it is called too late this unit tests fails. I modified the unit test to manually provide a time and run without using `setTimeout`.

Flaky timer test

---

src/Player.ts
src/cards/promo/EnergyMarket.ts

Is this a good idea? It reduces some use, and I'd use it at least twice.

Include `Player.spendableMegacredits`, which takes heat into account.

---

src/components/overview/PlayerTags.ts

I moved the `v-else` onto an element with `v-for` and this seems to have indirectly attempted to run the `v-else` on each item in the array. I moved this to a template and that seems to have solved the problem.

separate teplate for v-else

---

src/CardLoader.ts
src/Dealer.ts
src/Player.ts

Unless I missed something I think it makes more sense to keep the "complication" of the method inside the class itself.

Make CardLoader.get...Cards() less convoluted

---

src/styles/preferences.less

Fixes visual bug from https://discord.com/channels/737945098695999559/742721510376210583/793552139922178068
Happens with `smaller cards` option.

fixes layout

---

src/cards/promo/MoholeLake.ts
tests/cards/promo/MoholeLake.spec.ts

Scheduling is difficult for humans and computers. There is some strategy that if a task will not take long to do it right away. This change allows MoholeLake to do nothing with an action which is the precedent we have started with other cards.

let MoholeLake always take action

---

src/Player.ts
src/SerializedPlayer.ts
src/cards/Card.ts
src/cards/ICard.ts
src/cards/base/MiningCard.ts
src/cards/community/ScienceTagCard.ts
src/cards/corporation/BeginnerCorporation.ts
src/cards/corporation/CrediCor.ts
src/cards/corporation/EcoLine.ts
src/cards/corporation/Helion.ts
src/cards/corporation/InterplanetaryCinematics.ts
src/cards/corporation/Inventrix.ts
src/cards/corporation/MiningGuild.ts
src/cards/corporation/PhoboLog.ts
src/cards/corporation/SaturnSystems.ts
src/cards/corporation/Teractor.ts
src/cards/corporation/TharsisRepublic.ts
src/cards/corporation/Thorgate.ts
src/cards/corporation/UnitedNationsMarsInitiative.ts
src/cards/prelude/PreludeCard.ts
src/cards/standardProjects/StandardProjectCard.ts
tests/Player.spec.ts
tests/cards/Card.spec.ts
tests/cards/ares/BioengineeringEnclosure.spec.ts
tests/cards/ares/BiofertilizerFacility.spec.ts
tests/cards/corporation/CrediCor.spec.ts

Been trying to work around a problem a few other ways in regards to all of our cards creating new values for their properties. With a moment of inspiration when @Lynesth mentioned creating a separate interface for dynamic properties I remembered that when using a `get` for a property we don't have to store these values. With this change the values which are static such as `name`, `tags`, `cost`, and `metadata` wont store a new value on each instance but will instead provide the value at runtime.
The trade off here is the generated javascript will be slightly larger per card and some operations will run marginally slower as the value will be calculated when it is needed versus stored in memory. As a dealer creates an instance of most cards per game I think this trade off is well worth it. …

use getters for corporation cards

---

src/components/CorporationsFilter.ts

A recent change moved the beginner corporation into a manifest so that it's name can be pulled without needing to specify it wherever we pull the cards by their manifest. This had a side effect of now requiring us to hide the corporation whenever we don't want it displayed. This change hides it from the custom corporations list as it was not showing previously.

hide Beginner Corporation from custom corporations list

---

src/components/card/Card.ts

With the update for corporation cards to extend the base card class the cost is defaulting to zero. This makes the client side logic more robust to never display the cost for corporation cards as they don't have a cost.

hide code for corporation cards

---

src/CardLoader.ts
src/cards/ICardFactory.ts

I had hoped not to start putting behavior specific to the moon yet, but this has been overwritten once already (as code moved from Dealer to CardLoader so I thought I'd get it in now.

Add the ability for a card to need to be compatible with more than one other module.

---

src/CardFinder.ts
src/CardLoader.ts
src/Deck.ts
src/cards/AllCards.ts
src/cards/CardManifest.ts
src/cards/community/PoliticalUprising.ts
src/components/CorporationsFilter.ts
src/components/DebugUI.ts
tests/CardLoader.spec.ts
tests/Deck.spec.ts
tests/cards/CardMetadata.spec.ts
tests/cards/base/RoboticWorkforce.spec.ts

Finish the work for #2215 . Uses a `Map` and `Set` within `CardManifest` and `Deck` to make the look-up more efficient.

use Map for efficient card finding

---

src/Player.ts

This change moves Sell Patents to where it was before. This option is always the last one as in most cases players prefer to pass than actively sell patents. It also avoids auto expanding the cards unless the player deliberately clicked to sell (e.g. https://github.com/bafolts/terraforming-mars/issues/749#issue-627949117)

Restore previous option order where Sell patents is always last option

---

src/components/SelectCard.ts

This should resolve the issue in #2274 . I can't seem to recreate the issue with this in place. Without looking into vue source I would think that it is somehow creating a key based off of something since we didn't provide one. With the recent card change most cards could look the same.

use key when iterating cards

---

src/cards/promo/AsteroidRights.ts
src/cards/venusNext/SulphurEatingBacteria.ts
tests/cards/promo/AsteroidRights.spec.ts
tests/cards/venusNext/SulphurEatingBacteria.spec.ts

For Sulphur-eating bacteria, I put add microbe on top as a default action. Players will more often add microbes instead of removing it.
For Asteroid Right, I put remove asteroid for 2 Ti on top as a default action. Any sane person would do that instead of 1 mc production.

rearrange more often used actions

---

index.html
src/styles/create_game_form.less
src/styles/start_screen.less

`Not affiliated with FryxGames, Asmodee Digital or Steam in any way.`
is now absolutely positioned and reasonable in almost all screens. General layout could be further improved though in another PR.

Fixes the notice stuck to the bottom right

---

src/components/overview/PlayerResource.ts
src/styles/resources.less

New version of the metal bonus indicator as proposed by @ssimeonoff .
Show the value of the metal as a superscript next to the metal icon. Only show the value that is above 2 for steel or above 3 for Ti
Before Unity round. 
During Unity round.

new version of metal bonus indicator

---

src/Game.ts

Once Philares player has passed, the player should not be able to place greenery later using plants obtained from other players' adjacent tile placements

Fix bug where Philares can place final greenery after passing

---

package.json
webpack.config.js

I am planning to pick up the work to show the mega credit total required when initially selecting cards. I plan to rewrite `AndOptions` and `OrOptions` to not rely on `PlayerInputFactory` but instead make use of vue templates. Once in a vue template I plan to then leverage a `SelectInitialCards` (or better name) for displaying that option. Without the custom javascript it should be easier for everyone to read.
While developing locally I have noticed I need to leverage watch so that as I make changes the build is updated for me to save me time. This introduces the tool I use for doing this.
First I start the watch command and leave it running in background
```
npm run watch &
```
Then after I make a change I run `npm run compile` to compile my typescript changes. This in turn gets detected …

add basic support for watching changes

---

src/database/PostgreSQL.ts

Increases the retention for all games to 10 days. This will give us more time to capture data when bug reports come in.

for postgres delete after 10 days for any game

---

src/cards/base/StripMine.ts
tests/cards/base/StripMine.spec.ts

Adds a regression test related to https://discord.com/channels/737945098695999559/742826825922904225/798210229597634631.
The issue is related to an incorrect check which assumes that the user can pay for Reds tax using steel. It seems that canPlay requires 2 checks, namely (1) that the user has enough MC to pay Reds tax, and (2) the user has enough MC plus steel and/or titanium where applicable to pay the card's cost plus Reds taxes.
Pre-Lynesth's Reds tax PR we will likely need to update this check for all other building and space cards that can raise TR as an interim measure.

Add regression test for StripMine with Reds ruling

---

src/Player.ts
src/components/PaymentWidgetMixin.ts
src/components/SelectHowToPay.ts
src/components/SelectHowToPayForProjectCard.ts
src/deferredActions/SelectHowToPayDeferred.ts
src/inputs/HowToPay.ts

Bug from discord where helion could pay 0 mc and 0 heat and buy some cards.
Very ugly one.
It was caused by that line of code:
```ts
app.$data.isResearchPhase = app.playerinput.title === 'Select how to pay for cards';
```
With my card rework I changed the card selection msg to exactly this one, while on main server it was earlier like this: `Select how to pay 6 for purchasing 2 card(s)`.
I removed the unnecessary `isResearchPhase` flag. It was added earlier to allow Helion pay with heat in Research Phase, now it works without it.

Fixed helion card buying bug

---

src/cards/base/RoboticWorkforce.ts

I've introduced a small bug in robotic workforce. This'll fix it.

Use the card as the log's source for name.

---

src/Game.ts
src/components/CreateGameForm.ts
tests/TestingUtils.ts

Setting timer option to be checked by default.
This is only for the info-only timer as its current state. If we ever have a timer with penalty once someone runs out of time, I don't think it should be on by default.

timer on by default

---

src/cards/Tags.ts
src/components/Tag.ts
src/components/TagCount.ts
src/styles/player_home.less

closes #1426
> Move none closer to wild tag since it is still a tag, somewhat.
@vsrisuknimit I'm not sure about moving `none` closer to `wild` just for the sake of it. It will complicate things in code if I do it anyway. But the separation would be helpful for those tag counting events and cards for sure!

Separate Event

---

src/boards/Board.ts
tests/boards/Board.spec.ts

This throws an error when there are no spaces available to avoid blocking the thread. This would take down heroku instance.
Closes #2416

throw when no spaces available

---

src/components/SelectHowToPayForProjectCard.ts
src/models/PlayerModel.ts
tests/components/SelectHowToPayForProjectCard.spec.ts

By simplifying this, it will significantly localize the changes I need to add to accommodate Moon cards with steel and titanium costs.
I am not afraid to say that those tests were a huge pain. But now I know how to do them.
SelectHowToPay is different from SelectHowToPayForProjectCard, but the enterprising coder will merge the two, I am sure.

Reorganize SelectHowToPayForProjectCard, which was needlessly overcomplicated.

---

src/models/GameOptionsModel.ts
src/server/ServerModel.ts

This allows WGT to display correctly here:

add solarphaseoption to gameoptionmodel

---

src/components/ActiveCardsSortingOrder.ts

- Previously we return index 0 for Earth Catapult. This causes `ActiveCardsSortingOrder.get(cardA.name as CardName) || size` to become `0 || size` for Earth Catapult which has index of 0 .The logic statement considers 0 to be false and picks size instead so Earth Catapult was pushed to the back of the blue cards list. @Lynesth helped me with adding +1 index to the map to prevent this.
- Remove size. Use -1 if card is not found instead. This way we make sure that corporation power is in the front, not back.
- Add Ares blue cards to the ordering list.

Update blue card sorting list with Ares and fix Earth Catapult ordering

---

src/cards/promo/CuttingEdgeTechnology.ts

So turns out that I did fix the Tactician but not the Cutting Edge. Sorry for that.
More detailed explanation in https://github.com/bafolts/terraforming-mars/pull/2452

Fixed CuttingEdgeTechnology

---

src/CardName.ts
src/Player.ts
src/cards/Card.ts
src/cards/CardManifest.ts
src/cards/CardType.ts
src/cards/StandardActionCard.ts
src/cards/StandardCardManifests.ts
src/cards/base/standardActions/ConvertHeat.ts
src/cards/base/standardActions/ConvertPlants.ts
src/components/LogPanel.ts
src/components/card/Card.ts
src/components/card/CardTitle.ts
tests/cards/base/standardActions/ConvertHeat.spec.ts
tests/cards/base/standardActions/ConvertPlants.spec.ts
tests/cards/corporation/EcoLine.spec.ts

Hi, once again the Standard Actions - SAs. (I closed old messy https://github.com/bafolts/terraforming-mars/pull/2288 PR and opened this one, clearer imo).
In this PR I've:
1. Added the class StandardActionCard, which is meant to be a class for actions like converting plants / heat, turmoil actions, claiming milestone and similar. This time it is parallel to `StandardProjectCard`, those two do not extend each other. The most important part of it is:
```ts
export abstract class StandardActionCard extends Card implements IActionCard, ICard {
constructor(...) {
super({
cardType: CardType.STANDARD_ACTION,
name: name,
metadata: metadata,
});
}
public abstract canAct(player: Player): boolean
public abstract action(player: Player): PlayerInput | undefined
}
```
2. Added first two SAs - Convert …

Standard actions once again

---

src/components/SelectHowToPayForProjectCard.ts
tests/components/SelectHowToPayForProjectCard.spec.ts

Pay enough mc by default when playing a card. 
This is done by trying to overspend steel and Ti if possible. Then if we are overspending the mc at the end, spend less mc if possible.
This can close #2483 .

Fix not paying enough

---

src/server.ts
webpack.config.js

I have been slowly watching the `gzip` generated file size grow during the static property card refactor. Something with that change doesn't compress as well with `gzip`. Recently discovered brotli (`br`). The compression is much better.
```
Hash: f8a95101496ec90b61fe
Version: webpack 4.44.2
Time: 19076ms
Built at: 01/22/2021 6:33:36 PM
Asset      Size  Chunks                   Chunk Names
main.js   3.7 MiB    main  [emitted]        main
main.js.br   380 KiB          [emitted]        
main.js.gz   560 KiB          [emitted]        
```
Smaller file size means less code server has to send and smaller file client has to download. Everyone wins! 
The browser support is vast.
https://caniuse.com/brotli
If only `gzip` available that is still used as back-up.

use brotli when available

---

compile-vue-templates.js
src/components/SelectSpace.ts
src/components/common/ConfirmDialog.ts
src/styles/common.less

This should work to replace `window.confirm` with a dialog element.
Moved more logic into `methods` from the `mounted` function as well. Eventually we could probably work this all onto the board component.

use dialog element instead of window.confirm

---

src/database/Cloner.ts
src/database/IDatabase.ts
src/database/LocalFilesystem.ts
src/database/PostgreSQL.ts
src/database/SQLite.ts

The sqlite3 bindings return `err = null` when there's no error, but `Cloner.ts` checked `err === undefined`, so it thought there was an error.
This made it past the typechecker due to using `any` all over the place, which I have replaced with `Error | undefined` (or `Error | null` when using the sqlite3 bindings).

Fix loading games from SQLite

---

src/cards/base/CommercialDistrict.ts
src/cards/base/Decomposers.ts
src/cards/base/Herbivores.ts
src/cards/base/Mangrove.ts
src/cards/base/MartianRails.ts
src/cards/base/Plantation.ts
src/cards/base/ProtectedValley.ts
src/cards/base/Zeppelins.ts
src/cards/base/standardActions/ConvertPlants.ts
src/cards/base/standardProjects/GreeneryStandardProject.ts
src/cards/prelude/ExperimentalForest.ts
src/cards/promo/Philares.ts
src/cards/render/CardRenderer.ts
src/cards/turmoil/Recruitment.ts
src/cards/turmoil/VoteOfNoConfidence.ts
src/cards/turmoil/WildlifeDome.ts
src/styles/cards_v2.less
tests/metadata/CardRenderer.spec.ts

#2355
@kevinb9n 
The things I haven't done and probably won't any time soon becaues of other priorities:
- `Celestic: Floater icons should be square` - Current (overall) secondary tag design is round, didn't want to add squares as an exception
- `Arcadian Communities: missing "Effect" banner (space?). Also does it want to use an actual player cube icon perhaps?` - Again, a special case is needed just for one card
- `MIssing asterisk: Factorum (action 1)` - I skipped it when I did the card because, again a special design for just that card might be needed (to have smaller arrows, or smaller MC icon, or custom position for the asterix)
- `Capital (ocean icon)` - Probaby, doable but not in this PR, requires a bit of customization
- `The Trade Fleet icon usually looks like this, is there a …

Minor fixes for cards

---

src/Player.ts
tests/cards/venusNext/Dirigibles.spec.ts

I added `reserveUnits` to `Player.canAfford`.
This allows to simplify the `Player.canPlay` significantly.
In future it could be used a lot in cards:
The `LocalHeatTrapping` could change from:
```ts
public canPlay(player: Player): boolean {
const requiredHeatAmt = 5;
// Helion must be able to pay for both the card and its effect
if (player.canUseHeatAsMegaCredits) {
return (player.heat >= requiredHeatAmt) && (player.heat + player.megaCredits >= requiredHeatAmt + player.getCardCost(this));
}
return player.availableHeat >= requiredHeatAmt;
}
```
to
```ts
public canPlay(player: Player): boolean {
return player.canAfford(player.getCardCost(this), false, false, false, false, {heat: 5});
}
```
and a lot of cards like `Asteroid`:
```ts
return player.canAfford(player.getCardCost(this) + …
```

Player.canAfford - further optimizations

---

package.json

In a chat  with @alrusdi I discovered this was a failed attempt at running a single test, which they now do with local node commands.

Remove testgiven from package.json.

---

src/components/PlayerHome.ts
src/styles/player_home.less

Uses `window.addEventListener` for listening to keyboard events for navigation. This will avoid needing to have any element focused in the DOM.

use window event listener for keyboard navigation

---

src/components/Board.ts
src/components/BoardSpace.ts
src/styles/board.less

Normal ![image](https://user-images.githubusercontent.com/14239220/106386978-98d85480-63a5-11eb-96bc-23a3a3120f6b.png)
Once click 'hide tiles'
It does not persist. As soon as you refresh or other player take an action, the view mode goes back to default. I think this is what we want.
Question: Not sure what the button name should be. 'hide tiles'? 'show bonus'?
Question: Should we show player cube during hide tiles?
Still have to adjust the position so it does show over the card during initial research phase.
This PR can close #2050 .

add button to hide tiles

---

.env.sample
README.md
make_static_json.js
src/components/LogPanel.ts

This commit allows a variable number of lines of history in the game log. The number defaults to 50 to maintain the previous behavior, but can be configured using the new LOG_LENGTH variable noted in the updated README.
I used the same pattern as PostgreSQL.ts (for purge days) to define and parse the number of lines.

Resolves #2587 - Adds a configurable number of history lines in game log via .env variable

---

src/database/PostgreSQL.ts
src/database/SQLite.ts

I don't know why I thought it was already the case, and the undo mechanism I wrote expected it to...
Anyway, so this allow overwriting saves when undoing actions, and fixes the [last known undo bug](https://github.com/bafolts/terraforming-mars/issues/2328) (solo games only).
Edit: I'm not sure what to do in the event the save failed. We only assumed that it would be because of a duplicate entry before that, so I only added a console output for now. Please tell me your thoughts @bafolts @kberg

Use UPSERT in saveGame() to overwrite previous saves

---

make_static_json.js

Fix the version text when built on Heroku. This PR can close #2384.
Before
After
This problem does not happen when build locally. Not sure how to safely get rid of the `(Coordinated Universal Time)` at the end. Also do we want GMT +0? Probably right.

fix version text

---

src/routes/Route.ts
src/server.ts

Start to add support for client side caching. This starts with `styles.css`. Introduces a `notModified` route. Will introduce this in parts for remaining client side resources.

add etag for styles.css

---

src/server.ts
src/server/BufferCache.ts
tests/server/BufferCache.spec.ts

This should make a major dent in the amount of bandwidth we are sending from production environments. Trying to only introduce this when `NODE_ENV=production` to not impact local development where these files may change.
The change is pretty great.
Only 19kb transferred for 7MB.

etag support for assets

---

src/styles/cards.less

I have trouble compiling with my eyes which cards are gray and which are not, this change makes it easier to fast notice.
They are darker now (didn't change opacity).
We could also try grayscale + darker if u want, I don't think it's necessary. 
Before:
After:
Note, it also changes the used blue cards (intended):

Darker unavailable cards instead of grayscale

---

src/components/WaitingFor.ts
src/models/WaitingForModel.ts
src/server.ts
src/server/ServerModel.ts

I have been taking a closer look at the data we send between client and server in an attempt to minimize the bandwidth we use. When looking at the request we use for polling in multiplayer games I discovered a property we aren't using. Eventually I want to minimize this response body to rely on HTTP status codes versus sending any response data as it quickly adds up. Right now we send back roughly 150 bytes every 5 seconds. Over time this quickly becomes megabytes of data. Should be able to use status codes to map to `GO`, `WAIT`, and `REFRESH`. Will do that in separate PR.

remove unused property in polling

---

src/server/ServerModel.ts

Fixed discord bug (created when added displaying Standard Projects):
```
regolith eaters no longer shows how many resources it has under perform an action from a played card
thats kinda annoying
```

Fixed showing resources on cards

---

src/Player.ts

This closes #2713 .
Pass should be as low as possible but still higher than sell cards as users will pass at the end of every gen but should not sell cards unless they are forced to.
More PRs later for making minimalist mode and more player aids on the help page.

move pass below standard projects

---

CONTRIBUTING.md
README.md
src/components/CreateGameForm.ts
src/components/StartScreen.ts

The previous discord link direct you to #general-chat which is not accessible for a new comer, so you will just see a blank screen. You have to select the only available channel on the side bar to see anything.
The new invite link redirects the user directly to the #guidelines channel where they can read the guidelines, obtain a role, and enter the server.

Update discord link

---

src/turmoil/SerializedTurmoil.ts
src/turmoil/Turmoil.ts
src/turmoil/globalEvents/GlobalEventDealer.ts
tests/GlobalEventsDealer.spec.ts
tests/Turmoil.spec.ts

And fix current global event, which still didn't serialize efficiently.

Remove old and out of date fields from Serialized turmoil.

---

src/models/GameOptionsModel.ts
src/server/ServerModel.ts

This fixes an issue where selecting "Mandatory Venus Terraforming" as a game option is not reflected in the popup panel showing the game settings. I tested by creating games with and without the mandatory Venus option and it appropriately shows the correct message (or lack thereof).

Fixes missing Mandatory Venus Terraforming option in game setup details panel

---

src/cards/StandardCardManifests.ts
src/cards/prelude/PreludeCardManifest.ts

This PR can close #2788 . It allows buffer gas to be available when Prelude is not used, as long as 63TR mode is on.

Move buffer gas out of Prelude Manifest

---

src/components/help/Help.ts
src/components/help/HelpStandardProjects.ts
src/styles/help.less

Added the missing standard project colonies. Separate the projects into sections.

add standard project colony, separate into sections

---

src/routes/GameLogs.ts

This introduces support for `br` compression. The `gzip` compression went out yesterday and I didn't notice an impact to CPU. The `br` compression should compress to an even smaller size leading to lower bandwidth usage.

also support brotli compression for logs

---

src/Player.ts
src/cards/CardRequirement.ts

From Discord:
`About fan expansion Agenda: When the Scientists rule and their Ruling Policy is 'Cards with :tag_science: requirements may be played with 1 :tag_science: less', 1 additional :tag_science: is here (which is a good thing) but Orbital Cleanup should not take this tag into account I think :smiley:`

Move Agendas Scientists P4 code to correct place

---

src/server.ts

We are starting to migrate all of the code in `src/server.ts` into separate routes. This makes them easier to unit test. While moving the `/game` route seems we have overlooked a collision where this route name is hit with both PUT and GET. This avoids the collision temporarily.

avoid collision for /game route temporarily

---

src/Game.ts

This PR closes #2362 .
Problem: RemoveColonyFromGame was previously called from newInstance. This means it is not called when the game is cloned via cloner.
This problem did not exist before January. It was caused up by #2223 . New cloner was made without the remove colony check.
Solution: Move that part to gotoInitialResearchPhase. Remove the colony first thing after someone pick their corporation.

fix seeded solo colony

---

src/routes/GameLogs.ts

The heroku instance on terraforming-mars.herokuapp.com has climbed to the highest CPU usage I have seen and response times are high across the board. The log routes are the slowest routes I can see. Changing this to only return the last 50 log messages again. With how the log component UI is written users can still select as many generations back as the 50 log messages contain. This will buy time to put in a fix I plan to do to allow user to select the logs from any generation. Want to get this out to calm down the CPU load.

only show last 50 logs again

---

src/components/card/Card.ts
src/routes/ContentType.ts
tests/routes/ContentType.spec.ts

Seems the `?` operator can't be compiled in a vue-js template in every browser. In firefox I get an error that vue can't parse this template. Will have to upgrade the vue type checker to look for these. Generating the templates at compile time would help here too. Also spotted a bug with the extension for `css`. We use `.gz` suffix and not `.gzip` suffix when naming files for gzip.

avoid ? in vue templates

---

src/components/Party.ts
src/components/Turmoil.ts
src/models/TurmoilModel.ts
src/styles/turmoil.less

This PR can close #2381. It adds a marker for Scientist policy use and more.
The marker will be centered align right below the ruling policy. It will only show up for Scientists policy.
Show nothing for standard Kelvinists policy.
For Agendas policy that has `politicalAgendasActionUsedCount` property. It will show the number inside the cubes.

add turmoil policy use count, fix party boolean

---

src/components/card/CardCorporationLogo.ts

The Saturn Systems HTML contains javascript that is being displayed.
This removes it.

remove formatting from Saturn Systems

---

src/routes/ApiWaitingFor.ts
src/server/ServerModel.ts
tests/routes/ApiWaitingFor.spec.ts

Adds unit tests for the waiting for route. Also took the opportunity to use the search params instead of parsing the query string. This route gets hit quite often so worth being efficient.

unit tests for api/waitingfor

---

src/styles/log.less

Uses `pointer` for `log-card`. This will indicate to users that you can click these items. Will close #2905

use pointer for log-card

---

src/Game.ts
src/GameSetup.ts
src/MilestoneAwardSelector.ts
tests/MilestoneAwardSelector.spec.ts

This in part starts to make #2577 easier, but mostly it's so I can integrate the Moon's milestones and awards into this without too much trouble. It also clarifies and simplifies a few changes.
This change is best reviewed commit-by-commit.
I have a few more changes coming, but this is a good starting point.

Refactor the MIlestoneAward selelctor

---

src/routes/ApiPlayer.ts
src/routes/Handler.ts
tests/routes/ApiPlayers.spec.ts

Removes a few usages of `querystring` as we are parsing the query string twice. Adds unit tests to verify.

remove querystring and add unit tests

---

src/components/GameEnd.ts

The new properties on `log-panel` were not added to the `log-panel` component shown on `GameEnd`. This adds the properties which are required.

add missing properties to log-panel for GameEnd

---

src/Player.ts
src/components/overview/PlayerInfo.ts
src/models/PlayerModel.ts
src/server/ServerModel.ts
src/styles/player_home.less

This PR adds a counter for available blue card action for each player. This will help the players know who can outlast them in the generation.

blue action counter

---

src/CardLoader.ts
src/Player.ts
tests/Player.spec.ts
tests/TestPlayer.ts
tests/turmoil/Turmoil.spec.ts

The check to show buffer gas was relying on the game option versus checking for solo mode. This moves the check to `Player` and looks for solo mode. Unit test was added to verify this logic.

only show buffer gas for solo games

---

package-lock.json
package.json

The dependabot has flagged a security concern with a dependency webpack used to use.
https://github.com/bafolts/terraforming-mars/security/dependabot/package-lock.json/elliptic/open
This upgrades webpack to 5.25.0 which should no longer rely on the problematic dependency. Never a perfect time to update but as there is an excuse here with the security alert better time than never.

upgrade webpack to 5.25.0

---

src/server.ts

The default uncaught exception handler stops the node process. This is a problem since heroku doesn't re-start the app. This implements an uncaught exception handler so that the node process does not stop.
https://nodejs.org/api/process.html#process_event_uncaughtexception
With this application this should only prevent one game from working versus taking down the application. This should allow us to determine what went wrong versus today where we have to hope a good willed developer redeploys the app.

log uncaught exceptions

---

src/Player.ts
tests/Player.spec.ts

The logic implemented with unit tests for Buffer Gas I had completely backwards and only showed Buffer Gas for multi player games. This shows buffer gas only for solo games. Closes #2961

should only show Buffer Gas for solo games

---

src/Player.ts
tests/Player.spec.ts

This PR fixes #2973 . Buffer Gas is on IF AND ONLY IF (1) it is solo mode AND (2) 63 TR mode is on. Off otherwise.

Fix Buffer Gas Again

---

src/Player.ts
src/cards/base/Cartel.ts
src/cards/base/EnergySaving.ts
src/cards/base/Insects.ts
src/cards/base/MirandaResort.ts
src/cards/base/PowerGrid.ts
src/cards/base/Satellites.ts
src/cards/base/TollStation.ts
src/cards/base/Zeppelins.ts
src/cards/colonies/EcologyResearch.ts
src/cards/colonies/QuantumCommunications.ts
src/cards/venusNext/Gyropolis.ts
src/cards/venusNext/LunaMetropolis.ts
src/cards/venusNext/SulphurExports.ts
tests/cards/base/Cartel.spec.ts
tests/cards/base/MirandaResort.spec.ts
tests/cards/base/PowerGrid.spec.ts
tests/cards/base/Satellites.spec.ts

This closes #2956.
Only log the production gain for card with variable gain such as Cartel, Miranda Resorts, etc.

add log for multiplier production cards

---

tests/cards/ares/DesperateMeasures.spec.ts

hazard tile with player marker is not removed after placing the sixth ocean
I wrote this to track down bug #2904 but it is not reoccurring, even via manual test.

Add Desperate Measures test

---

src/cards/moon/DarksideMiningSyndicate.ts
src/cards/moon/DarksideObservatory.ts
src/cards/moon/LunaPoliticalInstitute.ts
src/cards/moon/LunaProjectOffice.ts
src/cards/moon/LunaTrainStation.ts
src/cards/moon/MooncrateBlockFactory.ts
src/cards/moon/StagingStationBehemoth.ts
src/cards/render/CardRenderDynamicVictoryPoints.ts

Once this is merged, only `Earth Office` remains as the medium-priority card to fix. The rest are medium-low and low.

Fix visualization on 8 Moon cards.

---

src/VictoryPointsBreakdown.ts
src/components/GameEnd.ts
src/styles/game_end.less

- icons in the table header 
- Combining the two wide cells (player+corporation) in one
- bigger numbers (so posted results in discord to be more visible without opening the original image)
- vp details columns of 4 players to fit the mobile width 
- vp details columns to easily show the points - vp are now aligned in their own sub-column
- column MC -  I like the idea this to be completely gone and when there is a tie a MC icon with the value in it is displayed next to the Total vps for that player. E.g. 77 [50] - 77vp total and 50mc. I can't it at the moment, so I leave it for now as it is.
- time + mc columns position - I agree that those two show more of a meta info, not real VPs, but I think "Total" column being last looks better. 
- table VPs per generation - this is in the …

Game End page tables rework

---

src/routes/ApiWaitingFor.ts
tests/routes/ApiWaitingFor.spec.ts

I was dual writing `prev-game-age` and `gameAge` to handle the transition for clients which may had been polling with `prev-game-age`. Removing for good now.

remove prev-game-age for good

---

src/Player.ts
src/PlayerInput.ts
src/components/PaymentWidgetMixin.ts
src/components/SelectHowToPayForProjectCard.ts
src/inputs/SelectHowToPayForProjectCard.ts
src/server/ServerModel.ts
tests/components/SelectHowToPayForProjectCard.spec.ts

This commit does a few things: it deals with keeping track of what the
proper remaining steel and titanium a player may use and applies it
throughout the algorithm. That was the most complicated part -- no --
writing the tests was the most complicated part.
There's a bit of code in SHPTFPC which uses the player's played cards,
and includes the self replicating robots as its source for card data.
That just seems wrong. Of the many changes in this commit, that's the
one I'm most surprised is in the code, and the one I most want someone
to scrutinize and evaluate.
I rewrote the tests, but just a bit -- to take advantage of things like
Partial<>.
Finally, there's a server-side change which verifies that someone can't
overspend their steel, consequently, they can't go negative. Now, this
won't …

Make SelectHowToPayForProjectCard work with Moon cards.

---

src/components/GameEnd.ts
src/styles/game_end.less
src/styles/player_home.less
src/styles/players_overview.less

Fixes: 
- Reverted to "Ubuntu" on the game and and player boards (forgot that Prototype does not display well non-english text)
- reverted the "cards in hand" back to black (my fault for making it a bit transparent)
- fixed the discount icon position on all cards in the player board
- fixed game end table when no timer option is selected
- (hopefully haven't missed/messed now)

Game end and player board css fixes

---

src/components/SelectHowToPayForProjectCard.ts
tests/components/SelectHowToPayForProjectCard.spec.ts

This can close #3042.
When the app tries to reduce overspending, it should save steel only if it is actually spending steel. 
The bug was introduced by #3025. When the app sees that it is overspending by 2 mc and the player has steel, it tries to reduce the amount of spending steel by 1 even if that amount is already 0. As a result, the player is trying to pay with negative one steel forcing the player to have to overspend by 2 mc to cover that deficit.

Fix the problem with selectHowToPay

---

src/routes/ApiWaitingFor.ts
tests/routes/ApiWaitingFor.spec.ts
tests/routes/HttpMocks.ts

First usage of the `ETag` I think we can leverage for most routes. This implements for the waiting for route. During multi player games this should be hit often. This saves 100 bytes or so from the normal response. Over time this will add up to saved bandwidth!

add ETag for waiting for route

---

src/routes/ApiWaitingFor.ts
tests/routes/ApiWaitingFor.spec.ts

Will need a different strategy for generating the `ETag`. The strategy I was using relied on `gameAge` being incremented. Nothing must be logged during the initial drafting phase. Without `gameAge` being updated this hashing strategy doesn't work.

Do not use ETag header for waiting for route.

---

src/Dealer.ts
src/Game.ts

Getting the player before or after can be simplified, and deck shuffling can be static.

Two cleanups

---

src/turmoil/globalEvents/GenerousFunding.ts
tests/globalEvents/GenerousFunding.spec.ts

This PR can closes #3058 .
It counts zero set of 5 TR, if TR is not greater than 15, instead of negative number as before.

fix generous funding global event

---

src/cards/base/HiredRaiders.ts
src/cards/base/Sabotage.ts
src/cards/venusNext/CometForVenus.ts
tests/cards/base/HiredRaiders.spec.ts
tests/cards/base/Sabotage.spec.ts
tests/cards/moon/LunarSecurityStations.spec.ts
tests/cards/venusNext/CometForVenus.spec.ts

This can close #2954 . Currently, Sabotage, Hired Raiders, and Comet for Venus do not offer an option not to attack someone. The rule allows players not to attack. Players may want to do that if they are Mons Insurance or expect someone to have Law Suits.
I tried changing RemoveAnyPlants to RemoveAnyResources but it will cover just Comet for Venus and Flooding. The deferred action is not great for Hire Raiders and Sabotage which have multiple resource type targets. So I decided to go with this option instead.

add option not to attack

---

src/turmoil/Turmoil.ts

This can close #3057, for now at least. 
We don't have a way to show the turmoil card once clicked yet. That is not how the turmoil event cards are rendered. 
For now, just showing the name of the global event that just happened should be helpful enough. Players can look them up later on Simon's database. But eventually we may want to consider rendering the global event as a unit of card.

global event name in the log

---

src/turmoil/globalEvents/Sabotage.ts

This PR can close #2380. It should try to reduce the steel/energy production if the player has any. This prevents inaccurate log report.

Sabotage Global Event reduce only if has any

---

compile-vue-templates.js
src/components/Preferences.ts
src/components/PreferencesManager.ts
src/styles/preferences.less

This PR improves on #2969 .
It makes the color brighter but with gradient toward the bottom so the text on the top are not impossible to see. It also rotates the player cube slowly as movement should get attention of users.
It is possible to hide this animation from the Preferences panel.
Example
https://user-images.githubusercontent.com/14239220/112772426-b79e4480-8ffe-11eb-892c-cf326012b8e8.mov

Hidable animated side bar

---

src/cards/community/CuriosityII.ts

This PR fixes the issue that Curiosity production cannot be copied by Robotic Workforce.

allow curiosity ii to be copied by robotic workforce

---

src/VictoryPointsBreakdown.ts
src/components/GameEnd.ts

This PR closes #3027 .
It would be better if we rename the promo cards to `Great Dam (promo)` instead of `Great Dam:  promo`, but that will breaks existing games.

Fix promo card on end game page

---

src/PlayerInput.ts
src/cards/colonies/TitanShuttles.ts
src/cards/venusNext/SulphurEatingBacteria.ts
src/components/SelectAmount.ts
src/inputs/SelectAmount.ts
src/models/PlayerInputModel.ts
src/models/ServerModel.ts

This PR can close #3099 .
Any sensible player should only activate these cards when they want to convert everything to MC or Ti. Current implementation make it likely someone might not convert everything or just convert 1. That would be a game-ruining move.

Make max amount by default for TitanShuttles and SEB

---

src/deferredActions/SendDelegateToArea.ts
src/turmoil/Turmoil.ts

This PR can close #3114 .
Switching Mars First
Mars First still dominant
Test with Banned Delegate
In this case, dominance check happens properly.

Fix recruitment

---

src/components/SelectCard.ts

If working properly, this PR can close #3104.
It only adds a number to the button for selectCard only if selectCard allows it to select more than one card.
It works properly for 'Buy' during Research Phase.
But somehow it does not work for 'Sell'. 
Again it has some weird thing to do about the 'Sell' button not really being a part of SelectCard.

Fix card number on button

---

src/Game.ts

While trying to recreate #3116 I noticed we compare `milestone` and `award` with the `===` operator. I don't think this is causing the bug in the ticket but it requires us to pass the same instance of the `milestone` and `award` when calling to see if a milestone or award has been claimed or funded. This changes to check the `name` property.

check name when comparing award and milestone

---

src/components/LogPanel.ts
src/components/SelectSpace.ts

Uses a key for the displayed cards. Using only `index` was leading to the bugs seen in the video provided with the bug. This fixes #2264 . Also saw we weren't passing in a boolean as expected. Vue was logging a warning regarding the `enableDontShowAgainCheckbox`. Updated that to use a boolean.

use better key for logged cards

---

src/Player.ts
src/cards/ICard.ts
src/cards/base/CEOsFavoriteProject.ts
src/models/ServerModel.ts
tests/Player.spec.ts
tests/cards/base/CEOsFavoriteProject.spec.ts

Fixes #2453 . Allows `CEOsFavoriteProject` to add resources to `SelfReplicatingRobots` cards.

allow CEOsFavoriteProject to select SelfReplicatingRobots cards

---

src/routes/PlayerInput.ts
tests/routes/PlayerInput.spec.ts

I plan to start improving the action we currently know as undo. On my quest I stumbled upon this small clean up. Uses the search params instead of parsing the id out of the query string. Added unit test for the route to verify my addition of added bad request response.

use searchParams for player input

---

src/styles/ares.less

Get the Moon secondary tag to go where it belongs, above the empty tile.

---

src/components/card/CardRenderTileComponent.ts

Restore proper non-ares tile visualization.

---

src/turmoil/globalEvents/GlobalEventDealer.ts

Uses a `Map` instead of `Array` for the global event dealer. This will improve the look-up time of `getGlobalEventByName`.

use a map for turmoil global events

---

src/Player.ts
src/components/WaitingFor.ts
src/database/GameLoader.ts
tests/Player.spec.ts

This is part 2 (of 3 or 4) on a quest to have undo work without needing to click refresh. After this change after performing an undo the user will see the message "Not your turn to take any actions". Seconds later once we again query for the updated player the latest player object will be returned. This is still not perfect but better. In the change after this I plan to wait to send the updated player response until the database has rolled back. Once all of these commits are in when a player performs the undo last action they wont have to remember to click refresh.

set usedUndo synchronously

---

src/components/Award.ts
src/components/Board.ts
src/components/DebugUI.ts
src/components/LanguageSwitcher.ts
src/components/LogPanel.ts
src/components/Milestone.ts
src/components/OrOptions.ts
src/components/PlayerHome.ts
src/components/Preferences.ts
src/components/PreferencesManager.ts
src/components/SelectHowToPay.ts
src/components/SelectHowToPayForProjectCard.ts
src/components/SelectInitialCards.ts
src/components/SelectSpace.ts
src/components/TopBar.ts
src/components/WaitingFor.ts
src/components/card/Card.ts
src/components/card/CardCost.ts
src/components/card/CardNumber.ts
src/components/overview/PlayerInfo.ts
src/components/overview/PlayerResource.ts
src/directives/i18n.ts

1. Limit valid fields to a key type. Avoiding using the namespace/enum solution as it seems namespaces and enums are deprecated. Huh.
2. Shortened the method names. Shorter and easier to read. 
3. Added default value parameters. These will help us standardize on `show` versus `hide` as a parameter name. In the long run.
4. Encompassed boolean management inside PreferencesManager. Each bit of code did their own thing, but all of them used `1` as a true, so it was easy to internalize.

Rework the preferences API.

---

compile-vue-templates.js
src/components/create/CardsFilter.ts
src/components/create/CreateGameForm.ts
src/styles/corporations_filter.less
src/styles/create_game_form.less

Backend already supports prelude filtering via cardsBlackList, so i've done only client side part.
Added small visual hint to distinguish project cards and preludes in cards filter widget:

Prelude cards filter; Create game form page styling fixes

---

src/ares/AresHazards.ts
tests/ares/AresHandler.spec.ts

Keep Desperate Measures from being removed when tiles are upgraded to severe.

---

src/turmoil/Turmoil.ts
tests/cards/moon/TempestConsultancy.spec.ts
tests/turmoil/Turmoil.spec.ts

Chairman uses deferredAction to resolve the policy, so TR increase should be deferredAction too. This way TR from being a chairman is not raised until after the new ruling bonus is resolved.

Fix reds and chairman

---

src/components/TopBar.ts

Commit` #3212 reversed the topbar logic
```
isExpanded(): boolean {
-      const val = PreferencesManager.load('hide_top_bar');
-      return val !== '1';
+      return PreferencesManager.loadBoolean('hide_top_bar');
},
```
This fixes it and works in my test.

Fix the top bar expansion logic

---

src/cards/moon/HE3FusionPlant.ts
src/cards/moon/LunaHyperloopCorporation.ts
src/components/GameEnd.ts
src/styles/game_end.less

Using icons instead.
Also for two cards I just made larger tile icons, they looked better.

[Moon] Two card render fixes and Game End render fixes.

---

assets/index.html
src/styles/common.less

This means if, for instance, you get a server error, it won't scroll all the way to the top of the page.
Here's where this happens all the time: select "Take an action from a played card" but don't select a card. Before, the whole page scrolled up. Now the page doesn't move just to show the error dialog.
Before:
After:

Alert dialog is now in fixed position.

---

src/Game.ts

This seems to work with @bafolts by-generation log filter just because it happens to be the last one.

Add log for final greenery placement.

---

src/Game.ts
src/Player.ts
src/deferredActions/DeferredActionsQueue.ts
tests/Player.spec.ts

Reviewer: the key is that the new function signature for `setWaitingFor` which sets a default second parameter:
`public setWaitingFor(input: PlayerInput, cb: () => void = () => {}): void {`

Minor optimization on waitingFor API, and related simplifications.

---

src/Player.ts
src/SerializedPlayer.ts
src/components/WaitingFor.ts
src/database/GameLoader.ts
src/inputs/UndoActionOption.ts
src/routes/PlayerInput.ts
tests/Player.spec.ts
tests/routes/PlayerInput.spec.ts

This is a step towards a more robust and reliable undo. This change waits to send the response of the action until we have rolled the game back within the database and javascript memory. It also moves the logic out of `Player` making it clearer how this works.
I still need to update the unit tests.

perform undo asynchronously

---

src/cards/turmoil/CulturalMetropolis.ts
tests/cards/turmoil/CulturalMetropolis.spec.ts

#3252 broke this with a sloppy deletion of canPlay() from cultural metropolis.
This PR adds back the requirement check for energy and delegate count. It also improves the tests on this card.

fix cultural metropolis canPlay bug

---

src/Player.ts
tests/Player.spec.ts

Considers how much is removed from a player for the mons insurance hook. Fixes #3281 
Added regression test.

consider delta for Mons Insurance and Lawsuit

---

src/Game.ts
src/deferredActions/DeferredActionsQueue.ts
tests/deferredActions/DeferredActionsQueue.spec.ts

This can close #2498 . During the research phase if a player has deferred actions those actions will be set for that player before they are done with their research phase. Will no longer run the deferred action for all after research phase.

add methods to DeferredActionsQueue to act for Player

---

.github/stale.yml

The current state of activity doesn't necessitate a 90-day deadline.

Reduce stale latency to 500 days

---

src/ares/AresHazards.ts
src/cards/ares/OceanCity.ts
src/cards/ares/OceanFarm.ts
src/cards/ares/OceanSanctuary.ts
tests/cards/ares/OceanCity.spec.ts
tests/cards/ares/OceanFarm.spec.ts
tests/cards/ares/OceanSanctuary.spec.ts
tests/cards/base/RoboticWorkforce.spec.ts
tests/cards/community/CuriosityII.spec.ts

The existing solution doesn't work. Oh, it might have at the beginning. But the bits of code in Ocean* that remove a tile before placing another one introduced this regression.
Turns out this was easy to fix, but it impacted a few tests along the way.
Fixes #2843

Placing a tile on top of another one should not trigger space bonus.

---

src/Player.ts
tests/TestPlayer.ts

Moves the `public` runInput method to `TestPlayer`.

make runInput protected

---

src/components/overview/PlayerResource.ts
src/components/overview/PlayerResources.ts

It's not used at all, and the code that manages increasing the alloy values is already taken into consideration when generating the player model.

Remove Turmoil from PlayerResources.

---

src/Game.ts

Was looking into when we change game phase to `Phase.END`. Spotted an unnecessary check for `Phase.END` left over from a migration.

Remove check that is not needed

---

src/database/GameLoader.ts
src/database/IGameLoader.ts
src/routes/PlayerInput.ts
tests/database/GameLoader.spec.ts
tests/routes/FakeGameLoader.ts
tests/routes/PlayerInput.spec.ts

The first try with garbage collection I ended up blocking the main thread iterating through every game. The strategy this time is to set a timeout when the game transitions to the end phase. This will avoid having to iterate through thousands of games at once. It will also allow for a finished game to remain in javascript memory for an hour.
The goal of this ticket is to cut down on the amount of memory being used on the heroku instance. With no process in place today to every free memory we eventually use enough that heroku tries to restart the dyno. We have seen in the past that when it restarts the dyno it sometimes fails to start.

try removing ended games again

---

src/database/GameLoader.ts
src/database/IGameLoader.ts
src/routes/PlayerInput.ts
tests/database/GameLoader.spec.ts
tests/routes/FakeGameLoader.ts
tests/routes/PlayerInput.spec.ts

Reverts bafolts/terraforming-mars#3327
Seeing strange memory spikes again after this change. The good news is I think something is being learned from each of these attempts at freeing memory. I am pretty sure users are attempting to access their game after we have removed it from javascript memory and those requests time out. When requests time out like in #3331 I am not sure what happens to the `req`, `res` or any memory we create along the way. I am guessing it piles up. Heroku cancels the request external of our node code.

Revert "try removing ended games again"

---

src/database/PostgreSQL.ts

This should close #3331 . I believe eventually the one `Client` we use for Postgres throws an error and we never reconnect. Using a `Pool` should always open a new connection for us when needed.
Tested this locally with the terraforming-mars.herokuapp.com postgres connection string.

use a Pool instead of one Client for postgres

---

src/components/Sidebar.ts

There is javascript we rely on running as the `PreferencesDialog` component is mounted. Using `v-show` ensures that it is mounted and runs javascript to apply css to the DOM. This can close #3321 
Where we call to `syncPreferences()`.
https://github.com/bafolts/terraforming-mars/blob/main/src/components/PreferencesDialog.ts#L103

use v-show to run preferences javascript

---

src/routes/ServeAsset.ts

At some point I remember suggesting using `Set(req.headers['accept-encoding'])` to be clever. This has caused a bug. Since `req.headers['accept-encoding']` returns a `string` we end up with a `Set` that has each character in the string as an element in the set. This changes the code to pull the values from the array. The logic is now written out to enforce the typing as well as avoiding a type cast.
Tested this locally.
This closes #3348

pull in encodings as string and not array

---

src/cards/base/Decomposers.ts
src/cards/base/EcologicalZone.ts
tests/cards/base/Decomposers.spec.ts
tests/cards/base/EcologicalZone.spec.ts

This PR can closes #3344 .
Note that EcoZone's requirement is not overridden by EcoExperts but it is possible to get a greenery tile from Experimental Forest and then play EcoExperts ignoring its benefit just so you can play EcoZone during the Preludes phase. If we are already talking about terrible plays (EcoExpert on Decomposers), we might as well fix this unimaginably bad play.
¯\\\_(ツ)\_/¯

Add Ecoexperts interaction with deco-eco

---

src/cards/ares/EcologicalSurvey.ts
src/cards/ares/GeologicalSurvey.ts
tests/cards/ares/EcologicalSurvey.spec.ts
tests/cards/ares/GeologicalSurvey.spec.ts

Fixes #3358.
I'll follow this up with code that removes the duplication between these cards.

Don't grant bonuses to Ecological Survey and Geological Survey when overplacing tiles.

---

src/Game.ts
src/Player.ts
tests/Game.spec.ts
tests/cards/promo/Philares.spec.ts

Instead of relying on knowing that Philares is involved and shunting it into the existing code, this makes the assumption that if a player has a `waitingFor` they just aren't done. It also abandons precomputing whether a player may place greeneries during the phase start in favor of determining whether the player can place a greenery when it's that player's turn.
It's kind of unfortunate that this doesn't just use the existing code about active players and transitions, making it understandably difficult to parse and understand. I hope this code is easier to understand, made even easier by comments. Add more comments as need be. I will probably add more.

Vastly simplify taking final greenery action, making it philares-compatible

---

src/components/App.ts
src/components/common/ConfirmDialog.ts

I verified this manually on Chrome, looks reasonable.
For the most part this removes clutter warnings from tests such as what is below. I got the conditional by reading the code for dialogPolyfill:
```
dialogPolyfill.forceRegisterDialog = function(element) {
if (window.HTMLDialogElement || element.showModal) {
console.warn('This browser already supports <dialog>, the polyfill ' +
'may not work correctly', element);
}
...
};
```

Only register with Polyfill when window does not contain HTMLDialogElement.

---

package.json

Removed: `--mode development`
There is no [option](https://sysgears.github.io/mochapack/docs/installation/cli-usage.html) `mode` in mochapack cli
Removed: `--webpack-config webpack.config.js`
webpack.config.js is set by default
Removed: `npm run compile`
Seems like this command is unnecessary here 🤔
Added watch mode to component testing. No more waiting 15s+ to check a test

Improve components testing

---

src/cards/venusNext/HydrogenToVenus.ts

Related to issue #3414
The name-based filter from `HydrogenToVenus.venusCardsWithFloaters` was unable to perform a text-compare on `CardName.CELESTIC` vs. `CardName.CELESTIC_REBALANCED`
Replaced with a check to see if the card contained any tags (copied from `Player.getTagCount()` https://github.com/bafolts/terraforming-mars/blob/26eecb167bed1595405193c555ea48fe6e04a01a/src/Player.ts#L770

Change Hydrogen To Venus name-based filter to tag-based

---

src/server.ts

Something has started to request HEAD requests every few minutes to terraforming-mars.herokuapp.com. This change ignores the request. Without ignoring these requests they time out as we don't support HEAD requests. Test this with curl locally.

ignore HEAD requests

---

src/Game.ts
src/Player.ts
src/cards/CardRequirement.ts
src/cards/community/ByElection.ts
src/cards/community/Incite.ts
src/cards/moon/LunaPoliticalInstitute.ts
src/cards/moon/TempestConsultancy.ts
src/cards/turmoil/BannedDelegate.ts
src/cards/turmoil/CulturalMetropolis.ts
src/cards/turmoil/EventAnalysts.ts
src/cards/turmoil/MartianMediaCenter.ts
src/cards/turmoil/Recruitment.ts
src/cards/turmoil/SeptumTribus.ts
src/cards/turmoil/VoteOfNoConfidence.ts
src/cards/turmoil/WildlifeDome.ts
src/colonies/Colony.ts
src/deferredActions/SendDelegateToArea.ts
src/milestones/Terraformer.ts
src/models/ServerModel.ts
src/models/TurmoilModel.ts
src/turmoil/Turmoil.ts
src/turmoil/parties/PartyHooks.ts
tests/cards/turmoil/SeptumTribus.spec.ts

While there are places where this change is slightly more complicated, it eliminates the need for if(there's a turmoil object) guards, and more important the (I know there's turmoil, so `game.turmoil!`) cases. Those will still fail with an error, but the error will report which game was the problem.
In a couple of places, it looks like a huge change, and it's just whitespace. I tried to avoid those but the linter insisted. Use the github code review feature that ignores whitespace - I'm sure you know how to do that.
There are some places where it seems I removed guards. For example `Septum Tribus`, which had a `canPlay` test. But Septum Tribus is a Turmoil card. `game.turmoil` WILL be there. In fact, the card won't even be in the deck without it. That kind of made the test useless, which …

Add Turmoil.ifTurmoil, Turmoil.ifTurmoilElse, Turmoil.getTurmoil.

---

src/cards/moon/LunaEcumenopolis.ts
tests/cards/moon/LunaEcumenopolis.spec.ts

According to the designer:
> That card is based on "Terraforming Ganymede" card of the original game. Ganymede card grants 1 TR per Jovian tag plus 2VPs at the end of the game.  Yes both cards have a high potential but they can be played at the very end of the game. Plus Luna Ecu has a requirement to place your colonies to adjacent colonies, and due to placements and/or cards played just to increase colony rate without placing colonies on Moon, you may not find the chance to play it at all.
However,
> For Terraforming Ganymade you has to put effort in building up your jovian tag yourself, but with Luna Ecu you don't need to invest in the colony rating at all and you will get this great award anyway. The only difference is the requirement that you have to place the colony tiles, which is …

Nerf Luna Ecumenopolis.

---

src/database/Database.ts
src/server.ts

Before
```
[2021-07-17 11:41:05 EDT] Starting server on port 8080
[2021-07-17 11:41:05 EDT] version 0.X
[2021-07-17 11:41:05 EDT] 
The secret serverId for this server is a20008759bcd. Use it to access the following administrative routes:
[2021-07-17 11:41:05 EDT] * Overview of existing games: /games-overview?serverId=a20008759bcd
[2021-07-17 11:41:05 EDT] * API for game IDs: /api/games?serverId=a20008759bcd
```
After
```
[2021-07-17 11:45:11 EDT] Starting server on port 8080
[2021-07-17 11:45:11 EDT] Connecting to SQLite database.
[2021-07-17 11:45:11 EDT] version 0.X
[2021-07-17 11:45:11 EDT] 
[2021-07-17 11:45:11 EDT] The secret serverId for this server is c60a5e4f3b63. Use it to access the following administrative routes:
[2021-07-17 11:45:11 EDT] * Overview of existing games: …
```

Provide slightly better information during startup logging

---

src/Log.ts
src/Message.ts
src/components/LogPanel.vue
src/directives/i18n.ts
tests/TestingUtils.ts

I verified that this works in a local game in English and another langauge. Plus the unit tests themselves rely on the TestUtils to work as expected.

Centralize parsing the log message.

---

Dockerfile

I'm not sure if it affects only ARM builds but I could not manager to build TMars without these changes.
- Justification for the change with chown : https://github.com/docker/for-linux/issues/388
- Justification for the virtual gyp to be able to build npm libs on ARM :  https://github.com/nodejs/docker-node/issues/282

Fix build on ARM + faster chown

---

src/database/SQLite.ts

- made sqlite implementation consistent with postgresql one in that by default running games are purged after 10 days
- fixed the purge query to work

Fixed issues with purging old running games in sqlite database

---

src/cards/moon/WaterTreatmentComplex.ts

Bug report from Discord. The card does not seem like it should decrease plant production. The reserved unit cost of 1 Ti is already covered by `player.deductUnits(adjustedReserveUnits)` in `ProjectCard`

Remove incorrect line in Water Treatment Complex

---

src/Player.ts
src/cards/promo/InterplanetaryTrade.ts
src/constants.ts
tests/cards/promo/InterplanetaryTrade.spec.ts
tests/milestones/Diversifier.spec.ts

Planetary Trade (card) should not count Venus tag or Moon tag by default.

fix interplanetary trade

---

src/database/GameIds.ts
src/database/GameLoader.ts
src/database/IGameLoader.ts
src/routes/ApiGames.ts
tests/database/GameLoader.spec.ts
tests/routes/FakeGameLoader.ts

Hello, everyone,
this is an attempt to fix #2802, unfortunately it comes with rather major refactoring of the `GameLoader` class.  Please be gentle with me, because I have not written for nodejs before, and I have not used typescript before, so I have certain gaps in the knowledge. I do understand how nodejs works in principle, though.
I tried to keep the spirit of the functionality of the class intact, and only change what is required for better flow, and for adding the [necessary callback](https://github.com/bafolts/terraforming-mars/pull/2807#discussion_r579861467) for fixing the issue.
The need to refactor the `GameLoader` class came from the desire to streamline and simplify state tracking and callbacks that were used there before the refactoring.
The main idea behind the refactoring …

An attempt to fix #2802

---

src/database/SQLite.ts

Reverts bafolts/terraforming-mars#3470
We have an issue where we don't wait for queries to finish running. The tables haven't necessarily been created by the time we call to `purgeUnfinishedGames`. We will need to fix this problem as it is preventing a fresh clone from starting without error.
This will close #3500 for the time being until we can improve our `IDatabase` implementations.

Revert "Fixed issues with purging old running games in sqlite database"

---

src/database/SQLite.ts

Since https://github.com/bafolts/terraforming-mars/pull/3470 was reverted, this is a lighter fix that does not change the timing. It just fixes the syntax error in the SQLite query.
Note: the timing issue might be present both before and after the fix and will need to be addressed separately.

fixed syntax error in the SQLite purge query

---

src/components/PreferencesDialog.vue

Fixes a vue warning.
```
vue.esm.js:628 [Vue warn]: Duplicate keys detected: '[object Object]'. This may cause an update error.
found in
---> <PreferencesDialog> at src/components/PreferencesDialog.vue
<Sidebar> at src/components/Sidebar.vue
<PlayerHome> at src/components/PlayerHome.vue
<Root>
```

use string for key with v-for

---

src/Player.ts
tests/cards/colonies/TradingColony.spec.ts

Fix for bug raised in https://discord.com/channels/737945098695999559/742721510376210583/874003713889562624. Also adds missing tests for TradingColony to verify existing and new behaviour.

Fix: Colony placement cards should only consider active colonies

---

src/Player.ts
tests/turmoil/parties/Scientists.spec.ts

Bug reported on https://discord.com/channels/737945098695999559/742721510376210583/873835903758499851. Agendas Scientists P4 should consider a bonus Science tag for cards with multiple tag requirements.

Fix: Agendas Scientists P4 for multi-tag requirements

---

src/components/overview/PlayerInfo.vue
src/components/overview/PlayerStatus.vue

Fixes minor issue with recent refactor. This warning was seen prior to this change.
```
vue.esm.js:628 [Vue warn]: Error in render: "TypeError: Cannot read property 'timer' of undefined"
found in
---> <PlayerStatus> at src/components/overview/PlayerStatus.vue
<PlayerInfo> at src/components/overview/PlayerInfo.vue
<PlayersOverview> at src/components/overview/PlayersOverview.vue
<PlayerHome> at src/components/PlayerHome.vue
```
Would have expected vetur to catch this but it may not be as robust as we expect. Could consider failing component tests on any warning from vue.

use playerView instead of player for PlayerStatus component

---

package-lock.json
package.json
src/routes/ServeAsset.ts
webpack.config.js

It's a little workaround because backend doesn't have separation of prod/dev mode.
1. If there is no `main.js.br` - the server sends original js file. This uncompressed file is necessary in front dev mode
2. The `npm run watch` command now deletes `.js*.br` and `.js*.gz` files before it runs
3. Webpack compression plugin is only available in production mode
4. `NODE_ENV` is now explicitly set for each of build/dev command
1. Users will no longer build their instances in webpack development mode. (to build in production mode you must have NODE_ENV set to the `production` and nobody except heroku has)
2. Recompiling components in `npm run watch` now takes 20x faster
3. Rerun test in `npm run test:componets:watch` now is instant

Improve DX

---

assets/index.html
src/components/AndOptions.vue
src/components/App.ts
src/components/GameEnd.vue
src/components/OrOptions.vue
src/components/PaymentWidgetMixin.ts
src/components/PlayerHome.vue
src/components/PlayerInputFactory.vue
src/components/SelectCard.vue
src/components/SelectHowToPay.vue
src/components/SelectHowToPayForProjectCard.vue
src/components/SelectInitialCards.vue
src/components/TopBar.vue
src/components/WaitingFor.vue
tests/components/PlayerInputFactory.spec.ts
tests/components/SelectHowToPay.spec.ts
tests/components/SelectHowToPayForProjectCard.spec.ts
tests/components/SelectInitialCards.spec.ts

Depends on #3563 and #3564
Rather than rename all the fields in all the components at once, this commit uses computed to ease the transition. Then I can do the change for each one individually. But these have to be in a bunch because there's a cross-reference between them thanks to the relationship between PlayerInputFactory, AndOptions and OrOptions.

Have input selection use playerView

---

src/cards/Card.ts
src/cards/CardMetadata.ts
src/cards/ICard.ts
src/cards/ICardMetadata.ts
src/cards/StandardActionCard.ts
src/cards/StandardProjectCard.ts
src/cards/base/Capital.ts
src/cards/base/CommercialDistrict.ts
src/cards/base/EcologicalZone.ts
src/cards/base/IndustrialCenter.ts
src/cards/base/LavaFlows.ts
src/cards/base/MiningArea.ts
src/cards/base/MiningCard.ts
src/cards/base/MiningRights.ts
src/cards/base/MoholeArea.ts
src/cards/base/NaturalPreserve.ts
src/cards/base/NuclearZone.ts
src/cards/base/RestrictedArea.ts
src/cards/community/ScienceTagCard.ts
src/cards/prelude/PreludeCard.ts
src/components/card/Card.vue
src/components/card/CardContent.vue
tests/cards/moon/EarthEmbassy.spec.ts

As I start to detach the card metadata interface, I'm going to take advantage of the (inconsistently applied) standard in this project to start interfaces with I. As I've been prototyping a solution, not knowing what's a class and what's an interface has been a significant point of confusion.
Note that some of the changes include removing CardMetadata for some cards and renaming the interface in others. For some reason I don't yet understand, some of those parameters need the declaration. So I'm not sure if I'm causing a breakable issue by doing this.

Rename CardMetadata -> ICardMetadata. 

---

package.json
src/routes/ServeAsset.ts
tests/routes/ServeAsset.spec.ts

This makes it possible to locally change CSS without having to restart the server.
Dev still works:
And production reads from the cache (set `NODE_ENV=production` and verified with a debugger)

Disable css caching more effectively.

---

src/Player.ts
src/moon/MoonExpansion.ts
tests/cards/moon/LunaArchives.spec.ts

Science resources on Luna Archives reduces the cost of Moon cards by 1MC per resource. SelectHowToPayForProjectCard already takes this into account, but it wasn't taken into account when choosing valid cards to play.
Fixes #3626

Luna Archives pre-cost calculation

---

src/client/components/card/Card.vue
src/client/components/card/CardResourceCounter.vue
src/styles/cards_v2.less

I don't like copying the CSS. I wonder if `less` can help here.

Show card resource icons instead of 'RES' in the corner.

---

src/boards/Board.ts
tests/Game.spec.ts
tests/ares/AresHandler.spec.ts
tests/ares/AresTestHelper.ts
tests/cards/ares/DesperateMeasures.spec.ts
tests/cards/moon/CosmicRadiation.spec.ts
tests/cards/moon/HE3ProductionQuotas.spec.ts
tests/cards/moon/HypersensitiveSiliconChipFactory.spec.ts
tests/cards/moon/LunaConference.spec.ts
tests/cards/moon/LunaHyperloopCorporation.spec.ts
tests/cards/moon/LunaResort.spec.ts
tests/cards/moon/LunarMineUrbanization.spec.ts
tests/cards/moon/LunarSecurityStations.spec.ts
tests/cards/moon/MicrosingularityPlant.spec.ts
tests/cards/moon/OffWorldCityLiving.spec.ts
tests/cards/moon/OrbitalPowerGrid.spec.ts
tests/cards/moon/RevoltingColonists.spec.ts
tests/cards/moon/WaterTreatmentComplex.spec.ts

This does not prevent a current bug in main, but it caused one in Pathfinders. Nothing pathfinders-specific, but Pathfinders has code that calls `player.game.board.getSpaces(/* no parameter */)`. No cards on the main server skip that parameter. And that's all fine until you play with Hellas, whicch overrides `getSpaces` with a mandatory player parameter.
This led to my second-ever stackoverflow question: https://stackoverflow.com/questions/69340304/is-there-a-typescript-compiler-option-to-prevent-a-subclass-method-from-removing

Patch: Player should be required arg for some Board methods

---

src/cards/render/CardRenderer.ts
src/tools/export_card_rendering.ts

There was a lot of pop and push when it wasn't necessary in CardRenderer, making the class tricky to read. That and a little cleanup makes for a completely identical output.
I know this for two reasons: the first is that I visually inspected every card, and they matched on the `/cards` path. The second is that I extracted the full card renderings, and ran diffs until they were exactly the same:
I've done a fair bit of analysis of the non-method elements of the rendering classes, and I am confident that the export is the complete set.

Clean up CardRenderer.

---

src/cards/moon/LunaEcumenopolis.ts
tests/cards/moon/LunaEcumenopolis.spec.ts

This was surprisingly easier than I expected. What am I missing?
The algorithm takes into account the possibility that the first
colony placed is necessary to place to second colony.

Make Luna Ecumenopolis not playable unless player can place 2 colonies.

---

src/cards/base/ResearchOutpost.ts

Another place where using `every` is a performance boost. In this case it may actually be easier to read as well.

perf: use every for ResearchOutpost

---

src/routes/ServeAsset.ts
src/tools/gzip.js
tests/routes/ServeAsset.spec.ts

This saves 10kb over `gzip` when loading CSS on browsers which support `br` compression.

use brotli compression for styles

---

src/client/components/Milestone.vue

Set milestones display to collapsed by default once all milestones have been funded.

Default collapsed milestones display once they have been funded

---

src/cards/CardRequirement.ts
src/cards/CardRequirements.ts
src/cards/pathfinders/FlatMarsTheory.ts
src/cards/pathfinders/PathfindersCardManifest.ts
tests/TestPlayer.ts
tests/cards/CardRequirements.spec.ts
tests/cards/pathfinders/FlatMarsTheory.spec.ts

This required tweaking a few changes to how tag requirements are calculated. Also, TestPlayer's `tagsForTest` didn't take wild tags into account.

PF18: Add pathfinders card Flat Mars Theory.

---

src/LogBuilder.ts
src/Player.ts
src/cards/moon/AnOfferYouCantRefuse.ts
src/cards/moon/LunaPoliticalInstitute.ts
src/cards/moon/TempestConsultancy.ts
src/cards/pathfinders/DeclarationOfIndependence.ts
src/cards/turmoil/CulturalMetropolis.ts
src/cards/turmoil/MartianMediaCenter.ts
src/cards/turmoil/Recruitment.ts
src/cards/turmoil/VoteOfNoConfidence.ts
src/colonies/Colony.ts
src/deferredActions/SendDelegateToArea.ts
src/models/TurmoilModel.ts
src/turmoil/Turmoil.ts
tests/cards/moon/AnOfferYouCantRefuse.spec.ts
tests/cards/moon/TempestConsultancy.spec.ts
tests/cards/pathfinders/DeclarationOfIndependence.spec.ts
tests/cards/turmoil/CulturalMetropolis.spec.ts

1. counting delegates can include the lobby.
2. can log by party name.
3. Rename hasAvailableDelegates to hasDelegatesInReserve.
4. Rename getDelegatesInReserve to getAvailablePartyDelegateCount.
5. For now, make Declaration of Independence only take delegates from the reserve. Later make it like Cultural Metropolis.
6. Organize SendDelegateToArea just a little bit. It'll make it easier to read. Plus I want to get it to be more protective of accidentally sending more delegates than it has.

Series of minor Turmoil API changes.

---

src/Game.ts
src/SerializedGame.ts
tests/Game.spec.ts

This will use less space per entry by storing only the award name instead of the entire award object. There are plans to eventually keep more records in the database and this will help use less space.

only use name when serializing IAward for Game

---

src/Game.ts
src/SerializedGame.ts
tests/Game.spec.ts

Stores milestones by only their name versus the JSON string for the object. Will use less space per saved game.

only use name when serializing IMilestone for Game

---

src/deferredActions/PlaceCityTile.ts

Before this, Place City Tile would choose spaces at construction time.
Those spaces can change, if, for example, another tile placement action
occurs.

Make Place City Tile delay identifying available spaces.

---

tests/cards/pathfinders/StrategicBasePlanning.spec.ts

The test was failing beacuse often Europa was the chosen colony, causing
the next event in the queue to be to place the ocean tile,  and not the
city tile.

Make StrategicBasePlanning determinsitic.

---

src/client/components/GlobalEvent.vue
src/client/components/PreferencesDialog.vue
src/client/components/Turmoil.vue
src/client/utils/PreferencesManager.ts

I'm going to move the card requirements UI feature under the same preference.

Use an Experiemental UI preference to show the new global events icons.

---

src/client/components/card/CardCorporationLogo.vue

This turns all the string literals for rendering the card corporation logo into template HTML.
Ignore the card without a logo in that screenshot, it's a Pathfinders corp that doesn't have a logo ... yet.

Remove getHtmlContent when rendering corporation logos.

---

src/client/components/card/CardRequirementComponent.vue
src/client/components/card/CardRequirementsComponent.vue

1. Restore the yellow border around card requirements when the experimental UI is off.
2. Fix code review comment about closing div tags.
After:

Minor requirements UI fixes

---

src/styles/cards_v2.less
src/styles/preferences.less

There's still a z-index issue when highlighting the first one. :/

Make Turmoil global event cards magnify and zoom scale the party icons.

---

src/Game.ts
src/cards/base/ArtificialLake.ts
tests/cards/base/ArtificialLake.spec.ts

Artificial Lake should not be playable if no land spaces are available.

Add method canAddOcean, and further refine Artifical Lake.

---

src/cards/venusNext/CorroderSuits.ts
tests/cards/venusNext/CorroderSuits.spec.ts

This is done by just removing its resource type constraints, which
were probably put there at a time when getResourceCards required
a resource type.

Make Corroder Suits compatible with Floater Urbanism.

---

src/Player.ts
src/cards/colonies/TitanFloatingLaunchPad.ts
src/colonies/ColoniesHandler.ts
src/colonies/IColonyTrader.ts
tests/cards/colonies/TitanFloatingLaunchPad.spec.ts

This simplifies the code, and makes it easier to split out
Titan Floating Launch Pad. Another card for Pathfinders will
also allow trading with its resources; this will help.

Split out colonies trading details into handlers.

---

src/client/components/SelectHowToPayForProjectCard.vue
src/client/mixins/PaymentWidgetMixin.ts
tests/components/PaymentTester.ts
tests/components/SelectHowToPayForProjectCard.spec.ts

1. `getAmount` wasn't safe, and it was often arguing because seeds was undefined. And that should be an OK case.
2. Restore ability to purchase Stratospheric Birds.  (Removing the complicated `isStratosphericBirdsEdgeCase` was acceptable because of all the reasons laid out in the long comment block in `PaymentWidgetMixin`.)
It was good to add tests for `onSave` because it wasn't, you know, tested. There's room for even more tests to check the failure case, too.

Two fixes for selecting how to pay for project cards

---

src/cards/CardRequirement.ts

This does not impact anything except the new experimental renderer
because the field is never used. See, that attribute is used as part of
the `satisfies` behavior, but actually, ProductionRequirement has its
own `satisfies` method, ignoring `CardRequirement.type`

Production req't shouldn't have ResourceTypes.

---

src/Player.ts
src/turmoil/globalEvents/Election.ts
src/turmoil/globalEvents/Revolution.ts
src/turmoil/globalEvents/WarOnEarth.ts

Log TR gains and losses for global events.

---

src/CardFinder.ts
src/Deck.ts
src/cards/AllCards.ts
src/client/cards/ClientCardManifest.ts
src/client/components/DebugUI.vue
src/client/components/LogPanel.vue
src/client/components/SelectHowToPayForProjectCard.vue
src/client/components/SelectInitialCards.vue
src/client/components/card/Card.vue
src/client/components/create/CardsFilter.vue
src/client/components/create/CorporationsFilter.vue
src/client/components/create/CreateGameForm.vue
tests/cards/pathfinders/SoylentSeedlingSystems.spec.ts
tests/cards/venusNext/Celestic.spec.ts

This will make it far easier to find a replacement that doesn't import actual card instances. Plus by doing this all the code uses the same API, making things so much simpler! Look at how small `AllCards.ts` is. I already see new minor things that can change and improve.

Isolate fetching cards to one place on the client

---

src/client/components/WaitingFor.vue

This is some work that will be needed for #3899 . Eventually we are going to have to create a service worker. Until that time this wraps the call to `Notification` in a try...catch. This will allow unsupported browsers to move past the error. Even with service worker we will still need to wrap this. Both `Notification` and service worker are only supported in secure contexts. Users using `http` to run the game locally will still hit an error in the future.

catches exception from Notification

---

Dockerfile

Pin nodejs base image in Dockerfile to allow the docker build not to fail. See https://github.com/terraforming-mars/terraforming-mars/issues/3963

pin nodejs base image in Dockerfile

---

.github/workflows/main.yml
package-lock.json
package.json

Node version upgrades seem to happen rapidly. The most current version is 17.
To get this to work in an old environment you might need to run `npm rebuild`
A couple of sanity tests passed for me, including deploying to Heroku.

Upgrade to Node v16.

---

src/common/cards/Tags.ts

As request by @kberg on discord, removed symlink that is breaking _docker build_ on Windows.

removed symlink

---

src/routes/ServeAsset.ts
tests/routes/ServeAsset.spec.ts

I am putting up a new `sw.js` file in preparation for adding a service worker. While I was looking at `ServeAsset` I saw we were always checking if files exist. This avoids the check for production. Should avoid synchronous file i/o.

avoid synchronous file access in production

---

tests/cards/base/RoboticWorkforce.spec.ts

Also rely on existing behavior to simulate these cards. An upcoming card
relies on the card being placed in hand before running deferred actions,
and this is pretty normal behavior. That this test did it itself, means
that it was using abnormal behavior. Not to mention it was doing more
work that way.
(Edited to add: in retrospect, this doesn't look smaller, does it? But it's certainly more standard.

Simplify Robotic Workforce test.

---

src/cards/pathfinders/ReturntoAbandonedTechnology.ts

I wish the logging option was a little more powerful, but for now, I'm just removing it.

Don't log drawn cards in Return to Abandoned Technology.

---

src/Game.ts
src/database/IDatabase.ts
src/database/LocalFilesystem.ts
src/database/PostgreSQL.ts
src/database/SQLite.ts
tests/database/SQLite.spec.ts

The use of await in Postgres seems to have changed the lastSaveID, resulting in production games' last ID being lost forever. Rather than just fix that, I resolved a couple of other synchronicity errors, too.
1. Make sure that lastSaveId is correct by reading the last save ID from
the database rather than trusting the game.
2. Don't purge games until the current game is marked as finished, so it
doesn't accidentally get deleted.
3. Don't mark the game as finished until the game is truncated. It's
more efficient.

Fix synchronicity errors with end games.

---

src/client/main.ts
src/client/sw.ts
src/routes/ServeAsset.ts
src/server.ts
tests/routes/ServeAsset.spec.ts

For notifications on android the `Notification` constructor can't be used. This adds an empty service worker to allow us to use notifications on android. Once this merges if it doesn't seem to cause any issue I will put up the PR to show notifications.
https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications
Eventually the `WaitingFor` component can be fully updated to utilize these push notifications versus the polling used today.

add empty service worker prepping for better mobile notifications

---

src/cards/pathfinders/NewVenice.ts
tests/cards/pathfinders/MarsDirect.spec.ts

MarsDirect changes, but I won't change the MC in the base card; that adjustment didn't take this card into consideration.

Fix wrong New Venice tag.

---

src/Game.ts
src/cards/base/BiomassCombustors.ts
src/cards/base/Birds.ts
src/cards/base/CloudSeeding.ts
src/cards/base/Fish.ts
src/cards/base/HeatTrappers.ts
src/cards/base/Herbivores.ts
src/cards/base/RoboticWorkforce.ts
src/cards/base/SmallAnimals.ts
src/cards/colonies/SubZeroSaltFish.ts
tests/cards/pathfinders/PrivateSecurity.spec.ts

Cards that reduce production should not be playable if the only opponent has Private Security.

---

Dockerfile

I've introduced a bug during last Dockerfile refactoring. Assets are copied from clean source files and are missing some files (such as locales directory with translations). Fixed this by copying the assets directory from image with built application and not from clean sources.
Workaround over this bug is to build docker file after building app locally, because assets directory then contains everything docker image needs. Sadly this is why I did not find this bug in the previous PR.

Fixed Dockerfile to copy assets from built application, not from sources

---

tsconfig.json

ES2018 seems to already be supported by default.
ES2019 support is pretty broad for Browsers, except for Function.prototype.toString, which is just not likely to be a problem
ES2020 is very well supported in modern browsers.
ES2021 has a couple of features not supported in Opera, but they're WeakRef and Promise.any. It is safe to assume those features won't be run on a browser.
See https://caniuse.com/sr_es10, https://caniuse.com/sr_es11, https://caniuse.com/sr_es12. Click "Feature Support List" for each of those.

Use ~~ES2021~~ ES2019

---

src/client/components/GameHome.vue
src/client/components/create/CreateGameForm.vue

This clears the custom corporations list if the showCorporationList is toggled off. After fixed an issue I saw in console logs where `game` was `undefined` while I was testing this change.
This can close #4046

clear customCorporationsList if not selected

---

src/cards/pathfinders/BioSol.ts
src/client/components/SelectCard.vue

Show card owner when selecting targets for Ants
One issue is that the corp card has this padding that I can't find.

Add corporation card to list of selectable cards when finding owner. (Also fix BioSol rendering)

---

src/locales/pl/promo.json

Polish translation wrongly stated, that you should place a microbe and increase greenery production for every played building tag.

Fixed polish translation of Recyclon corp

---

src/client/components/GamesOverview.vue
src/client/components/overview/PlayersOverview.vue

The `PlayersOverview` component wasn't considering the `SpectatorHome` component. This can close #3860

show other-players for spectators

---

src/Player.ts
src/client/components/overview/PlayerTags.vue

By accident, Iapetus card discount was applying active player's discount
to all players. That's because I used `thisPlayer` instead of `player`.
Fixes #4093

Fix rendering Iapetus card discount.

---

.github/workflows/main.yml

https://github.blog/changelog/2021-11-16-github-actions-windows-server-2022-with-visual-studio-2022-is-now-generally-available-on-github-hosted-runners/
2022 is causing issues. I think.

Fallback to windows-2019.

---

.eslintrc.js

Adds the tags used which are not using `multi-word-component-names`. These tags were added prior to the linting rule being enforced. Avoids having warnings on every build.

ignore tag names from before linting rule

---

src/server.ts

Hi,
I've noticed that when deploying the latest version on heroku the application no longer binded to $PORT (crashed).
Maybe a dependency update made the variable name case sensitive.
This change is all that was required to work again on my own heroku instance.

Fix PORT env var name (for heroku setup)

---

tests/boards/ArabiaTerraBoard.spec.ts
tests/boards/Board.spec.ts

Moving from 5,000 to 4,000 is because a recent Windows test timed out.

Minor board test updates

---

src/cards/colonies/FloaterTechnology.ts
tests/cards/colonies/FloaterTechnology.spec.ts

Bug: Floater Technology action should be usable (as a stall action) even with 0 targets available

Fix bug with Floater Technology

---

src/client/components/create/ColoniesFilter.vue

This is a case where the method, seemingly unused, was deleted. However,
it was used in CreateGameForm, which references it with `(refs.xxx as
any)`. Getting rid of tne 'any' typing would be a big help.

Restore ColoniesFilter.updateCorporationsByName.

---

src/cards/base/EarthOffice.ts
src/locales/br/base_cards.json
src/locales/cn/cards.json
src/locales/es/base_cards.json
src/locales/it/cards.json
src/locales/pl/cards.json
src/locales/ru/cards.json

Unofficial FAQ says that earlier versions of Earth Office had the text
"play an earth card" but was updated to "play an earth tag."

Update Earth Office card text.

---

package.json
src/cards/community/Incite.ts
src/client/components/card/CardContent.vue
src/client/components/card/CardRenderEffectBoxComponent.vue
src/common/cards/render/Types.ts

TIL JSON.stringify converts undefined to null, which means
being smarter about defined values when reading card components.

Fixing json card rendering.

---

src/cards/pathfinders/PathfindersCardManifest.ts

Hopefully it'll come back, but for now, it'll be removed from play. For those
few games that might be using it, it'll break it for the short-term. Sigh.

Remove Odyssey from the manifest.

---

src/cards/CardRequirements.ts
tests/cards/moon/EarthEmbassy.spec.ts
tests/cards/pathfinders/HabitatMarte.spec.ts

Besides probably reducing computation time, this also fixes an edge case
with fan expansion cards that implement tag substitutions.
This will not fix an edge case that doesn't exist yet, where a card
requires a Moon and 2 Earth tags, and the player has played Earth Embassy.

Only check for multiple tags when there are many tags.

---

src/Player.ts
tests/cards/base/OlympusConference.spec.ts
tests/cards/community/Leavitt.spec.ts

This is an issue with Leavitt and Vitor compatibility. If a player plays
Vitor, and then puts a colony on Leavitt, it calls onCardPlayed, which
calls Vitor's onCardPlayed, which relies on card.metadata. However the
proxy card's metadata throws an error.
This bug arose when centralizing VP management.

Proxy cards should not trigger onCardPlayed.

---

package-lock.json
package.json

This removes a vulnerability introduced in 5.0.2
After `npm i`:
```
npm install
added 50 packages, removed 33 packages, changed 16 packages, and audited 803 packages in 7s
70 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
Fixes #3965

Upgrade to Sqlite 5.0.3.

---

package-lock.json
package.json

Docker image is failing to start after the latest sqlite update. This is alrady [fixed upstream](https://github.com/TryGhost/node-sqlite3/issues/1576). This PR updates to the later version of sqlite which has this issue fixed.
For reference, the error is:
```text
> terraforming-mars@1.0.0 start
> node build/src/server.js
node:internal/modules/cjs/loader:1183
return process.dlopen(module, path.toNamespacedPath(filename));
^
Error: Error relocating /usr/src/app/node_modules/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node: fcntl64: symbol not found
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require …
```

bump sqlite version

---

src/client/components/SelectHowToPay.vue
tests/client/components/SelectHowToPay.spec.ts

The SHTP widget doesn't really do much when the megacredit value
changes; it's up to players to change the other units. That can change.
But for now, this will do the bare minimum while generating feedback for
how to refine this.

Adds a "Max" button for Megacredits.

---

src/client/components/SelectCard.vue
src/client/mixins/PlayerMixin.ts
src/styles/cards.less
tests/client/components/SelectInitialCards.spec.ts

Two changes:
1. When having to select a card for adding resources, if the card was played this generation, use the dark filter.
2. When hovering over a card with a dark filter, remove the filter, making it easier to see.
This fixes #3046

Extra visuzliation for action cards played this generation

---

src/cards/pathfinders/LobbyHalls.ts
tests/cards/pathfinders/LobbyHalls.spec.ts

That's because DeclareCloneTag calls onCardPlayed,
which raises the track one space on declaration.
Fixes #4049

Lobby Halls was raising the planetary track an additional step.

---

src/Player.ts
src/common/Units.ts
src/deferredActions/SelectProductionToLoseDeferred.ts
tests/deferredActions/SelectProductionToLoseDeferred.spec.ts

This PR adds validation so that users are not able to specify negative or non-numeric unit amounts. Before this validation, players could make their production massive by "losing" a negative amount of production.

Fix SelectProductionToLose parsing for Units

---

src/cards/base/MediaGroup.ts
src/cards/promo/PharmacyUnion.ts
src/deferredActions/DeferredAction.ts
tests/cards/base/MediaGroup.spec.ts
tests/cards/promo/PharmacyUnion.spec.ts

This makes the reward come after the cost, which is generally how we
want this to play out.
Fixes #2191

Make Media Group's behavior a deferred action.

---

src/client/components/create/CreateGameForm.vue

I've adjusted the placeholder for the "Your name" input. The localizations are now correctly applied to the placeholder.
Before:
After:

Fix placeholder for 'Your name' input in game setup, enabling i18n

---

src/database/SQLite.ts
src/database/utils.ts.ts
tests/TestingUtils.ts
tests/database/SQLite.spec.ts

First, the code centralizes computing time to seconds, because trusting
sqlite's date math is fine, but putting the complexity in Typescript is
better; we're better in Typescript than SQLite.
Second, type SQLite functions were not computing days ago as if it were
that many seconds ago, but rather some midnight date n days ago. That
means all unfinished games over a 24-hour period are purged at once
rather than over time.
If this same behavior exists with PostgreSQL, it could account for some
of the occasional slow operations, but I doubt it.
Finally, fixing the purge method; async sleep() is kinda better.

Rewrite how sqlite purges unfinished games.

---

tsconfig.json

From https://www.typescriptlang.org/tsconfig#target:
> Modern browsers support all ES6 features, so ES6 is a good choice. You might choose to set a lower target if your code is deployed to older environments, or a higher target if your code is guaranteed to run in newer environments.

Target es6.

---

src/common/logs/LogMessage.ts
tests/common/logs/LogMessage.spec.ts

This change avoids setting the `playerId` property on the `LogMessage` object when the argument is `undefined`. With less properties used per `LogMessage` less memory will be used. As JSON doesn't store properties with values of `undefined` this should also reflect what we have stored in JSON within the database. I added a regression test to ensure the generated javascript no longer adds the property.
```js
class LogMessage {
constructor(type, message, data, playerId) {
this.type = type;
this.message = message;
this.data = data;
this.playerId = playerId;
this.timestamp = Date.now();
}
}
```
```js
var LogMessage = (function () {
function LogMessage(type, message, data, playerId) {
this.type = type;
this.message = message;
this.data = data;
this.timestamp = Date.now();
if (playerId !== …
```

This one trick to lower memory for our LogMessage will surprise you.

---

package.json

Since we are using `ts-mocha` we shouldn't need to transpile the typescript to javacript anymore. This will speed up the build.

remove unnecessary pretest:server script

---

src/cards/moon/AnOfferYouCantRefuse.ts
src/turmoil/Turmoil.ts
src/turmoil/parties/Party.ts
src/turmoil/parties/PartyHooks.ts

I want to enable the [no-unnecessary-condition](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-unnecessary-condition.md) linting rule as it can spot code we can remove. These places usually pop up during re-factors when properties that were once optional gain default values. Going to do this change in small pieces to make it easier to review before enabling the rule. The changes in this PR were fixed after eslint found uncessary conditions.
This PR fixes the files in src/turmoil subdirectory.

refactor: remove unused conditionals for src/turmoil

---

src/client/components/LogPanel.vue
src/common/logs/LogMessage.ts
tests/common/logs/LogMessage.spec.ts

This change only stores the `type` property when the value is not `LogMessageType.DEFAULT`. The only messages that have a different type are the new generation log messages. This should remove this property from a large percentage of log messages. With the property not applied less memory will be consumed on the server as well as in the database. Performed quick sanity check locally and still saw generation messages appear and survive server reboot.

only store property when not LogMessageType.DEFAULT

---

src/client/components/create/CreateGameForm.vue

This commit enables translations for default player names when creating a game so there's no longer a player called "Green" when starting a Korean game without entering a name for instance :)
Granted, not the most likely scenario I assume.

enables i18n of default player names used when creating a game

---

src/Game.ts
tests/Game.spec.ts

This change avoids setting properties to `undefined`. Setting the property to `undefined` creates a key on the `Game` object which will take up memory. This also reflects what the resulting JSON will have as JSON doesn't create keys for properties that are `undefined`.

avoid setting properties to undefined

---

src/Player.ts

Avoids setting properties to `undefined` on the `Player` class. Unnecessary and takes up small amount of memory and CPU.

remove setting properties to undefined for Player

---

src/boards/Board.ts

[One of the unit tests](https://github.com/terraforming-mars/terraforming-mars/blob/main/tests/boards/Board.spec.ts#L302) can sometimes run over 2 seconds when I run `test:server`. This test creates 4000 board instances. I started to look into how this could be optimized. 
Noticed a minor change to our check for computing adjacent spaces that should help a bit. We would check for the x and y coordinate of the space last when that is the check that is more likely to fail. Moving these up front helped this unit test in question run 30% faster for me when ran in isolation with `it.only`.
The other change avoids duplicating the array and instead uses `ReadonlyArray` so that readonly is enforced at compile time versus having to copy the array each time using CPU.

performance improvements to getAdjacentSpaces

---

src/styles/player_home.less

Rise z-index of top-bar  top 105 in order to be higher than the z-index of a hovered card (100).
This takes care that the hovered card does not show over the top-bar
Old behavior:

Rising z-index of top bar

---

package.json

This won't get run during npm run test, which is better for Brian's
current setup.

Still need a compilation phase for the tests.

---

src/styles/cards.less

Reduce the opacity of the card selection, to be able to read all information of the selected card.
This is especially helpful if there is only one card which is directly selected.

Make card selection translucent

---

src/cards/colonies/MarketManipulation.ts
tests/cards/colonies/MarketManipulation.spec.ts

Prompt the user using the `SelectColony` input instead of the checkbox text options.
Issue https://github.com/terraforming-mars/terraforming-mars/issues/4541
Before: 
After: Prompts the user to select which colony to increase, then which colony to decrease.

Market Manipulation Action Changes

---

src/database/IDatabase.ts
src/database/LocalFilesystem.ts
src/database/PostgreSQL.ts
src/database/SQLite.ts
src/routes/ApiCloneableGame.ts
src/routes/Handler.ts
tests/database/SQLite.spec.ts
tests/integration/PostgreSQL.spec.ts
tests/routes/ApiCloneableGame.spec.ts
tests/routes/RouteTestScaffolding.ts
tests/utils/setup.ts

This required a couple of external changes. For instance, introducing an
Async version of a handler, so tests could wait for results.
Also fixed an irritating issue, looks like I did a poor job of
saving and restoring the fake database test. Ha.

Make getPlayerCount async

---

src/client/components/create/CreateGameForm.vue

This was introduced with [this commit](https://github.com/terraforming-mars/terraforming-mars/commit/3bc27172efffcd48ec6d309aa7f3391d7c553d9a). When the `venusNext` option is changed this toggles `solarPhaseOption` as it is now a watched property. This changes the setting of `solarPhaseOption` to happen on the next tick to avoid the watched property modification. This closes #4511

set solarPhaseOption on next tick to avoid watch

---

src/cards/colonies/MarketManipulation.ts

Noticed while playing the log said the same colony was increased and decreased. This was just an issue with the log. Changed variable name from `colony` to `decreasedColony` to make it more clear.

Fix market manipulation log

---

src/turmoil/globalEvents/GlobalEventDealer.ts

Saw non-null assertions being used in #4588 . Was surprised to see them! Then realized we didn't have a linting rule in place preventing them. Hoping to enable [no-non-null-assertion](https://typescript-eslint.io/rules/no-non-null-assertion/). There are 20 or so places we are using these in `/src`. This removes them from the `GlobalEventDealer`.

remove non-null assertion from GlobalEventDealer

---

src/cards/base/RoboticWorkforce.ts
tests/cards/base/RoboticWorkforce.spec.ts

From FAQ:
> This card can be used to copy the Research Network prelude card to
> gain 1 MC production (by treating the Wild tag as a building tag
> for that action).

Wild tags count for Robotic Workforce.

---

src/cards/pathfinders/DeclarationOfIndependence.ts
src/locales/de/pathfinder_cards.json

The current text description of the card is a bit misleading.
Align it with other cards that explicitly state the requirement is based only on player's tags (such as Luna Political Institute).

Update description of card "Declaration of Independence"

---

src/styles/globs.less

Pathfinders' Odyssey lets you replay and then discard an event. Butterfly Effect changes Ares global parameters. Changing them twice works fine, functionally, but doesn't render markers to indicate their new value.

Make Odyssey compatible with Butterfly Effect.

---

src/styles/cards.less

Fixes #4618
Chrome above, firefox below:

Reduce z-index for the search for life alien.

---

src/database/PostgreSQL.ts
tests/TestPlayer.ts
tests/TestPlayers.ts
tests/database/IDatabaseSuite.ts
tests/database/SQLite.spec.ts
tests/integration/PostgreSQL.spec.ts

The broken behavior* is due to the fact that when the server switches between players it saves -- twice. Isn't that strange? It's how it works. While that should be fixed, it's how it works.
If the app saved twice by saving from id 3 to 4, and then 4 to 5, that would be great, but it's not what it was doing. It was saving v3, and then saving as v3 again. Because save() also updates, this isn't a real problem.
The problem is that both times, it increments `game.lastSaveId`, so during the first save it saves v3 and bumps `game.lastSaveId` from 3 to 4, and during the second save it saves v3 and bumps `game.lastSaveId` from 4 to 5.
This repair ensures that no matter what version the server expects to save, it bumps `game.lastSaveId` to the number above it.
This is verified in the test with …

Fix broken undo.

---

src/database/IDatabase.ts
src/database/PostgreSQL.ts
tests/database/IDatabaseSuite.ts
tests/integration/PostgreSQL.spec.ts

This behavior causes startup to be very very slow for games
played during a restart.

Restore loading order when getting game IDs.

---

src/Game.ts

1. Ensure that the game is saved at game.end.
2. When deserializing a game, don't do anything if the game is at end
phase.
What was happening was that the server resets and then the players
somehow get to reload their game and also find that they're in their
final action phase again.
Testing was hard because there are still some things that aren't async.
I manually tested these, including verifying that the game wasn't saving
the end phase.

Improve game-end state management.

---

src/.eslintrc.js
src/database/GameIds.ts
src/database/SQLite.ts
src/routes/PlayerInput.ts

Adding the [require-await](https://eslint.org/docs/latest/rules/require-await) lint rule. This rule can help developers new to async and await. Also useful during refactors to catch usages that become unnecessary.

add linting rule require-await

---

src/Player.ts
src/ares/AresHandler.ts
src/cards/corporation/MiningGuild.ts
src/cards/corporation/SaturnSystems.ts
src/cards/promo/Splice.ts
src/client/utils/PreferencesManager.ts
src/deferredActions/RemoveResourcesFromCard.ts
src/models/ServerModel.ts
src/moon/MoonExpansion.ts

Removes some unnecessary null chains. These were spotted with the @typescript/eslint rule of no-unnecessary-conditions.

remove a few unnecessary null chains

---

src/database/GameLoader.ts

Now that loadGame is only called in one spot, it can be inlined.
Also, it is now apparent from the prior version that the part of
loadGame which checked the cache is no longer necessary, so that was
removed.
Also added documentation to clarify why getGame's map checks are the way
they are.

Inline loadGame.

---

tests/utils/setup.ts

Actually most tests. This is generating silent errors, which aren't really meaningful, but this is more appropriate.

Fix GameIDs tests.

---

src/server/Player.ts
src/server/cards/Card.ts
src/server/cards/ICard.ts
src/server/cards/base/TerraformingGanymede.ts
src/server/cards/pathfinders/SocialEvents.ts
src/server/turmoil/TurmoilHandler.ts

This allows those cards which can compute its impact on TR only at
runtime. to have their computation done by the system.

Add DynamicTRSource

---

src/server/cards/pathfinders/PathfindersCardManifest.ts

Don't include community's ValuableGases when playing with Prelude.

---

src/client/components/GameEnd.vue
src/client/components/LogPanel.vue

I have added a few strings being able to be translated in the Game End view and improved render of some translation.
New Strings :
"Milestones points": "Milestones points",
"Awards points": "Awards points",
"won!": "won!",
"Download game log": "Download game log",
"Gen:": "Gen:",

Improve translatable string in GameEnd view

---

src/server/cards/moon/LunaFirstIncorporated.ts

It does this by not fully overwriting the production amounts.
This will help with #4763

Make Luna First Incorporated compatible with merger.

---

src/client/directives/i18n.ts

Hi! 
I'm a big fan of the game, and we play this web version quite often, thank you for the great implementation!
I fixed https://github.com/terraforming-mars/terraforming-mars/issues/4349 by removing trim() function from normalizeText() function. This results in identical whitespace placing in both English and translated versions: 
**English version:** 
**Translated version pre-fix:** 
**Translated version post-fix:** 
- normalizeText() function is only getting applied to English words (such as max-min) during the client translation, thus this change only covers such English words. 
- Making this change doesn't cause any whitespace problem, as regex in normalizeText() ensures that multiple whitespaces gets reduced to just one whitespace, thus behaving as the English version and making …

fix i18n trim space

---

tests/cards/base/CaretakerContract.spec.ts
tests/cards/prelude/MiningOperations.spec.ts
tests/cards/prelude/Mohole.spec.ts
tests/cards/prelude/MoholeExcavation.spec.ts
tests/cards/prelude/SpaceHotels.spec.ts
tests/cards/promo/Potatoes.spec.ts
tests/cards/venusNext/SisterPlanetSupport.spec.ts
tests/cards/venusNext/TerraformingContract.spec.ts
tests/cards/venusNext/VenusGovernor.spec.ts

There's a little bit of improved testing, but as this service moves toward the Behavior/bespoke API, tests with Player instances and not Game instances will break. So this is pre-emptive.

Update some tests.

---

src/server/cards/promo/HiTechLab.ts

When using Hi-tech lab with one energy the game asks you to choose a card from one option which is unnecessary. Replaced draw one keep one simply by drawing a card.

Hi-tech lab unnecessary choose when using 1 energy

---

src/server/Player.ts
src/server/cards/Card.ts
src/server/cards/base/LocalHeatTrapping.ts
tests/cards/base/LocalHeatTrapping.spec.ts

Moving reserveUnits caused a little trouble in this one place where resources weren't meant to be deducted.

Local Heat Trapping is double-deducting.

---

src/server/boards/Board.ts
tests/cards/base/LandClaim.spec.ts
tests/cards/pathfinders/RareEarthElements.spec.ts
tests/globalEvents/SpaceRaceToMars.spec.ts
tests/milestones/LandSpecialist.spec.ts

Don't count hazard tiles as "special" in the rewarding sense.

---

.eslintrc.js
src/server/Player.ts

A case of the perfect being the enemy of the good.

Remove the well-formed jsdoc requirement.

---

src/styles/language_icon.less

Accidentally used double-hyphen

CSS to fix language icon positions and layout.

---

src/server/cards/venusNext/Viron.ts
tests/cards/venusNext/Viron.spec.ts

Now that Viron can apply to other corporations thanks to Merger, the card needs to be aware that it cannot apply to itself. OZherwise it creates an infinite loop. Besides, once Viron is played, it can't be replayed through itself anyway.

Fix Viron bug that creates stack overflow.

---

src/server/Player.ts
src/server/cards/colonies/Aridor.ts
src/server/cards/corporation/ICorporationCard.ts
src/server/cards/promo/PharmacyUnion.ts
tests/cards/colonies/Aridor.spec.ts
tests/cards/promo/PharmacyUnion.spec.ts

While looking to remove some dependencies, I found this small efficiency which seems worth keeping. Could extend this to other cards (I'm looking at you, Robotic Workforce.)

Make corps handle their own custom serialization.

---

src/server/colonies/Colony.ts

No functional change, just simpler. If the reward is based on counting all delegates in parties, well, let's count all the delegates in parties.

Revised Pallas behavior.

---

src/styles/cards.less
src/styles/colonies.less
src/styles/preferences.less
src/styles/turmoil.less

Fixes https://github.com/terraforming-mars/terraforming-mars/issues/3211
Alternative approach to https://github.com/terraforming-mars/terraforming-mars/pull/4347
- Checkbox moved above the card. 
- Slightly more room made for it with increasing top margin and reducing the box-shadow. 
- A very slight change to turmoil checkbox to go along the party background with rounded corners. 
- Colony checkbox unchanged. 
Tested with solo play with google chrome and mozilla firefox.

Move the selection checkbox above the card

---

src/styles/cards.less

Remove reduced brightness from unselected cards. Selected cards slightly less distinguishable. I think it is either this or full roll back to old visualization.
Fixes the problems escpecillay with in initial card selection.

Remove problematic reduced brigness in inputs

---

src/server/MilestoneAwardSelector.ts
tests/MilestoneAwardSelector.spec.ts

1. When Cololnizer is in play.
2. When fan Colonies expansion is out of play.
Beef up the tests.
Fixes #5126

Remove Pioneer from limited synergy in two circumstances:

---

src/client/components/SelectProjectCardToPlay.vue
src/client/mixins/PaymentWidgetMixin.ts
src/common/Units.ts
src/common/models/CardModel.ts
src/server/Game.ts
src/server/models/ServerModel.ts
tests/client/components/SelectProjectCardToPlay.spec.ts
tests/common/Units.spec.ts

Reserve units on cards can be empty objects now. Also, don't bother generating milestones and awards in solo games.

Reduce the amount of material sent through the server model.

---

src/client/components/create/CreateGameForm.vue
src/common/game/NewGameConfig.ts
src/common/models/GameOptionsModel.ts
src/server/Game.ts
src/server/GameCards.ts
src/server/GameOptions.ts
src/server/Player.ts
src/server/inputs/SelectInitialCards.ts
src/server/models/ServerModel.ts
src/server/routes/Game.ts
src/server/tools/analyze_ma.ts
tests/GameCards.spec.ts
tests/routes/ApiGame.spec.ts

Implements the Merger Variant, which Everyone gets the Merger Prelude.  It's given post-drafting (if enabled).
- A few visual changes to New Game menu were made to make it a little 'easier'.
- Based off the wonderful work in [tfm-community](https://github.com/nwai90/terraforming-mars)
- You can very easily run out of corporations if minimal expansions are added.  
- A check should be done prior to game start to ensure more than enough corporations have been selected.
- I'm unsure on how to approach doing this just yet
(My apologies for the number of superfluous commits as I try to figure out how this language likes to concat strings.. recommending squashing if PR is accepted.)
---

Add Merger Variant (twoCorpsVariant)

---

src/client/components/create/CreateGameForm.vue

This will at least allow further development to continue. This does mean that someone who custom-selects corporations AND the two corps variant might have issues during gameplay, but one thing at a time.

Disable the revised corporation counting algorithm.

---

src/server/CardFinder.ts
src/server/cards/AllCards.ts
src/server/cards/leaders/LeaderCardManifest.ts
tests/CardFinder.spec.ts

_PR#1 in a set of card+deck related PRs_
I pretty much just tried to replicate the code as-is for Preludes, however there are a few oddities I'm not 100% sure on.  
For starters, `getLeaderByName`+`getPreludeByName` are only ever referenced in this `CardFinder.ts` in their respective `leadersFromJSON`+`preludesFromJSON` blocks in this same file.  Not sure why they'd need to be split out?
I've also included `leaderCards` in the generic `getCardByName`, but again, not sure this needed
Prior to this I'd just used the generic `cardsFromJSON` and it worked Fine, but would rather get this right if necessary.
(This whole PR for CardFinder.ts may be unnecessary, but will want to get it ironed out before moving on to `Deck.ts`+`Game.ts`

CEO PR#4.1 - CardFinder.ts

---

src/client/components/create/CreateGameForm.vue
src/common/game/NewGameConfig.ts
src/server/GameOptions.ts
src/server/cards/leaders/LeaderCardManifest.ts
src/server/routes/Game.ts

_PR#2 in a set of card+deck related PRs_
These options are required for tests that will be coming in `Deck.ts` and `Game.ts`.
No tests for this work _yet_, it needs Deck and Game set up before we can test it properly.  I can include some basics if desired.
I'm filling out the manifest for all of the Leaders we've added so far.  These will be used for future tests of Deck and Game.ts

 CEO PR#4.2 - GameOptions.ts

---

src/server/cards/Deck.ts
tests/cards/Deck.spec.ts

_PR#4 in a set of card+deck related PRs_
Another easy one.  Just a clone of Preludes really
This one is trickier.  I'm not 100% sure why the Preludes test is hard coded, but.. it is.  I don't really want to update this test every single time we push in a new CEO during deployment so I'm leaving it dynamic.  We are testing to see if the drawing works as expected, and the serialisation works after that. So maybe the hard coded length isn't ever necessary.
I _could_ add a test that we draw a custom list of Leaders, and work with that.  A deck size of 5 leaders maybe?  But I _think_ the test intentions are met as-is
I'm also not sure what the `customCorporationsList: [CardName.MERGER]` on the Prelude test is doing? I didn't replicate it in any case

CEO PR#4.4 - Deck

---

src/server/Game.ts
src/server/inputs/SelectInitialCards.ts
tests/inputs/SelectInitialCards.spec.ts

This makes them available for Merger.
Also, this is moved to SelectInitialCards as it puts most of the initial card setup in one place. There's probably a cleaner way to do this by moving _all_ the selection out of SIC, but this is an easy way to test.
Partially fixes #5277

Add unplayed corporation cards to the discard pile.

---

src/client/components/create/CreateGameForm.vue

Allow players to enable CEOs via CreateGameForm, with a simple (BETA) warning:
The wiki page linked is heavily under construction.  I'll do a quick edit there to explain what BETA in this context means
Wiki: https://github.com/terraforming-mars/terraforming-mars/wiki/CEOs

CEOs: Add checkbox to CreateGameForm.ts for CEOs (BETA)

---

src/server/Game.ts

This slipped through because of the way I did my testing using custom CEO draws.
Whoops

CEO Bugfix :: Increase default drawn CEOs from 2 to 3 to match Community

---

src/server/GameCards.ts

This is required for CEOs Caesar and Gaia, and anyone else in the future who needs to add ares compatibility :)
The two CEOs:
```ts
// [CardName.CAESAR]: {Factory: Caesar, compatibility: 'ares'},
// [CardName.GAIA]: {Factory: Gaia, compatibility: 'ares'},
```

Add 'ares' to list of expansions for card compatibility

---

src/client/components/create/CreateGameForm.vue
src/common/game/NewGameConfig.ts
src/server/Game.ts
src/server/GameOptions.ts
src/server/routes/Game.ts
src/styles/create_game_form.less

Allow players to choose how many CEOs they'd like to be dealt.
`startingCeos` has been added to all the GameOption locations where `startingCorporations` lives
My playgroup has been using 4 instead of the default 3, sometimes its more interesting.
Output display:

CEO CreateGameForm :: select starting card count

---

src/server/boards/Board.ts
src/server/cards/ceos/CeoCardManifest.ts
src/server/cards/ceos/Gordon.ts
tests/cards/ceo/Gordon.spec.ts

There probably needs to be discussions around how this plays with Ares and other special tiles.
Either we need to be strict in the definition, or work through special tiles.
If we rework Gordon from:
* 'Ignore placement restrictions for greenery and city tiles on Mars. Gain 2 M€ when you place a greenery or city tile on Mars.'
To:
* 'Ignore **normal** placement restrictions for greenery and city tiles on Mars. Gain 2 M€ when you place a greenery or city tile on Mars.',
We can say that special tile placement restrictions override even Gordon. If so, does Gordon override placement rules/get 2MC for:
|Tile|Placement Rules|2MC Bonus if the player places it?|
--|--|--
**Red City**|Gordon _can_ place next to Red City|Player **does** gain 2MC|
**Martian Natural Wonders**| Gordon can **not** …

CEO Gordon

---

src/common/constants.ts
src/server/turmoil/Turmoil.ts
tests/cards/turmoil/VoteOfNoConfidence.spec.ts

Per official rulebook.  
Moved out of `setRulingParty()` and into `setNewChairman()`, so that Vote of No Confidence returns Neutral Chairman to Reserve. (and Oscar will too)
Just making sure Neutrals get their Chairman Delegate back to reserve

Turmoil Bugfixes

---

src/server/cards/ceos/Apollo.ts
src/server/cards/ceos/Asimov.ts
src/server/cards/ceos/Bjorn.ts
src/server/cards/ceos/Caesar.ts
src/server/cards/ceos/Clarke.ts
src/server/cards/ceos/Duncan.ts
src/server/cards/ceos/Ender.ts
src/server/cards/ceos/Floyd.ts
src/server/cards/ceos/HAL9000.ts
src/server/cards/ceos/Ingrid.ts
src/server/cards/ceos/Jansson.ts
src/server/cards/ceos/Karen.ts
src/server/cards/ceos/Lowell.ts
src/server/cards/ceos/Musk.ts
src/server/cards/ceos/Naomi.ts
src/server/cards/ceos/Neil.ts
src/server/cards/ceos/Quill.ts
src/server/cards/ceos/Rogers.ts
src/server/cards/ceos/Ryu.ts
src/server/cards/ceos/Stefan.ts
src/server/cards/ceos/Tate.ts
src/server/cards/ceos/Ulrich.ts
src/server/cards/ceos/Will.ts
src/server/cards/ceos/Xavier.ts
src/server/cards/ceos/Yvonne.ts
src/server/cards/ceos/Zan.ts

There are reported issues with **Karen** and **Floyd** that both are able to reuse their OPG actions.  I'm not able to replicate this in either usage or testing, but I think it _may_ be be cause the `this.isDisabled = true;` on those two happen to appear in deferred actions.
If the first thing that `action()` does for every CEO is prevent it from being used again, seems like a fine approach
Minor rework in the way this behaves to ensure that we're disabling the CEO while still providing reward

Put this.isDisabled in the same place on every CEO

---

src/server/cards/ceos/Floyd.ts
src/server/deferredActions/PlayProjectCard.ts
tests/cards/ceo/Floyd.spec.ts

May need to update tests too
Should resolve:
> Floyd CEO bug - would not allow me to use the discount against a card that cost more than the discount to be given.  Generation 3, should be a discount of 13 + 6, would not let me play Phobos Space Haven when I had 9 MC in hand and 3 titanium

Fix: CEO Floyd OPG Discounts

---

src/client/components/GameEnd.vue
src/client/components/overview/PlayerInfo.vue
src/styles/players_overview.less

Display all corporation names under the players name on both player screen and endgame.
This kinda breaks the placement of the First Player token, but I think the utility outweighs the issue.
PlayerView:
Endgame:

Show All Corporation Names (Merger etc)

---

src/client/components/turmoil/Agendas.vue

This one's been bugging me for so long.  It's like finally removing a piece of food stuck in your teeth.
This backtick:
Gone.
```vue
<template v-else-if="id === 'up04'"> `<div class="policy-top-margin"><div class="resource-tag tag-space"></div> : <div class="money resource">-2</div></div>
```
to:
```vue
<template v-else-if="id === 'up04'"><div class="policy-top-margin"><div class="resource-tag tag-space"></div> : <div class="money resource">-2</div></div>
```

Remove Errant Backtick

---

src/server/Player.ts

Bug reported from Discord: https://discord.com/channels/737945098695999559/742721510376210583/1093460776561410048
```test
19:02]tappi: Am I mistaken in that you should be able to buy all five cards with Luna Project Office?
Image
[19:04]tappi: https://terraforming-mars.herokuapp.com/spectator?id=s4950bd1b0176 I'm playing a game against Mars Maths where I played this card but I am unable to buy all five cards
```
I am _pretty sure_ that this should fix it, in drafting variant it looks like the player wouldnt ever get to keep all 5 cards.
Testing could be updated to ensure that the actual keepMax is 5 for LPO? I'm unsure how to do that

Luna Project Office not keeping 5 cards

---

src/server/CeoExtension.ts
src/server/cards/ceos/Clarke.ts
src/server/cards/ceos/Duncan.ts
src/server/cards/ceos/Faraday.ts
src/server/cards/ceos/Greta.ts
src/server/cards/ceos/Naomi.ts
src/server/cards/ceos/Quill.ts
src/server/cards/ceos/Will.ts
src/server/cards/ceos/Zan.ts
src/server/colonies/Colony.ts
tests/cards/ceo/Clarke.spec.ts
tests/cards/ceo/Duncan.spec.ts
tests/cards/ceo/Faraday.spec.ts
tests/cards/ceo/Greta.spec.ts
tests/cards/ceo/Naomi.spec.ts
tests/cards/ceo/Quill.spec.ts
tests/cards/ceo/Will.spec.ts
tests/cards/ceo/Zan.spec.ts

I know, I know, a lot of changes in one PR.. I'm hoping it will be allowed, but I wont defend it any further than this and can submit a PR per CEO if required :)
* **Clarke**: 💚 Buff 
* Gain 1 Heat and Plant _production_ before gaining bonuses.
* **Duncan**: 💚 Buff
* Increased initial VP gain from 6 to 7
* **Faraday**: 💀 Nerf
* Increase cost of drawing card from 2 to 3MC
* **Greta**: 💀 Nerf
* TR gain is now per ACTION, not per steps increased
* MC gain is limited to 10x (40MC total gain)
* **Naomi**: 💚 Buff
* Increase MC gain from 2 to 3 per colony built
* **Quill**: 💚 Buff
* Gains an additional 1MC for every 2 floaters added.
* Can no longer act if player has no floater cards in play
* **Will**: 🔁 Rebalance
* Rebalance bonus resources:
* old: 2 animals, 2 microbes, 1 science, 1 floater, …

CEO Balance Update

---

src/client/components/GameSetupDetail.vue

This was missing for ages and I finally remembered to fix it:

Add CEO icon to game details

---

src/client/components/PlayerHome.vue
src/client/components/PreferencesDialog.vue
src/server/server.ts
src/styles/player_home.less
src/styles/preferences.less

In other words add a toggle button similar to other card filters next to the Cards in hand section that allows hiding cards in hand without going into preferences.
Vis when toggled off:
Vis when toggled on:

Change hide cards in hand functionality to be similar to card filters

---

src/client/components/card/Card.vue
src/client/components/card/CardContent.vue
src/styles/cards_v2.less

Splitted from #5640
When card has a huge of description, it can be scrolled.
It will look like (pointed scroll at the right side)
Needs almost for every locale

Adding scrolling for cards with huge description

---

.env.sample
src/server/Game.ts
src/server/database/IDatabase.ts
src/server/database/LocalFilesystem.ts
src/server/database/PostgreSQL.ts
src/server/database/SQLite.ts
src/server/server.ts
tests/database/ITestDatabase.ts
tests/database/SQLite.spec.ts
tests/database/databaseSuite.ts
tests/integration/LocalFilesystem.spec.ts
tests/integration/PostgreSQL.spec.ts
tests/testing/InMemoryDatabase.ts
tests/utils/setup.ts

This is a pretty significant rewrite, and contains a few things:
1. Completed games remain for two full days by default, making it simple to download games with bug reports filed against them.
2. Database maintenance is separated from cleanGame. So it's now called markFinished.
3. Some comments.

Improved purge for Postgres and SQLite, and general DB maintenance.

---

src/client/components/create/CreateGameForm.vue
src/locales/de/ui.json
src/locales/ru/ui.json

All the core components are done, remaining issues are external from the CEO application itself.
Wiki is up to date: https://github.com/terraforming-mars/terraforming-mars/wiki/CEOs
All future issues/bugs can be reported as regular App bugs, not part of the CEO Beta

Remove BETA tag from CEOs

---

src/server/cards/moon/RoadPiracy.ts
tests/cards/moon/RoadPiracy.spec.ts

This prevents an endless loop.

Reset the Road Piracy ledger on error.

---

src/client/components/OrOptions.vue
src/client/components/PlayerInputFactory.vue
src/common/input/PlayerInputType.ts
src/server/inputs/AndOptions.ts
src/server/inputs/OrOptions.ts
src/server/inputs/SelectAmount.ts
src/server/inputs/SelectCard.ts
src/server/inputs/SelectColony.ts
src/server/inputs/SelectDelegate.ts
src/server/inputs/SelectInitialCards.ts
src/server/inputs/SelectOption.ts
src/server/inputs/SelectPartyToSendDelegate.ts
src/server/inputs/SelectPayment.ts
src/server/inputs/SelectPlayer.ts
src/server/inputs/SelectProductionToLose.ts
src/server/inputs/SelectProjectCardToPlay.ts
src/server/inputs/SelectSpace.ts
src/server/inputs/ShiftAresGlobalParameters.ts
src/server/models/ServerModel.ts
tests/client/components/AndOptions.spec.ts
tests/client/components/OrOptions.spec.ts
tests/client/components/PlayerInputFactory.spec.ts
tests/client/components/ShiftAresGlobalParameters.spec.ts

This increases readability and debuggability. Plus, `enum` is considered no longer that great for ongoing Typescript projects.

Replace player input type enum with string type.

---

package-lock.json
package.json
webpack.config.js

Building on Debian 12 failed with `error:0308010C:digital envelope routines::unsupported`, because `webpack` defaults to MD4 which is disallowed by recent versions of OpenSSL.  Use a stronger hash function instead.  This required first upgrading `webpack`, which in turn required upgrading `vue-loader`.

Use a stronger webpack hash function

---

src/client/components/SelectProjectCardToPlay.vue

Currently, the reserveUnits variable for playing a card is fixed to the first card selected and when the selected card is changed, the variable is not updated. This may allow a user to try and play a card they cannot afford or be unable to play a card that they can afford. The bug is fixed by updating reserveUnits as the selected card changes.

Update reserveUnits when a new card is selected (#5840)

---

src/client/components/pathfinders/PlanetaryTrack.vue
src/client/components/pathfinders/PlanetaryTracks.vue
src/styles/pathfinders.less

Changes:
- numbers track is gone (it is useless for the gameplay)
- all empty cells have the same width (only 1 card in the game care which is the lowest track and it is not that hard to check anyway)
- more padding
- more prominent highlight of the current level track cells
Top: Before
Bottom: After

Pathfinders minor css tweaks

---

src/server/IPlayer.ts
src/server/Player.ts
src/server/boards/HellasBoard.ts
src/server/boards/VastitasBorealisBoard.ts
src/server/cards/StandardProjectCard.ts
src/server/cards/base/AquiferPumping.ts
src/server/cards/base/CaretakerContract.ts
src/server/cards/base/WaterImportFromEuropa.ts
src/server/cards/base/standardActions/ConvertHeat.ts
src/server/cards/base/standardActions/ConvertPlants.ts
src/server/cards/colonies/BuildColonyStandardProject.ts
src/server/cards/colonies/TitanAirScrapping.ts
src/server/cards/community/Playwrights.ts
src/server/cards/corporation/UnitedNationsMarsInitiative.ts
src/server/cards/moon/DarksideIncubationPlant.ts
src/server/cards/moon/LunaEcumenopolis.ts
src/server/cards/moon/TheArchaicFoundationInstitute.ts
src/server/cards/pathfinders/Ambient.ts
src/server/cards/pathfinders/RobinHaulings.ts
src/server/cards/pathfinders/SecretLabs.ts
src/server/cards/pathfinders/ValuableGases.ts
src/server/cards/promo/CometAiming.ts
src/server/cards/promo/DirectedImpactors.ts
src/server/cards/promo/PharmacyUnion.ts
src/server/cards/venusNext/Atmoscoop.ts
src/server/cards/venusNext/ExtractorBalloons.ts
src/server/cards/venusNext/ForcedPrecipitation.ts
src/server/cards/venusNext/JetStreamMicroscrappers.ts
src/server/cards/venusNext/RotatorImpacts.ts
tests/cards/moon/LunaTradeFederation.spec.ts

This is going to be significant when the next PR comes in that vastly simplifies Ares cost prediction.

Replace canAffordCard, and put `cost` in CanAffordOptions.

---

src/server/cards/promo/TychoMagnetics.ts

Currently the Tycho Magnetics card does not show the starting production or megacredits. This change adds that information and makes it similar to other corporation cards.

Render starting production and megacredits for Tycho Magnetics

---

.github/workflows/main.yml

https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Upgrade workflows/main.yml.

---

package-lock.json
package.json
src/server/database/PostgreSQL.ts
src/server/database/SQLite.ts

This change allows for pg or sqlite3 to fail to load. I am working on a mode where the server will run in a web worker. Within web worker will not use pg or sqlite3 so need these dependencies to be optional. This change should also help users who struggle to get sqlite3 to install. The file system database is now used as default if we fail to setup any other database.

allow for optional database providers

---

src/client/components/SelectParty.vue
src/client/components/SelectSpace.vue
src/common/models/PlayerInputModel.ts
src/server/inputs/SelectParty.ts
src/server/turmoil/Turmoil.ts
tests/client/components/PlayerInputFactory.spec.ts
tests/turmoil/Turmoil.spec.ts

1. Reduce data sent to client.
2. Improve global event processing order when a global event requires player input.

Two turmoil cleanups

---

src/client/components/SelectProductionToLose.vue

Fixes Set Production to Lose Form's +/- buttons and removes last references to $.data
I noticed a bug last week when selecting production to lose (as a result of hazards on the map), where the plus/minus buttons weren't working at all and you have to type in to edit the value.  I believe this bug change was introduced in https://github.com/terraforming-mars/terraforming-mars/pull/6136 when cleaning up `$.data` usage.
This PR contains the following changes:
- Updated the `delta` function to mutate the new nested `data.units` structure
- Fixes typo on `megacredit` in the `delta` function which prevents reducing megacredits production below 0
- Updates type matching on the delta function to use `keyof Units` instead of a `string` which enables indexing into `this.units[unit]` instead of …

Fix Set Production to Lose form +/- buttons

---

src/server/turmoil/globalEvents/CorrosiveRain.ts
src/server/turmoil/globalEvents/Election.ts
src/server/turmoil/globalEvents/GenerousFunding.ts
src/server/turmoil/globalEvents/RedInfluence.ts
src/server/turmoil/globalEvents/Revolution.ts
src/styles/turmoil.less

**AC**
- css changes - removed the 0.9 scaling, the vertical scrolling and added vertical alignment
The "drawback" is that only 2 events ELECTION and REVOLUTION have iconography on two rows and slightly go off the desired borders
- minor events polish

Global events css polish

---

src/client/components/OtherPlayer.vue
src/client/components/overview/PlayerTags.vue
src/styles/log.less
src/styles/other_player.less
src/styles/player_home.less

**AC**
- EV icon fix - double margin right has been removed and the width is proper now 
(top: current state, bottom: previous state)
- "other player cards" fixes:
-- on mobile and desktop the width matches the width of the player boards
-- player colour, label and close button are in a header - the backgroud colour and text colour now matches the colours of the player board
-- background colour is now 222 - identical to the background of the backlog
-- vertical scrolling now longer hides/scrolls away the close button

Few minor css changes

---

src/server/Game.ts

This puts the ocean bonus in the same branch as all other space bonuses
Fixes #6285

Make Hellas Ocean bonus compatible with Survey Mission.

---

src/server/Game.ts
src/server/Player.ts
src/server/cards/Deck.ts
src/server/cards/base/SearchForLife.ts
src/server/cards/ceos/CoLeadership.ts
src/server/cards/ceos/Karen.ts
src/server/cards/ceos/Lowell.ts
src/server/cards/community/JunkVentures.ts
src/server/cards/pathfinders/OumuamuaTypeObjectSurvey.ts
src/server/cards/prelude/ValleyTrust.ts
src/server/cards/promo/AsteroidDeflectionSystem.ts
src/server/cards/promo/Merger.ts
src/server/cards/promo/NewPartner.ts
tests/cards/Deck.spec.ts
tests/cards/community/JunkVentures.spec.ts
tests/cards/moon/LunarPlanningOffice.spec.ts

Renames existing `draw` method to `drawLegacy` while we switch references over to the new `draw` in stages.
The new `draw` returns undefined when the draw pile is empty, rather than throwing an error that's generally not handled properly.
~~Switches `AsteroidDeflectionSystem` and `SearchForLife` over to the new `draw` with some light refactoring to tidy them up a bit.~~

Create new Deck.draw that returns undefined when draw pile is empty

---

src/client/components/WarningsComponent.vue
src/common/cards/ClientCard.ts
src/common/cards/Warning.ts
src/server/cards/Card.ts
src/server/cards/ICard.ts
src/server/cards/colonies/MinorityRefuge.ts
src/server/cards/colonies/PioneerSettlement.ts
src/server/models/ModelUtils.ts
src/server/tools/export_card_rendering.ts

Looks like a nice cleanup, actually. It removes `warning` from ICard and ClientCard.

Standardize the luna colony warning.

---

.github/workflows/main.yml

Windows is always slower than Linux, and adds no real value; running the tests twice is at best useful for finding non-determinstic tests, and possibly occasionally other things?

Minimize Windows CI.

---

src/server/Player.ts
tests/cards/underworld/FriendsInHighPlaces.spec.ts

Players were reporting finding that the UI was allowing them to play cards they couldn't afford without corruption and Friends in High Places. The cards were being deemed playable before sending them to the UI. Fortunately the UI prevented their purchases.

Fix Underworld payment regression with Friends in High places.

---

src/server/behavior/Executor.ts
tests/cards/underworld/Neutrinograph.spec.ts

Make Neutrinograph playable even when all spaces are identified.

---

src/client/components/PlayerHome.vue

Enables CTRL-SHIFT-A on Chrome

Allow browser to use its modified keys.

---

src/server/routes/PlayerInput.ts

This removes prior warnings that do not apply to the card, currently.

Clear tableau warnings at the start of every playerinput.

---

src/common/Types.ts
src/server/GameSetup.ts
src/server/boards/BoardBuilder.ts
src/server/database/PostgreSQL.ts
src/server/moon/MoonBoard.ts
src/server/routes/Game.ts

This isn't meant to remove all uses of `as` but helps with some particularly obvious cases.

Add safeCast to remove some obvious casts.

---

src/server/cards/pathfinders/HuygensObservatory.ts
tests/cards/pathfinders/HuygensObservatory.spec.ts

This was broken in 4f3f26f152941a6a38be1b4f2b762d347b73ecd5 and would have been caught with the right canPlay tests. Those tests are now in place.

Restore Huygens behavior.

---

src/locales/cn/pathfinder_cards.json
src/locales/de/pathfinder_cards.json
src/locales/nl/pathfinder_cards.json
src/locales/pl/pathfinder_cards.json
src/server/cards/pathfinders/PublicSponsoredGrant.ts
tests/cards/pathfinders/PublicSponsoredGrant.spec.ts

According to Google Translate, most of the translations already referenced "Every other player."

Update Public Sponsored Grants behavior to match printed card.

---

src/client/components/create/CardsFilter.vue
src/client/components/create/CreateGameForm.vue
src/client/components/create/CreateGameModel.ts
src/client/components/create/json.ts
src/common/game/NewGameConfig.ts
src/common/models/GameOptionsModel.ts
src/server/GameCards.ts
src/server/game/GameOptions.ts
src/server/models/ServerModel.ts
src/server/routes/Game.ts
tests/GameCards.spec.ts
tests/routes/ApiGame.spec.ts

Intended as a mirror to the excluded cards feature. In my group we like to play without the actual expansions while still being able to include cards from all expansions. This feature allows for that.

Allow players to include specific cards 

---

.github/workflows/main.yml

Current version uses Node 16, which is deprecated.

Move gh actions to @4

---

src/server/cards/underworld/AnubisSecurities.ts
tests/cards/underworld/AnubisSecurities.spec.ts

It should be played after all production, so players have MC to spend on the Anubis player.
Fixes #6604

Execute Anubis Securities after all other ops.

---

src/server/cards/base/RoboticWorkforce.ts
src/server/cards/promo/CyberiaSystems.ts
src/server/deferredActions/Priority.ts
tests/cards/base/MiningRights.spec.ts
tests/cards/base/RoboticWorkforce.spec.ts
tests/cards/pathfinders/SpecializedSettlement.spec.ts
tests/cards/venusNext/Gyropolis.spec.ts

These got deprioritized at the same time as part of addressing #5488. By and large, these two behaviors don't need to be priority options; discard after you get all the cards you can get! Implement robotic workforce after gaining all the required production you can get!
Though these are close-to-the-edge cases, I'm surprised that Robotic Workforce had such high priority for this long.

Deprioritize robotic workforce and mars univeristy.

---

make_static_json.js

This probably happens when someone downloads a tarball or zip file of the source.
Perhaps it's worth updating instructions to require Git.

Allow make_static_json work without a .git directory.

---

src/client/components/create/CreateGameForm.vue

Fix link to wiki due to header rename:
https://github.com/terraforming-mars/terraforming-mars/wiki/Variants/_compare/16d7b7be46dc2a6fde414506e624246f8f9b427a...39f835b06355380830b42ba62c0da311a0372c88

Fix link to wiki due to wiki header rename (Solar Phase -> World Government Terraforming)

---

src/server/awards/amazonisPlanitia/Engineer.ts
src/server/cards/ICard.ts
src/server/cards/ares/SolarFarm.ts
src/server/cards/base/MiningCard.ts
src/server/cards/base/RoboticWorkforceBase.ts
src/server/cards/pathfinders/SpecializedSettlement.ts
src/server/cards/underworld/Landfill.ts
tests/awards/amazonisPlanitia/Engineer.spec.ts
tests/cards/base/RoboticWorkforce.spec.ts

This will facilitate better prediction for Cyberia Systems. It has the side effect of making a better calculation for Specialized Settlement and Robotic Workforce, in the case where the player gained one energy production (e.g. on Terra Cimmeria.)
The final remnant of card.production is Small Open Pit Mine, which lets a player choose between two options. This can't be reduced to a single option, but as a single-case, it will probably be hard-coded into dealing with Cyberia Systems.

Move most uses of card.production to card.productionBox.

---

src/styles/cards.less

Make card help sit above card logos.

---

src/server/Player.ts
tests/Player.spec.ts

Could fix #6511 
canUseCorruptionAsMegacredits was not deserialized

Deserialization of canUseCorruptionAsMegacredits attribute in Player

---

src/client/components/create/CreateGameForm.vue

Once the player has turned off Prelude, then toggling Prelude 2 won't re-toggle Prelude.
Fixes #6712

Select Prelude when player selects Prelude 2.

---

src/server/cards/ICard.ts
src/server/cards/base/MarsUniversity.ts
src/server/cards/base/OlympusConference.ts
src/server/cards/ceos/Faraday.ts
src/server/cards/colonies/Aridor.ts
src/server/cards/promo/CarbonNanosystems.ts
src/server/cards/promo/PharmacyUnion.ts
src/server/cards/underworld/StemFieldSubsidies.ts
src/server/cards/venusNext/VenusianAnimals.ts
src/server/colonies/Colony.ts
tests/cards/base/MarsUniversity.spec.ts
tests/cards/base/OlympusConference.spec.ts
tests/cards/ceo/Faraday.spec.ts
tests/cards/colonies/Aridor.spec.ts
tests/cards/community/Leavitt.spec.ts
tests/cards/promo/PharmacyUnion.spec.ts
tests/cards/underworld/StemFieldSubsidies.spec.ts
tests/cards/venusNext/VenusianAnimals.spec.ts

This used to work but I'm sure stopped working at some point when I did a bunch of things. The cleanest way to fix this is to add a custom callback. Not the very best, but it does the job.
Cards impacted include
Pharmacy Union
Mars University
Stem Field Subsidies
Venusian Animals
Carbon Nanosystems
Olympus Conference
Faraday
Aridor
Cards not impacted include
Collegium Copernicus:
Specifically says it only works with cards. There's an argument that
this should count, but I think this is OK.
Valley Trust:
represents a discount when playing a science tag. There's an argument
that this should enable the player to get a 2MC discount when buying
a colony on Leavitt, but it's not very good.
Fixes #6349

Make cards that operate on science tags compatible with Leavitt colony

---

src/server/Game.ts
src/server/Player.ts
src/server/cards/promo/PharmacyUnion.ts
src/server/cards/promo/Splice.ts
src/server/colonies/ColoniesHandler.ts
src/server/turmoil/parties/Greens.ts
tests/TestingUtils.ts
tests/cards/promo/Merger.spec.ts
tests/cards/promo/PharmacyUnion.spec.ts
tests/cards/promo/Splice.spec.ts
tests/turmoil/parties/Greens.spec.ts
tests/utils/log-the-log.ts

The key commit in this set of commits confirms Pharmacy Union effects occur before cards with positive Microbe effects.
The Splice/Pharmacy Union issue was limited specifically to when the played microbe card did NOT store microbe resources. So that part of splice is now deferred, and that ought to do it.
Greens gp03 had a similar behavior and was also adjusted.
Fixes #5674 
Related to #3126

Mostly, fix Spice to work with Pharmacy Union

---

src/server/IPlayer.ts
src/server/Player.ts
src/server/player/Tags.ts
tests/cards/promo/PharmacyUnion.spec.ts

This gets half of #1670 resolved. This and Colonies, and we're pretty close to good. (FWIW, Pathfinders bonuses are fairly disregarded when it comes to predicting Reds costs.)

Use Pharmacy Union's effect when predicting playable cards

---

src/client/components/card/CardExpansion.vue
src/styles/cards_v2.less

This is experimental for now. When a card has resources, the icon is not visible. So for now, all expansion icons are in the upper right of the card.

Experimental: alawys show expansion icon in upper right of a card.

---

src/server/awards/amazonisPlanitia/Engineer.ts

Reviewed the list of currently implemented prelude 2 cards and added relevant cards to be included in the engineer award count

Update Engineer Award to include Prelude 2 Bespoke Production Cards

---

src/server/Draft.ts
src/server/IPlayer.ts
src/server/Player.ts
src/server/createCard.ts
src/server/inputs/SelectInitialCards.ts
tests/TestingUtils.ts
tests/inputs/SelectInitialCards.spec.ts

This required a little bit of work rewriting some type management, with an unfortunate 'as' added to createCard. We'll get rid of it I'm sure.
Helps with #6813 but doesn't solve it.

Properly discard unchosen preludes and CEOs during initial card selection.

---

src/styles/cards_v2.less

The Icon on the Corporation Cards that shows the expansion would occasionally overlap the card. There's no real great place to place this icon, so I tucked it in the top right hand corner, slightly proud of the card to match the card's tag.
Regular Cards:
Small Cards:

Adjust Corporation Card Expansion Icon

---

src/server/cards/prelude2/FloatingRefinery.ts
tests/cards/prelude2/FloatingRefinery.spec.ts

It should be usable regardless of number of floaters on card
https://github.com/terraforming-mars/terraforming-mars/issues/6935

Update Floating Refinery

---

src/client/components/SelectCard.vue
src/client/components/SelectResource.vue

Fixes #6944
Another, better solution is to provide a validate step for each playerInput, but that seems to get a little tricky, particularly as there's a difference between PlayerInput and BasePlayerInput, being that one of them is typed. That makes it difficult for a validate step to include type checking.

Use canSave on the UI side to prevent issues with Focused Organization.

---

src/client/components/create/CreateGameForm.vue
src/client/components/create/PreludesFilter.vue

CEO and Underworld preludes now auto-select when those expansions are selected in the Create Game Form. Also, titles for CEOs, Underworld and Prelude 2 are now present in the Custom Preludes list, as they are for all other expansions.

Auto select preludes in create game form

---

src/server/cards/pathfinders/EarlyExpedition.ts
src/server/cards/pathfinders/MartianCulture.ts

Changes production box on Early Expedition, so it is visually in line with other city cards; capitalises the word 'any' on Martian Culture

Pathfinders aesthetic changes

---

src/tools/make_static_json.ts

I'm having trouble deploying; Heroku's build container is running out of memory. Perhaps this is the cause of the change.

Remove translation duplication warnings

---

src/client/components/Award.vue
src/client/components/BoardSpace.vue
src/client/components/GameHome.vue
src/client/components/Milestone.vue
src/client/components/PreferencesDialog.vue
src/client/components/overview/PlayerInfo.vue
src/client/utils/PreferencesManager.ts
src/client/utils/playerSymbol.ts
src/styles/board.less

There's definitely more to cover (colonies, turmoil, player logs, and more.)

Symbol overlays to support color visualization

---

.env.sample
src/server/server.ts

Issue #7376 
- Maintain existing behavior by using '::' as default host to listen to all IPv4 and IPv6 addresses
- As far as I understand, on the vast majority of systems '::' also encompasses '0.0.0.0', but this is not 100% given. On systems where that is not the case, the existing behavior with the unspecified host in `server.listen(port)` would _not_ be preserved.
- Add localhost as suggested HOST to .env.sample
- However, this is not the default value, so this could be confusing? Would it be better to leave it empty?
- `server.listen(port)` with `port = process.env.PORT` is also present in [analyze_ma.ts](https://github.com/terraforming-mars/terraforming-mars/blob/main/src/server/tools/analyze_ma.ts#L40)
- I'm not sure what analyze_ma.ts is used for, but it could be that the HOST …

Add HOST .env variable to server.listen(port, host)

---

src/client/components/card/CardCorporationLogo.vue
src/server/cards/corporation/UnitedNationsMarsInitiative.ts
src/server/cards/pathfinders/Odyssey.ts
src/styles/cards_v2.less
src/styles/language_hacks.less

Before fix:
After fix:
Brief description of fix:
- part of the issue was that there were empty card rows with margin, so I made those have 0 margin
- also gave the card-corporation-box a bit more top margin to match the rest of the card
Note: This fix is not specific to this card, but a more general fix that will impact all corporation cards. Credicor is just an example of the issue.

Fix: Corporation Visualizations

---

src/client/components/create/CreateGameForm.vue

Also moved the prelude 2 expansion to after turmoil in the create-game menu, to be in chronological order of release. This has always bothered me

Removed Beta and "New" symbols for official expansions

---

src/server/cards/base/OlympusConference.ts
src/server/cards/underworld/HyperspaceDrivePrototype.ts
src/server/deferredActions/Priority.ts
tests/cards/base/OlympusConference.spec.ts

Fixes #7505
I have chosen the Priority values so that if a player also had Mars University, this interaction would take place before discard and draw. I will add a test(/s) and manual test worked as expected

Defer adding science resource to Olympus Conference for Hyperspace Drive Prototype

---

src/server/cards/pathfinders/AdhaiHighOrbitConstructions.ts

Creating extra orbitals on game start because of migration to the new API for corporate cards. I forgot to clean a little of it up.

Fix Adhai Orbit Construction

---

src/server/cards/underworld/CloudVortexOutpost.ts

Fixes #7591. Should have been fixed in #7592 , but I rolled it back like a goofball.

#7591 - Fix name of moved resource in CloudVortexOutpost

---

src/common/constants.ts
src/server/moon/MoonExpansion.ts
tests/cards/moon/LunaFirstIncorporated.spec.ts

Moved all raise[Moon]Rate methods into one reusable method. The bug was due to all three tracks repeating the same code. Ah, repetition.

Fix Luna First Incorporated bug.
